### ISSUE TITLE
[vite-node] [ERR_LOAD_URL] ..vue error in dev mode (Docker only)

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#20446] opened 2023-04-22 15:31 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/daniluk4000/nuxt-3.4.2-docker-error

Please read Readme.md in this repo before you launch it.

### Describe the bug

The only thing I did - executed nuxi upgrade to upgrade from 3.4.1 to 3.4.2, then I've started to face this error when I launch project (dev mode only)

![image](https://user-images.githubusercontent.com/10450717/233792803-d74f7cc8-3318-426c-8930-0ced572d77f1.png)

I've tried to clear .nuxt folders and do clean startup, but had no success.

Reproduction repo is simply "npx nuxi@latest init" with a bit of changes for Dockerization.

### Additional context

I wasn't able to reproduce this error outside of Docker environment. 

### Workaround
Change WORKDIR from /app to any random folder, ex. /frontend

**Comment by outluch** [comment] 2023-04-22 23:24
What a coincidence. Just 3 hrs ago tried to run nuxt3 development in docker and see exact same error. Still fighting...

**Comment by outluch** [comment] 2023-04-22 23:58
Ok, I managed to run it in docker by downgrading nuxt to 4.3.1 version in package.json.
So, bug is somehow related to latest bump to Vite 4.3 I guess.. https://github.com/nuxt/nuxt/releases/tag/v3.4.2

**Comment by AwesomeAnders** [comment] 2023-04-25 08:12
I'm also running a docker setup and been getting a bunch of these errors after upgrading nuxt. It happens seemingly spontaneous on page refreshes. Maybe it's related? 

![image](https://user-images.githubusercontent.com/37805682/234215665-0bd47ad2-438f-44be-9e03-e110fc1544ab.png)

**Comment by danielroe** [comment] 2023-04-25 14:43
cc: @antfu

**Comment by tebaly** [comment] 2023-05-01 01:45
# No 

```json
  "devDependencies": {
    ...
    "nuxt": "^3.4.1",
    "vite": "4.2.1"
  }
```
yarn install
yarn list vite

```
├─ @nuxt/vite-builder@3.4.3 (!)
│  └─ vite@4.3.3 (!)
├─ vite-node@0.30.1 (!)
│  └─ vite@4.3.3 (!)
└─ vite@4.2.1 (!)
```

# Yes

```json
  "devDependencies": {
    ...
    "nuxt": "3.4.1" (!)
  },
  "resolutions": {
    "vite": "4.2.1"
  }
```

```
└─ nuxi@3.4.1
└─ vite@4.2.1
```

If you have a compatibility issue with dependencies and a bug in one of them, you can use Yarn's resolutions feature to enforce a specific version for all dependent packages. Simply add the required version to the resolutions property in your package.json file and run yarn install. However, keep in mind that this may lead to incompatibilities, so make sure you understand the implications before using it.

PS: in k8s okteto - delete PVC

**Comment by tebaly** [comment] 2023-05-01 14:26
```json
  "devDependencies": {
    ...
    "nuxt": "~3.3.2"
  }
```

use --force option (ignore `vite` cache)

yarn dev --force

**Comment by daniluk4000** [comment] 2023-05-02 11:19
@antfu Can you please take a look at this? This is a blocker for updating Nuxt.

**Comment by antfu** [comment] 2023-05-02 11:38
I am not familiar with Docker, and I need sometime to set it up

**Comment by daniluk4000** [comment] 2023-05-02 11:39
> I am not familiar with Docker, and I need sometime to set it up

Ah. Is there any way I can help with debugging? This error is super not informative.

**Comment by daniluk4000** [comment] 2023-05-02 12:26
The bug is: on defaultTemplates resolve in generateApp it inserts `export { default } from "/app/app.vue";`, where `/app` is Docker workdir.

But when I try to import it, Vite fails, it works fine without Docker and breaks inside. File does exist in filesystem.

![image](https://user-images.githubusercontent.com/10450717/235665503-7db04922-fcb6-4878-937e-d21f65af6143.png)

**Comment by daniluk4000** [comment] 2023-05-02 18:05
Well, I decided to go deep.

Found a workaround: change /app to any random folder in Dockerfile WORKDIR e.t.c.

**Comment by daniluk4000** [comment] 2023-05-02 19:30
I've spent hours on this and I give up.

My conclusion: it looks so much like Vite 3.4.0 bug. I downgraded vite-node version and it worked just fine, also my other project on Nuxt 3.4.1 uses same vite-node version.

I have reviewed all Nuxt 3.4.2. diff and didn't find anything. 

I have also downgraded Vite version to 4.2.2, removed some not compatible code and it worked just fine without any errors.

If I will be able to reproduce this in pure vite environment, I'll report an issue to them and close this.

**Comment by daniluk4000** [comment] 2023-05-03 19:03
Wasn't able to reproduce this in pure Vite without Nuxt. 

![image](https://user-images.githubusercontent.com/10450717/236017562-17723b3c-309a-43d2-9c35-26b9d3463788.png)
![image](https://user-images.githubusercontent.com/10450717/236017593-b8bba1f2-c141-413c-ac20-067b96365d58.png)

Maybe Vite 4.3.2 somehow broke something how Nuxt uses Vite. I'll leave this issue to you guys as we have workaround for upgrading to Nuxt now.

**Comment by vwnd** [comment] 2023-05-19 22:02
> Well, I decided to go deep.
> 
> Found a workaround: change /app to any random folder (e.g. /frontend) in Dockerfile WORKDIR e.t.c.
> 
> Something is going on with /app/app.vue path...

Solved for me. Very weird.

**Comment by nrueckmann** [comment] 2023-05-30 13:46
Still happening in 
Nuxi 3.5.2
Nuxt 3.5.2
Nitro 2.4.1

**Comment by fredevery** [comment] 2023-06-09 21:42
> Same error for me in a node:18 docker container with a fresh install with Nuxt 3.5.2 and using /app as the WORKDIR.
> 
> Using any other folder than /app as the WORKDIR "solves" it.

How did you figure that out? Totally fixed my issue.

**Comment by zejefferson** [comment] 2023-06-09 21:57
> > Same error for me in a node:18 docker container with a fresh install with Nuxt 3.5.2 and using /app as the WORKDIR.
> > Using any other folder than /app as the WORKDIR "solves" it.
> 
> How did you figure that out? Totally fixed my issue.

I didn't, [daniluk4000](https://github.com/daniluk4000) did and shared it earlier in the thread. :)

**Comment by daniluk4000** [comment] 2023-06-10 15:32
> > Same error for me in a node:18 docker container with a fresh install with Nuxt 3.5.2 and using /app as the WORKDIR.
> > Using any other folder than /app as the WORKDIR "solves" it.
> 
> How did you figure that out? Totally fixed my issue.

Well if you're curious... First I've tried to find problem in Nuxt, debugged it and found out the problem is somewhere inside "import" and Nuxt seems to do everything correctly. Then, I've tried to debug vite-node and figured out the problem is somewhere inside Vite. 

During debug, I saw that /app/app.vue is being replaced to /app.vue somewhere inside Vite. I thought it can't be just coindidence and changed /app to /frontend. When it worked on both hello world and my real project, I've stopped debugging (except for pure Vite check) and posted workaround here. 

Sadly, I don't have time & expertise to debug Vite with Nuxt configuration. My best guess is something in Nuxt's Vite configuration got broken after Vite 4.3.0 (probably on Vite side), but I couldn't go much far.

**Comment by MrCheater** [comment] 2023-06-27 11:10
+1

**Comment by makakken** [comment] 2023-06-28 09:20
+1

**Comment by just-maik** [comment] 2023-06-29 08:51
+1 using Docker on Kubernetes having the same issue. Moving from /app to /nuxt worked for me.

**Comment by Sascha-Block** [comment] 2023-08-26 08:56
I'm having the same issue right now.

├── @invictus.codes/nuxt-vuetify@0.3.0
├── @nuxt/devtools@0.7.0
├── @types/node@18.16.19
├── nuxt@3.6.5
└── nuxt3@3.7.1-28216789.9013f88e

Meine Sourcen sind hier public: https://github.com/rock-the-prototype/nuxt-the-prototype/ 

Der Fehler trat erst nach den heutigen Änderungen auf.

**Comment by gnuion** [comment] 2023-08-29 19:47
> Well, I decided to go deep.
> 
> Found a workaround: change /app to any random folder (ex. /frontend) in Dockerfile WORKDIR e.t.c.
> 
> Something is going on with /app/app.vue path...

Thank you! Looks to be a nuxt bug. Finally running nuxt inside podman inside code-server inside kubernetes inside alpine os virtual machine inside windows 10

**Comment by danielroe** [comment] 2023-10-22 07:59
this will be resolved in vite v5.

**Closed by danielroe** 2023-10-22 07:59 UTC
Labels: 3.x, workaround available, bug, vite

**Comment by etherphis** [comment] 2024-02-21 00:52
> ```json
>   "devDependencies": {
>     ...
>     "nuxt": "~3.3.2"
>   }
> ```
> 
> use --force option (ignore `vite` cache)
> 
> yarn dev --force

I changed from ^3.10.2 to ~3.3.2

appreciate it that u gave me this nuxt version it fixed this issue for me.

**Comment by AleksandrCherednichenko-developer** [comment] 2024-03-11 07:16
@wrode The same thing is happening with my nuxt project, I have been trying to overcome this problem for the second day. I've seen comments that this is solved by upgrading the nuxt version to newer ones, but in my case it doesn't work. Please let us know if you find a solution

**Comment by mklueh** [comment] 2024-05-19 12:34
Similar issue here, can't reproduce it at all, but I assume it must be workspace related. I've copied the project of my NX monorepo into a different project, and there it works.

![image](https://github.com/nuxt/nuxt/assets/1553757/3865537e-aea7-4627-a355-2b8609d74ba4)

https://github.com/nuxt/nuxt/issues/26731

**Comment by McSneaky** [comment] 2024-07-03 08:49
Had similar error with latest everything, but .css files. Came having `buildAssetsDir` set to `assets` only works in production. It has to be something else in dev mode. Renamed it to `dist` and everything started to work

I assume that `buildAssetsDir` can't be anything, that Nuxt itself uses
