### ISSUE TITLE
Dynamic Componets dont work under 3.4.3 but under 3.4.2

### ISSUE THREAD

**Issue by Letsion** [nuxt/nuxt#20736] opened 2023-05-09 06:46 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v19.9.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      ssr, modules, imports, css, pinia, runtimeConfig, components, app, pwa, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.6, @pinia/nuxt@0.4.9, @vite-pwa/nuxt@0.0.7, @nuxt/devtools@0.3.2
- Build Modules:    -

### Reproduction

Dynamic loading of components no longer works. 

This is my config:

```
export default defineNuxtConfig({
    ssr: false,
    modules: ['@nuxtjs/tailwindcss', '@pinia/nuxt', '@vite-pwa/nuxt', '@nuxt/devtools'],

    imports: {
        dirs: ['./store'],
    },

    css: [
        '~/assets/css/tailwind.css',
        '~/assets/css/brands.min.css',
        '~/assets/css/solid.min.css',
        '~/assets/css/fontawesome.min.css',
        '~/assets/css/regular.min.css',
        'v-calendar/style.css',
    ],

    pinia: {
        autoImports: ['defineStore', 'acceptHMRUpdate'],
    },

    runtimeConfig: {
        public: {
            apiUrl: dev ? 'https://localhost:44390' : 'https://url',
            baseUrl: dev ? 'http://localhost:3000' : 'https://url',
            azure_clientId: '',
            azure_authority: '',
            azure_scope: '',
        },
    },

    components: {
        global: true,
        dirs: ['~/components'],
    },

    app: {
        head: {
            title: '',
            meta: [
                {
                    charset: 'utf-8',
                },
                {
                    name: 'viewport',
                    content: 'width=device-width, initial-scale=1',
                },
                {
                    hid: 'description',
                    name: 'description',
                    content: '',
                },
            ],
            link: [
                {
                    rel: 'icon',
                    type: 'image/x-icon',
                    href: '/favicon.ico',
                },
                {
                    rel: 'stylesheet',
                    href: 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap',
                },
            ],
        },
    },

    pwa: {
        manifest: {
            name: ' ERP',
            lang: 'de',
        },
    },
    // @ts-ignore
    devtools: true, //TODO: Remove in production
});
```

### Describe the bug

On 3.4.2 it work all fine.
On Upgrade to 3.4.3 i get this Error:
```
ERROR  Internal server error: Failed to resolve import "#components" from "virtual:nuxt:C:\Projects\MAC\Frontend\.nuxt\components.plugin.mjs". Does the file exist?                                                        08:41:22  
  Plugin: vite:import-analysis
  File: virtual:nuxt:C:/Projects/MAC/Frontend/.nuxt/components.plugin.mjs:2:7763
  1  |  import { defineNuxtPlugin } from '#app/nuxt'
  2  |  import { LazyCommonDirektkachel, LazyCommonKacheln,
  3  |  const lazyGlobalComponents = [
  4  |    ["CommonDirektkachel", LazyCommonDirektkachel],
```

**Comment by danielroe** [comment] 2023-05-09 07:22
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Letsion** [comment] 2023-05-11 06:02
Ok, I will try to reproduce this error in a separate project in the next few days.

**Comment by Letsion** [comment] 2023-05-11 06:23
I have found the error. The error comes from a colleague having a file with special characters like Ü, Ä, Ö.
In the 3.4.2 it still worked. it not really is a bug, if you want to take it over you are welcome to do so. :)

**Comment by danielroe** [comment] 2023-05-11 06:51
Thanks for the triage. The issue is caused upstream by `mlly` which is used by `unimport`. PR opened.

**Comment by danielroe** [comment] 2023-05-11 22:06
This should be resolved in mlly's latest release. which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt`.

Let me know if not and I'll reopen.

**Closed by danielroe** 2023-05-11 22:06 UTC
Labels: 3.x, upstream, upstream-bug
