### ISSUE TITLE
input Use v-model bidirectional binding hot update exception

### ISSUE THREAD

**Issue by dxhuii** [nuxt/nuxt#23688] opened 2023-10-16 07:23 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version: 3.7.4
- CLI Version: 3.9.0
- Nitro Version: 2.6.3
- Package Manager:  pnpm@8.9.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-4cyshx?file=pages%2Findex.vue

### Describe the bug

input Use v-model two-way binding, when change the v-model to :value, the two-way binding is still effective, need to refresh the page, then it will be normal.

**Comment by danielroe** [comment] 2023-10-16 08:32
Everything seems to be working fine for me in your reproduction. What is the issue?

**Comment by dxhuii** [comment] 2023-10-16 17:26
> Everything seems to be working fine for me in your reproduction. What is the issue?

When the v-model is changed to :value, the two-way binding should not take effect and it should become an assignment. But it doesn't, the two-way binding still works. You can modify it to try that. My guess is that there might be a problem with the hot update.

**Comment by danielroe** [comment] 2023-10-16 18:57
Would you check if this is reproducible without Nuxt in https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter ? 🙏

**Comment by dxhuii** [comment] 2023-10-17 06:26
Using the scaffold you gave, I recorded a video. You can watch it. It seems that it is difficult to describe it clearly in words.


https://github.com/nuxt/nuxt/assets/2328917/b122388b-1c46-44cf-9869-c7b2e05019a8

**Comment by danielroe** [comment] 2023-10-17 08:33
Yes, I understand. The scaffold is not using Nuxt, so this seems like an (edge-case) issue with Vue itself or possibly with @vitejs/plugin-vue. You can open an issue upstream at http://github.com/vuejs/core if you would like, but I'm closing here as it's not related to Nuxt.

**Closed by danielroe** 2023-10-17 08:33 UTC
Labels: 3.x, pending triage, needs reproduction
