### ISSUE TITLE
Any change of content makes hydration node/text content mismatch

### ISSUE THREAD

**Issue by teamboot88** [nuxt/nuxt#18764] opened 2023-02-04 14:56 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@3.4.1`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `nuxt-icon@0.2.10`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-dgdjfn-hhmxav?file=pages%2Findex%2Fposts.vue,nuxt.config.ts,pages%2Findex.vue

### Describe the bug
- After upgrade to 3.1.2 from 3.0.0, any content change makes `hydration mismatch` error.

### pages/index
```vue
<template>
  <div>
    aaa
  </div>
</template>

<script setup>
</script>

<style scoped>
</style>
```

### Reproduction
- Start nuxt
- Open page `http://localhost:3000`
- Change template content (e.g. "aaa" to "bbb")
  - (Any change of content makes Hydration node mismatch error)
- Refresh page  `http://localhost:3000`
- See console.

### Additional context

![image](https://user-images.githubusercontent.com/54491002/216773645-5698aa0b-1852-445b-b04f-122067061035.png)

**Comment by sandercoffee** [comment] 2023-02-04 19:54
Same error for me, on a brand new nuxt project..

The server simply takes the code of the "run dev" and uses it in the SSR, so when it comes to hydration, the error occurs..

**Comment by sandercoffee** [comment] 2023-02-04 20:20
The error was introduced in version **3.1.1**, in 3.1.0 does not happen.

**Comment by madebyfabian** [comment] 2023-02-04 22:52
Maybe duplicate of https://github.com/nuxt/nuxt/issues/18635

**Comment by teamboot88** [comment] 2023-02-21 05:28
It is resolved in https://github.com/nuxt/nuxt/issues/18635

**Closed** 2023-02-21 07:37 UTC
Labels: 3.x, pending triage, windows
