### ISSUE TITLE
TransitionGroup hydration mismatch

### ISSUE THREAD

**Issue by fabkho** [nuxt/nuxt#28381] opened 2024-08-01 14:15 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      modulesDir, build, modules, eslint, tailwindcss, vite, css, i18n, compatibilityDate
- Runtime Modules:  @pinia/nuxt@0.5.1, vue3-swatches/nuxt, floating-vue/nuxt, @nuxtjs/i18n@8.3.1, @nuxtjs/tailwindcss@6.12.1, @nuxt/eslint@0.4.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-muuvjp?file=app.vue

### Describe the bug

A hydration mismatch occurs inside a TransitionGroup when there is an element with v-if. This issue only happens if a tag is set on the TransitionGroup. Replacing v-if with v-show resolves the error.
````
[Vue warn]: Hydration children mismatch on <div>​…​</div>​ 
Server rendered element contains more child nodes than client vdom. 
  at <TransitionGroup tag="div" > 
````

Additionally, if there is a comment inside the TransitionGroup, a similar error occurs. Removing the tag resolves the hydration mismatch caused by the comment. However, after removing the tag and switching v-if to v-show, the error reappears.
````
runtime-core.esm-bundler.js?v=5dd078cf:50 [Vue warn]: Hydration node mismatch:
- rendered on server: <!-- test -->  
- expected on client: div 
  at <TransitionGroup> 
````

I have provided both cases in the reproduction.

**Comment by fabkho** [comment] 2024-08-02 07:03
I forgot to mention that there was a [Vue issue](https://github.com/vuejs/core/issues/6715) and a [fix](https://github.com/vuejs/core/commit/5a9626708e970c6fc0b6f786e3c80c22273d126f) which should have resolved my issue regarding the comment, but it hasn't.

**Comment by huang-julien** [comment] 2024-08-04 20:39
Hey :wave: thanks for opening the issue. At first sight, this seems to be a vue bug. 

Do you think you'll be able to reproduce it in a vue ssr repo ?

**Comment by fabkho** [comment] 2024-08-05 09:13
@huang-julien i've raised an issue for vue here: [TransitionGroup hydration mismatch · Issue #11514 · vuejs/core](https://github.com/vuejs/core/issues/11514), with a vue ssr repro.

But i could not reproduce the warning regarding the comment inside a transition group.

**Comment by huang-julien** [comment] 2024-08-05 13:07
Thank you for the repro and the issue :heart: ! let's get it solved first in vue/core then see if this happens again

**Comment by danielroe** [comment] 2024-09-18 06:08
Well, it's still reproducible in Vue:

https://play.vuejs.org/#__SSR__eNp9Uk1vm0AQ/SvTvTixDChJT9Sp1FQ5pIe2StNT6WEFA2wCu2h3wI4Q/72zi2tcq8qJYd6bj/dmR/Gp6+KhR5GKLWHbNZLwY6YBtoUaQsAhWamdImV0VFnTd0Cyus0EMzJx4MwFMESlsQxdKG62AaUL3F/yBwpJMhOQvuArwx6NVXFSDTCOENJatgjTdGybLIvw37soInQURedzVcl9S9k4XMbc8IDT+m1yrmSWeqAwvDjAvy63qiNwSIGo2s5YghEsljBBaU0LK7Zu9cGzkwQesTWD0hVQjd4iJjrTDOhCon4trPSToVWulZTXoeju59MGZElomX5Wv15LXazX4HaK6X8RrxXIgOTI1WYHCiokkBrQWmNBVlLp2O+UG+0oWA+3fuuLX14u+1ykcLUB73QKqwdWDVcrmDYLev0vej2jvy9Z6jaZfWFHxEaQ4yGlquJnZzQ/otH3yERu2k41aL91XrHLRAoB8ZhsGrP7EnJkewxTQ02N+ct/8s9u73OZ+M5+oh34wEeMpGXtM3z/4yvuOT6CrSn6htlvgI/+Qr3fcabd9brgtU94YduHcHo+wJO73xPyEzqI8ot65uxdJvg5fH5D+rLuTfw+1GV6EtMf72ojRg==

Would you raise another upstream issue please? 🙏

**Comment by danielroe** [comment] 2024-09-19 11:24
thank you!

closing here to track upstream 🙏

**Closed by danielroe** 2024-09-19 11:24 UTC
Labels: bug, upstream, upstream-bug
