### ISSUE TITLE
Hot reload is not working (OSX)

### ISSUE THREAD

**Issue by jkd77** [nuxt/nuxt#19529] opened 2023-03-08 15:23 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.29.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`
- Build Modules:    `-`

### Reproduction

Hey Team - I'm following along with the Mastering NUXT 3 class using - [https://github.com/MasteringNuxt/mastering-nuxt-3](https://github.com/MasteringNuxt/mastering-nuxt-3)

### Describe the bug

I'm on OSX attempting to get things working for the very first lesson and when running pnpm dev, localhost does start but the arrows spin for a long time and hot reload doesn't work. I can manually refresh the page to see changes made to index.vue however. 

I've tried the latest edge version of NUXT and no dice. I've also tried several recommendations in the Windows version of this issue: https://github.com/nuxt/nuxt/issues/18964#issuecomment-1459549393

Any assistance would be greatly appreciated.

**Comment by manniL** [comment] 2023-03-08 16:03
Hey! According to your environment info, you still use `Nuxt Version: 3.0.0` in your project. 🤔
Can you double-check that?

**Comment by manniL** [comment] 2023-03-08 20:21
Yeah, latest edge should work but also latest "normal" (3.2.2)

Errors in the console? Worst case, feel free to create a tiny video with a fresh installation (via nuxt.new)

**Comment by jkd77** [comment] 2023-03-08 21:38
Thanks for the input - I installed 3.2.2 and got the following warnings, not really sure how to go about solving these:

`devDependencies:
- nuxt 3.0.0
+ nuxt 3.2.2 (3.2.3 is available)

 WARN  Issues with peer dependencies found
.
├─┬ @nuxtjs/tailwindcss 6.1.3
│ └─┬ @nuxt/postcss8 1.1.3
│   ├─┬ css-loader 5.2.7
│   │ └── ✕ missing peer webpack@"^4.27.0 || ^5.0.0"
│   └─┬ postcss-loader 4.3.0
│     └── ✕ missing peer webpack@"^4.0.0 || ^5.0.0"
└─┬ @tailwindcss/typography 0.5.8
  └── ✕ missing peer tailwindcss@">=3.0.0 || insiders"
Peer dependencies that should be installed:
  tailwindcss@">=3.0.0 || insiders"            webpack@">=4.27.0 <5.0.0 || >=5.0.0 <6.0.0"`

I went ahead and ran pnpm dev anyway, and the same issue persists. I'm not getting any console errors.

**Comment by danielroe** [comment] 2023-03-08 21:43
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by jkd77** [comment] 2023-03-08 22:09
Hey Daniel - does this link work?: https://stackblitz.com/edit/github-vhctgb

I've not tried to provide a repo before.

**Comment by danielroe** [comment] 2023-03-08 22:19
Does it not work for you in the sandbox? (It does for me.)

I think it might be an issue with your setup. Can you try in an incognito window, or in a fresh browser profile? Maybe try clearing your service workers.

What is your full directory path? Sometimes libraries like vite or rollup have issues with paths with spaces or quotation marks in them.

Finally, do you see any errors in your network tab (ie. files that couldn't be downloaded)?

**Comment by jkd77** [comment] 2023-03-08 23:20
Thanks for the input. I just now tried the sandbox and it did work. I'll give those suggestions a try asap.

**Comment by jkd77** [comment] 2023-03-09 19:56
Hey Daniel - I can confirm that attempting to run dev in an incognito window unfortunately did not fix the issue. If full directory path is the same as RootDir as supplied by `npx nuxi info`, then that is:

`/Applications/MAMP/htdocs/nuxt/nuxt-3/mastering-nuxt-3-main/mastering-nuxt-3`

If I'm incorrect, please let me know how I can find the full directory path. In my Google searches on this I've also come across `NUXT_APP_BASE_URL` but I haven't discovered how to retrieve it. As an aside, I wouldn't think storing the NUXT files within MAMP would be an issue. I'm also not actively running a local Mamp server instance (which I also wouldn't think would be an issue either way). I can relocate the NUXT files if that might be useful.

I'm not seeing any Console errors currently. However another data point is the tailwind viewer never loads. I try to launch it and I just get a spinning empty browser tab. Eventually, the following error appears within the Visual Studio Code terminal:

`[nuxt] [request error] [unhandled] [500] Body is unusable                                                                 13:53:13
  at specConsumeBody (node:internal/deps/undici/undici:6372:15)  
  at Response.text (node:internal/deps/undici/undici:6272:18)  
  at $fetchRaw2 (./node_modules/.pnpm/ofetch@1.0.1/node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:192:43)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async default (./node_modules/.pnpm/@nuxt+vite-builder@3.2.2_vue@3.2.47/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:16:23)  
  at async Object.renderToString (./node_modules/.pnpm/vue-bundle-renderer@1.0.2/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)                                                                                                                    13:46:42
  at async ./.nuxt/dev/index.mjs:717:21  
  at async ./.nuxt/dev/index.mjs:378:22  
  at async Object.handler (./node_modules/.pnpm/h3@1.5.0/node_modules/h3/dist/index.mjs:1196:19)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.5.0/node_modules/h3/dist/index.mjs:1271:7)
[nuxt] [request error] [unhandled] [500] fetch failed (http://localhost:3000/__nuxt_vite_node__/invalidates)              13:54:43
  at async $fetchRaw2 (./node_modules/.pnpm/ofetch@1.0.1/node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:180:24)  
  at async default (./node_modules/.pnpm/@nuxt+vite-builder@3.2.2_vue@3.2.47/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:16:23)  
  at async Object.renderToString (./node_modules/.pnpm/vue-bundle-renderer@1.0.2/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)  
  at async ./.nuxt/dev/index.mjs:717:21  
  at async ./.nuxt/dev/index.mjs:378:22  
  at async Object.handler (./node_modules/.pnpm/h3@1.5.0/node_modules/h3/dist/index.mjs:1196:19)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.5.0/node_modules/h3/dist/index.mjs:1271:7)`

**Comment by khairulhaaziq** [comment] 2023-03-14 17:55
I have the same issue, MacOS Big Sur, node v16.17.1, Nuxt 3.3.1, pnpm 7.14.0. Just boilerplate nuxt with pnpm dlx nuxi init <project-name>

**Comment by jkd77** [comment] 2023-03-28 15:26
I'll try nuxt v 3.1.1 and report back. Thanks!

**Comment by gel1123** [comment] 2023-04-11 03:14
> [nuxt] [request error] [unhandled] [500] Body is unusable   

Nuxt3.3.1 + Node v18.13.0 gives the same error.
However, this does not occur with Node v18.15.0.

**Comment by jkd77** [comment] 2023-04-13 00:27
Hey Team - combined with Node v18.15.0, neither Nuxt 3.1.1, 3.3.1, nor 3.3.3 worked for me. When attempting 3.4.0 I get a new error: Named export 'consola' not found. Various attempts to fix that have also failed.

**Comment by jkd77** [comment] 2023-04-13 00:38
I was able to fix the 3.4.0 error using:
`"pnpm": {
    "overrides": {
      "consola": "3.0.1"
    }
  }`

in package.json then reinstalling using: `pnpm install --shamefully-hoist`

hot reload still not working. It's a very hard reset in the browser situation at this point.

**Comment by pallabez** [comment] 2023-05-18 14:40
Perhaps you were using firefox? I switched to chrome, and it now works fine.

**Comment by bitsnaps** [comment] 2023-06-26 11:45
Here are the latest issues I've found in  v3.5 & v3.6 versions:
1- The warnings about peer dependencies:
```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @nuxt/devtools
  ├── ✕ missing peer vite@"*"
  ├─┬ vite-plugin-inspect
  │ └── ✕ missing peer vite@"^3.1.0 || ^4.0.0"
  ├─┬ vite-plugin-vue-inspector
  │ └── ✕ missing peer vite@"^3.0.0-0 || ^4.0.0-0"
  └─┬ @nuxt/devtools-kit
    └── ✕ missing peer vite@"*"
✕ Conflicting peer dependencies:
  vite  
```
I had to add `auto-install-peers=true` to `.npmrc` as suggested after `pnpm install`.

2- I had to disable `devtools` in `nuxt.config.ts`, otherwise I get: `performance is not defined` error (I know it's experimental feature).
3- Lastly the message:
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.3

Please only submit bug reports when using the officially supported version.
```
Can these issues be solve somehow with by installing stable versions (`--prod` option)?
I believe all these issues are related to my old node version `v14.18.3` (I know it's too old), although I've upgraded node two times last year, that's wasn't easy when maintaining too many projects simultaneously, that's ok if it was a library, but for a web framework, that's feel like we need more stable LTS versions for Nuxt?

**Comment by danielroe** [comment] 2023-10-20 10:58
I'm closing this as I can't reproduce and the latest comments are not really related to the original reported issue. If you can provide a reproduction or some steps I can take to reproduce on OSX, let me know and I'll reopen.

**Closed by danielroe** 2023-10-20 10:58 UTC
Labels: 3.x, pending triage, needs reproduction
