### ISSUE TITLE
Pinia tab is broken in `3.14`

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#29944] opened 2024-11-16 12:45 UTC
### Environment

````
------------------------------
- Operating System: Linux (Ubuntu 20.04 LTS)
- Node Version:     v20.12.2
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    -
- Package Manager:  pnpm@8.1.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.2, @vueuse/nuxt@11.2.0, @pinia/nuxt@0.7.0
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/~/github.com/martinszeltins/nuxt-3-14-pinia-issue?file=app.vue

### Describe the bug

Since Nuxt `3.14` the Pinia tab in devtools seems to be broken showing `No Data` while this was working in `3.13`

Please see the reproduction.

Screenshot:
![Image](https://github.com/user-attachments/assets/8285f163-f201-4fbc-82de-76e1b3ca928e)

### Logs

```shell-script

```

**Comment by manniL** [comment] 2024-11-16 20:38
Duplicate of https://github.com/nuxt/devtools/issues/724.

**Comment by arashsheyda** [comment] 2024-11-17 18:07
I can't reproduce it 🤔 

![Image](https://github.com/user-attachments/assets/13711b35-9756-4438-b018-3fc629de03b4)

**Comment by martinszeltins** [comment] 2024-11-17 18:15
> I can't reproduce it 🤔

Yikes! This is really strange. I just opened it in a new Chrome profile and it works while in my existing profile it does not work. Perhaps some extension might be causing the issue? Others have reported the same problem over at https://github.com/nuxt/devtools/issues/724

![Image](https://github.com/user-attachments/assets/0ef38378-1046-4954-99fb-0fc6e7154fce)

**Comment by arashsheyda** [comment] 2024-11-17 18:23
what version of chrome are you using? I haven't updated mine in a while. it might be that...

**Comment by danielroe** [comment] 2024-11-17 19:36
let's track upstream in the nuxt/devtools repo.

**Closed by danielroe** 2024-11-17 19:36 UTC
Labels: pending triage, possible regression

**Comment by serkon** [comment] 2025-08-20 00:51
It’s not stable. Sometimes it displays correctly, but other times it shows "no-data". The first initialization starts with "connecting"; I managed to see it working once, but when I press the "Reset Local Settings and States" button in the settings, everything disappears. Also, no matter what I try, I can’t see the stores again.

**Comment by klaveren** [comment] 2026-06-11 00:49
Codeless tests — check manually right now

In DevTools → Click Render Tree, then go to Pinia tab. If states appear there—just confirm they're only tree-registered (the data is present).

If you have Vue devtools on Arc: Disable it and reload.

This fixes most cases.
