### ISSUE TITLE
nuxt3.9.1在ios的qq浏览器上报错，其他浏览器正常

### ISSUE THREAD

**Issue by chenhan19** [nuxt/nuxt#25110] opened 2024-01-09 03:48 UTC
### Environment

![image](https://github.com/nuxt/nuxt/assets/57612000/e4f2df60-776d-4a1c-b36b-0ab0efce7c98)

### Reproduction

https://servicehall.chaoxing.com/home

### Describe the bug

nuxt3.9.1在ios的qq浏览器上报错，其他浏览器正常

**Comment by chenhan19** [comment] 2024-01-09 03:49
![Uploading IMG_0153.PNG…]()

**Comment by miosenpai** [comment] 2024-01-09 06:09
Possibly a duplicate of https://github.com/nuxt/nuxt/issues/24229, you might want to try some of the workarounds in that issue.

**Comment by manniL** [comment] 2024-01-09 08:08
Let's track in https://github.com/nuxt/nuxt/issues/24229

**Closed by manniL** 2024-01-09 08:08 UTC
Labels: 3.x, pending triage

**Comment by xiaoruo-lin** [comment] 2024-06-14 08:40
I also hope the author can solve this problem of QQ browser
