### ISSUE TITLE
Using method decorators in components results in fatal parse failure

### ISSUE THREAD

**Issue by alex-eliot** [nuxt/nuxt#24920] opened 2023-12-27 13:33 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mybirp?file=app.vue

### Describe the bug

There's a fatal parse failure occurring when using method decorators.

**Comment by alex-eliot** [comment] 2023-12-29 14:35
Update: the same issue was experienced in vitest and as explained by a reply in my issue for it. (https://github.com/vitest-dev/vitest/issues/4809), the main issue is **ESBuild doesn't yet support decorators**.

As mentioned in the issue I linked, the same [temporary solution](https://github.com/vitest-dev/vitest/issues/708#issuecomment-1045201786) works for Nuxt as well:

```ts
export default defineNuxtConfig({
  vite: {
    esbuild: false,
    plugins: [RollupPluginSwc()]
  }
})
```

However, I get several warnings during build that source maps are not generated by this plugin, so I cannot confirm that this solution will make Nuxt behave the same in regards to debugging.

**Comment by manniL** [comment] 2023-12-29 14:39
Is this a duplicate of https://github.com/nuxt/nuxt/issues/14126? 🤔

**Comment by alex-eliot** [comment] 2024-01-01 10:45
@manniL You are right, yeah. Though, while the core issue that ESBuild doesn't support decorators yet is the case, one of the proposed solutions (to use `@rollup/plugin-typescript`) seems to allow the dev build, but it still crashes when building for production (check https://stackblitz.com/edit/github-mybirp-mjpsra).

I have gotten both dev preview and production build to work by setting `esbuild: false` here:
```ts
import typescript from '@rollup/plugin-typescript';

export default defineNuxtConfig({
  vite: {
    esbuild: false,
    plugins: [typescript()],
  },
});
```

However, this now breaks typechecking. Try going to the reproduction URL I linked in this comment and run `npx nuxi typecheck`.

**Comment by manniL** [comment] 2024-01-01 12:49
@alex-eliot Would you mind sharing your findings in #14126 then so we can track it there and close this issue afterwards? ☺️

**Comment by alex-eliot** [comment] 2024-01-01 14:57
@manniL Thank you, I just did so, feel free to close this :)

**Closed** 2024-01-01 19:49 UTC
Labels: 3.x, pending triage
