### ISSUE TITLE
Nuxt Escalates External Console Log Levels

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt#26383] opened 2024-03-19 16:49 UTC
### Environment

Nuxt 3.11.1

### Reproduction

When upgrading from Nuxt 3.10.3 to 3.11.0, external logs in dev seem to be escalated.  In code, console.log/warn/error seem to be fine.

This shows warnings that are supposed to be debug.
https://stackblitz.com/edit/github-wg3yu6-fqhvrw

### Describe the bug

In Nuxt 3.11.0 dev logs seem to be escalated.  Logs that were warnings in 3.10.3 are now error.

This used to be just a warning in 3.10.3
![image](https://github.com/nuxt/nuxt/assets/2112282/0275decf-b6fb-4032-915f-9da6f99e9d5c)

These weren't even visible in 3.10.3 (they use debug)
![image](https://github.com/nuxt/nuxt/assets/2112282/1567cbee-d41c-486c-8068-15e5e0542c26)

**Comment by danielroe** [comment] 2024-03-21 14:01
Did you forget to add a `Test.vue` component? The stackblitz doesn't reproduce the bug you describe, it just complains about a missing file...

**Comment by hecktarzuli** [comment] 2024-03-21 14:16
@danielroe lol, that's what I get for trying to clean up a demo at the last minute.  Fixed.

**Comment by danielroe** [comment] 2024-03-21 14:44
Checking, it seems that `vite-svg-loader` _does_ call `console.warn`:

https://unpkg.com/browse/vite-svg-loader@5.1.0/index.js

**Comment by hecktarzuli** [comment] 2024-03-21 15:03
Ug, the current version uses `debug`, but for some reason it's not actually in any release even though the change was made before other releases.

https://github.com/jpkleemans/vite-svg-loader/blob/main/index.js

At this point I'm totally confused.  Any idea why Nuxt 3.10 wouldn't show these messages at all, whereas now Nuxt 3.11 does?  (Assuming it's been .warn all along)

**Comment by danielroe** [comment] 2024-03-21 15:08
Nuxt 3.11 shows the warnings because we now handle public assets resolution, and vite-svg-loader doesn't deal with that. It should be fixed in vite-svg-loader. To be honest, if you want to use it your svgs should be in `~/assets` as the `~/public` folder is not intended for files that pass through the build pipeline.

**Closed** 2024-03-21 15:09 UTC
Labels: 3.x, pending triage

**Comment by hecktarzuli** [comment] 2024-03-21 15:16
These are plain SVGs and shouldn't be in the build pipeline at all which is why we put them in the `/public` folder.  They should be treated just like a `.jpg` but for some reason either vite or nuxt is trying to pass them through a loader.
