### ISSUE TITLE
Cached pages fail to run async calls when ssr is false

### ISSUE THREAD

**Issue by marr** [nuxt/nuxt#22022] opened 2023-07-07 15:56 UTC
### Environment

3.6.2

### Reproduction

https://github.com/marr/nuxt3-bug

Make sure `ssr: false` is set in the nuxt config.

Open the `/` url, and click login. You should see that `submit()` gets called in the login.vue page, but the await refreshNuxtData call never resolves. The request that it should make to _/api_ never fires either.

There is different behavior if the page is soft loaded, so make sure you do a hard load.

### Describe the bug

It appears the the[ page caching bug fix](https://github.com/nuxt/nuxt/pull/21823) that was introduced with 3.6.2 introduces a regression. The result is that async behaviors on cached pages don't appear to run properly. Downgrading to 3.6.1 is a workaround for now, but I believe this should be addressed.

### Additional context

The commit that seems to have introduced the issue is https://github.com/nuxt/nuxt/commit/d0dde6426fe6ae58ec1ea94e47c66f6e0e2a4d63

**Comment by ChronicStone** [comment] 2023-07-17 08:02
Since I can't downgrade to 3.6.1 (needed fixes from 3.6.2) and my temporary fix for this, that kind of does the job, is to simply clear cache between each route navigation with clearNuxtData.

Not really a solution, more like monkey patching, but does the job until the issue is adressed.

**Comment by danielroe** [comment] 2023-07-17 09:39
If someone picks this up before me, I believe the issue here is that we never properly mark Nuxt as fully hydrated.

**Comment by ChronicStone** [comment] 2023-07-17 09:52
@danielroe When in the lifecycle should we consider nuxt is fully hydrated & mark it ? I want to give this a shot, but I'm not sure I fully understand how nuxt hydration works.

**Closed** 2023-07-18 15:21 UTC
Labels: 3.x, bug, ❗ p4-important
