### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by Artem-Schander** [nuxt/nuxt#21841] opened 2023-06-28 14:50 UTC
### Environment

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, modules, app, imports
- Runtime Modules:  @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

1. Open https://vs3g68-3000.csb.app/foo
2. click on `Bar Layout` link

### Describe the bug

Layout loading fails

### Additional context

See also #13309 (possibly not related)

**Comment by manniL** [comment] 2023-06-28 16:14
@danielroe should be https://codesandbox.io/p/sandbox/vs3g68

**Comment by Artem-Schander** [comment] 2023-06-28 16:18
Sorry @danielroe 
Thats correct. Thanks @manniL

**Comment by theguriev** [comment] 2023-07-25 18:03
I have the same with navigation back

**Comment by danielroe** [comment] 2023-08-01 11:55
The issue here is that you are changing the layout in a global store during the transition. So it starts changing the layout on the old page as well as the new one.

This is an upstream Vue bug: https://github.com/vuejs/core/issues/6463.

However you can probably resolve by not setting the layout in a _single_ global store but instead on the metadata for that individual route, which will not change the layout on the _old_ page while transitioning.

**Comment by tomsdob** [comment] 2023-08-01 12:03
@danielroe Is it really the same Vue bug as in #22353? I don't use multiple layouts there and still get this error.

**Comment by danielroe** [comment] 2023-08-01 12:11
The issue isn't layouts as such, but rerendering a node within suspense while a transition is taking place.

**Comment by tomsdob** [comment] 2023-08-01 12:37
@danielroe What would be the right way to fix the issue I'm dealing with (redirecting to the same route but adding/changing a query param in setup)? I don't seem to be implementing any transitions when navigating to the route as far as I know.

**Comment by Artem-Schander** [comment] 2023-08-02 08:10
> The issue here is that you are changing the layout in a global store during the transition. So it starts changing the layout on the old page as well as the new one.
> 
> This is an upstream Vue bug: [vuejs/core#6463](https://github.com/vuejs/core/issues/6463).
> 
> However you can probably resolve by not setting the layout in a _single_ global store but instead on the metadata for that individual route, which will not change the layout on the _old_ page while transitioning.

Ok, thank you for the info. I'll try the suggested approach

**Comment by Artem-Schander** [comment] 2023-08-02 09:33
@danielroe 
I managed to solve it, Thanks again for the tip.
However, I was not able to get it done with `definePageMeta` (which, if I understood it correctly, is what you suggested). Instead I needed to solve it with a nasty `setTimeout`. I think the reason is that the layout info comes from the API asynchronously.
I'll keep my eye on vuejs/core#6463, Maybe there will be no need for this workaround anytime soon.

**Comment by ilyaDegtyarenko** [comment] 2023-09-14 17:40
Nuxt 3.7.3 @danielroe 

Detailed reproduction:
https://stackblitz.com/edit/nuxt-starter-btlcfb?file=pages%2Fwaiting.vue

**Comment by ilyaDegtyarenko** [comment] 2023-09-14 18:43
Related issue with nuxt 3.7.3 

[https://github.com/nuxt/nuxt/discussions/23221](https://github.com/nuxt/nuxt/discussions/23221)

**Comment by mlsjla** [comment] 2023-12-19 17:10
the same issues as https://nuxt.com/blog.

when I fast click the menu...

and then  console got error

![1234](https://github.com/nuxt/nuxt/assets/9654331/b5f54653-0c02-46fc-b97c-309e983f67a4)

**Comment by dargmuesli** [comment] 2023-12-21 10:46
@Artem-Schander, would you please check if [vue@3.4.0-beta.3](https://github.com/nuxt/nuxt/issues/13309#issuecomment-1861104026) solves the issue?

**Comment by Artem-Schander** [comment] 2023-12-21 11:31
@dargmuesli 
For some reason my codesandbox has been reset :(
In my current project the beta.3 seems to solve the issue. However, the project is quite complex and I'm not sure if I can rely on this quick test. I'll try to get the repro back and let you know how it behaves there.

**Comment by manniL** [comment] 2024-01-01 22:49
Closing here as most likely resolved via Vue 3.4.0

I'll open another issue that reflects what @ilyaDegtyarenko posted.

**Closed by manniL** 2024-01-01 22:49 UTC
Labels: 3.x, pending triage
