### ISSUE TITLE
Error on using postcss

### ISSUE THREAD

**Issue by vahid-bagh3ri** [nuxt/nuxt#18814] opened 2023-02-06 13:34 UTC
### Environment

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 690.30 MB / 15.78 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.23.0-20220130.1630 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566

### Reproduction

-

### Describe the bug

This bug happened in the first installation of "nuxt": "^2.15.8" project, also in my old projects after reinstalling the packages.

I tried several different ways such as upgrading nuxt to v2.16.0 or upgrading PostCSS to v8 and tried different configuration docs of postCss plugins, but it's still the same Error.

### Logs

```shell-script
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }
```

**Comment by acibilous** [comment] 2023-02-06 14:31
please use schema in nuxt.config:
```postcss: {
      postcssOptions: {
        plugins
```

**Comment by robinscholz** [comment] 2023-02-06 14:34
Running into the same error, with the following (I assume correct) build property in my `nuxt.config.ts`

```
build: {
    postcss: {
      postcssOptions: {
        plugins: {
          'postcss-import': {},
          'postcss-each': {
            plugins: {
              beforeEach: [require('@tailwindcss/nesting')],
            },
          },
          tailwindcss: tailwindConfig,
          'postcss-custom-media': {},
          autoprefixer: {},
        },
      },
    },

    // @ts-ignore
    transpile: [
      '@thenightleague/shared',
      'tailwindcss/plugin',
      'lodash-es',
      'blaze-slider',
      'vee-validate/dist/rules',
    ],
  },
  ```

**Comment by manniL** [comment] 2023-02-06 15:16
When upgrading to `v2.16`, you might have to "manually" upgrade postcss to version 8.

**Comment by vahid-bagh3ri** [comment] 2023-02-06 15:23
> When upgrading to `v2.16`, you might have to "manually" upgrade postcss to version 8.

I've Already updated but it's still the same

But I'll try again

**Comment by robinscholz** [comment] 2023-02-06 15:28
@manniL https://github.com/nuxt/bridge/issues/701 Pretty sure this is the problem.
@vahid-bagh3ri If you run bridge, try disabling postcss8 in the bridge options in your nuxt.config.js:

```
 bridge: {
    postcss8: false,
  },
  ```

**Comment by vahid-bagh3ri** [comment] 2023-02-06 15:29
> @vahid-bagh3ri Do you run nuxt-bridge?

No I mean v2.16.0

**Comment by vahid-bagh3ri** [comment] 2023-02-06 15:33
> When upgrading to `v2.16`, you might have to "manually" upgrade postcss to version 8.

I've tried with following configs

```
   "dependencies": {
    	"nuxt": "2.16.0",
	},
    "devDependencies": {
   		"postcss": "^8.4.5"
	}
```
config:
```
  build: {
    postcss: {
      postcssOptions: {
        plugins: {
          autoprefixer: {},
          'postcss-import': {}
        }
      }
    }
  }
```

**Comment by robinscholz** [comment] 2023-02-06 15:40
@vahid-bagh3ri can you share your package.json as well as your nuxt.config.js files here?

**Comment by vahid-bagh3ri** [comment] 2023-02-06 15:50
@robinscholz 
**Yes For Sure but I removed unnecessary lines**


Package.json: 
<details>
<summary>Details</summary>

```{
  "name": "untitle",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint:prettier": "prettier --check .",
    "lint": "yarn lint:js && yarn lint:prettier",
    "lintfix": "prettier --write --list-different . && yarn lint:js --fix"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.113.0",
    "@aws-sdk/lib-storage": "^3.113.0",
    "@nuxt/content": "^1.15.1",
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/composition-api": "^0.33.0",
    "@nuxtjs/i18n": "^7.2.0",
    "@nuxtjs/proxy": "^2.1.0",
    "@nuxtjs/pwa": "^3.3.5",
    "@tailwindcss/line-clamp": "^0.4.0",
    "@vueuse/components": "^9.2.0",
    "@vueuse/integrations": "^9.2.0",
    "aws-s3": "^2.0.5",
    "cookie-universal-nuxt": "^2.1.5",
    "core-js": "^3.23.1",
    "fuse.js": "^6.6.1",
    "gsap": "^3.10.4",
    "nuxt": "2.16.0",
    "qs": "^6.10.5",
    "ua-parser-js": "^1.0.2",
    "vee-validate": "^3.4.14",
    "vue": "^2.7.7",
    "vue-demi": "^0.13.1",
    "vue-server-renderer": "^2.7.7",
    "vue-template-compiler": "^2.7.7",
    "vuetify": "^2.6.1",
    "vuex": "3.6.2",
    "webpack": "^4.46.0"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.16.3",
    "@mdi/js": "^6.5.95",
    "@nuxt/kit": "3.0.0-rc.13",
    "@nuxtjs/eslint-config": "^8.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/svg": "^0.4.0",
    "@nuxtjs/tailwindcss": "^5.0.0-4",
    "@nuxtjs/vuetify": "^1.12.3",
    "@vueuse/core": "^9.2.0",
    "@vueuse/nuxt": "^9.2.0",
    "autoprefixer": "^10.4.2",
    "eslint": "^8.4.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-nuxt": "^3.1.0",
    "eslint-plugin-vue": "^8.2.0",
    "postcss": "^8.4.5",
    "prettier": "^2.5.1"
  },
  "resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
  }
}
```

</details>

Nuxt.config.js: 
<details>
<summary>Details</summary>

```{
import fa from './locale/i18n/fa.js'

export default {
  // Global CSS: https://go.nuxtjs.dev/config-css
  css: ['@/assets/css/main.scss', '@/assets/css/tailwind.css'],
  devServerHandlers: [],

// Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    '@nuxtjs/eslint-module',
    // https://github.com/nuxt-community/tailwindcss-module
    '@nuxtjs/tailwindcss',
    // https://github.com/nuxt-community/composition-api
    '@nuxtjs/composition-api/module',
  ],

  tailwindcss: {
    cssPath: '~/assets/css/tailwind.css',
    configPath: 'tailwind.config.js',
    exposeConfig: false,
    config: {},
    injectPosition: 0,
    viewer: true
  },

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    postcss: {
      postcssOptions: {
        plugins: {
          autoprefixer: {},
          'postcss-import': {}
        }
      }
    },
    terser: {
      terserOptions: {
        compress: {
          drop_console: true
        }
      }
    },
    extend(config, { isDev, isClient }) {
      config.node = {
        fs: 'empty'
      }

      // ....
    }
  },
}

```

</details>

**Comment by danielroe** [comment] 2023-02-06 17:27
I suspect this is caused by the version of `@nuxtjs/tailwindcss` you are using. It likely is setting a property directly on `build.postcss.plugins`. Would you try entirely removing your plugins object in your nuxt.config, or moving it outside `postcssOptions` to see if that makes a difference?

**Comment by vahid-bagh3ri** [comment] 2023-02-06 17:40
> I suspect this is caused by the version of `@nuxtjs/tailwindcss` you are using. It likely is setting a property directly on `build.postcss.plugins`. Would you try entirely removing your plugins object in your nuxt.config, or moving it outside `postcssOptions` to see if that makes a difference?

@danielroe 

```
    postcss: {
      plugins: {
        autoprefixer: {},
        'postcss-import': {}
      }
    }
```

If you mean this, it doesn't make any difference.

**Comment by vahid-bagh3ri** [comment] 2023-02-06 17:49
@danielroe 
I got the same result by installing  `"@nuxtjs/tailwindcss": "6.1.3"`

**Comment by danielroe** [comment] 2023-02-06 17:50
It might not be that module then. Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment] 2023-02-06 22:59
resolved in https://github.com/nuxt/nuxt/pull/18839

**Closed by danielroe** 2023-02-06 22:59 UTC
Labels: 2.x, bug, webpack

**Comment by vahid-bagh3ri** [comment] 2023-02-07 05:56
Sorry for late @danielroe
Reproduction:
https://stackblitz.com/edit/nuxt-starter-vsudyh
