### ISSUE TITLE
upgrade nuxt 3.0.0 to 3.2.2 create error on dev server (reading 'port' of undefined)

### ISSUE THREAD

**Issue by Alireza1996Sh** [nuxt/nuxt#19164] opened 2023-02-20 08:14 UTC
### Environment

Nuxt project info:                                                    07:37:15

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `buildModules`, `css`, `purgecss`, `vite`, `nitro`, `runtimeConfig`, `experimental`, `app`, `sourcemap`
- Runtime Modules:  `@vueuse/nuxt@9.3.1`, `@pinia/nuxt@0.4.3`
- Build Modules:    `@nuxtjs/eslint-module@3.1.0`, `nuxt-purgecss@2.0.0`
------------------------------

### Reproduction

here is `nuxt.config.js`
```js
import postcssRTLCSS from 'postcss-rtlcss';
import {VitePWA} from 'vite-plugin-pwa';
import app from './config/app';

export default defineNuxtConfig({
  modules: [
    '@vueuse/nuxt',
    '@pinia/nuxt',
  ],
  buildModules: [
    '@nuxtjs/eslint-module',
    'nuxt-purgecss',
  ],
  css: [
    '~/assets/styles/vendors/bootstrap/index.scss',
    '~/assets/styles/globals/index.scss',
  ],
  purgecss: {
    enabled: true,
  },
  vite: {
    server: {
      hmr: {
        protocol: 'ws',
        host: process.env.HOST,
      },
    },
    css: {
      postcss: {
        plugins: [
          postcssRTLCSS(),
        ],
      },
    },
    plugins: [
      VitePWA({
        base: '/',
        workbox: {
          navigateFallback: null,
        },
        manifest: {
          name: app.name,
          short_name: app.shortName,
          description: app.description,
          dir: app.dir,
          lang: app.lang,
          theme_color: app.themeColor,
          background_color: app.backgroundColor,
          icons: app.icons.manifest,
        },
      }),
    ],
  },
  nitro: {
    compressPublicAssets: true,
  },
  runtimeConfig: {
    mainApi: process.env.MAIN_API_SERVER,
    treksPageCache: process.env.TREKS_PAGE_CACHE,
    agenciesPageCache: process.env.AGENCIES_PAGE_CACHE,

    public: {
      mosaferanUrl: process.env.MOSAFERAN_URL,
      mainApi: process.env.MAIN_API_CLIENT,
      leafletTileUrl: process.env.LEAFLET_TILE_URL,
      gaMeasurementId: process.env.GA_MEASUREMENT_ID,
      gaDebugger: process.env.GA_DEBUGGER,
    },
  },
  experimental: {
    writeEarlyHints: false,
  },
  app: {
    buildAssetsDir: process.env.NUXT_APP_ASSETS_PATH,
    cdnURL: process.env.NUXT_APP_CDN_URL,
    pageTransition: false,
    layoutTransition: false,
  },
  sourcemap: {
    client: process.env.SOURCEMAP_CLIENT === 'true',
  },
});
```
here is `.env`
```env
HOST=172.20.20.52
PORT=3000

MOSAFERAN_URL="http://mos.test"
MAIN_API_CLIENT="http://api.mos.test"
MAIN_API_SERVER="http://api.mos.test"

NUXT_APP_ASSETS_PATH=""
NUXT_APP_CDN_URL="http://mos.test"

LEAFLET_TILE_URL=https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png

GA_MEASUREMENT_ID=""
GA_DEBUGGER="false"

TREKS_PAGE_CACHE=10 # time in seconds
AGENCIES_PAGE_CACHE=10 # time in seconds

SOURCEMAP_CLIENT=true
```
here is `package.json`
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "analyze": "nuxt analyze",
    "postinstall": "nuxt prepare",
    "lint": "eslint --fix --ext .js,.ts,.vue ."
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^11.0.0",
    "@nuxtjs/eslint-module": "^3.1.0",
    "@types/bootstrap": "^5.2.5",
    "@vueuse/core": "^9.3.1",
    "@vueuse/nuxt": "^9.3.1",
    "eslint": "^8.25.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "nuxt": "^3.2.2",
    "nuxt-purgecss": "^2.0.0",
    "postcss-rtlcss": "^4.0.1",
    "sass": "^1.55.0",
    "vite-plugin-pwa": "^0.13.1",
    "vue-gtag-next": "^1.14.0"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.3",
    "@vue-leaflet/vue-leaflet": "0.5.0",
    "@vueform/multiselect": "^2.5.6",
    "@vueform/slider": "^2.1.5",
    "bootstrap": "^5.2.2",
    "dayjs": "^1.11.5",
    "jalaliday": "^2.3.0",
    "leaflet": "1.9.1",
    "lodash": "^4.17.21",
    "mobile-detect": "^1.4.5",
    "qs": "^6.11.0",
    "resize-sensor": "^0.0.6",
    "sticky-sidebar": "^3.3.1",
    "swiper": "^8.4.4",
    "vue-toastification": "^2.0.0-rc.5"
  }
}
```

### Describe the bug

The bug appeared after upgrading to `nuxt@3.2.2` from `nuxt@3.0.0` using `npx nuxi upgrade`.
dev server could not start because of the following error:
```
Nuxi 3.2.2
Nuxt 3.2.2 with Nitro 2.2.2
 
 ERROR  Cannot read properties of undefined (reading 'host')

  at Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6768:82)
  at async _main (node_modules/nuxi/dist/cli.mjs:51:20)
```

so I went to `node_modules/nuxi/dist/chunks/dev.mjs:6768:82` and then I saw the following code:
```js
const listener = await listen(serverHandler, {
  showURL: false,
  clipboard: args.clipboard,
  open: args.open || args.o,
  port: args.port || args.p || process.env.NUXT_PORT || config.devServer.port,
  hostname: args.host || args.h || process.env.NUXT_HOST || config.devServer.host,
  https: args.https !== false && (args.https || config.devServer.https) ? {
    cert: args["ssl-cert"] || config.devServer.https && config.devServer.https.cert || void 0,
    key: args["ssl-key"] || config.devServer.https && config.devServer.https.key || void 0
  } : false
});
```
I wrote `console.log(args)` and there was just this: `{ _: [] }`
then I added `NUXT_PORT=3000` in my `.env` file and another error appeared:
```
ERROR  Cannot read properties of undefined (reading 'host')
  at Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6769:82)
  at async _main (node_modules/nuxi/dist/cli.mjs:51:20)
```
then I added `NUXT_HOST=172.20.20.52` in my `.env` file and again another error appeared:
```
ERROR  Cannot read properties of undefined (reading 'https')
  at Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6770:70)
  at async _main (node_modules/nuxi/dist/cli.mjs:51:20)
```
I couldn't do anything about it.
So I wrote `console.log(config.devServer)` and it was `undefined`
Then I found out that the problem was `config.devServer`
I added the `devServer: {}` to `nuxt.config.js` and I solved my problem.
but this is not true solution
it's better you handle the problem in your code

**Comment by MeeDNite** [comment] 2023-02-20 08:28
I can confirm this.

**Comment by danielroe** [comment] 2023-02-20 09:33
Thanks for the report. For now, you can likely workaround by passing `devServer: {}` in your Nuxt options.

**Comment by hassan715** [comment] 2023-02-20 10:49
I can confirm this, with an error message `config.devServer is undefined`.

**Comment by Alireza1996Sh** [comment] 2023-02-20 13:14
> Thanks for the report. For now, you can likely workaround by passing `devServer: {}` in your Nuxt options, as you have pointed out.
> 
> Is there any chance you have an older version of `@nuxt/schema` in your project? (Check your lockfile.)

@danielroe 

I checked my `yarn.lock` file and here we are:
```
"@nuxt/kit@3.2.2", "@nuxt/kit@^3.2.0":
  version "3.2.2"
  resolved "https://registry.yarnpkg.com/@nuxt/kit/-/kit-3.2.2.tgz#5b369122ce853f99ecaf8cddc950ad8c4ca47e58"
  integrity sha512-T3UeLxGSNl7dQgKzmtBbPEkUiiBYgXI+KkemmpkYbQK/l+bWy2f9VQw/Rl0HkQLfRTE2fS8q8jhsOedFiEnHQQ==
  dependencies:
    "@nuxt/schema" "3.2.2"
    ...

"@nuxt/kit@^3.0.0-rc.11":
  version "3.0.0-rc.12"
  resolved "https://registry.yarnpkg.com/@nuxt/kit/-/kit-3.0.0-rc.12.tgz#637ab3e63d4213b886ab3cda19632bd08bc5ccb6"
  integrity sha512-d/6SeNVL1OPdru5aKjjUIWIwqIjbYN/VYGCrZs5gddkzJ5202DsMxyn2rs/ZyT8+oBbbVTYcCK6M+G0945mQdA==
  dependencies:
    "@nuxt/schema" "3.0.0-rc.12"
    ...


"@nuxt/schema@3.0.0-rc.12":
  version "3.0.0-rc.12"
  resolved "https://registry.yarnpkg.com/@nuxt/schema/-/schema-3.0.0-rc.12.tgz#2980cb83738093db88143d406608cf39f0bfa9ff"
  integrity sha512-LZFy8a+5tZKtqTHvUJrlCjZXmKPSmar4S/p3SpjzgIbc4jDuWzA5r4voUODozd2/bCnYxfYyNtOgtbJSJtDUrw==
  dependencies:
    c12 "^0.2.13"
    ...

"@nuxt/schema@3.2.2":
  version "3.2.2"
  resolved "https://registry.yarnpkg.com/@nuxt/schema/-/schema-3.2.2.tgz#61a305f83df266c02b4018d840421fcf84d4ee51"
  integrity sha512-o3O2OqLAMKqb/DlGpK8eJq4tH29NA4OMaohknSSXl35+Nw/qHB5eOLDz+cFxNE+MKHoMj1rRVMCfi/Y/PrCN6g==
  dependencies:
    c12 "^1.1.2"
    ...

nuxt@^3.2.2:
  version "3.2.2"
  resolved "https://registry.yarnpkg.com/nuxt/-/nuxt-3.2.2.tgz#c9017e5b2a0a1d5004a36036a238ebf0e4cdf20f"
  integrity sha512-fxO8zjNwWBd6ORvuOgVFXksd0+eliWSNQwACsCwqNRFXsjFawONfvqtdTd/pBOlRDZMJpPUTvdflsyHPaAsfJg==
  dependencies:
    "@nuxt/kit" "3.2.2"
    "@nuxt/schema" "3.2.2"
    ...
```

**Comment by danielroe** [comment] 2023-02-20 13:15
Would you refresh your lockfile with `npx nuxi upgrade --force` and let me know if it resolves the issue? 🙏

**Comment by danielroe** [comment] 2023-02-20 13:30
Okay, I think we can confirm that the issue is that your kit (which imports schema) and nuxt versions were mismatching. We can track improving resolving the right kit version in https://github.com/nuxt/nuxt/issues/14146.

**Closed by danielroe** 2023-02-20 13:30 UTC
Labels: 3.x, workaround available, pending triage, needs reproduction

**Comment by feritarou** [comment] 2023-05-04 17:41
I have the same issue running Nuxt 3.4.3, and nothing seems to resolve it. I have tried:
- updating `@nuxt/kit` using `nuxi upgrade --force`
- explicitly installing the kit as recommended [here](https://nuxt.com/docs/guide/going-further/kit)
- explicitly adding `@nuxt/schema@3.4.3` as a dev dependency
- adding the suggested workaround, an empty-object `devServer` option in `nuxt.config.ts`

I've been removing `yarn.lock` and `node_modules` and re-installing everything after each of these steps to no avail.
It seems like I have a dependency which always restores the schema in version 3.0.0, so it is always present alongside the 3.4.3 one no matter what I do:
```
"@nuxt/schema@3.4.3", "@nuxt/schema@^3.4.3":
  version "3.4.3"
  resolved "https://registry.yarnpkg.com/@nuxt/schema/-/schema-3.4.3.tgz#106548003b7bbc40428b2af290b31b1e89acffc5"
  integrity sha512-8bv0/mRDw6THQguSz+cKG5FzDZc2XBkjcc5VZ7yET84r4aWzW9/R274cjlEagFKrw9BDaPEQhnkwpg+kZnpOUA==
  dependencies:
    defu "^6.1.2"
    hookable "^5.5.3"
    pathe "^1.1.0"
    pkg-types "^1.0.2"
    postcss-import-resolver "^2.0.0"
    std-env "^3.3.2"
    ufo "^1.1.1"
    unimport "^3.0.6"
    untyped "^1.3.2"

"@nuxt/schema@npm:@nuxt/schema-edge@3.0.0-27338323.1e98259":
  version "3.0.0-27338323.1e98259"
  resolved "https://registry.yarnpkg.com/@nuxt/schema-edge/-/schema-edge-3.0.0-27338323.1e98259.tgz#c9aeedfcde18a5d81404df9e5012ec3707ad6c23"
  integrity sha512-TV8HMFEkD2cMLnsYBE0+wQcOSwElw6SW4rnDOFoDhHI61GeflpGZOfXLQRJS2FLAyMv/QVeBHdd+PWWOxDqGgA==
  dependencies:
    create-require "^1.1.1"
    defu "^5.0.0"
    jiti "^1.12.9"
    pathe "^0.2.0"
    scule "^0.2.1"
    std-env "^3.0.1"
    ufo "^0.7.9"
```
And the same holds for the kit.
This makes the dev server crash with an error
```
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'https')                                                                                                                                                   19:24:31

  at buildClient (/home/.../node_modules/@nuxt/vite-builder/dist/shared/vite-builder.b946f6f0.mjs:285:38)
  at async bundle (/home/.../node_modules/@nuxt/vite-builder/dist/shared/vite-builder.b946f6f0.mjs:851:3)
  at async build (node_modules/nuxt/dist/index.mjs:3175:5)
  at async Promise.all (index 1)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:210:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:233:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)
```
Any suggestions on how I can force the schema to stick to only the later (3.4.3.) version?

**Comment by danielroe** [comment] 2023-05-04 20:13
you can add this to your `package.json`:

```json
{
  "resolutions": {
    "@nuxt/schema": "3.4.3"
  }
}
```

**Comment by hhofner** [comment] 2023-09-19 23:45
I'm still getting this issue on a fresh install of Nuxt using this command:

```
pnpm dlx nuxi@latest init <project-name>
```

and I've added the resolutions to my `package.json` but it didn't do anything.
<img width="924" alt="Screenshot 2023-09-19 at 17 43 25" src="https://github.com/nuxt/nuxt/assets/12394200/13fe61c1-604b-463d-873e-1e0ae10005c8">
