### ISSUE TITLE
Adding typescript plugin via addPlugin isn't transpiled into js

### ISSUE THREAD

**Issue by GM-Alex** [nuxt/nuxt#10619] opened 2022-08-03 21:25 UTC
### Versions

- nuxt: 2.15.8
- node: v16.15.1

### Reproduction

Create a plugin with Typescript and add it via a module with the following code:

```
this.addPlugin({
    src: path.resolve(__dirname, 'plugin.ts'),
    fileName: 'plugin.js',
    options
});
```

### Steps to reproduce

see above

### What is Expected?

plugin.ts is transpiled into plugin.js

### What is actually happening?

The plugin code is copied to the .nuxt build folder as plugin.js but still in typescript instead of javascript.

**Comment by bianliuzhu** [comment] 2022-08-13 02:24
Nice to talk to you. I am a developer in China, I like the framework of NUXT very much， But it also brings me some troubles Because we do not know much about the bottom implementation and operating principle of NUXT.
About the following four issues, I hope to get a little inspiration from you  thank you very much

I use NUXT2


Will using Vuex reduce performance?
Will Vuex run on the server? and will vuex data be downloaded from the server to the client?
Does the use of Vuex increase the memory?
The same state, what is the difference between storing in vuex and storing in components

**Comment by avxkim** [comment] 2023-03-20 13:57
@danielroe nuxt 2.16, issue remains!

**Comment by danielroe** [comment] 2023-03-20 21:22
What makes you think these files should be transpiled? Would you provide a reproduction? Are you using nuxt/typescript-build?

**Comment by danielroe** [comment] 2023-03-20 22:14
Just checking this out, this works fine with nuxt/typescript-build, assuming you copy it with `fileName: 'plugin.ts'`. And Nuxt 2 does not otherwise have support for TypeScript, so I think we can safely close this.

It is worth adding that Nuxt 3 has built-in support for TypeScript.

**Closed by danielroe** 2023-03-20 22:14 UTC
Labels: pending triage, 2.x, needs reproduction

**Comment by avxkim** [comment] 2023-03-21 03:49
> Just checking this out, this works fine with nuxt/typescript-build, assuming you copy it with `fileName: 'plugin.ts'`. And Nuxt 2 does not otherwise have support for TypeScript, so I think we can safely close this.
> 
> It is worth adding that Nuxt 3 has built-in support for TypeScript.

Yes, i do have nuxt/typescript-build installed:

```js
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
    '@nuxtjs/eslint-module',
    '@nuxtjs/vuetify',
    '@nuxtjs/date-fns',
    '@nuxtjs/composition-api/module',
  ],
```

And still it doesn't transpile as you said.

This is contents of my custom module index.ts:


```js
import type { Module } from '@nuxt/types'
import { resolve } from 'path'

const sharedModule: Module = function () {
  this.addPlugin({
    src: resolve(__dirname, 'lib/plugins/plugin.ts'),
    mode: 'client',
  })
}

export default sharedModule
```

**Comment by danielroe** [comment] 2023-03-21 08:20
Here's a working example: https://stackblitz.com/edit/github-gqugvr.

**Comment by avxkim** [comment] 2023-04-01 12:58
@danielroe it works, when the module is a part of your app, but in case if you use NX monorepo, there's different folder structure:

-apps
--my_app
-libs
--shared

obviously it's not transpiling external modules/plugins
