### ISSUE TITLE
v3.3.1 breaks v2.16

### ISSUE THREAD

**Issue by MooseSaeed** [nuxt/nuxt#19717] opened 2023-03-15 18:31 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.2`
- Package Manager:  `npm@9.6.1`
- Builder:          `webpack`

-----

After the recent updates to `@nuxt/kit` and `@nuxt/schema` in nuxt v3.31, any nuxt app running on v2.16.* will have a problem if we run `npm install` without having package-lock.json. 

When running `npm run dev` or `npm run build`:

```
 ✖ Nuxt Fatal Error 
   │   Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in                             │
   │   /Users/said/Desktop/Mostafa/Gfinity/repos/stealthoptional/node_modules/@nuxt/kit/package.json 
```

This was solved when I replaced `@nuxt/kit@3.3.1` in package-lock.json with `@nuxt/kit@3.2.3` and `@nuxt/schema@3.3.1` with `@nuxt/schema@3.2.3`

### Reproduction

Reproducing the issue is easy:
1- Nuxt v2.16.2 project without package-lock.json file.
2- npm install
3- npm run dev or build

### Describe the bug

After the recent updates to `@nuxt/kit` and `@nuxt/schema` in nuxt v3.31, any nuxt app running on v2.16.* will have a problem if we run `npm install` without having package-lock.json. 

When running `npm run dev` or `npm run build`:

```
 ✖ Nuxt Fatal Error 
   │   Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in                             │
   │   /Users/said/Desktop/Mostafa/Gfinity/repos/stealthoptional/node_modules/@nuxt/kit/package.json 
```

**Comment by danielroe** [comment] 2023-03-16 10:45
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by MartinX3** [comment] 2023-03-16 10:47
@danielroe 
```
"overrides": {
    "unplugin": "1.1.0"
}
```
fixes it

**Comment by MooseSaeed** [comment] 2023-03-16 11:45
> reproduction

I'm still getting the error even after adding the mentioned code to package.json

```
 FATAL  No "exports" main defined in /Users/said/Desktop/Mostafa/site/repos/site/node_modules/@nuxt/kit/package.json                  13:44:12

  at new NodeError (node:internal/errors:371:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:645:7)
  at resolveExports (node:internal/modules/cjs/loader:482:36)
  at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:241025)
  at jiti (node_modules/jiti/dist/jiti.js:1:243309)
  at node_modules/@ryntab/web-vitals/dist/module.mjs:3:12
  at Resolver.jiti [as _require] (node_modules/jiti/dist/jiti.js:1:245784)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:267:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:122:38)
  at node_modules/@nuxt/utils/dist/utils.js:490:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:34:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:342:5)


   ╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                 │
   │   ✖ Nuxt Fatal Error                                                                            │
   │                                                                                                 │
   │   Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in                           │
   │   /Users/said/Desktop/Mostafa/site/repos/site/node_modules/@nuxt/kit/package.json   │
   │                                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by MooseSaeed** [comment] 2023-03-16 11:46
> @danielroe
> 
> ```
> "overrides": {
>     "unplugin": "1.1.0"
> }
> ```
> 
> fixes it. Any higher unplugin version breaks nuxt bridge. It appears on new projects or if you remove your node_modules and (p)npm-lock.yaml.
> 
> Same issue:
> 
> * [Nuxt 2 to Bridge Migration: ERROR No "exports" main defined in node_modules/@nuxt/kit/package.json   bridge#716](https://github.com/nuxt/bridge/issues/716)
> * [Missing dependency error in new project bridge#715](https://github.com/nuxt/bridge/issues/715)

> reproduction

I'm still getting the error even after adding the mentioned code to package.json

```
 FATAL  No "exports" main defined in /Users/said/Desktop/Mostafa/site/repos/site/node_modules/@nuxt/kit/package.json                  13:44:12

  at new NodeError (node:internal/errors:371:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:645:7)
  at resolveExports (node:internal/modules/cjs/loader:482:36)
  at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:241025)
  at jiti (node_modules/jiti/dist/jiti.js:1:243309)
  at node_modules/@ryntab/web-vitals/dist/module.mjs:3:12
  at Resolver.jiti [as _require] (node_modules/jiti/dist/jiti.js:1:245784)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:267:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:122:38)
  at node_modules/@nuxt/utils/dist/utils.js:490:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:34:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:342:5)


   ╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                 │
   │   ✖ Nuxt Fatal Error                                                                            │
   │                                                                                                 │
   │   Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in                           │
   │   /Users/said/Desktop/Mostafa/site/repos/site/node_modules/@nuxt/kit/package.json   │
   │                                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by danielroe** [comment] 2023-03-16 11:49
Okay, closing in favour of bridge issue, as this is not replicable on a pure Nuxt 2 project without bridge.

**Comment by danielroe** [comment] 2023-03-16 12:02
Okay - would you provide a reproduction? 🙏

**Comment by erdemyunsel** [comment] 2023-03-16 15:06
I have nuxt2 project running successfully on Vercel. It hasn't been getting builds since yesterday due to this error.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/8062528/225659477-e4595842-ad04-4daf-bd02-188ccc4bb25d.png">

**Comment by Rafa410** [comment] 2023-03-16 15:22
> I have nuxt2 project running successfully on Vercel. It hasn't been getting builds since yesterday due to this error.
> 
> <img alt="image" width="956" src="https://user-images.githubusercontent.com/8062528/225659477-e4595842-ad04-4daf-bd02-188ccc4bb25d.png">

Same problem here, deploying a pure Nuxt 2 project with Node v16.x to Vercel returns this build error. It was working 2 days ago and nothing was changed in package.json or package-lock.json recently.

**Comment by danielroe** [comment] 2023-03-16 16:02
I would guess that Vercel was ignoring your lockfile in this case. Check your logs to see why.

**Comment by mplno** [comment] 2023-03-16 16:43
I had the same errors during Vercel deploy as @Rafa410 and @erdemyunsel; using Next 2.15.8.

It does look related to the lockfile. I don't have evidence that Vercel ignored it. But I noticed @nuxt/kit and @nuxt/schema where both not listed anywhere in my package-lock.json file.

Adding those dependencies directly to the project gets the app building on Vercel:

```
npm i @nuxt/kit@3.2.3 --save
npm i @nuxt/schema@3.2.3 --save
```

I'm still not sure about the root cause, but wanted to offer those steps as a clue to those who find this issue.

**Comment by danielroe** [comment] 2023-03-16 16:44
That's an interesting idea. I wonder if this is to do with `@nuxtjs/web-vitals`, which Vercel may be installing for you.

**Comment by andreaminieri** [comment] 2023-03-16 21:01
I had the same issue: a pure Nuxt 2 project deployed on Vercel. We hadn't done any new pushes in a few weeks, today I made a small change to a text, pushed and got the same error: 

```
[fatal] No "exports" main defined in /vercel/path0/node_modules/@nuxt/kit/package.json
```

Redeploys of previous builds that were working gave the same error.

I found this issue just now and can confirm that  nuxt-modules/web-vitals#64 fixed the error. I redeployed the same build that was giving error just before and now it is generated successfully. Thanks for the very quick hotfix.

**Comment by ritter1** [comment] 2023-03-18 06:46
I have issues building my 2.16 project locally, after I upgraded my other project to 3.3.1. I also globally updated @nuxt/devtools from 0.1.0 to 0.2.5. I'm not 100% sure which of both updates broke my 2.16. Downgrading devtools to 0.1.0 didn't help.

How would I create a repro for @danielroe ?

**Comment by SunnyAureliusRichard** [comment] 2023-03-18 10:30
Can confirm the issue is still occurring.

To reproduce:
1. clone https://github.com/viandwi24/nuxt3-awesome-starter
2. run `pnpm run dev` - it should run without errors
3. run `pnpm install axios`
4. run `pnpm run dev` - now it errors with the above

**Comment by danielroe** [comment] 2023-03-18 21:04
@SunnyAureliusRichard This issue is about a Nuxt 2 project.

In your case, you can either upgrade your Nuxt version or install the version of kit that matches your Nuxt version:

```sh
pnpm i @nuxt/kit@3.1.1
```

**Comment by mst101** [comment] 2023-03-21 10:49
In my case, the issue was caused by an old version of nuxi which I had installed globally on my machine via `pnpn install -g nuxi`. 

Upgrading nuxi by running the same command again, solved the issue for me.

**Comment by danielroe** [comment] 2023-03-21 10:57
Okay, I'm going to close this issue for now. If anyone is experiencing this on a pure Nuxt 2 project, please let me know. 🙏

**Closed** 2023-03-21 10:57 UTC
Labels: 3.x, pending triage, 2.x, needs reproduction, ❗ p4-important

**Comment by ericirish** [comment] 2023-03-21 21:26
I'm having this problem with nuxt@2.16.3 generating a static site on Netlify. Suddenly, new builds would error out during generation:

```
8:07:23 AM: [error]  /terms-and-conditions
8:07:23 AM: 
8:07:23 AM: Error: Request failed with status code 401
8:07:23 AM:     at createError (/opt/build/repo/node_modules/axios/lib/core/createError.js:16:15)
8:07:23 AM:     at settle (/opt/build/repo/node_modules/axios/lib/core/settle.js:17:12)
8:07:23 AM:     at IncomingMessage.handleStreamEnd (/opt/build/repo/node_modules/axios/lib/adapters/http.js:260:11)
8:07:23 AM:     at IncomingMessage.emit (events.js:327:22)
8:07:23 AM:     at endReadableNT (_stream_readable.js:1201:12)
8:07:23 AM:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by danielroe** [comment] 2023-03-21 21:31
That doesn't seem to be the same issue.

**Comment by MooseSaeed** [comment] 2023-03-28 10:37
Thank you for the fix @danielroe

**Comment by MooseSaeed** [comment] 2023-03-30 18:21
@danielroe Another site we have is facing the below error when deleted package-lock.json and run `npm install` again

```
[fatal] No "exports" main defined in /opt/atlassian/pipelines/agent/build/node_modules/@nuxt/schema/package.json

  at new NodeError (node:internal/errors:371:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:645:7)
  at resolveExports (node:internal/modules/cjs/loader:482:36)
  at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:241025)
  at jiti (node_modules/jiti/dist/jiti.js:1:243309)
  at node_modules/@nuxt/kit/dist/index.mjs:18:15
  at jiti (node_modules/jiti/dist/jiti.js:1:245784)
  at node_modules/@ryntab/web-vitals/dist/module.mjs:3:12
  at Resolver.jiti [as _require] (node_modules/jiti/dist/jiti.js:1:245784)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:267:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:122:38)
  at node_modules/@nuxt/utils/dist/utils.js:490:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:34:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:342:5)
  ```
