### ISSUE TITLE
Nuxt Link missing to causes cannot read property '_normalized' of undefined

### ISSUE THREAD

**Issue by CraftingGamerTom** [nuxt/nuxt#7277] opened 2020-04-26 22:15 UTC
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://ibb.co/PGJTVB0](https://ibb.co/PGJTVB0)

### Steps to reproduce

**Description**
`nuxt-link` components that are missing a `to="some-value"` argument results in an unclear error and significantly slows down loading of the page affected.

Here is an example

**test.vue**
```
<template>
  <nuxt-link>
    xxxxxx
  </nuxt-link>
</template>
```
When the page is rendered we receive this error
![image](https://user-images.githubusercontent.com/10101712/80320827-bf4ddb80-87e6-11ea-8018-ede209b73171.png)
**Text:** 
> Cannot read property '_normalized' of undefined
> An error occurred while rendering the page. Check developer tools console for details.

Example of proper implementation that will silence the error - requires hard refresh after fixing to see change
```
<template>
  <nuxt-link to="#">
    xxxxxx
  </nuxt-link>
</template>
```

### What is expected ?

A better error message in console, a link that doesnt work but page still renders? Something easier to understand at least.

### What is actually happening?

Error that blocks rendering, slows down application, and is not clear how to fix without prior knowledge of this issue.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10575">#c10575</a>)</em></sub></div>

**Comment by highoncarbs** [comment] 2022-07-12 10:10
Any fix ?

**Comment by danielroe** [comment] 2023-02-17 00:03
For Nuxt 2, this is an upstream issue in `vue-router` with a solution - ensure you always provide a `to` value, as vue-router will try to resolve whatever you pass to it.

You could provide your own component (`<MyLink>`) that does this, perhaps defaulting `to` to `#` as suggested above.

The issue is resolved in the latest version of `vue-router` + Nuxt 3.

**Closed by danielroe** 2023-02-17 00:03 UTC
Labels: pending, pending triage, 2.x
