### ISSUE TITLE
Webpack error on video tag display with require on src

### ISSUE THREAD

**Issue by JordanQui** [nuxt/nuxt#20564] opened 2023-04-28 17:21 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v19.7.0
- Nuxt Version:     2.16.3
- Nitro Version:    -
- Package Manager:  npm@9.5.0
- Builder:          webpack
- User Config:      head, css, plugins, components, buildModules, modules, devMiddleware, build
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

load a video tag in a page with a video loaded with require on src

### Describe the bug

video don't load and a message error occur 

### Logs

```shell-script
ERROR  context.outputFileSystem.lstat is not a function

  at size (node_modules/webpack-dev-middleware/dist/middleware.js:157:36)
  at new Promise (<anonymous>)
  at processRequest (node_modules/webpack-dev-middleware/dist/middleware.js:155:28)
  at ready (node_modules/webpack-dev-middleware/dist/utils/ready.js:17:5)
  at Object.middleware (node_modules/webpack-dev-middleware/dist/middleware.js:69:5)
  at node_modules/pify/index.js:33:11
  at new Promise (<anonymous>)
  at Object.<anonymous> (node_modules/pify/index.js:6:9)
  at Object.apply (node_modules/pify/index.js:80:20)
  at WebpackBundler.middleware (node_modules/@nuxt/webpack/dist/webpack.js:1863:37)
  at node_modules/@nuxt/server/dist/server.js:495:14
  at call (node_modules/connect/index.js:239:7)
  at next (node_modules/connect/index.js:183:5)
  at SendStream.error (node_modules/serve-static/index.js:121:7)
  at SendStream.emit (node:events:512:28)
  at SendStream.error (node_modules/send/index.js:270:17)
  at SendStream.onStatError (node_modules/send/index.js:417:12)
  at onstat (node_modules/send/index.js:722:26)
  at FSReqCallback.oncomplete (node:fs:191:21)
```

**Comment by danielroe** [comment] 2023-04-28 19:05
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by JordanQui** [comment] 2023-04-28 19:09
my mistake it's a nuxt 2.16 issue

**Comment by JordanQui** [comment] 2023-04-28 22:46
a clean instal and a try to load a video in a tag with require in src is sufficient to reproduce on my side

**Comment by ClydeFroga** [comment] 2023-05-02 03:37
I have the same problem

**Comment by ian-bitts** [comment] 2023-05-05 12:38
It looks like this is a mismatch between the memory file system that is being used in `nuxt-webpack@2.16.3` and the one that is being used by `webpack-dev-middleware` at version 5.1.0 and above.

`nuxt-webpack@2.16.3` uses `memory-fs`, a deprecated package which does not include an `lstat` function (hence the error message) but `webpack-dev-middleware` requires this function as of [this commit](https://github.com/webpack/webpack-dev-middleware/commit/e8b21f0979c4807b28f7be45aff0d25cca1585ae).

I was able to work around the issue by resolving the `webpack-dev-middleware` version to `5.0.0`, before the call to this function was introduced. To do so, add this to your package.json

```
"resolutions": {
...
"webpack-dev-middleware": "5.0.0"
}
```

It's worth mentioning that it is also possible to override the in-memory outputFileSystem that is used by the webpack-dev-middleware, and you should be able to replace `memory-fs` with `memfs`, however I was not able to get this working. Since this only affects the dev server, I decided that downgrading the `webpack-dev-middleware` package was a good enough work around for my purposes.

**Comment by JordanQui** [comment] 2023-05-06 08:21
Still got the error on my side on node 19.7.0

**Comment by JordanQui** [comment] 2023-05-11 15:17
@ian-bitts error is still here even with overrides in package.json

**Comment by shahzodjonweb** [comment] 2023-06-22 07:04
@ian-bitts  worked thanks!

**Closed** 2023-06-27 09:17 UTC
Labels: 👉 good first issue, 2.x, bug, webpack

**Comment by dndnp4** [comment] 2023-07-28 01:07
@ian-bitts 감사합니다 형님

**Comment by christopher4lis** [comment] 2023-11-21 04:07
@ian-bitts give this man a medal 🥇

**Comment by mark980828** [comment] 2024-03-07 12:29
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏


This problem has arisen again in nuxt2.17.3.

my env↓
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz
  Memory: 7.14 GB / 15.93 GB
Binaries:
  Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - F:\Other\nodejs\global\yarn.CMD
  npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: 8.6.0 - F:\Other\nodejs\global\pnpm.CMD
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (122.0.2365.52)
  Internet Explorer: 11.0.19041.1566

**Comment by mark980828** [comment] 2024-03-07 12:29
> Would

This problem has arisen again in nuxt2.17.3.

my env↓
System:
OS: Windows 10 10.0.19045
CPU: (8) x64 Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz
Memory: 7.14 GB / 15.93 GB
Binaries:
Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.19 - F:\Other\nodejs\global\yarn.CMD
npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
pnpm: 8.6.0 - F:\Other\nodejs\global\pnpm.CMD
Browsers:
Edge: Spartan (44.19041.1266.0), Chromium (122.0.2365.52)
Internet Explorer: 11.0.19041.1566
