### ISSUE TITLE
Route does not update when no slot in layout

### ISSUE THREAD

**Issue by serkodev** [nuxt/nuxt#25069] opened 2024-01-05 13:21 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-x6a5q5?file=layouts%2Fdefault.vue

1. run nuxt dev and nagivate to `/`
2. you will see `current route` is `index`
3. click `foo` link to nagivate to `/foo`
4. you will see the `current route` remains `index` but the url changes
5. click `foo` link again
6. the `current route` changed to `foo`

### Describe the bug

route does not changes.
if I add `<slot />` to `layouts/defaults.vue` then it works as expected

**Comment by manniL** [comment] 2024-01-05 17:41
I wonder what the use case for a layout without slot is 🤔
Should we possibly warn in this scenario? (cc @danielroe)

**Comment by jonathan-rvezy** [comment] 2024-01-12 20:31
Possible duplicate of https://github.com/nuxt/nuxt/issues/25107 ?

**Comment by serkodev** [comment] 2024-03-01 11:07
@manniL I made a minimum demo (https://github.com/nuxt/nuxt/discussions/26030) and explain my use case of this issue.  Hope can get some suggestions.

**Comment by danielroe** [comment] 2024-09-17 13:56
I think this is the same issue as https://github.com/nuxt/nuxt/issues/14595 - let's track there.

**Closed by danielroe** 2024-09-17 13:56 UTC
Labels: pending triage, dx, needs details
