### ISSUE TITLE
ESLint import/no-unresolved on 3.7.0 when importing with @-alias

### ISSUE THREAD

**Issue by janericwinkelmann** [nuxt/nuxt#22994] opened 2023-09-04 13:04 UTC
### Environment

- Operating System: Darwin
- Node Version:     v19.3.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.2.0
- Builder:          -
- User Config:      runtimeConfig, css, nitro, vite, experimental, components, app, modules, i18n, build
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -

### Reproduction

Create a new nuxt project, add a new custom folder and place a js file inside. Try to import this file. Enable linting and you should be able to reproduce the error on build.

### Describe the bug

Prior to Nuxt 3.7.0 this was working fine. When importing a file from a non standard root level folder with the "@"-alias we now receive a linting error on build and on lint, but not when running nuxi dev:

import fragment from '@/shaders/fragment.glsl'
or
import math from '@/lib/math.js'

On build we than receive the error:
```6:20  error  Unable to resolve path to module '@/shaders/fragment.glsl'    import/no-unresolved```

When using 
```import fragment from '../shaders/fragment.glsl'```
instead, everything's working fine.

**Comment by daspete** [comment] 2023-09-05 09:20
Same here, no alias imports are working.

**Comment by killjoy1221** [comment] 2023-09-06 20:24
It seems to be related to the `extends` paired with the generated `tsconfig.json` no longer having a `baseDir` value. My quick fix is to specify the nuxt tsconfig in the eslint settings.

```json
// .eslintrc
{
  "settings": {
    "import/resolver": {
      "typescript": {
        "project": "./.nuxt/tsconfig.json"
      }
    }
  }
}
```

Possibly related: dividab/tsconfig-paths#224

**Comment by leo-buneev** [comment] 2023-09-15 15:14
Can confirm.
Source of the issue is package `get-tsconfig`, which `eslint-import-resolver-typescript` depends on
https://github.com/privatenumber/get-tsconfig/blob/develop/src/parse-tsconfig/index.ts

here when it resolves `extend`ed config it doesn't adjust relative values in `compilerOptions.paths`

**Comment by danielroe** [comment] 2023-10-20 22:10
Thanks for the debugging. This isn't a Nuxt issue, it seems, so I'm closing. But if you think there's something we should be doing, please feel free to let me know.

**Closed** 2023-10-20 22:10 UTC
Labels: 3.x, pending triage, needs reproduction
