### ISSUE TITLE
useFetch infinite loop until heap allocation error

### ISSUE THREAD

**Issue by aarjeli** [nuxt/nuxt#25959] opened 2024-02-26 10:08 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.14.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      modules, devtools, css, vite, runtimeConfig, nitro
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @pinia/nuxt@0.5.1, nuxt-quasar-ui@2.0.7, nuxt-svgo@3.7.0
- Build Modules:    -
------------------------------

### Reproduction

Replace useFetch with $fetch and do a load test on it.

### Describe the bug

We have a product that does two calls in order to fully get all information for a page. The first call is done in a Pinia store while the second call is done in a composable.

The first call in the store I will call `configRequest` looks like this:

```js
export const useConfigStore = defineStore("config", () => {
  const offer = ref({});
  const site = ref({});

  const initializeConfig = async () => {
    const { data, error } = await useFetch(API_URLS.config, {
      retry: false,
      watch: false,
    });

    if (error.value) console.error("Config Error", error.value);


  await nuxtApp.runWithContext(() => {
    if (data.seo) useCustomMeta(data.seo);
  });


    offer.value = data.value.offer;
    site.value = data.value.site;
  };

  return { offer, site, initializeConfig };
});
```

And is loaded in the main layout:
```vue
<template lang="pug">
slot
</template>

<script setup>
const configStore = useConfigStore();

await configStore.initializeConfig();
</script>
```

The second call is in a composable that I will call `pageRequest` looks like:
```javascript
export const usePage = async (pageSlug) => {
  const configStore = useConfigStore();

  const { data, error } = await useFetch(API_URLS.postType(pageSlug), {
    retry: false,
    watch: false,
  });

  if (error.value)
    throw createError({
      statusCode: 404,
      statusMessage: "Page Not Found",
    });

  return { data };
};
```

# Issue 1

The problem is two-fold. First, the `configRequest` has a tendency to get in an infinite loop where the same error is thrown every 25 seconds:

```
2024-02-25T21:43:39.807860482Z [nuxt] [request error] [unhandled] [500] fetch failed
2024-02-25T21:43:39.807905054Z   at node:internal/deps/undici/undici:12345:11
2024-02-25T21:43:39.807914626Z   at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-02-25T21:43:39.807918366Z   at runNextTicks (node:internal/process/task_queues:64:3)
2024-02-25T21:43:39.807921770Z   at process.processImmediate (node:internal/timers:449:9)
2024-02-25T21:43:39.807925011Z   at async sendProxy (./.output/server/chunks/nitro/node-server.mjs:1934:20)
2024-02-25T21:43:39.807928526Z   at async Object.handler (./.output/server/chunks/nitro/node-server.mjs:2290:19)
2024-02-25T21:43:39.807931670Z   at async toNodeHandle (./.output/server/chunks/nitro/node-server.mjs:2479:7)
2024-02-25T21:43:39.807934746Z   at async ufetch (./.output/server/chunks/nitro/node-server.mjs:2845:17)
2024-02-25T21:43:39.807952212Z   at async $fetchRaw2 (./.output/server/chunks/nitro/node-server.mjs:2717:26)
2024-02-25T21:43:39.807955683Z   at async $fetch2 (./.output/server/chunks/nitro/node-server.mjs:2759:15)
2024-02-25T21:43:58.245553941Z [nuxt] [request error] [unhandled] [500] fetch failed
2024-02-25T21:43:58.245579788Z   at node:internal/deps/undici/undici:12345:11
2024-02-25T21:43:58.245582397Z   at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-02-25T21:43:58.245584535Z   at runNextTicks (node:internal/process/task_queues:64:3)
2024-02-25T21:43:58.245586552Z   at process.processImmediate (node:internal/timers:449:9)
2024-02-25T21:43:58.245588493Z   at async sendProxy (./.output/server/chunks/nitro/node-server.mjs:1934:20)
2024-02-25T21:43:58.245590672Z   at async Object.handler (./.output/server/chunks/nitro/node-server.mjs:2290:19)
2024-02-25T21:43:58.245593250Z   at async toNodeHandle (./.output/server/chunks/nitro/node-server.mjs:2479:7)
2024-02-25T21:43:58.245596582Z   at async ufetch (./.output/server/chunks/nitro/node-server.mjs:2845:17)
2024-02-25T21:43:58.245599666Z   at async $fetchRaw2 (./.output/server/chunks/nitro/node-server.mjs:2717:26)
2024-02-25T21:43:58.245602751Z   at async $fetch2 (./.output/server/chunks/nitro/node-server.mjs:2759:15)
```

This eventually leads to a heap allocation error:

```
2024-02-25T21:46:29.727241284Z <--- Last few GCs --->
2024-02-25T21:46:29.727244908Z
2024-02-25T21:46:29.727247476Z [1:0x7f32d457e680] 45318823 ms: Mark-Compact 4052.4 (4139.6) -> 4039.3 (4142.3) MB, 4136.01 / 0.00 ms  (average mu = 0.702, current mu = 0.264) allocation failure; scavenge might not succeed
2024-02-25T21:46:29.727250413Z [1:0x7f32d457e680] 45323783 ms: Mark-Compact 4056.1 (4143.3) -> 4042.5 (4145.6) MB, 4022.37 / 0.00 ms  (average mu = 0.555, current mu = 0.189) allocation failure; scavenge might not succeed
2024-02-25T21:46:29.727253032Z
2024-02-25T21:46:29.727255192Z
2024-02-25T21:46:29.727257368Z <--- JS stacktrace --->
2024-02-25T21:46:29.727273237Z
2024-02-25T21:46:29.727275353Z FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
2024-02-25T21:46:29.727277565Z ----- Native stack trace -----
```

There is no indication on why this happens when it is just a simple API call. I have ran the same api call using curl and I got a valid response back on the server. We have seen the RAM usage of the docker container spike to something like 600 mb on production, while the idle mode is 40mb. More on this later. It looks a lot like this problem: https://github.com/nuxt/nuxt/issues/22645. However, when the docker container is fresh everything works accordingly, it is after a bit of load that things start to fail.

What I also saw is that with 240 requests the CPU usage spikes over 100%. What is the leak in my code? I do not seem to be using any weird API's of Nuxt. This seems like basic stuff.

What have I tried:
- Not using a proxy, but directly accessing the API (only on server)
- Changing where the initializeConfig is called (plugin or layout)
- Turning off retry
- Switch to `$fetch`
- Changing node version
- Changing nuxt version

I can not reproduce the error looping locally.

# Issue 2

Both the `configRequest` and the `pageRequest` are using use fetch. When trying to load-test the container using Apache benchmark (`ab -n 24 -c 10 http://localhost:3000/`) with only 240 requests the ram usage spiked. Here are my findings:

| Solution | Max ram usage |
|----------|---------------|
| Nothing changed both use useFetch  |   366mb  |
|  Using $fetch for `configRequest` and useFetch for `pageRequest`   |  279 mb  |
|    Using $fetch for both requests   |    128mb    |

I am not sure if these problems are related. I have just deployed a solution where I replaced my useFetch with $fetch, but I am not sure if I am doing anything wrong or if this is just a bug with useFetch. Maybe it is similar to this issue: https://github.com/nuxt/nuxt/issues/5396 . However, I do not see the link with useFetch as I have.

**Comment by danielroe** [comment] 2024-02-26 12:15
I think you should be using `$fetch` in this instance - `useFetch` should not be called programmatically to perform fetches.

However, the infinite loop was caused by the fact that Nuxt was rendering the 404 error page in response to your `useFetch` call and should be fixed in the latest h3 version with https://github.com/unjs/h3/pull/646.

Check if updating your lockfile/upgrading h3 resolves things for you.

**Closed** 2024-03-05 01:46 UTC
Labels: 3.x, pending triage, needs reproduction, closed-by-bot
