### ISSUE TITLE
Slow initial connection on each request

### ISSUE THREAD

**Issue by Skyle** [nuxt/nuxt#25979] opened 2024-02-27 13:24 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v21.5.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      ssr, runtimeConfig, modules, i18n, auth, css, vite, app
- Runtime Modules:  @nuxtjs/i18n@8.1.1, @sidebase/nuxt-auth@0.6.7, @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

Sorry, it is nor really possible for me to provide any minimal reproduction because this is a big corporate project and i am not sure  how to separate the error into an extra repo

### Describe the bug

The bug occured first after we upgraded from version 3.6.2 to 3.10.2. There is a ≈300ms delay for the initial connection of each request. The total loading time per request goes up to 2 seconds because some requests get stalled. i will provide a few screenshots from the network tab.
![image](https://github.com/nuxt/nuxt/assets/971723/46b1e085-0b46-4b10-bb8c-a431c7b9c88a)
![image](https://github.com/nuxt/nuxt/assets/971723/fef2e634-4dc5-406a-aa14-02eeef23739e)
i found this related Issue: [https://github.com/nuxt/cli/issues/136](https://github.com/nuxt/cli/issues/136).
One of the mentioned solution is to change from localhost to 127.0.0.1. This works! Is there any other workaround you know about?

**Comment by manniL** [comment] 2024-02-27 13:51
Duplicate of https://github.com/nuxt/cli/issues/209

**Closed by manniL** 2024-02-27 13:51 UTC
Labels: 3.x, pending triage
