### ISSUE TITLE
Is inlining styles not working?

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/nuxt#28029] opened 2024-07-04 16:56 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.4.0`
- Builder:          `-`
- User Config:      `telemetry`, `compatibilityDate`, `runtimeConfig`, `modules`, `future`, `sourcemap`, `devtools`, `site`, `app`, `vite`, `nitro`, `css`, `postcss`, `eslint`, `image`, `content`, `colorMode`, `icon`, `plausible`, `ogImage`, `linkChecker`, `sitemap`
- Runtime Modules:  `@nuxt/content@2.13.0`, `@nuxt/devtools@1.3.9`, `@nuxt/eslint@0.3.13`, `@nuxt/fonts@0.7.1`, `@nuxt/icon@1.0.0`, `@nuxt/image@1.7.0`, `@nuxtjs/plausible@1.0.0`, `@nuxtjs/seo@2.0.0-rc.11`, `@eschricht/nuxt-color-mode@1.0.5`, `@unocss/nuxt@0.61.0`, `@vueuse/nuxt@10.11.0`
- Build Modules:    `-`

### Reproduction

This is from nuxt.com

<img width="499" alt="Screenshot 2024-07-04 at 17 00 47" src="https://github.com/nuxt/nuxt/assets/2703233/f02eb091-a9ef-4549-b2ba-eda026508a33">

<img width="973" alt="Screenshot 2024-07-04 at 17 52 27" src="https://github.com/nuxt/nuxt/assets/2703233/73e7e40a-4948-4d85-b9f0-89be1dc208d3">

### Describe the bug

With `nuxt@3.12.3` and

```
future: {
    compatibilityVersion: 4,
}
```

it seems like `inlineStyles` should be enabled by default (I also tested with explicitly setting it in `future`), but I still get stylesheets linked on my landing page ([Promptmetheus](https://promptmetheus.com)) and Google Pagespeed complains about it.

<img width="502" alt="Screenshot 2024-07-04 at 17 05 22" src="https://github.com/nuxt/nuxt/assets/2703233/83278607-624a-476c-816d-16455f609bdd">

**Comment by manniL** [comment] 2024-07-04 17:23
Duplicate of https://github.com/nuxt/nuxt/issues/21821

**Closed by manniL** 2024-07-04 17:23 UTC
Labels: pending triage
