### ISSUE TITLE
Conflict between `ssr:false` configuration and Island Components

### ISSUE THREAD

**Issue by maximepvrt** [nuxt/nuxt#22550] opened 2023-08-08 22:56 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.10
- Builder:          vite
- User Config:      modules, devtools, content, experimental, routeRules
- Runtime Modules:  @nuxt/content@2.7.2, @nuxtjs/tailwindcss@6.8.0, @nuxthq/studio@0.13.4, nuxt-headlessui@1.1.4, @nuxt/devtools@0.7.5
- Build Modules:    -
------------------------------

### Reproduction

- Create a Nuxt 3 project.
- Configure a route or a group of routes with ssr:false.
- Include Island Components within these routes.
- Visit the configured route(s) in a browser.

### Describe the bug

When using Nuxt 3 with `ssr:false` or a catch all `routeRules` with `ssr:false`, a conflict arises when Island Components are involved. Island Components are designed to be render by ssr, but when combined with the ssr:false configuration, unexpected behavior may occur. The loading component is render.

For the time being, I am addressing this by adding the following code snippet to the configuration file:
```
routeRules: {
    '/__nuxt_island/**': { ssr: true },
    '/my-page-with-island': { ssr: true },
    '/**': { ssr: false },
},
```

### Additional context

Additionally, it's important to note that attempting to add an Island Component to a page with the ssr:false configuration is not feasible.

**Comment by ojvribeiro** [comment] 2023-08-21 17:58
Maybe duplicate of #22693?

**Comment by huang-julien** [comment] 2023-08-22 18:24
probably not, #22693 is due to the component scanning behavior. This one is related to the `ssr: false` option (i think it disable the renderer ?) and routeRules. I'll take a look when i'll have some times :). Thanks for reporting this.

**Comment by dulnan** [comment] 2023-08-28 06:33
I also encountered this bug and started making a reproduction project before coming across this issue. Posting it here anyway in case it might help.

https://stackblitz.com/edit/github-fmjaoz?file=app.vue

- Go to the front page where SSR is enabled. The island placed in app.vue is rendered correctly
- Click on /spa and see the island placed in `~/pages/spa/index.vue` being rendered correctly
- Now refresh the page (/spa)
- Both the island placed in app.vue and in the page component are not rendered

**Comment by dulnan** [comment] 2023-08-28 06:58
Looking through the code of the `<NuxtIsland>` component, the issue comes from this line:

https://github.com/nuxt/nuxt/blob/d905e5f51916dbe797b90800f7f590e1b7857239/packages/nuxt/src/app/components/nuxt-island.ts#L172

On load `nuxtApp.isHydrating` is true, so it falls through the if statement and never actually loads the component. Since it's SPA, `ssrHTML` is empty and therefore nothing is being rendered.

Quickly adding another else if condition fixed it for me:

```typescript
} else if (import.meta.client && !ssrHTML.value) {
  fetchComponent();
}
```

Though I'm not sure what the intention is with the `!isHydrating && props.lazy` and if adding this else if breaks other scenarios.

**Closed** 2023-08-28 16:46 UTC
Labels: 3.x, bug, 🔨 p3-minor-bug
