### ISSUE TITLE
external script doesn't always loads when we navigate between components nuxt 3

### ISSUE THREAD

**Issue by samairali** [nuxt/nuxt#22208] opened 2023-07-18 23:20 UTC
### Environment

nuxt 3, tailwind.css

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/17316135/7fb73313-773a-4e98-9e40-d34dcd3bd415)

### Describe the bug

external script doesn't always loads when we navigate between components nuxt 3 , i have created component dashboard/index.vue added this code

````
<template>
    <div>
        <div id="highchart-1" class="rounded-lg"></div> 
    </div>       
</template>
<script setup>
useHead({
    script: [
        {
            src: 'https://code.highcharts.com/highcharts.js',
            type: 'text/javascript',
            async: true,
            body: true
        },
    ],
});
onMounted(() => {
    initializeChart();
});
const initializeChart = () => {
    window.Highcharts.chart('highchart-1', {
        chart: {
            type: 'spline',
            height: 310
        },
        title: {
            text: 'Monthly Average Temperature'
        },
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            accessibility: {
                description: 'Months of the year'
            }
        },
        yAxis: {
            title: {
                text: 'Temperature'
            },
            labels: {
                format: '{value}°'
            }
        },
        tooltip: {
            crosshairs: true,
            shared: true
        },
        plotOptions: {
            spline: {
                marker: {
                    radius: 4,
                    lineColor: '#666666',
                    lineWidth: 1
                }
            }
        },
        series: [{
            name: 'Tokyo',
            marker: {
                symbol: 'square'
            },
            data: [5.2, 5.7, 8.7, 13.9, 18.2, 21.4, 25.0, {
                y: 26.4,
                marker: {
                    symbol: 'url(https://www.highcharts.com/samples/graphics/sun.png)'
                },
                accessibility: {
                    description: 'Sunny symbol, this is the warmest point in the chart.'
                }
            }, 22.8, 17.5, 12.1, 7.6]

        }, {
            name: 'Bergen',
            marker: {
                symbol: 'diamond'
            },
            data: [{
                y: 1.5,
                marker: {
                    symbol: 'url(https://www.highcharts.com/samples/graphics/snow.png)'
                },
                accessibility: {
                    description: 'Snowy symbol, this is the coldest point in the chart.'
                }
            }, 1.6, 3.3, 5.9, 10.5, 13.5, 14.5, 14.4, 11.5, 8.7, 4.7, 2.6]
        }]
    });
}

</script>
````

when i go to dashboard page /dashboard or reload the dashboard page then useHead works and  i can see highchart.js script added before the body tag closing tag , i have also tried using useHead without body:true then i will see it in head tag, 
the issue i am facing is when i navigate from one page to other via NuxtLink then useHead is not working and script is not being added anywhere in the page/component element inspection and highchart is not working , it always works when we reload page completely  . i am using nuxt3

**Comment by danielroe** [comment] 2023-07-19 09:44
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

I suspect the script is being added to the DOM but your `onMounted` code is running before it's initialised.

cc: @harlan-zw

**Comment by rtibaldo** [comment] 2023-07-19 15:24
Couldn't this simply due to the script being async?

Try and see if this will help https://unhead.harlanzw.com/guide/guides/dom-event-handling#onload

**Comment by samairali** [comment] 2023-07-19 23:33
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> I suspect the script is being added to the DOM but your `onMounted` code is running before it's initialised.
> 
> cc: @harlan-zw

thanks for reply , 
btw i am fan of your work , i followed you on twitter as well :)
so for this issue useHead actually dont work when we navigate from one component to other , lets say i am going from home page to dashboard page useHead will not load the script not in dom or any where , but if i refresh the page 'f5' then it will be loaded in the dom and every thing works as required , for now i have added it in nuxt config like that 
```
`app: {
    head: {
      script: [
        {
            src: 'https://code.highcharts.com/highcharts.js',
            type: 'text/javascript',
            async: true,
            body: true
        },
      ],
    },
  },`
```
it worked but the issue is it loads on every component , it might not be good i only want to load this highchart script where it is required

**Comment by samairali** [comment] 2023-07-19 23:41
> Couldn't this simply due to the script being async?
> 
> Try and see if this will help https://unhead.harlanzw.com/guide/guides/dom-event-handling#onload

thanks for reply ,
i have tried adding removing async , defer , body: true etc but nothing worked at all 
it only works when we reload the page completely , with nuxtlink navigate it is not working at all

**Comment by samairali** [comment] 2023-07-19 23:52
i am not sure what do you exactly want from me , but i have tried creating two components just to show you the issue in stackblitz 
here you go 
https://stackblitz.com/edit/github-kqvufh?embed=1

**Comment by harlan-zw** [comment] 2023-07-20 08:32
Hi, as others have suggested the issue is related to a race condition on you trying to access Highcharts before it's loaded. The  `onload` function with client mode is the way to go.

Will the stackblitz example you provided you would do:

```ts
useHead({
  script: [
    {
      // ensures you only end up with a single script
      key: 'highcharts',
      src: 'https://code.highcharts.com/highcharts.js',
      onload(el) {
        // highcharts is only available when this function is called
        initializeCharts();
      },
    },
  ],
}, { mode: 'client' ); // onload isn't reliably triggered when rendering server-side
```

> lets say i am going from home page to dashboard page useHead will not load the script not in dom or any where ,

I don't think this is the case, if you can provide a reproduction for this I'm happy to investigate.

Getting this type of behavior to work will be made more intuitive with the new Nuxt Scripts https://github.com/nuxt/nuxt/discussions/22016.

Will close this for now, let me know if you still have questions though.

**Closed by harlan-zw** 2023-07-20 08:32 UTC
Labels: 3.x, pending triage, needs reproduction
