### ISSUE TITLE
Issue with layout when using same page across multiple routes

### ISSUE THREAD

**Issue by acemero-dev** [nuxt/nuxt#29268] opened 2024-10-04 05:58 UTC
### Environment

- Operating System: Linux
- Node Version:     v22.8.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.27
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. Create a page and link it with multiple routes
2. attach a layout to it via definePageMeta
3. Now build and see only the first route got the layout.

### Describe the bug

When I try to attach multiple routes to the same page and use a layout with definePageMeta, the layout seems to load only for the first route. The other routes still function correctly but do not apply the layout. This issue occurs only when we use the same page across different routes.

For example, if we have a page named LayoutPage with two routes: /admin/hello and /admin/hi, and apply the layout admin-master-layout to both routes, only /admin/hello displays with the layout, while /admin/hi does not. Could someone clarify if this is the expected behavior, or if it's a potential bug? If so, are there any workarounds available?"

**Comment by connect2fayis** [comment] 2024-10-04 07:45
me too facing the same issue with nuxt3.

**Comment by danielroe** [comment] 2024-10-06 05:01
Basically with `scanPageMeta` we scan and set the layout in the route meta. If you add a second copy of an already scanned route we don't _rescan_ it as we want to allow you to change the scanned meta. So you need to add the layout on the second page you've added manually.

This will no longer be necessary after https://github.com/nuxt/nuxt/pull/28861 is merged.

For now you could set `experimental.scanPageMeta` to false.

**Comment by danielroe** [comment] 2024-10-06 05:02
Duplicate of https://github.com/nuxt/nuxt/issues/27814.

**Closed by danielroe** 2024-10-06 05:02 UTC
Labels: pending triage

**Comment by acemero-dev** [comment] 2024-11-12 11:05
Sorry the issue still there i have tried both removing and using the value "after-resolve" for the property "scanPageMeta" in nuxt.config but still i can see the layout only work for only one page assigned to a route but i need multiple pages work for a same route without any layout issue.Any help is highly appreciated.
