### ISSUE TITLE
`prerender` option not working for `routeRules`

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/nuxt#22496] opened 2023-08-04 14:32 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      routeRules
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/serene-sunset-zd3944?file=%2Fpages%2Ffetch.vue%3A3%2C10

### Describe the bug

None of the rendering modes seem to have any effect (I only included `prerender` in my repro).

I would expect the `/test` and `/fetch` pages to be rendered at build time and served as a static asset. Instead it's all done with SSR and re-rendered client-side , which you can see because the `console.log` shows up in the browser, as well as the client-side fetch and the changing timestamp.

The data should've been fetched at build-time and the result rendered as a static asset (maybe with hydration for `NuxtLink`?), but none of that seems to work currently.

**Comment by danielroe** [comment] 2023-08-04 16:34
With `prerender`, the page is prerendered, so it won't be rendered again when requested.

But it will still be hydrated on the client-side - you still have client-side JS. Instead of using Date.now, you can use `useState` to ensure that the date value isn't updated when client hydration happens.

If you don't want the fetch to happen when navigating to `/fetch` on client-side, set `experimental.payloadExtraction` to true and it will use the prerendered payload.

If you really don't want any JS on the client, you can use another route rule:

```ts
// https://nuxt.com/docs/guide/directory-structure/nuxt.config
export default defineNuxtConfig({
  routeRules: {
    '/test/': { prerender: true, experimentalNoScripts: true },
    '/fetch/': { prerender: true, experimentalNoScripts: true }
  }
})
```

**Comment by TheDutchCoder** [comment] 2023-08-04 16:52
Ok that's very interesting. I think it might be worth putting something into the docs for this, because it _feels_ like it should grab data at build time and render a static asset, but at the same time the hydration doesn't make a lot of sense if that were the case (which is what you're referring to as well).

I will take a look at `experimental.payloadExtraction`, I appreciate the answer!

**Comment by TheDutchCoder** [comment] 2023-08-09 00:03
Hi @danielroe can this issue be reopened? I'm pretty sure it's currently not actually working as intended.
`experimentalNoScripts` doesn't have any effect, the calls are still made on the client (I think this is an actual bug, what follows is more around expectations around `prerender`).

Furthermore, the `_payload.json` seems to contain the correct data, but the client doesn't (on soft-nav) use that at all, instead it just makes the API call again, which will yield the same result.

I know you've explained that this is the intended way, but I think it then warrants a (maybe broader) discussion?

The way I interpreted the `prerender` rendering option was as follows:
1. At build time, the component's/page's code is executed, the API call is made, and the result stored as `_payload.json` for that route.
2. On hard-nav the page is already prerendered and served. `_payload.json` is sent for hydration.
3. On soft-nav, `_payload.json` is used again for mounting.

This is not the way it works obviously, it really only uses the payload for a hard-nav, still hydrates, and from that point on forever acts like an SPA, with no benefits from prerender (I would argue the vast majority of users will therefore never get the benefit of the prerender, unless it's a hugely popular page that shows up in search results).

Especially for pages/routes that have "static" content pulled in (static in the sense that the API call's URL is static), it would be a _huge_ performance boost if the content was to be fetched only at build time, and from that point on re-used through both hard and soft navs. In SWR mode this could result in only _occasional_ new API calls (on the server, not client).

This might be incredibly difficult to do (I have no knowledge of Nuxt internals), because how do you "mark" certain queries as "static", but I think that's the expectation that some people have.

There's an active discussion on Discord around these expectations as well, for reference: https://discord.com/channels/473401852243869706/1138217695171592192

**Comment by danielroe** [comment] 2023-08-17 06:35
The issue is that all routeRules are server-request-only (https://github.com/nuxt/nuxt/issues/19228). So `experimentalNoScripts` doesn't affect client-side navigation, just the initial request to the server. When performing client-side navigation you (currently) need to set `external` prop on your `<NuxtLink>` to force a full reload without JS.

Having said that, with https://github.com/nuxt/nuxt/pull/21641 we at last have support for route rules on client-side navigation.

The reason the payload is not being fetched is that the root URL `/` in your case is not prerendered. This is a legitimate issue  and also scoped to be fixed in that PR. For now you can workaround it by creating the following plugin to _force_ fetching of payloads.

https://stackblitz.com/edit/github-42lxcj?file=server/api/test.ts,pages/about.vue,pages/index.vue,nuxt.config.ts,plugins/force-payload.server.ts,package.json

I'm closing this not because it's not an issue but I think we already have several tracking issues for this.

**Closed by danielroe** 2023-08-17 06:35 UTC
Labels: 3.x, workaround available, pending triage

**Comment by TheDutchCoder** [comment] 2023-08-17 10:07
Thanks for taking the time to write a thorough explanation!

I'll track the other issues instead and will look at the workaround as well.
