### ISSUE TITLE
Slow nuxt startup when importing sass file

### ISSUE THREAD

**Issue by dikesh** [nuxt/nuxt#13824] opened 2022-04-26 07:03 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cimcyj

### Describe the bug

I am using Bulma CSS with Nuxt app.

When I `@import 'node_modules/bulma/bulma.sass';` in my `'@/assets/main.scss'` file. the nuxt startup becomes too slow. It takes around 20-60 seconds for vite client and server to warm up.

![image](https://user-images.githubusercontent.com/1618526/165240771-bb4697a7-02d8-4d97-8924-bd660238e648.png)

Currently I have app running with `nuxt3@3.0.0-27460489.53fbca7` without this issue.

**Comment by Salamante** [comment] 2023-06-27 10:38
Contribution to this topic;
If you are using tailwindcss in your project make sure your `tailwind.config.js` has set up correctly.

if your content looks like this;
`content: ['./**/*.{html,js,vue}']`

Than it scans the entire project which takes too much time to warm up. Change it so only includes required folder;

`content: [
   "./components/**/*.{html,js,vue}", "./pages/**/*.{html,js,vue}"
   ]`

**Comment by danielroe** [comment] 2023-06-27 10:43
I'm closing this as this seems to be an upstream issue. Feel free to provide an updated reproduction and I'll happily look into this again.

**Comment by matias-gmg** [comment] 2023-08-02 23:26
After reading all the thread I don't understand what is the workaround for this.

<img width="690" alt="Screenshot 2023-08-03 at 9 24 13 am" src="https://github.com/nuxt/nuxt/assets/124641980/13c213b4-db16-49c2-b429-82cf6505da43">

I am using `sass` with a very long list of `css` assets in `additionalData` (this was the only way I found to make my styles work after a migration from Nuxt 2 to Nuxt 3).

Any suggestions on how I can decrease this slow startup? Thanks!

**Comment by danielroe** [comment] 2023-08-03 09:49
I suspect the issue is the very long list of css assets.

**Comment by matias-gmg** [comment] 2023-08-06 23:37
> I suspect the issue is the very long list of css assets.

What do you suggest? Should I put all files together in one file and only reference that one?

**Comment by Xaaalera** [comment] 2023-09-13 13:55
+1

**Comment by valh1996** [comment] 2023-10-12 15:27
> I suspect the issue is the very long list of css assets.

I wanted to start migrating from Nuxt Bridge to Nuxt 3 by starting simple. So, I simply created a basic nuxt3 project and added these 3 modules. The startup time is:
```
ℹ Vite client warmed up in 6061ms       
✔ Nitro built in 1105 ms
```
But when I include the scss entry, the problem appears:
```js
css: [
    '@/assets/css/main.scss'
],
```
main.scss:
```scss
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

```
ℹ Vite client warmed up in 17376ms
✔ Nitro built in 8830 ms
```
How is this possible? I don't have this problem with Nuxt 2.

**Comment by manniL** [comment] 2023-10-17 08:53
Possibly related: https://github.com/nuxt/nuxt/issues/23504

**Comment by danielroe** [comment] 2023-10-24 02:39
let's track in https://github.com/nuxt/nuxt/issues/20533.

**Closed by danielroe** 2023-10-24 02:39 UTC
Labels: 3.x, pending triage, dx, performance
