### ISSUE TITLE
nuxt generate command takes lot of memory

### ISSUE THREAD

**Issue by parzychu** [nuxt/nuxt#22449] opened 2023-08-02 14:40 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `plugins`, `app`, `postcss`, `runtimeConfig`, `modules`, `graphqlMiddleware`, `vite`, `nitro`, `experimental`, `ssr`, `vue`, `schemaOrg`
- Runtime Modules:  `nuxt-graphql-middleware@3.0.2`, `@nuxt/content@2.5.2`, `@pinia/nuxt@0.4.9`, `nuxt-schema-org@2.2.0`
- Build Modules:    `-`

### Reproduction

I've created a small application that shows the problem with keeping memory for long time:
https://github.com/parzychu/nuxt-memory-reproduction

Please see it's README file where I put more description than in this issue and a way to run it.

To get out of memory error you need application with more components and about 2.5k statically generated pages. 

### Describe the bug

When using `nuxi generate` application holds memory for longer than I think it should and in application having more than 2k pages it can cause out of memory issue. 

See log from generation of application from [reproduction repo](https://github.com/parzychu/nuxt-memory-reproduction)  [demo.log](https://github.com/parzychu/nuxt-memory-reproduction/blob/master/demo.log).
If you search for `/page3652` you will see that setup of this page was run at `2:14`, page was generated at `2:16`, but payload was extracted at `9:00`. I guess that after payload extraction memory frees, but in between over 6600 pages were generated and their content was added to memory.

This delay is visible in memory usage even for demo application. For my production application difference is much more evident and 4GB RAM is used after payload extraction of 260 pages when 2500 were generated. I need about 11GB of RAM to successfully render about 5k pages.

Situation with memory is the same when I turn off payloadExtraction. I guess that payloadExtraction starts generating just before page generation process is finished, but in the meantime its data is stored in memory.

Situation with memory slightly improves (generates 40-50% more pages), but is dozen times slower when I set `"nitro.prerender.concurrency": 1`. But then in my application case pages that were rendered within first 15 min had payload extracted 4 hrs later.

I was trying to figure this on my own, but issue seems to be more complex and I think it requires more familiarity with nuxt codebase. I couldn't understand why payload is extracting so late or rather why the page lives for so long in memory after being generated. I guess it's a key to solving this issue.

More description in [reproduction's repo README](https://github.com/parzychu/nuxt-memory-reproduction)  

I guess this issue may be the cause of
https://github.com/nuxt/nuxt/issues/22257
Because moving from nuxt 3.5 to 3.6 increased a bit memory usage during the generation and it may combine with this issue and show off in other projects

### Logs

```shell-script
https://github.com/parzychu/nuxt-memory-reproduction/blob/master/demo.log
```

**Comment by danielroe** [comment] 2023-08-03 11:58
@parzychu I can't reproduce the OOM issue even with concurrency at 1000. But I've drafted a speculative fix. Would you try it by running:

```sh
yarn add nuxt@npm:nuxt3@pr-22465 h3@1.8.0-rc.2
```

**Comment by parzychu** [comment] 2023-08-04 09:30
@danielroe Thanks for quick fix and all the work you put in the project!

I can confirm that it works and reduces my memory usage by about 40-50%. Still I have OOM issue with 4GB after about 1,8k payloads extracted (in previous version it was only 260). With 5GB it seems to be working. 

"Seems" because in this version I don't have a memory error, but some looped url generation as something appends %23(23)b and more 23 to probably all urls. On some pages I don't check if such page should exist and it loops. (it's another issue, maybe peer dependency, maybe bug in my codebase) 
More than 6k payloads were generated before I terminated the process.


If I understand PR correctly it should limit the rendering queue to 1000 elements so for 2000 pages started generation, there should be 1000 payloads extracted. Or it's just a check and if it overflows the cache then payloads for some pages are not generated? In my case I still have a situation that 200 payloads were extracted after 2000 pages were generated. Idk if this information will be usefull for you.

**Comment by danielroe** [comment] 2023-08-04 11:56
I think the unusual url generation is from https://github.com/unjs/nitro/issues/1527.

See also https://github.com/unjs/nitro/pull/1529 which I think may be related.

**Comment by parzychu** [comment] 2023-08-04 12:19
Yes, unusual url generation is the same issue as in this task https://github.com/unjs/nitro/issues/1527

I think that fix by @Hebilicious will definitely solve memory issue

**Comment by danielroe** [comment] 2023-08-04 19:57
Great! The rest of this issue should now be fixed upstream in nitro. Would you check with the latest edge version of nitropack? 🙏

**Comment by danielroe** [comment] 2023-08-14 08:33
Closing as I believe this is now resolved with these two PRs. Let me know if you find otherwise. 🙏

**Closed by danielroe** 2023-08-14 08:33 UTC
Labels: 3.x, bug, performance
