### ISSUE TITLE
Allow replacing entirely the aliases in nuxt config

### ISSUE THREAD

**Issue by ddahan** [nuxt/nuxt#19932] opened 2023-03-27 07:48 UTC
### Describe the feature

Using `alias` in nuxt config extends default aliases. A reason why I'd need to get rid of the default aliases is that VS Code always suggest the `~~` prefix in suggest import feature, while I want to use the `@` one.

The workaround I found is to change ts config directly, but I think it's confusing to split this kind of config between nuxt config and ts config.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment] 2023-03-27 09:49
Duplicate of https://github.com/nuxt/nuxt/issues/14816#issuecomment-1397366520

**Closed by manniL** 2023-03-27 09:49 UTC
Labels: 3.x, pending triage
