### ISSUE TITLE
Cannot start nuxt Cannot find module simpleConfig.stub.js

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#19975] opened 2023-03-29 05:14 UTC
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.4`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/martinszeltins/nuxt-test-1

### Describe the bug

I am getting this error after installing the tailwind module:

````
 ERROR  Cannot start nuxt:  Cannot find module '/home/martins/Programming/test/nuxt/my-nuxt-1/node_modules/tailwindcss/stubs/simpleConfig.stub.js' imported from /home/martins/Programming/test/nuxt/my-nuxt-1/node_modules/@nuxtjs/tailwindcss/dist/module.mjs

  at new NodeError (node:internal/errors:393:5)
  at finalizeResolution (node:internal/modules/esm/resolve:323:11)
  at moduleResolve (node:internal/modules/esm/resolve:916:10)
  at defaultResolve (node:internal/modules/esm/resolve:1124:11)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
````

Here is what I did:

1. I started a brand new Nuxt project using `npx nuxi@latest init my-app`
2. I added tailwind with `yarn add --dev @nuxtjs/tailwindcss`
3. I added the tailwind module to `nuxt.config.ts`

````
export default defineNuxtConfig({
    modules: [
        '@nuxtjs/tailwindcss'
      ]
})
````

and then I got the error, even though I followed the module installation process perfectly.

**Comment by danielroe** [comment] 2023-03-29 05:16
this is an issue with the new tailwind version and is resolved in https://github.com/nuxt-modules/tailwindcss/pull/651.

**Comment by martinszeltins** [comment] 2023-03-29 05:17
> this is an issue caused by the new tailwind version and is resolved in [nuxt-modules/tailwindcss#651](https://github.com/nuxt-modules/tailwindcss/pull/651). It will be present in the next release.

what do I do now? How can I fix the issue for myself?

**Closed by danielroe** 2023-03-29 05:16 UTC
Labels: 3.x, pending triage

**Comment by danielroe** [comment] 2023-03-29 05:21
You can pin `tailwindcss` to `3.2.7` in your `package.json` for now.

**Comment by martinszeltins** [comment] 2023-03-29 05:22
> You can pin `tailwindcss` to `3.2.7` in your `package.json` for now.

But I do not have tailwindcss in my package.json, I have `"@nuxtjs/tailwindcss": "^6.6.4"`

````
"devDependencies": {
    "@nuxtjs/tailwindcss": "^6.6.4",
    "nuxt": "^3.3.2"
  }
````

**Comment by danielroe** [comment] 2023-03-29 05:23
I am suggesting you add it.

**Comment by martinszeltins** [comment] 2023-03-29 05:27
I updated my package.json file like this:

````
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.6.4",
    "tailwindcss": "3.2.7",
    "nuxt": "^3.3.2"
  }
````

but getting the same error:

```shell
$ yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 || ^5.0.0".
warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > postcss-loader@4.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > tailwindcss@3.2.7" has unmet peer dependency "postcss@^8.0.9".
[4/4] Building fresh packages...
$ nuxt prepare
Nuxi 3.3.2                                                                                                                                           08:25:54

 ERROR  Cannot find module '/home/martins/Programming/test/nuxt/my-nuxt-1/node_modules/@nuxtjs/tailwindcss/node_modules/tailwindcss/stubs/simpleConfig.stub.js' imported from /home/martins/Programming/test/nuxt/my-nuxt-1/node_modules/@nuxtjs/tailwindcss/dist/module.mjs
Did you mean to import tailwindcss/stubs/simpleConfig.stub.js?

  Did you mean to import tailwindcss/stubs/simpleConfig.stub.js?
  at new NodeError (node:internal/errors:393:5)
  at finalizeResolution (node:internal/modules/esm/resolve:323:11)
  at moduleResolve (node:internal/modules/esm/resolve:916:10)
  at defaultResolve (node:internal/modules/esm/resolve:1124:11)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by danielroe** [comment] 2023-03-29 05:29
It looks like you need to use yarn resolutions in that case.

**Comment by martinszeltins** [comment] 2023-03-29 05:31
> It looks like you need to use yarn resolutions in that case.
> 
> (Or you can wait for a release of the tailwindcss module, which will likely be today.)

Ok, thanks, I think I will wait for the new release.

**Comment by danielroe** [comment] 2023-03-29 17:22
It's out - hopefully the issue is resolved for you 🙏
