### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by zabavnikov** [nuxt/nuxt#25191] opened 2024-01-13 15:13 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/~/github.com/zabavnikov/nuxt
https://stackblitz.com/~/github.com/zabavnikov/nuxt-div (NuxtLayout is wrapped in a div)

### Describe the bug

After upgrading to the latest version of Nuxt and Vue, an error appeared - TypeError: Cannot read properties of null (reading 'parentNode').

I noticed that on pages where NuxtLayout is wrapped in a div, this error doesn't occur and navigating to another page works fine.

**Comment by manniL** [comment] 2024-01-13 15:42
Duplicate of https://github.com/nuxt/nuxt/issues/25179

**Closed by manniL** 2024-01-13 15:42 UTC
Labels: 3.x, pending triage
