### ISSUE TITLE
Generate and dynamic route fallback if static file is not generated

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/nuxt#7051] opened 2020-03-04 14:47 UTC
### What problem does this feature solve?

As discussed here a few years ago: https://github.com/nuxt/nuxt.js/issues/2177 we need a smart way to fallback if a requested static file is not yet generated. It makes sense to generate all routes on `nuxt generate`, however, some routes will be created after site has been generated, and in this case, a fallback method (such as nginx / htaccess) will be required.

### What does the proposed changes look like?

Perhaps just a simple part in the documentation that explains how to create this htaccess / nginx rule to forward to index.html which then will handle the request to the server.

**Comment by simplenotezy** [comment] 2020-03-04 14:48
Ping Alex @manniL

**Comment by manniL** [comment] 2020-03-05 20:01
Hey 👋🏻

Basically this is what `generate.fallback` is there for. An SPA fallback in case the route is excluded or not generated at all.

Creating an NGINX/Apache config to redirect the 404 page to the generated fallacbk HTML (either 200.html by default or when fallback is set to true, 404.html) should be a doable task, especially w/ references from https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

I'd accept a doc PR that adds examples to the corresponding guide ☺️

**Comment by avanishp2** [comment] 2020-03-06 11:34
Hey @manniL I am trying to create static website with dynamic routes using `nuxt generate`. 
So here what I am doing, I have some routes in excluded section of generate which is dynamic in nature and `fallback: true`. This generate dist folder with 404.html, other static html and _nuxt folder with js. 

The issue I am facing is dynamic routes are behaving as SPA means the head meta data are not getting updated instead the index page meta are showing up in view source of a dynamic page. Is this a intended behaviour? 

My website runs on SSR mode and so everything is working fine. I am trying to get benefit of static html for some pages to load faster and keeping dynamic page as it is... what I am missing here? What approach should I take? For me SEO is important. It's a ecommerce website.

**Comment by simplenotezy** [comment] 2020-03-06 15:26
Hey @manniL  - I'd love to write the documentation for it, but I am not sure yet how this is achieved. I have also tried setting the "fallback" setting to true, but that didn't work, out of the box.

I am using universal mode (static generated site).

**Comment by manniL** [comment] 2020-03-10 21:08
> The issue I am facing is dynamic routes are behaving as SPA means the head meta data are not getting updated instead the index page meta are showing up in view source of a dynamic page. Is this a intended behaviour?

Yes, this is the intended behavior. ☺️

A "hybrid mode" to serve static sites but also having a server running dynamic SSR for others might be possible as well but is not a feature that is present (yet?).

**Comment by manniL** [comment] 2020-03-10 21:08
> Hey @manniL - I'd love to write the documentation for it, but I am not sure yet how this is achieved. I have also tried setting the "fallback" setting to true, but that didn't work, out of the box.
> 
> I am using universal mode (static generated site).

What is missing is the configuration for you nginx/apache/... or platform provider (e.g. netlify). Netlify should pick up the 404.html automatically though.

**Comment by simplenotezy** [comment] 2020-03-11 12:43
@manniL please let me know of a htaccess setup that falls back, and I'll post a PR to add it to the documentation

**Comment by simplenotezy** [comment] 2020-03-12 11:56
@manniL what about setting "fallback" to "index.html"? Wouldn't that work?

**Comment by simplenotezy** [comment] 2020-03-12 17:30
@manniL Several people are asking this very question, also on discord. Would love to help them as well as my self, with an answer

**Comment by simplenotezy** [comment] 2020-03-18 15:50
OK, so I've done it successfully, however, there is a problem with nuxtServerInit not being called (naturally, since it is not server generated). How could I call it, when a page is dynamically resolved?

This is my .htaccess, having /my-account/orders/{some_id} as the dynamic parameter:

```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /my-account/orders/
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . index.html [L]
</IfModule>
```

**Comment by Atinux** [comment] 2020-03-27 09:59
Hi @simplenotezy 

To be able to work with the SPA fallback, I recommend to use a client plugin exporting an async function:

`plugins/init.client.js`
```
export default async function ({ store }) {
   // check if spa fallback, by checking if a value in store is empty for example
   if (!store.state.filled) {
     // be careful that context does not have req & res
     await store.dispatch('nuxtServerInit', context)
   }
}
```

**Comment by simplenotezy** [comment] 2020-04-18 13:50
Hi @Atinux - thanks for your reply. This was the code I ended up using:

	export default async function ({ store, app }) {
		// check if spa fallback, by checking if a value in store is empty for example
		if (!store.state.filled) {
			await app.store.dispatch('nuxtServerInit', app.context);
		}
	}

I have tested a bit, by changing mode to `spa` and then refreshing a page, and so far, it seems to be working. I will keep on testing, after I have run `generate` and see how it goes.

Thanks a lot for your help so far.

**Comment by simplenotezy** [comment] 2020-04-18 16:49
It seems to be working, your solution.

However, for some reason my htaccess is not working. I am not sure if I use the right one, but what I've done is:

1. Place the .htaccess in /dist/ folder.
2. The .htaccess have the following contents:
	<IfModule mod_rewrite.c>
		RewriteEngine On
		RewriteBase /my-account/orders/
		RewriteRule ^index\.html$ - [L]
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteRule . index.html [L]
	</IfModule>
3. I visited `/my-account/orders/<some_order_id>`, however, I get a 404 from my server.

**Comment by simplenotezy** [comment] 2020-04-21 11:48
Hi @manniL, I noticed you said that non-static-generated sites should be directed to 200.html. 

I have discarded the .htaccess approach, since I switched to CloudFlare workers, and here I made a script to check the pathname. If the pathname is a route, that is not generated on deploy, it should fallback to index.html of that folder. That works. But now I am in doubt if I should display the 200.html file in the root instead?

		// orders (URL could look like this: /my-account/orders/some-order-id)
		if (url.pathname.indexOf('/my-account/orders/') !== -1) {
			url.pathname = '/my-account/orders/index.html';
		}

**Comment by manniL** [comment] 2020-04-21 12:59
> Hi @manniL, I noticed you said that non-static-generated sites should be directed to 200.html in #7247

Not exactly. Only if you don't have `generate.fallback` enabled. Else, it's 404 (`true`) or whatever string value you set it to.

> I have discarded the .htaccess approach, since I switched to CloudFlare workers, and here I made a script to check the pathname. If the pathname is a route, that is not generated on deploy, it should fallback to index.html of that folder. That works. But now I am in doubt if I should display the 200.html file in the root instead?

The best way would be to always fall back to the "fallback file" (`200.html`) if nothing configured if the route isn't present as HTML file.

**Comment by hummus-studio** [comment] 2020-04-24 09:23
Hello, I'm using the `fallback:true` option and a simple 404.vue. I am using nginx. It works, it shows contents of the 404.vue page but I get this error on the js console:
`Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild`

**Comment by danielroe** [comment] 2024-06-14 16:04
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉

**Closed by danielroe** 2024-06-14 16:04 UTC
Labels: enhancement, 2.x
