### ISSUE TITLE
`useId` hydration mismatch when used in a dynamic global component

### ISSUE THREAD

**Issue by tomek-ch** [nuxt/nuxt#27378] opened 2024-05-27 20:03 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, components
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-hqhma3?file=app.vue

### Describe the bug

When rendering a globally registered component like this: `<Component :is="resolveComponent('ComponentWithId')" />`, `useId` inside that component returns a different id on the server and client, causing a hydration mismatch. The difference is in the separator, `-` changes to `_`.

When rendering that same component normally like this `<ComponentWithId />`, there is no mismatch.

When rendering it like this, it also works:

```vue
<template>
  <Component :is="ComponentWithId" />
</template>

<script setup lang="ts">
const ComponentWithId = resolveComponent('ComponentWithId');
</script>

```

But when the component name is a variable, it breaks again:

```vue
<template>
  <Component :is="ComponentWithId" />
</template>

<script setup lang="ts">
const componentName = 'ComponentWithId';
const ComponentWithId = resolveComponent(componentName);
</script>

```

### Logs

```shell-script
[Vue warn]: Hydration text content mismatch on <div data-v-inspector=​"components/​ComponentWithId.vue:​2:​3" data-n-ids=​"{"nQ7nnZaq0gB-0":​"nQ7nnZaq0gB-0"}​">​nQ7nnZaq0gB_0​</div>​ 
  - rendered on server: nQ7nnZaq0gB-0
  - expected on client: nQ7nnZaq0gB_0 
  at <ComponentWithId> 
  at <AsyncComponentWrapper> 
  at <App key=3 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment] 2024-05-27 20:16
Likely the cause is https://github.com/vuejs/core/issues/6638. Basically Vue does not wait for suspense to resolve before marking the app as 'mounted', which means we have a hydration mismatch.

**Comment by codeflorist** [comment] 2024-07-10 15:43
Probably a different issue, but i'm also getting hydration mismatches, where the trailing number is different. E.g.:

```
  - rendered on server: for="nYyVnEmqzfB-2"
  - expected on client: for="nYyVnEmqzfB-0"
```

It happens in a more complex project with various global components, etc. Unfortunately i wasn't able to distill it into a stackblitz. 🫤

**Comment by dargmuesli** [comment] 2024-07-25 11:38
@tomek-ch Vue v`3.5.0-alpha.4` should include a fix for this issue. Could you try to reproduce it with that release? :pray:

**Closed** 2024-09-03 13:33 UTC
Labels: bug, upstream, upstream-bug
