### ISSUE TITLE
anchors do not work

### ISSUE THREAD

**Issue by syffs** [nuxt/nuxt#5359] opened 2019-03-24 00:35 UTC
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/mz4wjpzy18](https://codesandbox.io/s/mz4wjpzy18)

### Steps to reproduce

1) click anchored link
2) scroll back up
3) click same anchored link => nothing happens

### What is expected ?

working anchors accessible from any page (same or different)

### What is actually happening?

no navigation is perfomed

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8910">#c8910</a>)</em></sub></div>

### Additionnal comment

default `scrollBehavior` does not allow to reach anchors on the same page, but [overriding](https://toor.co/blog/nuxtjs-smooth-scrolling-with-hash-links/) it partially fixes the issue.

**Comment by syffs** [comment] 2019-03-24 01:03
the workaround I found is to combine `to` and `v-scroll-to`:
```
<nuxt-link :to="{path: '/', hash: 'why-data-recovery'}" v-scroll-to="{el: '#why-data-recovery'}">link<:nuxt-link>
```

**Comment by danielroe** [comment] 2019-03-24 13:46
Have you tried `hash: '#anchor'`?

**Comment by syffs** [comment] 2019-03-24 17:22
@danielroe I did know that it could be overrided, but [default scrollBehavior](https://fr.nuxtjs.org/api/configuration-router/#scrollbehavior) looks fine to me... 

Playing with the [repro link](https://codesandbox.io/s/mz4wjpzy18), `hash: '#anchor'` or `hash: 'anchor'` has the same effect. Only a full refresh of the page actually leads to #anchor

**Comment by danielroe** [comment] 2019-03-24 17:46
Yes, I understand, and agree there's an issue. It looks like hashes work if the page changes (try clicking the link from `/about`), but not otherwise. I suggest it is to do with the `window.$nuxt.$once` call.

**Comment by usb248** [comment] 2019-03-24 17:48
It doesn't work in nuxt 2.4.5 too. On first load, no scroll behavior too.

**Comment by syffs** [comment] 2019-03-24 17:56
@danielroe exactly. clicking on an anchored link, scrolling back up and clicking again: 2nd time doesn't work.

It might be an issue with [vue-router](https://github.com/vuejs/vue-router/issues/1668) though

**Comment by chanmathew** [comment] 2019-04-02 20:26
Also running into this issue with Nuxt, but trying this workaround here for now: https://forum.vuejs.org/t/how-to-handle-anchors-bookmarks-with-vue-router/14563/5

**Comment by MoNyU** [comment] 2019-06-06 15:33
Also running into this issue with v2.8.1.

I tried to fix `packages/vue-app/template/router.js` as follows.
This fix makes anchored links work in most browsers.
(However, smooth scrolling on history.back does not work well with iOS Chrome)

### before

https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/router.js#L86-L152

### after

```js
<% if (router.scrollBehavior) { %>
const scrollBehavior = <%= serializeFunction(router.scrollBehavior) %>
<% } else { %>
const scrollBehavior = async function (to, from, savedPosition) {
  // if the returned position is falsy or an empty object,
  // will retain current scroll position.
  let position = false

  // if no children detected and scrollToTop is not explicitly disabled
  if (
    to.matched.length < 2 &&
    to.matched.every(r => r.components.default.options.scrollToTop !== false)
  ) {
    // scroll to the top of the page
    position = { x: 0, y: 0 }
  } else if (to.matched.some(r => r.components.default.options.scrollToTop)) {
    // if one of the children has scrollToTop option set to true
    position = { x: 0, y: 0 }
  }

  // savedPosition is only available for popstate navigations (back button)
  if (savedPosition) {
    position = savedPosition
  }

  await new Promise((r) => window.<%= globals.nuxt %>.$once('triggerScroll', r))

  // coords will be used if no selector is provided,
  // or if the selector didn't match any element.
  if (to.hash) {
    let hash = to.hash
    // CSS.escape() is not supported with IE and Edge.
    if (typeof window.CSS !== 'undefined' && typeof window.CSS.escape !== 'undefined') {
      hash = '#' + window.CSS.escape(hash.substr(1))
    }
    try {
      if (document.querySelector(hash)) {
        // scroll to anchor by returning the selector
        position = { selector: hash }
      }
    } catch (e) {
      console.warn('Failed to save scroll position. Please add CSS.escape() polyfill (https://github.com/mathiasbynens/CSS.escape).')
    }
  }
  return position
}
<% } %>
```

**Comment by folamy** [comment] 2019-10-09 09:08
Nor of the suggested solutions works in latest nuxt version v2.10.0
another thing that gives me concern is that I tried to log document.querySelector() in mounted and it returns null
`
mounted () {
  console.log(document.querySelector('#loginView'))
}
`
result: null

**Comment by seanohue** [comment] 2019-10-23 00:13
Any chance of re-opening this issue as it has not been fixed and, based on @folamy 's comment, seems to have gotten worse?

**Comment by belgacea** [comment] 2020-02-29 09:15
Any news on this issue ?

**Comment by roncarino** [comment] 2020-03-01 12:22
> Also running into this issue with 2.5.1, but trying this workaround here for now: https://forum.vuejs.org/t/how-to-handle-anchors-bookmarks-with-vue-router/14563/5 (See 2nd last comment for solution)

Hi, I am quite a newbie with Nuxt JS, which is amazing btw. 
As @belgacea I am on v2.11.0 and facing this problem. I have used the workaround linked by @chanmathew (https://forum.vuejs.org/t/how-to-handle-anchors-bookmarks-with-vue-router/14563/5 (See 2nd last comment for solution)). Do you have an idea how to add a "smooth" behaviour to that as well? That solution is ok to me, for the moment, but it does look quite ugly to jump to the anchor in that way, without any fake scrolling.
Thanks for any suggestions/solutions :)

Cheers, Loris

**Comment by garyo** [comment] 2020-03-09 18:51
I'm also interested in seeing a "standard" solution to this.

**Comment by rylax** [comment] 2020-03-18 19:11
> Have you tried `hash: '#anchor'`?
> 
> You can see the default scrollBehavior [here](https://nuxtjs.org/api/configuration-router/#scrollbehavior) and you can override this.
> 
> I typically use something like this:
> 
> ```
>   router: {
>     scrollBehavior: async function(to, from, savedPosition) {
>       if (savedPosition) {
>         return savedPosition;
>       }
> 
>       const findEl = async (hash, x = 0) => {
>         return (
>           document.querySelector(hash) ||
>           new Promise(resolve => {
>             if (x > 50) {
>               return resolve(document.querySelector("#app"));
>             }
>             setTimeout(() => {
>               resolve(findEl(hash, ++x || 1));
>             }, 100);
>           })
>         );
>       };
> 
>       if (to.hash) {
>         let el = await findEl(to.hash);
>         if ("scrollBehavior" in document.documentElement.style) {
>           return window.scrollTo({ top: el.offsetTop, behavior: "smooth" });
>         } else {
>           return window.scrollTo(0, el.offsetTop);
>         }
>       }
> 
>       return { x: 0, y: 0 };
>     }
>   },
> ```

Thank you so much! This worked perfectly for me.

**Comment by gaugau3000** [comment] 2020-04-29 14:17
A workaround can be to use [VueScrollTo](https://github.com/rigor789/vue-scrollto) library.
Please look at https://github.com/rigor789/vue-scrollto/issues/251 issue status before using it (work only as a plugin for now)

**Comment by FabianEllenberger** [comment] 2020-05-13 18:07
@danielroe Thanks, your solution seems to work. But this generates the issue, that nuxt will no longer scroll back to top on each route change automatically, even when using `srcollTop: true` on every page manually. I'm using Nuxt 2.4.0.

**Comment by vadimyen** [comment] 2020-06-18 05:20
Is there any news on the _standard and recommended_ (not a workaround) solution?

**Comment by rolexta** [comment] 2021-10-31 13:25
got an issue if anchor tag is generated from kind of WYSISWYG editor from the CMS, when click all anchor tag with hash url it makes the page reload again

**Comment by HenrijsS** [comment] 2021-10-31 13:44
@rolexta Make sure that the anchor doesn't include a "/" before the "#"

**Comment by fkoosan** [comment] 2021-11-22 07:52
Since then, I have confirmed that it works normally with nuxt v2.15.8 by the following method.
・Url input

```
http://localhost:3000/#test
```

・ Anchor in the page

```
<a href="#test"> move to test </a>
```

I would appreciate it if you could refer to it.

◆ app / router.scrollBehavior.js

```
/*
 ** nuxt-link Top Scroll
 */
export default function (to, from, savedPosition) {
  if (savedPosition) {
    return savedPosition
  } else if (to.hash) {
    return {
      selector: to.hash,
    }
  } else {
    return { x: 0, y: 0 }
  }
}
```

◆ Target page.vue

```
<template lang="pug">
〜omit〜
  #test TEST
〜omit〜
</template>

  watch: {
    $route() {
      if (this.$route.hash) {
        setTimeout(() => this.scrollTo(this.$route.hash), 1)
      }
    }
  },
  mounted: function() {
    if (this.$route.hash) {
        setTimeout(() => this.scrollTo(this.$route.hash), 1)
    }
  },

  methods: {
    scrollTo: function(hash) {
      setTimeout(() => {
        location.href = hash
      }, 1)
    },
```

**Comment by josh-collinsworth** [comment] 2022-05-04 19:22
I am running into this issue with Nuxt Bridge, using `"nuxt-edge": "latest"` and  `"@nuxt/bridge": "npm:@nuxt/bridge-edge"`.

No matter what I do, the router never has a value for either `hash` or `query`. Even if I explicitly use `$router.push`, like this:

```js
this.$router.push({ to: '/some-path', hash: '#any' })
```
It still doesn't work; the `hash` is just an empty string. Tried with and without the `#` or a `/`. Tried using `NuxtLink` with the entire path as the `to` attribute; nothing helps. The router just seems to delete the hash and query every time no matter what. (Which means none of the workarounds here is viable in my case, because the `hash` attribute doesn't exist.)

**Comment by danielroe** [comment] 2022-05-04 20:58
@josh-collinsworth It seems to be working fine for me: https://stackblitz.com/edit/github-n3gkty. Note that if you are using object syntax then you use `path` and not `to`.

**Comment by adamchipperfield** [comment] 2022-05-16 12:42
Is there a way we can get this working without hard coded solutions? I have an app where we're passing whatever link is defined in the CMS to nuxt-link.

**Comment by Lucsy3012** [comment] 2022-08-22 13:55
Still no updates on this without using workarounds? I'm no leaning towards just using an `<a>` with `href="#anchor"` instead. The smooth scrolling effect can also be achieved by adding this to the CSS.

```
html {
    scroll-behavior: smooth;
}
```

**Comment by ryanklarhoelter** [comment] 2022-08-23 06:52
I think that might be fixed by this PR:

https://github.com/vuejs/vue-router/pull/3592

Isn't it?

**Comment by ankitsinghaniyaz** [comment] 2022-10-22 07:08
Waiting for this to be sorted out 😅

**Comment by bexter89** [comment] 2022-10-25 14:57
saaame 👀

**Comment by bayasdev** [comment] 2022-12-15 21:01
Is this ever going to be fixed? 🤔

**Comment by rchl** [comment] 2023-03-25 23:53
Appears to be working fine now, after vue-router bug was fixed. I've taken the initial codesanbox example, exported it, updated Nuxt to 2.16.3, ran `yarn upgrade` and it worked as expected.

**Comment by manniL** [comment] 2023-03-26 10:30
Closing here then 👍🏻

**Closed by manniL** 2023-03-26 10:30 UTC
Labels: waiting for dependency, pending, pending triage, 2.x
