### ISSUE TITLE
useState + component + layout create hydration node mismatch

### ISSUE THREAD

**Issue by j4tmr** [nuxt/nuxt#18912] opened 2023-02-09 06:37 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.3.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/jhd4tmr/bug

### Describe the bug

When combined using ```useState``` in ```Component``` in ```layout```, nuxt respond a warning. The server side did not create the component when ```v-if="true"``` in the page in this case.
```
runtime-core.esm-bundler.js:40 [Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM: <!---->  
  at <Test> 
  at <Default > 
  at <LayoutLoader key="default" name="default" hasTransition=false > 
  at <FragmentWrapper > 
  at <NuxtLayout> 
  at <App key=2 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment] 2023-02-09 07:42
I can't see your repo but I hope this comment helps: https://github.com/nuxt/nuxt/issues/18627#issuecomment-1408951142

**Comment by jhd4tmr** [comment] 2023-02-09 07:59
@danielroe I think the problem there is similar. I made a ```Page``` component with several slots to move some codes from layout into ```Page``` component. In every page i imported the ```Page``` component as the root dom. Afterall the warning disappeared. But now a new warning occurs ```Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. ``` 😢 😢

**Comment by jhd4tmr** [comment] 2023-02-10 07:48
@danielroe 
https://github.com/jhd4tmr/bug

1. git clone [https://github.com/jhd4tmr/bug.git](https://github.com/jhd4tmr/bug.git)
2. cd bug
3. yarn install
4. yarn dev
5. open this url: [http://localhost:3000](http://localhost:3000)

```Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.``` This warning is because of other reasons that have nothing to do with this issue.

**Comment by plcdnl** [comment] 2024-04-30 07:03
Got the same error, any updates on this?

**Comment by danielroe** [comment] 2024-04-30 08:23
Closing as I cannot access the reproduction and I believe it to be this issue: https://www.youtube.com/watch?v=dZSNW07sO-A&t=17s.

@plcdnl If that doesn't help, please open a new issue with a reproduction. 🙏

**Closed by danielroe** 2024-04-30 08:23 UTC
Labels: 3.x, pending triage

**Comment by plcdnl** [comment] 2024-04-30 09:12
Thank you for your time @danielroe. Even though the problem wasn't the one specified in the video I understood more or less where I needed to change things. I solved it 😄
