### ISSUE TITLE
Cannot read property 'beforeEach' of undefined

### ISSUE THREAD

**Issue by xuxchao** [nuxt/nuxt#29340] opened 2024-10-09 01:23 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

It's not easy. It's weird

### Describe the bug

![Image](https://github.com/user-attachments/assets/04e9aa6b-46a6-4614-8467-b7c0f8d908ff)

![Image](https://github.com/user-attachments/assets/1048d2a4-2cca-4b35-93bb-b686cfedc414)

Both files are dist artifacts of the nuxt package, which only appear on older browsers (Chrome/61.0.3163.79 in my case), but older browsers are fine. When I tried to solve this problem, I found two ways to solve it:

1. Comment out a line in the template and it will work
2. Delete the rest of the pages he will also perform

**Comment by xuxchao** [comment] 2024-10-09 02:14
Add a workaround:
Using a client-only wrapper is no problem

**Comment by danielroe** [comment] 2024-12-02 14:26
closing due to a lack of a reproduction - please feel free to provide one and I'll happily look into it.

**Closed by danielroe** 2024-12-02 14:26 UTC
Labels: pending triage, needs reproduction
