### ISSUE TITLE
tsconfig.server.json & VSCode warning "Cannot read file"

### ISSUE THREAD

**Issue by kalnode** [nuxt/nuxt#26871] opened 2024-04-20 14:33 UTC
**GOAL:** I'm interested in the benefits this doc item talks about, and not having warnings.
https://nuxt.com/docs/guide/directory-structure/server#server-types

### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      srcDir, devtools, modules, vite, strapi, css, runtimeConfig, image, future, imports
- Runtime Modules:  @nuxtjs/strapi@1.11.0, @pinia/nuxt@0.5.1, @nuxtjs/tailwindcss@6.11.3, @nuxt/image@1.3.0
- Build Modules:    -
------------------------------

### Reproduction

1 - Create `./server/tsconfig.json` with content according to docs:
https://nuxt.com/docs/guide/directory-structure/server#server-types

2 - Reload VSCode, observe warning in the file. To trigger warning, may need to wait some moments or open some other (.ts?) files.

### Describe the bug

VScode warning at top of `./server/tsconfig.json`:

> Cannot read file 'xxxxxxxxxxxxxxxxxxxxx/src/.nuxt/tsconfig.server.json'.ts
> JSON schema for the TypeScript compiler's configuration file

Where "xxxxx..." is my full path to project root.

### Additional context

For better TS support, I created file `./server/tsconfig.json` according to docs
https://nuxt.com/docs/guide/directory-structure/server#server-types

Between tests, I did a complete VSCode window reload.

I do see a generated file `.nuxt/tsconfig.server.json`; Nuxt _is_ generating it.

For fun, I adjusted the path to accurately point to `.nuxt`, `"extends": "../../.nuxt/tsconfig.server.json"` and the warning content changes to:

> Cannot write file 'xxxxxxxxxxxxxxxxxxxxxxxx/constants.js' because it would overwrite input file.ts

Where "xxxxx..." is my full path to project root.

**Comment by dsvgl** [comment] 2024-04-20 22:07
Could you please provide a minimal reproduction? thx 🙏🏻

**Comment by bordermedia** [comment] 2024-04-22 04:31
I also have the same issue in VSC. Can also reproduce the same issue with the new editor Zed.

**Comment by mitjans** [comment] 2024-04-29 09:11
Having a somewhat similar problem when using `@nuxt/eslint` package. When creating a new server route, I get the `Cannot write file '.../eslint.config.mjs' because it would overwrite input file` error.

After looking around `@nuxt/eslint` module repo I found [this comment](https://github.com/nuxt/eslint/issues/402#issuecomment-2069781849) from antfu.

For reproduction:
1. `pnpx nuxi@latest init repro`
2. `pnpm add -D @nuxt/eslint` and add it to the `modules` array.
3. `pnpm postinstall` 👉 this generates the file `eslint.config.mjs`
4. Create a new `server/api/test.get.ts` file

The error should now appear in `tsconfig.server.ts`.

**Comment by MirabelleCORPORATION** [comment] 2024-05-24 09:01
I had a similar issue and i runned "pnpm install" to fix this. My .nuxt was missing or corrupted due to a directory change.

**Comment by danielroe** [comment] 2024-05-24 13:26
This is resolved in https://github.com/unjs/nitro/pull/2402.

**Closed by danielroe** 2024-05-24 13:26 UTC
Labels: 3.x, pending triage, needs reproduction

**Comment by GanymedeIndustries** [comment] 2024-07-29 13:54
Sorry for re-opening, but if anyone is having this error while also defining their own `srcDir` to some child/wrapper dir, then don't forget to also change the `extends` property in the `<srcDir>/server/tsconfig.ts` file. I had the same error but once I re-pointed it to the new path then error went away.
