### ISSUE TITLE
fetching problem!!!!!!!!!

### ISSUE THREAD

**Issue by erbeyinn** [nuxt/nuxt#29327] opened 2024-10-08 14:14 UTC
I am experiencing some issues with the fetch composables provided by your team. These composables seem to function effectively only for GET requests. However, when using POST and PUT methods—especially when sending requests based on parameters like ID and slug—I am encountering “already mounted” and “hydration” warnings. These warnings are causing unexpected bugs and negatively impacting the development process of my project.

I would like to discuss this matter in detail and have you review my project. Please feel free to reach out to me at eyuperbeyinn@gmail.com.

Thank you for your attention to this matter

**Comment by McSundae** [comment] 2024-10-08 20:09
As the Github Bot already mentioned - we need more information for reproduction.

This is mostly an configuration error or the wrong function used for this case.

Can you show us the data fetch part of your app?

**Comment by McSundae** [comment] 2024-10-09 07:28
Thank you for the reproduction files, I see 2 potential problems within your setup.

First thing is that you are using the "lazy" parameter for useFetch, I would avoid that usually.

```
const { data, status, error, refresh, execute } = await useFetch<
    ApiResponse<T>
  >(request, {
    baseURL: config.public.baseURL,
    headers: header as HeadersInit,
    lazy: true,
    ...ops,
  });
```


The second thing I noticed is that you are calling `await execute()` in the mounted hook, which is being executed after the page is build initially. So your function is being executed later which could lead to hydration problems as you mentioned.

```
onMounted(async () => {
  await execute();
});
```

**Comment by erbeyinn** [comment] 2024-10-09 07:31
@McSundae but i have to call the execute function within the onMounted hook. Because the token is coming as null on the server side, but it’s populated on the client side. I also used useCookie, but I encountered the same issue.

**Comment by McSundae** [comment] 2024-10-09 08:01
We would have to check why authentication is not working before, sadly the repro is missing the "store" folder.

**Comment by erbeyinn** [comment] 2024-10-09 08:03
Sorry, I forgot to save it. It’s now available.

**Comment by McSundae** [comment] 2024-10-09 08:19
I see the store folder now and it helps - here lays the foundation why your token is always null without mounted call, you are limiting the setting of values to the client with process.client

process.client && localStorage.setItem('token', token);

I know you do this because of localStorage but instead of working around you should accept that localStorage is probably not the best way for this. I hope this points you in the right direction. The problem is not really the fetch function itself but the authentication or even more precise the storage of auth.

**Comment by danielroe** [comment] 2024-11-08 23:05
Closing as @McSundae is correct here. I hope that was helpful 🙏

**Closed by danielroe** 2024-11-08 23:05 UTC
Labels: pending triage
