### ISSUE TITLE
First tRPC request always returns null inside onMounted

### ISSUE THREAD

**Issue by Leni-Vienne** [nuxt/nuxt#28562] opened 2024-08-15 17:14 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v21.6.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  Bun 1.1.24
- Builder:          -
- User Config:      devtools, build, plugins, modules, css, compatibilityDate
- Runtime Modules:   -
- Build Modules:    -

### Reproduction

with tRPC-Nuxt, have two requests inside a onMounted hook. 
```vue
<template>
    first request: {{ categories }}
    <br>
    second request {{ name }}
</template>

<script setup lang="ts">

let categories = ref<number | null>(null)
let name = ref<string | null>(null)

const { $client } = useNuxtApp();
const { myRoute } = $client

onMounted(async () => {

    let response = await myRoute.getCategories.useQuery()
    categories.value = response.data.value

    let response2 = await myRoute.bookName.useQuery({ title: "x" })
    name.value = response2.data.value
})
</script>
```

### Describe the bug

The first request will return null. Swap the two requests and the same problem occurs, it will be the one on top that fails.
Removing the onMounted hook or adding a `await nextTick()` fixes the problem. Does not happen when navigating to the component, only on refreshes

### Additional context

I'm new to both tRPC and Nuxt. This issue may as well be caused by tRPC or tRPC-nuxt, so I had to choose a repo haha. Anyway not a critical issue and maybe I should just stop using onMounted (?)

### Logs

```shell-script
Just some hydration mismatch issues that I need to understand
```

**Comment by Serpentarius13** [comment] 2024-08-15 21:29
Is .useQuery() hook meant to be called in onMounted? It is a composable, so using it outside of Vue's SFC context wouldn't work I guess

**Comment by felix-dolderer** [comment] 2024-08-19 12:41
I wasn't able to reproduce your issue. For me neither call went through. (Attempted reproduction: https://stackblitz.com/edit/github-rakia6)

I kept getting the following error which seems to me like a problem with `trpc-nuxt` (I'm opening an issue there):
```
✘ [ERROR] Could not resolve "#imports"

    node_modules/trpc-nuxt/dist/client/index.mjs:22:93:
      22 │ import { getCurrentInstance, onScopeDispose, useAsyncData, toValue, ref, isRef, toRaw } from "#imports";
         ╵                                                                                              ~~~~~~~~~~

  You can mark the path "#imports" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.
```
Though that may be due to different version of `trpc-nuxt`. Can you provide a reproduction on stackblitz?

**Comment by Leni-Vienne** [comment] 2024-08-19 20:09
Here is the reproduction on StackBlitz (I'm impressed by how convenient this website is) https://stackblitz.com/edit/nuxt-starter-yfhjfd?file=app.vue
The issue doesn't occur when the requests are in the app.vue file, but everywhere else it does

**Comment by felix-dolderer** [comment] 2024-08-19 21:56
Thank you for that!
There is an issue with nuxt here (or at least some inconsistent / unintuitive behaviour), as the same issue comes up when using the built-in [`useFetch` composable](https://nuxt.com/docs/api/composables/use-fetch).

Reproduction using `useFetch`: https://stackblitz.com/edit/nuxt-starter-n1ok3k?file=pages%2Findex.vue

The intuitive behaviour would either be for all useFetch-calls to fail, or for all of them to succeed.
However the first one fails and all subsequent calls succeed.

---

### Workarounds

@Leni-Vienne I can offer you three workarounds: https://stackblitz.com/edit/nuxt-starter-neviec?file=pages%2Findex.vue

All workarounds make use of various other uses of asyncData. Since you seem to be interested only in the value and no other attributes the [`useFetch` composable](https://nuxt.com/docs/api/composables/use-fetch) provides (wich `useQuery` uses in the background), I'd suggest the first workaround to you.

1. Use `await $client.xxx.query()` inside the `onMounted` hook.
2. Define the `useQuery` statements beforehand and only await the execution in `onMounted`.
3. Define and await the `useQuery` statements directly in the `<script setup>` and not in the `onMounted` hook

**Comment by Leni-Vienne** [comment] 2024-08-19 22:55
thank you for those detailed workarounds! It's some nice pieces of information for me

**Comment by warflash** [comment] 2024-08-30 01:19
Closing this as it's module related and most likely caused by the incorrect registration of the `useQuery` composable within `onMounted`. Thanks @felix-dolderer 😊

**Closed by warflash** 2024-08-30 01:19 UTC
Labels: pending triage, needs reproduction
