### ISSUE TITLE
Routing: page resolutions issue on static web app (Azure)

### ISSUE THREAD

**Issue by Mitschiro** [nuxt/nuxt#19185] opened 2023-02-21 09:27 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `mode`, `css`, `build`, `plugins`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- Create a pages directory in the nuxt project
- Each page needs to have the first letter as Uppercase -> pages/Blogs.vue
- Generate the static web app via npm run generate
- Deploy and run the static web app on azure

### Describe the bug

The issue i have here, is that nuxt compiles the static pages with the uppercase directory like ".output/public/Blogs/*"
Yet when browsing to the page you get an error:
`[nuxt] Cannot load payload  /blogs/_payload.js TypeError: Failed to fetch dynamically imported module:`
This is because either the code, browser or azure automatically transforms the path to lowercase in order to fetch the data, while the real file directory is a direct reflection on how the filename is written.

The initial page load works, when coming from a nuxtlink but if the page is reloaded, a 404 page not found occurs.
Even when changing /blogs to /Blogs in the browser url, the browser still puts it back to lowercase and goes into a 404.

Now, im not a specialist, so i dont know where or what exactly causes this mismatch in behavior.
The only thing i can give is the observation with the case sensitivity of the routing.

**Comment by Baroshem** [comment] 2023-02-21 16:44
Hey!

Could you try to reproduce this issue in another hosting platform like Vercel or Netlify?

I think this issue could be caused by Azure actually but this reproduction would prove it.

**Comment by autorunman22** [comment] 2023-03-09 13:09
I could verify this very issue on Firebase hosting.

**Comment by artem-biryukov** [comment] 2023-03-21 19:06
We have the same issue with Azure Static Web App

**Comment by danielroe** [comment] 2023-10-20 10:52
Closing due to lack of reproduction. If you can still reproduce, please open an issue on https://github.com/unjs/nitro. 🙏

**Closed by danielroe** 2023-10-20 10:52 UTC
Labels: 3.x, pending triage, needs reproduction
