### ISSUE TITLE
Nested Routes + useHead not working correctly

### ISSUE THREAD

**Issue by c-schwan** [nuxt/nuxt#23620] opened 2023-10-11 15:35 UTC
### Environment

- Operating System: Darwin
- Node Version:     v20.7.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt3-nested-routes-head?file=app.vue

### Describe the bug

the body attributes are merged on nested routes.

`<body class="scroll no-scroll">`

useSafeHead({
  bodyAttrs: {
    class: () => (scroll.value ? 'scroll' : 'no-scroll'),
  }
})

**Comment by danielroe** [comment] 2023-10-12 12:35
cc: @harlan-zw

**Comment by Chantal5** [comment] 2024-03-05 11:01
Any progress on this already? I'm running into the same issue. Also found @harlan-zw 's comment in another topic about this issue, with a workaround for as long as the bug still exists. Perhaps it is a good idea to post it here. This works for now:

onMounted(() => {
  Object.values(injectHead()._dom?.sideEffects || {}).forEach((fn) => fn());
});

**Comment by harlan-zw** [comment] 2024-09-07 16:01
Duplicate of https://github.com/nuxt/nuxt/issues/25938 which will be fixed in the next Unhead release :slightly_smiling_face:

**Closed by harlan-zw** 2024-09-07 16:01 UTC
Labels: bug, upstream, 🔨 p3-minor, upstream-bug
