### ISSUE TITLE
SyntaxError: Identifier 'h' has already been declared

### ISSUE THREAD

**Issue by Szymon-dziewonski** [nuxt/nuxt#18823] opened 2023-02-06 15:40 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.1-rc.0-27857531.faf2607`
- Nitro Version:    `2.0.0-27860563.409fe2b`
- Package Manager:  `yarn@3.2.4`
- Builder:          `vite`
- User Config:      `app`, `tailwindcss`, `modules`, `css`
- Runtime Modules:  `@nuxtjs/tailwindcss@^6.1.3`
- Build Modules:    `-`

### Reproduction

Please checkout into https://github.com/vuestorefront/sfui2/tree/nuxt3-bug, and run `yarn` then `yarn dev` in `root` directory, when finished please navigate to http://localhost:3001/examples/VsfDialog in browser.  Error is visible in console right away.

### Describe the bug

Basically `nuxt3` add import that is not needed in external package, that leads to variable name classes and error `SyntaxError: Identifier 'h' has already been declared` . 

`packages/sfui/shared` package built code: 
```
import { h } from '/_nuxt/node_modules/.vite/deps/vue.js?v=d92671f3'; <-- this is added by nuxt when in reality in whole bundled code there is no `h` functional component, whole package is pure vanilla JS code
...
```
Obviously when adding ` --minify=false` into `"dev": "vite build --watch --minify=false",` for building `packages/sfui/shared` fix temporary issue, because there is no variable name clash.

Thank you in advance, for looking into this issue.

### Additional context

`packages/sfui/shared` is one of many monorepo packages, we have control over it. From my point of view it does not really matter because we import/consume this package from `node_modules` as normal `npm` package, its still treated as external package. Additionally this `shared` package is minifed with `vite` so bundle is in common format

I also tried it out with newest `nuxt3` version, unfortunately end up with same result.

**Comment by danielroe** [comment] 2023-02-06 20:26
This looks like it's caused by `unimport`, and one of the reasons we recommend not running it on built packages. To disable unimport scanning your built library, add this to your nuxt.config:

```js
  imports: {
    transform: {
      // you could also add the path of your built library to prevent this happening 
      // for your users, but the issue is probably only replicable in your monorepo
      exclude: [/\bsfui\b/]
    }
  },
```

**Comment by Szymon-dziewonski** [comment] 2023-02-06 21:14
@danielroe I can confirm this fixes my issue, thank you. Can you please point to this place in documentation where it is written anything about this?

>  and one of the reasons we recommend not running it on built packages. 

Issue occurs as well when building (`nuxt build`) whole app with already built `shared` package, so if I understand correctly there might be problems in `development` mode, but not in `production` one, could you please correct me ?

I would be really happy and appreciate if you could shed some light on this one, I would like to understand issue. Maybe this also it will help future travelers :) Thank you

**Comment by danielroe** [comment] 2023-02-06 22:48
Ah, what I mean is that we exclude files in `node_modules` from being imported. It's not something the user has to configure. A monorepo with a built package that you're testing is a little bit different, however.

**Comment by Szymon-dziewonski** [comment] 2023-02-07 14:09
@danielroe dont get me wrong, but I'm trying to understand root of this problem, why you do some auto-imports in first place and modifying packages that comes from `node_modules`

**Comment by danielroe** [comment] 2023-02-07 14:13
We're not modifying files in node_modules. But because you have a monorepo, your built and minified UI library _isn't_ in node_modules.

**Comment by Szymon-dziewonski** [comment] 2023-02-07 14:39
@danielroe my shared package IS in `node_modules`. In monorepo packages are as symlinks in `node_modules` , its exactly the same as I would use `vue` or `vueuse` package from npm

**Comment by danielroe** [comment] 2023-02-17 00:49
I think likely it's because it's a symlink and vite/rollup is following the symlink _out_ of node_modules.

**Comment by Szymon-dziewonski** [comment] 2023-02-17 08:19
then probably nuxt should handle this case as well, IMHO from my point of view this is bug, no matter if thats local workspace or external npm package, this would the same. Anyway thank you for your explanation and help with issue, I do appreciate switch response :)

**Comment by danielroe** [comment] 2023-02-17 09:05
Often users do exactly the same thing in a monorepo with the source code, which does need to be transpiled/processed by Nuxt. This is why we provide the opt-out option in `imports`. I appreciate it's an extra line of config, but it should not be an issue your users experience.

I'm going to close this for now, but I would certainly welcome any PRs to improve this (or if you encounter any other issues with this), and do feel free to reopen @antfu if you think there's something we can be doing better within auto-imports.

**Closed by danielroe** 2023-02-17 09:05 UTC
Labels: 3.x, pending triage

**Comment by samijaber** [comment] 2023-11-15 17:20
To anyone who stumbles on this: for some reason, @danielroe's suggestion didn't work for me.

My situation:
- yarn v3 monorepo
- nuxt 3 server is importing a workspace package

What did work for my use case was to combine these two configs instead:

```ts
// nuxt.config.ts
{
  nitro: {
    rollupConfig: {
      external: [YOUR_PKG_NAME],
    },
  },
  vite: {
    build: {
      rollupOptions: {
        external: [YOUR_PKG_NAME],
      },
    },
  },
}
```

**Comment by samijaber** [comment] 2023-11-15 17:50
I ran into a similar bug that needed a different solution. Sharing for others that might stumble on this:

My setup:
- yarn v3 monorepo
- `nuxt3` workspace server importing a separate `foo` workspace lib

Errors during Nitro Server build step:

```
ℹ Building Nitro Server (preset: node-server)                                          nitro 1:47:23 PM

 ERROR  Error: Transform failed with 3 errors:                                          nitro 1:47:25 PM
/Users/samijaber/code/work/builder/packages/sdks/e2e/nuxt3/.nuxt/dist/server/_nuxt/_...app_-770704c6.js:2207:3: ERROR: The symbol "getCookie" has already been declared
/Users/samijaber/code/work/builder/packages/sdks/e2e/nuxt3/.nuxt/dist/server/_nuxt/_...app_-770704c6.js:2214:3: ERROR: The symbol "setCookie" has already been declared
/Users/samijaber/code/work/builder/packages/sdks/e2e/nuxt3/.nuxt/dist/server/_nuxt/_...app_-770704c6.js:2331:3: ERROR: The symbol "createEvent" has already been declared
```

What worked for me was excluding the `.nuxt/dist/server` in `nitro.imports.exclude`:

```ts
// nuxt.config.ts
{
  nitro: {
    imports: {
      exclude: [/.*.nuxt\/dist\/server.*/],
    },
  },
}
```
