### ISSUE TITLE
Page transitions in 'out-in' mode disrupt layout order

### ISSUE THREAD

**Issue by flschweiger** [nuxt/nuxt#25065] opened 2024-01-05 08:36 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zo83ve?file=app.vue

### Describe the bug

When custom page transitions are defined with the 'out-in' mode, it causes a disruption in custom layouts. The <slot> is consistently rendered at the end of the page after the initial navigation. An example illustrating this issue can be found on [Stackblitz](https://stackblitz.com/edit/nuxt-starter-zo83ve?file=app.vue). The provided example uses the default layout and is expected to display components in the following order:

1️⃣ Navigation
2️⃣ [slot]
3️⃣ Footer

However, after navigating to the /second page, the layout breaks, resulting in the following rendering:

1️⃣ Navigation
3️⃣ Footer
2️⃣ [slot]

The page transition is defined inside the nuxt.config.ts.

**Comment by manniL** [comment] 2024-01-05 10:08
Duplicate of https://github.com/nuxt/nuxt/issues/24632

**Closed by manniL** 2024-01-05 10:08 UTC
Labels: 3.x, pending triage
