### ISSUE TITLE
`useHead` does not inject styles in concurrent pre-rendering

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#22763] opened 2023-08-23 10:49 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.12.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.0
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      devtools, nitro
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-4ah2ty?file=app.vue,nuxt.config.ts

### Describe the bug

We found an issue with `useHead` used in a plugin and using `nuxt generate`.

Download the Stackblitz because they don't have the `grep` command.

First, run `npm run generate`, it should generate 100 pages.

Running:
```bash
grep -RHl '__nuxt' dist/page/ | wc
```

Shows:
```
     100     100    2390
```

Then run:
```bash
grep -RHl 'header-height' dist/page/ | wc
```

Returns:

```bash
      69      69    1725
```

Happy to take a look at it @harlan-zw, seems related directly to `unhead`.

### Additional context

If I set the `concurrency` to `1`, it works perfectly:

```ts
export default defineNuxtConfig({
  nitro: {
    prerender: {
      concurrency: 1,
    }
  }
})
```

But as you know this is not the best case.

**Comment by harlan-zw** [comment] 2023-08-24 10:38
This is the valid work around working in Nuxt 3.7

```ts
export default defineNuxtPlugin((nuxtApp) => {
  const head = nuxtApp.ssrContext!.head
  head.push({
    style: [
      {
        innerHTML: ':root { --header-height: 5em; }',
        tagPriority: -2,
        id: 'nuxt-usehead-concurrency-bug',
      },
    ],
  })
});
```

**Comment by harlan-zw** [comment] 2023-08-24 10:39
Seems to be an issue with the useHead context being unsynced with the nuxt app head instance

**Comment by harlan-zw** [comment] 2023-08-27 14:15
Maybe related https://github.com/nuxt-modules/turnstile/pull/271?notification_referrer_id=NT_kwDOAFFGHbI3NTEzMzg3ODIwOjUzMjYzNjU#event-10201716443

**Comment by harlan-zw** [comment] 2023-08-31 15:54
This is now fixed in Unhead [1.4.0 ](https://github.com/unjs/unhead/releases/tag/v1.4.0) without any workarounds.

**Closed by harlan-zw** 2023-08-31 15:54 UTC
Labels: 3.x, bug, ❗ p4-important

**Comment by Ni55aN** [comment] 2023-09-01 11:29
`useSeoMeta` doesn't work for me since 3.7.0, but worked correctly in 3.3.1

unhead is v1.4.1

**Comment by harlan-zw** [comment] 2023-09-01 11:41
> 

Can you provide some reproduction details?

**Comment by Ni55aN** [comment] 2023-09-01 11:58
@harlan-zw 

https://github.com/retejs/retejs.org/tree/nuxt-use-head-issue

after `npm run generate` the html files inside /.output/public/examples have messy meta tags. For example, `twitter:image` should end with filename other than `main.png`

**Comment by harlan-zw** [comment] 2023-09-01 13:08
> @harlan-zw
> 
> [retejs/retejs.org@`nuxt-use-head-issue`](https://github.com/retejs/retejs.org/tree/nuxt-use-head-issue?rgh-link-date=2023-09-01T11%3A58%3A41Z)
> 
> after `npm run generate` the html files inside /.output/public/examples have messy meta tags. For example, `twitter:image` should end with filename other than `main.png` and be related to html page
> 
> If I downgrade nuxt to 3.5, it works correctly

Can you provide some actual code? I can't see what you mean, it looks like the examples don't have meta tags?

I'd recommend upgrading using `npx nuxi upgrade --force`

**Comment by Ni55aN** [comment] 2023-09-01 14:32
@harlan-zw it has latest nuxt version 3.7.0, right?

>  it looks like the examples don't have meta tags

they have, but these tags are mixed up between different examples (in .output/public) 

`npx nuxi upgrade --force` doesn't help. After my `npm run generate` I received `.output/public/examples/chatbot/index.html` without meta tags at all. At the same time `.output/public/examples/allmatter/index.html` has wrong meta tags from different example.

If I downgrade nuxt to 3.5, the resulting `.output` has correct files

**Comment by harlan-zw** [comment] 2023-09-05 14:32
> @harlan-zw it has latest nuxt version 3.7.0, right?
> 
> > it looks like the examples don't have meta tags
> 
> they have, but these tags are mixed up between different examples (in .output/public)
> 
> `npx nuxi upgrade --force` doesn't help. After my `npm run generate` I received `.output/public/examples/chatbot/index.html` without meta tags at all. At the same time `.output/public/examples/allmatter/index.html` has wrong meta tags from different example.
> 
> If I downgrade nuxt to 3.5, the resulting `.output` has correct files

Please try out 3.7.1 :pray:

**Comment by Ni55aN** [comment] 2023-09-06 10:24
@harlan-zw unfortunately after updating to 3.7.1 the `generate` command throws `500` for some pages. How to debug such an errors on `generate`? These pages do not throw any error on `dev` or `build` (+ node ./index.mjs)

![image](https://github.com/nuxt/nuxt/assets/8259641/1e3d75ec-4d0f-4e5b-96f6-1b31f9f1ca22)

I found a possible reason of the error (using `useSeoMeta` in one of the components), but I can't figure out what exactly Error it throws, because if I comment it like `/*useSeoMeta*/({ title, ... ` it works, so the exception is not TypeError

**Comment by harlan-zw** [comment] 2023-09-06 12:23
Would it be possible to make a separate issue @Ni55aN? It seems unrelated to the original

**Comment by Ni55aN** [comment] 2023-09-07 17:53
@harlan-zw https://github.com/nuxt/nuxt/issues/23074
