### ISSUE TITLE
theme-color meta tags are incorrectly deduped

### ISSUE THREAD

**Issue by P4sca1** [nuxt/nuxt#28298] opened 2024-07-24 14:39 UTC
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, modules
- Runtime Modules:  @nuxtjs/color-mode@3.4.2
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-ycyewb?file=app.vue

### Describe the bug

I set 3 different `theme-color` meta tags using `useHead` in `app.vue`.

```ts
useHead({
  meta: [
	  // Set theme-color based on color mode
	  {
		  name: 'theme-color',
		  key: 'system prefers light mode',
		  media: '(prefers-color-scheme: light)',
		  content: colorMode.preference === 'dark' ? '#111827' : '#ffffff',
	  },
	  {
		  name: 'theme-color',
		  key: 'system prefers dark mode',
		  media: '(prefers-color-scheme: dark)',
		  content: colorMode.preference === 'light' ? '#ffffff' : '#111827',
	  },
	  {
		  name: 'theme-color',
		  key: 'fallback for browsers without media support for theme-color',
		  // use dark style by default, unless preference is set to light explicitly.
		  content: colorMode.preference === 'light' ? '#ffffff' : '#111827',
	  },
  ],
})
```

I expect the following meta tags to be present when loading the page:
```
<meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#111827">
<meta name="theme-color" content="#111827">
```
In fact, after the initial render (SSR) these meta tags are correctly set. I verified using curl.

However, after client hydration, the meta tags change to the following:
```
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#ffffff">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#111827">
```

**Comment by harlan-zw** [comment] 2024-07-24 16:45
This is a duplicate of https://github.com/unjs/unhead/issues/172, @P4sca1 would you mind sharing the reproduction there?

**Closed by harlan-zw** 2024-07-24 16:45 UTC
Labels: pending triage, upstream
