### ISSUE TITLE
Why can't the server run?  "vue-router": "^4.3.2"，"vue": "^3.4.26",

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#27048] opened 2024-05-03 08:56 UTC
### Environment

{
  "name": "168bbwl",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@amap/amap-jsapi-loader": "^1.0.1",
    "@amap/amap-jsapi-types": "^0.0.13",
    "@ant-design-vue/nuxt": "^1.4.1",
    "@element-plus/nuxt": "^1.0.9",
    "@kjgl77/datav-vue3": "^1.7.2",
    "@nuxt/content": "^2.12.1",
    "@nuxt/ui-pro": "^1.1.0",
    "@nuxtjs/device": "^3.1.1",
    "@nuxtjs/mdc": "^0.7.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@tweenjs/tween.js": "^23.1.1",
    "@types/file-saver": "^2.0.7",
    "@types/streamsaver": "^2.0.4",
    "@types/three": "^0.164.0",
    "@vueuse/nuxt": "^10.9.0",
    "ant-design-vue": "^4.2.1",
    "dayjs-nuxt": "^2.1.9",
    "echarts": "^5.5.0",
    "element-plus": "^2.7.2",
    "jwt-decode": "^4.0.0",
    "mqtt": "^5.5.5",
    "nuxt": "^3.11.2",
    "nuxt-swiper": "^1.2.2",
    "pinia": "^2.1.7",
    "three": "^0.164.1",
    "vue": "^3.4.26",
    "vue-router": "^4.3.2"
  },
  "dependencies": {
    "@formkit/auto-animate": "^0.8.2",
    "@nuxt/image": "^1.6.0",
    "angular-expressions": "^1.2.1",
    "docxtemplater": "^3.47.1",
    "docxtemplater-image-module-free": "^1.1.1",
    "file-saver": "^2.0.5",
    "jszip": "^3.10.1",
    "pinia-plugin-persistedstate": "^3.2.1",
    "pixi.js": "^8.1.0",
    "pizzip": "^3.1.7",
    "streamsaver": "^2.0.6",
    "xlsx": "^0.18.5"
  }
}

### Reproduction

node  version 
v20.12.0

### Describe the bug

2|168bbwl  | [nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading 'isCE')
2|168bbwl  |   at renderSlot (./.output/server/node_modules/vue/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2309:32)  
2|168bbwl  |   at ./.nuxt/dist/server/_nuxt/Container-CO3S6tvy.js:53:11  
2|168bbwl  |   at normalizeChildren (./.output/server/node_modules/vue/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5821:34)  
2|168bbwl  |   at createBaseVNode (./.output/server/node_modules/vue/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5654:5)  
2|168bbwl  |   at _createVNode (./.output/server/node_modules/vue/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5716:10)  
2|168bbwl  |   at _sfc_ssrRender (./.nuxt/dist/server/_nuxt/Container-CO3S6tvy.js:47:25)  
2|168bbwl  |   at renderComponentSubTree (./.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:430:9)  
2|168bbwl  |   at renderComponentVNode (./.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:376:12)  
2|168bbwl  |   at ssrRenderComponent (./.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:84:10)  
2|168bbwl  |   at ./.nuxt/dist/server/_nuxt/index-j763oBm4.js:39:13
3|168bbwl  | [nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading 'isCE')
3|168bbwl  |   at renderSlot (./.output/server/node_modules/vue/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2309:32)  
3|168bbwl  |   at ./.nuxt/dist/server/_nuxt/Container-CO3S6tvy.js:53:11  
3|168bbwl  |   at normalizeChildren (./.output/server/node_modules/vue/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5821:34)  
3|168bbwl  |   at createBaseVNode (./.output/server/node_modules/vue/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5654:5)  
3|168bbwl  |   at _createVNode (./.output/server/node_modules/vue/node_modules/@vue/runtime-dom/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5716:10)  
3|168bbwl  |   at _sfc_ssrRender (./.nuxt/dist/server/_nuxt/Container-CO3S6tvy.js:47:25)  
3|168bbwl  |   at renderComponentSubTree (./.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:430:9)  
3|168bbwl  |   at renderComponentVNode (./.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:376:12)  
3|168bbwl  |   at ssrRenderComponent (./.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:84:10)  
3|168bbwl  |   at ./.nuxt/dist/server/_nuxt/index-j763oBm4.js:39:13

**Comment by manniL** [comment] 2024-05-03 09:53
Duplicate of https://github.com/vuejs/core/issues/4344#issuecomment-899064501

**Closed by manniL** 2024-05-03 09:53 UTC
Labels: 3.x, pending triage, needs reproduction
