### ISSUE TITLE
Upgrading to v3.4.0 breaks runtimeConfig

### ISSUE THREAD

**Issue by mtdvlpr** [nuxt/nuxt#20226] opened 2023-04-12 08:39 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  yarn@3.5.0
- Builder:          vite
- User Config:      srcDir, ssr, telemetry, typescript, build, imports, router, sourcemap, modules, i18n, vite, runtimeConfig
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.10, @vueuse/nuxt@9.13.0, nuxt-lodash@2.4.1, @pinia/nuxt@0.4.8, nuxt-electron@0.4.5, ()
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-eky4to?file=app.vue

### Describe the bug

With `ssr: false`, the `useRuntimeConfig()` breaks somehow. I get an error and the entire application is not rendered.

### Additional context

It has to do with these lines:
```js
const runtimeConfig = process.server ? options.ssrContext.runtimeConfig : reactive(nuxtApp.payload.config);
  const compatibilityConfig = new Proxy(runtimeConfig, {
    get(target, prop) {
      if (prop in target) {
        return target[prop];
      }
      if (process.dev && prop in target.public) {
        console.warn(`[nuxt] [runtimeConfig] You are trying to access a public runtime config value (\`${prop}\`) directly from the top level. This currently works (for backward compatibility with Nuxt 2) but this compatibility layer will be removed in v3.5. Instead, you can update \`config['${prop}']\` to \`config.public['${prop}']\`.`);
      }
      return target.public[prop];
    },
    set(target, prop, value) {
      if (process.server || prop === "public" || prop === "app") {
        return false;
      }
      target[prop] = value;
      target.public[prop] = value;
      return true;
    }
  });
```

### Logs

```shell-script
Error while mounting app: TypeError: `target` argument of Proxy must be an object, got undefined
```

**Comment by danielroe** [comment] 2023-04-12 08:43
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) via https://github.com/nuxt/nuxt/pull/20216, or in the next release.

Let me know if not and I'll reopen.

**Closed by danielroe** 2023-04-12 08:43 UTC
Labels: 3.x, pending triage

**Comment by vinayakkulkarni** [comment] 2023-04-12 20:19
Duplicate of #20212
