### ISSUE TITLE
Nuxt Installation failed

### ISSUE THREAD

**Issue by Croodo** [nuxt/nuxt#19866] opened 2023-03-22 18:46 UTC
### Environment

macOS Monterey
Macbook Air M2 (2022)
Node.js v18.13.0
### Reproduction

No production is required I guess.

### Describe the bug

Recently I tried to install nuxt, but got an error on installation command `npm install`.

Something wrong with the nuxt's package.json .
**error message:**
No "exports" main defined in ....../node_modules/nuxt/package.json 

<img width="1470" alt="Screenshot 2023-03-23 at 12 02 00 AM" src="https://user-images.githubusercontent.com/67230713/227006242-50b695ad-df3a-4281-b924-dffce5786b13.png">

**Comment by slaetthult** [comment] 2023-03-23 16:08
macOS Catalina 10.15.6
MacBook Pro
Node.js v18.15.0 (npm v9.5.0)

I have got similar issues:
  Vue packages version mismatch:
  
  - vue@2.6.12
  - vue-server-renderer@2.6.14
![Bildschirmfoto 2023-03-23 um 17 08 19](https://user-images.githubusercontent.com/22275417/227265037-ffdfe5e9-3a1d-4e7d-bbda-96344d01ee81.png)

**Comment by danielroe** [comment] 2023-03-23 16:29
@Croodo Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Croodo** [comment] 2023-03-23 17:54
Here is the reproduction [link](https://codesandbox.io/p/github/Croodo/nuxterror) .

It works in the codesandbox.

You should try it by creating a new project to identify the issue.

**Comment by Croodo** [comment] 2023-03-24 07:46
Yes, this reproduction is the project where I'm getting the error locally, tried creating multiple projects using `npx nuxi init .` 

I'm not sure but can it be an issue with my environment anyway?

**Comment by danielroe** [comment] 2023-03-24 22:36
Would you try with the latest 3.3.2 version?

**Comment by slaetthult** [comment] 2023-03-24 23:38
Unfortunately still have the same issue.

**Comment by slaetthult** [comment] 2023-03-28 08:12
Help

**Comment by danielroe** [comment] 2023-03-28 08:14
Would you check whether you have a node_modules folder in a parent directory, perhaps with Nuxt 2 installed? Or indeed, if you have Nuxt 2 installed globally?

**Comment by pumano** [comment] 2023-03-28 20:24
I got this with nuxt2 2.16.3 while updating from 2.16.1 

```Cannot start nuxt:  No "exports" main defined in /projectDir/node_modules/@nuxt/schema/package.json```

**Comment by Luferov** [comment] 2023-04-02 12:30
Apple M1 Max MacOS 13.3 Ventura
Node: v19.18.1
Npm: 9.5.1


<img width="1081" alt="image" src="https://user-images.githubusercontent.com/26242554/229352839-db26b6fb-ab12-4b25-8980-3e3d2cf4826a.png">

**Comment by Luferov** [comment] 2023-04-03 05:53
To reproduction:
```
git clone git@github.com:devind-team/partsorder.git partsorder
cd partsorder
rm package-lock.json # do not work without this file
npm i
```
Got error

**Comment by danielroe** [comment] 2023-04-03 10:04
@Luferov I can't reproduce this with those steps.

**Comment by Luferov** [comment] 2023-04-03 10:51
> @Luferov I can't reproduce this with those steps.

Are you deleting yarn.lock too? Need to delete all lock files…

**Comment by danielroe** [comment] 2023-04-03 11:24
Okay, I can reproduce that. But it's an issue stemming from https://github.com/nuxt-modules/i18n/blob/next/src/module.ts#L326-L328 (upstream in https://github.com/unjs/pkg-types).

The cause is that there is no package lockfile when `nuxi prepare` runs. You could probably work around it by removing it from your `postinstall` or just including a package lockfile in your project.

It's also not the same issue as the originally reported issue.

**Comment by Luferov** [comment] 2023-04-03 11:53
> The cause is that there is no package lockfile when `nuxi prepare` runs. You could probably work around it by removing it from your `postinstall` or just including a package lockfile in your project.
> 
> It's also not the same issue as the originally reported issue.

Omg, sorry😢 but thanks for help!

**Comment by lihbr** [comment] 2023-04-05 19:58
I'm not sure of the source of this issue, but I think I know a workaround:

Can you try deleting your **global** node modules folder? A friend of mine, @danielphilipjohnson, had this issue and sorted it out this way.

**Comment by danielroe** [comment] 2023-04-06 09:13
closing as it seems this is resolved upstream: https://github.com/nuxt-modules/i18n/issues/1976

**Closed by danielroe** 2023-04-06 09:13 UTC
Labels: 3.x, pending triage, needs reproduction

**Comment by shilongfeicool** [comment] 2023-05-29 10:17
How can I solve the same problem I encountered?
![image](https://github.com/nuxt/nuxt/assets/31263758/90299685-1c89-4f72-8001-57cda01e143d)

**Comment by s1mpLyy** [comment] 2023-06-30 13:13
I have fixed this issue on Windows after 1 month of trying xD,

I have deleted node_modules located in C:/Users/{PC_NAME}/node_modules

And hit npm i on my project

**Comment by mbadr2200** [comment] 2023-07-22 10:34
> I have fixed this issue on Windows after 1 month of trying xD,
> 
> I have deleted node_modules located in C:/Users/{PC_NAME}/node_modules
> 
> And hit npm i on my project

this works for me
