### ISSUE TITLE
Option to pass 'head' property in generate routes() function payload to create dynamic headers

### ISSUE THREAD

**Issue by Sford4** [nuxt/nuxt#8153] opened 2020-10-06 03:05 UTC
### Is your feature request related to a problem? Please describe.

At the moment, the `head()` method, executed at the component level, will not be triggered when `nuxt generate` is run, though a payload can be passed using the `routes()` method.  It is frustrating that we can generate all the static content but not the headers.  In order to get the SEO benefits, I'd need to have my app run in universal mode, which means having a dedicated express server, which is much more costly, stressful and complicated than serving statically (from S3, for instance).

### Describe the solution you'd like

Another optional property on each object in the array returned by the `generate` `routes()` method, probably called `head`, perhaps which can use the same syntax as the component-level `head()` method.  It might look like:

```
generate: {
    routes() {
      return axios
        .get(`${process.env.ROOT_URL}/products`)
        .then(res => { 
          return res.data.map(product => {
            return {
              route: `/product/${product.id}`,
              payload: product,
              head: {
                       title: product.name
                       meta: [
                           {
                                 hid: `productPageDescription-${product.id}`,
                                 name: "description",
                                 content: product.description
                           },
                           {
                                hid: `productPageKeywords-${product.id}`,
                                name: "keywords",
                                content: product.keywords
                           }
                      ]
                 }
            };
          });
        });
    }
  },
```

Under the hood, Nuxt would have to check if the `head` property is present on the payload, and insert html by route accordingly.

This way we could have all the benefits of a statically hosted site and the SEO that folks come to Nuxt for!

### Describe alternatives you've considered

Looked into serving a universal-style Nuxt app through an AWS Lambda to save on cost, other than that all the solutions I can find are much more costly and complicated.

### Additional context

I'd be totally fine if we could just crack the problem of the component's `head()` method not working its magic during `nuxt generate`, but this seems like this change would solve the SEO issue without messing with the other things going on with Nuxt under the hood.

Just spitballing, but this change might involve changes in [`nuxt.js/packages/generator/src/generator.js`](https://github.com/nuxt/nuxt.js/blob/dev/packages/generator/src/generator.js) like:

```
***Line  270***
async generateRoute ({ route, payload = {}, head={}, errors = [] }) {

***Line 287, inside generateRoute()***
const renderContext = {
        payload,
        head,  // the head property on each the objects returned from generate.routes()
        staticAssetsBase: this.staticAssetsBase
}
```

Then in [`nuxt.js/packages/vue-renderer/src/renderers/ssr.js` ](https://github.com/nuxt/nuxt.js/blob/61e93d01f96adf505025fafa85d4054658758e8b/packages/vue-renderer/src/renderers/ssr.js) change to add a conditional at `line 118`, which will either grab the meta info provided as a default in `nuxt.config.js` or else the `head` passed in on the `renderContext` object, creating the meta tags likely the same way as is currently done, subbing out whatever was provided in `head`.

Thank you so much for your consideration!

**Comment by jellymann** [comment] 2020-10-11 08:25
You can achieve this by using `asyncData` and `head` functions in a dynamic page, for example:

`pasges/projects/_projectId.vue`
```vue
<script>
export default {
  async asyncData() {
    let product = await axios.get(`${process.env.ROOT_URL}/products/${params.projectId}`);
    return { product };
  },
  head({ product }) {
    return {
      title: product.name
      meta: [
        {
          hid: `productPageDescription-${product.id}`,
          name: "description",
          content: product.description
        },
        {
          hid: `productPageKeywords-${product.id}`,
          name: "keywords",
          content: product.keywords
        }
      ]
    };
  }
}
</script>
```

**Comment by Sford4** [comment] 2020-10-13 23:21
@jellymann when I use your suggestion, either passing a `payload` to my dynamic component or having the dynamic component call for it's own data, `the index.html` that is created in my `dist` folder will only include headers from `nuxt.config.js` (the defaults).

I've been serving statically from S3.  When I visit one of my dynamic routes on the browser, the `<title>` tag starts as the default title then changes to the dynamic header the `head()` method creates (in this case 'Billy's Radish Shack', see gif)

![AWIzBF](https://user-images.githubusercontent.com/18560225/95925925-42a0c080-0d78-11eb-93c3-d596fff2cf8f.gif)

Are you saying that search engine crawlers will pick up the dynamic title, description, etc, rather than the default ones that initially come down with the index.html?  That's the problem I'm trying to address with my feature request.

Thanks!

**Comment by jellymann** [comment] 2020-10-14 10:53
I just checked and the method I used does in fact put the `<title>` tag in the HTML when generating a static site.

Have a look at my website: https://www.sourlemon.co.za, and click on one of the dynamic pages (like a blog post or talk page), you'll see the dynamic title if you view source. Also if you navigate the site with JavaScript disabled the dynamic title will also still show up.

**Comment by jscottsf** [comment] 2020-11-08 10:01
Having a similar issue. Seems that `asyncData` is not getting called during a static generate. Still debugging and digging - will followup.

**Comment by jscottsf** [comment] 2020-11-08 11:51
Since the `asyncData` doesn't fire on the page for an SPA generate, I managed to get dynamic head values in the generated static HTML (for SEO!).

1. Return a `route` and `payload` in your routes array like usual.

2. In your config, add a hook to modify the `head` in the `renderContext`. This is called right before the HTML is generated. e.g. you could modify `head.title` based on a value in the payload.

```
    hooks: {
      'vue-renderer': {
        spa: {
          prepareContext({ head, payload }) {
            // Example
            if (payload && payload.title) head.title = payload.title
          }
        }
      }
    },
```

**Comment by benoitemile** [comment] 2023-05-03 22:02
Hello,

I'm curious about that issue, it was previously opened here too : https://github.com/nuxt/nuxt/issues/2648 

Steps to reproduce : 
have some head global infos in nuxt.config.js : 
`head: {
    meta: [
      { hid: 'my-awesome-desc', name: 'description', content: 'lorem'}
   ]
}`

try to override them with pages/foo.vue :
`head: {
    meta: [
      { hid: 'my-awesome-desc', name: 'description', content: 'ipsum dolor sit amet'}
   ]
}`

in generate mode, this doesn't work, it always takes default/global nuxt.config.js data

thank you

**Comment by danielroe** [comment] 2024-06-14 16:04
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉

**Closed by danielroe** 2024-06-14 16:04 UTC
Labels: enhancement, 2.x
