### ISSUE TITLE
`inlineSSRStyles` option causes duplication of CSS

### ISSUE THREAD

**Issue by fabon-f** [nuxt/nuxt#21821] opened 2023-06-27 14:42 UTC
### Environment

Nuxi 3.6.1

RootDir: /home/projects/github-nk3n5b
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-nk3n5b?file=app.vue

### Describe the bug

Inlined CSS files are also loaded from `link` tag, which cause duplication of CSS. This problem occurs only if SSR is enabled (after `nuxi build` or `nuxi generate`), doesn't happen in `nuxi dev`.

![screenshot 2023-06-27 22:55:21](https://github.com/nuxt/nuxt/assets/8928378/8c8be53a-8b13-49ea-a02b-068f3b311040)

I guess `inlineSSRStyles` option is for the performance improvements, but this behavior wipes out the benefit. (HTML is bloated a bit, browser still fetches render-blockign CSS, and that's all)

### Additional context

Maybe related to #21762

**Comment by dargmuesli** [comment] 2023-08-30 23:58
Updated reproduction, still reproducible in v3.7: https://stackblitz.com/edit/github-nk3n5b-sex9hu?file=package.json

**Comment by harlan-zw** [comment] 2023-08-31 16:27
@danielroe any ideas?

**Comment by danielroe** [comment] 2023-08-31 19:10
I think this is a limitation of the current inlining style implementation.

Styles used _everywhere_ on your app could safely be removed entirely from CSS source directly. But CSS used only in one component or a page need to be located in a CSS file _as well as_ inlined.

At the moment, vite is in charge entirely of loading CSS on the client side which means that even if we did track what CSS was already loaded, we can't stop vite from loading the CSS files which contain duplicated CSS.

This is something I definitely want to fix.

**Comment by Barbapapazes** [comment] 2023-09-01 13:48
Yes, and this can remove the order of style so reset CSS can be applied after real CSS.

see https://github.com/unjs/website/pull/96#discussion_r1312789972

**Comment by iWatchYouFromAfar** [comment] 2023-11-22 08:58
> I think this is a limitation of the current inlining style implementation.
> 
> Styles used _everywhere_ on your app could safely be removed entirely from CSS source directly. But CSS used only in one component or a page need to be located in a CSS file _as well as_ inlined.
> 
> At the moment, vite is in charge entirely of loading CSS on the client side which means that even if we did track what CSS was already loaded, we can't stop vite from loading the CSS files which contain duplicated CSS.
> 
> This is something I definitely want to see fixed.

Do I understand correctly that with the `inlineSSRStyles` option enabled, we will currently get duplicate styles?

Is there anything we can do about this without turning off the `inlineSSRStyles` option?

Below is a link to reproduce duplicate styles at the .button class.

https://stackblitz.com/edit/github-g4givn?file=app.vue,package.json,components%2FButton.vue

**Comment by zavvla** [comment] 2024-02-03 08:47
In addition, there are no types, which causes a letter error.

nuxt: v3.10.0

![image](https://github.com/nuxt/nuxt/assets/11782509/8ceb584a-682e-4222-bcc0-41d7dbcdb590)

**Comment by danielroe** [comment] 2024-02-03 10:23
@zavvla The configuration option is now under the `features` namespace: https://nuxt.com/docs/api/nuxt-config#inlinestyles

**Comment by botmaster** [comment] 2024-03-01 11:14
I spent a lot of time trying to solve this strange behavior. Duplication of styles is a major performance issue.
Should the `inlineStyles` parameter be set to false by default?

**Comment by Barbapapazes** [comment] 2024-03-01 12:07
> I spent a lot of time trying to solve this strange behavior. Duplication of styles is a major performance issue.
> Should the `inlineStyles` parameter be set to false by default?

Having in-line styles help to have a better first rendering since there is no needs for the ccs files to be load before having styles. That's a compromise between visual rendering and global weight.

**Comment by Salotronic** [comment] 2024-04-10 14:55
Is there any news on this? Fix this for large projects with bigs css like designs systems, etc it is very important.
At this time makes Core Web Vitals very difficult to get good results, also google pagespeed shows a lot of alerts.

**Comment by septatrix** [comment] 2024-04-24 16:31
Another aspect which amplifies the effects even more is that stuff like `url("~/assets/icons/foobar.svg")` also results in the SVG itself being embedded into the `<style>` tag. In my case I have thousands of quite small pages so this contributed significantly to the output size.

**Comment by hecktarzuli** [comment] 2024-05-23 19:36
I have what seems to be a temp "fix".  It literally comments out links to css files in rendered html (server side).  I'm not sure if this works with pre-rendered sites etc.   You can adjust the regex as needed.  When I tested it in my local env, it took < 0.13ms
```
// server/plugins/css.ts

export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('render:html', (html, { event }) => {
    html.head.forEach((item, index) => {
      html.head[index] = item.replaceAll(/^(<link rel="stylesheet".+>)/gm, '<!-- $1 -->')
    })
  })
})
```
![image](https://github.com/nuxt/nuxt/assets/2112282/e5c05211-565a-4d5f-b05f-0b1be78ada16)

**Comment by manniL** [comment] 2024-05-24 12:46
> I have what seems to be a temp "fix".  It literally comments out links to css files in rendered html (server side).  I'm not sure if this works with pre-rendered sites etc.   You can adjust the regex as needed.  When I tested it in my local env, it took < 0.13ms
> 
> ```
> 
> // server/plugins/css.ts
> 
> 
> 
> export default defineNitroPlugin((nitroApp) => {
> 
>   nitroApp.hooks.hook('render:html', (html, { event }) => {
> 
> 
> 
>     // let dev run as normal
> 
>     if (import.meta.dev) return
> 
> 
> 
>     html.head.forEach((item, index) => {
> 
>       html.head[index] = item.replaceAll(/^(<link rel="stylesheet".+>)/gm, '')
> 
>     })
> 
>   })
> 
> })
> 
> ```
> 
> ![image](https://github.com/nuxt/nuxt/assets/2112282/e5c05211-565a-4d5f-b05f-0b1be78ada16)
> 
> 

I would probably limit that to the entry file only, otherwise CSS from eg client components might not be loaded (didn't test but likely given Daniel's comment above)

**Comment by hecktarzuli** [comment] 2024-05-24 12:58
@manniL The style above the commented out .css file is the contents of the css file.  So far so good.

**Comment by danielroe** [comment] 2024-05-24 13:21
**Note**: If we were certain that the we had _all_ the content in the `.css` files, Nuxt would omit rendering them. (And we do omit rendering CSS files we are confident have the same content.) If you can find an example of CSS that is _exactly_ the same  let me know with a reproduction and I'll investigate.

**Comment by hecktarzuli** [comment] 2024-05-24 13:24
> **Note**: If we were certain that the we had _all_ the content in the `.css` files, Nuxt would omit rendering them. (And we do omit rendering CSS files we are confident have the same content.) If you can find an example of CSS that is _exactly_ the same let me know with a reproduction and I'll investigate.

Is this in any case, or only when inlineSSRStyles is `true` ?

**Comment by hecktarzuli** [comment] 2024-05-24 13:34
@danielroe here ya go https://github.com/hecktarzuli/nuxt-3-inline-styles

**Comment by johannschopplich** [comment] 2024-05-31 04:56
I have written a lightweight Nuxt module that allows you to remove the entry stylesheet from the HTML: [Nuxt LCP Speedup](https://github.com/johannschopplich/nuxt-lcp-speedup). A workaround as a Nuxt module. 😄 

All you have to do is install the module:

```bash
npx nuxi@latest module add nuxt-lcp-speedup
```

Then add it to your Nuxt configuration and enable the `disableEntryStylesheet` option.

```ts
export default defineNuxtConfig({
  modules: ['nuxt-lcp-speedup'],

  lcpSpeedup: {
    disableEntryStylesheet: true
  },
})
```

Make sure to test the result!

👉 [Read the documentation](https://github.com/johannschopplich/nuxt-lcp-speedup).


[![Nuxt LCP Speedup module](https://raw.githubusercontent.com/johannschopplich/nuxt-lcp-speedup/main/.github/og.jpg)](https://github.com/johannschopplich/nuxt-lcp-speedup)

**Comment by danielroe** [comment] 2024-12-20 11:25
Should be resolved in https://github.com/nuxt/nuxt/pull/30305.

From v4, we will only inline styles for Vue components used on the page, which should keep duplicated CSS to a minimum.

If you want to try it out sooner, set:

```ts
export default defineNuxtConfig({
  features: {
    inlineStyles: (id) => !!id && id.includes('.vue')
  }
})
```

**Closed by danielroe** 2024-12-20 11:25 UTC
Labels: ❗ p4-important, performance, ✨ good reproduction, inline styles

**Comment by danielroe** [comment] 2025-01-01 21:21
@ihardz would you please open a new issue with a reproduction? 🙏

**Comment by Tofandel** [comment] 2025-01-07 13:11
Why are inline styles needed and enabled in the first place by default? Doesn't vite already bundle all of the component's css into separate css bundles which are already loaded on the page, hence the duplication

**Comment by hecktarzuli** [comment] 2025-01-07 14:11
@Tofandel CSS bundles are render blocking.  It's usually better to inline CSS when possible.

**Comment by Tofandel** [comment] 2025-01-07 15:40
Yes and no, it has pros and cons

Only critical css on the first visit should be inlined (eg only to style what's in the viewport), because it has the disadvantage of being tied to the html page and so not cacheable, which may highly reduce further page load times on slower networks. It's actually better to use a linked stylesheet that is cached for further navigation.
CSS being render blocking is not really a problem when you know that the HTML of the page is also render blocking and the CSS will start to load as soon as the link tag is parsed in the head of the HTML, yes it will do another request but it was going to happen no matter what, or at least the size of the content to download, this just helps avoid a ping rountrip (which should be less than 50ms already and if you have more then your CDN or other delivery mechanism should be improved)

Using both at the same time, which is what's currently happening is just getting the cons of both in all aspects
