### ISSUE TITLE
ERROR  [worker reload] [worker init] /home/luckyloo/WebstormProjects/SurfMarket/.nuxt/dev/index.mjs failed

### ISSUE THREAD

**Issue by luckyloo1730** [nuxt/nuxt#29948] opened 2024-11-17 11:35 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.1.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@8.8.0
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

When starting Nuxt development server, using `npm run dev` I get an error 

### Describe the bug

`ERROR  [worker reload] [worker init] /home/luckyloo/WebstormProjects/SurfMarket/.nuxt/dev/index.mjs failed`

### Additional context

I've tried reinstalling the packages, deleting .nuxt directory, didn't help. I've also tried to go to an older version, didn't help neither. At some point the error vanished for some time, before appearing again.

### Logs

```shell-script

```

**Comment by yannhodiesne** [comment] 2024-11-17 11:53
Potential duplicate of my issue here: https://github.com/nuxt/nuxt/issues/29929

**Comment by huang-julien** [comment] 2024-11-17 16:11
closing as duplicate of https://github.com/nuxt/nuxt/issues/29943

**Closed by huang-julien** 2024-11-17 16:11 UTC
Labels: pending triage, needs reproduction

**Comment by RajaShanmugamJM** [comment] 2024-11-21 04:46
In my case, I started using bun (`bun --bun run dev`) instead of node. Where everything was working fine. But when I tried to switch to npm (`npm run dev`) I got this error.

> Note: This happened on server/api

When debugged further I found the issue with lodash module import.

With bun, everything worked when I imported as follows (named import),
`import {first} from 'lodash'`

In order to make the app run with bun I'd refactor the imports to namespace import
`import l from 'lodash'`

I can confirm, I've specified `type:'module'` in package.json

https://github.com/user-attachments/assets/09b2640d-661b-4ab0-8f4e-92b067db42c9
