### ISSUE TITLE
title from defineNuxtConfig is not substituted into titleTemplate as default value if the page does not have its own title defined

### ISSUE THREAD

**Issue by Semdevmaster** [nuxt/nuxt#26550] opened 2024-03-29 11:55 UTC
### Environment

- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      app, devtools, ssr, modules, tailwindcss, ui, features, experimental
- Runtime Modules:  @nuxt/ui@2.15.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-7pdnsh?file=nuxt.config.ts
![with-title](https://github.com/nuxt/nuxt/assets/2706508/a0fe4a5d-73ad-4490-9268-0e7bf84c4bbe)
![without-title](https://github.com/nuxt/nuxt/assets/2706508/47021897-3304-4468-a704-1c1874eb088f)

https://github.com/nuxt/nuxt/assets/2706508/fb8dbc72-4936-4eba-89c8-4d6b9dcda192

### Describe the bug

title from defineNuxtConfig is not substituted into titleTemplate as default value if the page does not have its own title defined

**Comment by danielroe** [comment] 2024-03-30 08:10
cc: @harlan-zw

**Comment by harlan-zw** [comment] 2024-04-01 13:03
Thanks for the detailed reproduction, I can confirm this is a bug with [Unhead](https://github.com/unjs/unhead). I've moved the issue here https://github.com/unjs/unhead/issues/335.

Since this can be fixed outside of Nuxt, I'll close this.

**Closed by harlan-zw** 2024-04-01 13:03 UTC
Labels: 3.x, upstream-bug
