### ISSUE TITLE
404/200.html have no access to server generated state/payload on prerendered sites

### ISSUE THREAD

**Issue by codeflorist** [nuxt/nuxt#22952] opened 2023-09-01 16:51 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      nitro
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zforh2?file=app.vue

### Describe the bug

Consider this `app.vue`:

```vue
<script setup>
const foo = useState('foo');
if (process.server) {
  foo.value = 'bar';
}
</script>
<template>
  <div>
    {{ foo }}
  </div>
</template>
```

Using prerendering, this will result in a `404/200.html`, that has no info on the `foo` state/payload:
```html
<script type="application/json" id="__NUXT_DATA__" data-ssr="false">[{"_errors":1,"serverRendered":2,"data":3,"state":4},{},false,{},{}]</script>
```

Thus calling any non-existing page will not display `bar`, while in a `dev` or `build` environment it will be displayed, resulting in different behaviour between environments.

The main usecase/problematic is, that normally you want to display things like the menu on a 404-page just like on any other. With e.g. a headless CMS it makes sense to fetch this only during generation, store it in a state and never have it fetched by the client.

I would expect any server generated state/payload defined in `app.vue` to be also available in the `404/200.html` files.

**Comment by manniL** [comment] 2023-09-01 18:28
I think this is a duplicate of https://github.com/nuxt/nuxt/issues/18718

Please ping in case you think this is a different issue ☺️

**Closed by manniL** 2023-09-01 18:28 UTC
Labels: 3.x, pending triage

**Comment by codeflorist** [comment] 2023-09-01 20:37
@manniL thanks for researching and taking a look! it seems to be related, but #18718 doesn't touch the issue with state/payload at all. that issue is primarily about how to get `error.vue` to use the default-layout (which imho can be achived by using `NuxtLayout`). but i have just added a comment detailing the state/payload problem and refering to this issue.

also, in the issue @danielroe writes:
> /404.html is meant to be an empty shell that could render any page of the app

if that is the case, in my opinion it should also have access to states/palyoads that were set during prerendering in `app.vue` (or in the default-layout, if `NuxtLayout` is used in `error.vue`). because otherwise it might lack important information to actually be able to render any page of the app.

**Comment by codeflorist** [comment] 2023-09-16 07:25
what i'm doing now is the following:

in `error.vue` i use `NuxtLayout` and pass a special property:
```html
<template>
	<NuxtLayout :is-error="true">
		...
	</NuxtLayout>
</template>
```

in the default-layout i use this property to not load header and footer (which contain payload information that would trigger a new api-fetch which we don't want):
```html
<script lang="ts" setup>
const layoutCustomProps = useAttrs()
</script>

<template>
	<div>
		<PageHeader v-if="!layoutCustomProps['is-error']" />
		<slot />
		<PageFooter v-if="!layoutCustomProps['is-error']" />
	</div>
</template>
```

now this still leaves the problem, that a 404 call will still traverse `app.vue` > default layout > `[[...slug].vue]` before even hitting `error.vue`. thus the api call will still be triggered. to alleviate this, i check for `process.server` to allow api calls to only happen during generation, and never on the client.

of course this is all very ugly and header and footer will be missing from the 404 pages. :/

**Comment by joe-mohan** [comment] 2023-09-29 10:13
@codeflorist How are you using process.server ? 

I can't figure out how to use it with useAsyncQuery

**Comment by codeflorist** [comment] 2023-09-29 10:17
@joe-mohan 

you can simply use:

```js
if (process.server) {
    // do what you don't want to be done on client
}

**Comment by joe-mohan** [comment] 2023-10-03 11:42
@codeflorist thanks for the tip, We're still struggling to get this to work - i was wondering if you have any ideas?

```

<script setup>
import pageQuery from "~/apollo/queries/page.js";

let pageData = ref(null);

if (process.dev || process.server) {
  const route = useRoute();
  const slug = route.params.slug ? route.params.slug : "home";
  const data = await useAsyncQuery(pageQuery, { slug });
  pageData.value = data;
}
</script>

<template>
  <StructurePage
    v-if="pageData?.data?.page?.data"
    :page="pageData.data.page.data.attributes"
  />
</template>

```

With this code, we have strange behaviour where you get a flash of the page content but then the pageData disappears - it seems on mount

**Comment by codeflorist** [comment] 2023-10-03 13:34
@joe-mohan 

Try this:
```js
const route = useRoute();
const slug = route.params.slug ? route.params.slug : "home";
const pageData = useState('pageData-'+slug, null);
if (process.dev || process.server) {
  const data = await useAsyncQuery(pageQuery, { slug });
  pageData.value = data;
}
```

`useState()` will store the result in the payload of a statically generated page - making it available for the client.

`ref()` doesn't do that, which explains the behaviour. `pageData` gets filled on server, but on client it will be turned into `null` once the page is hydrated.
