### ISSUE TITLE
After update to Nuxt 3.5.0 after run npm i Cannot read properties of undefined (reading 'replace') 

### ISSUE THREAD

**Issue by vitjaz** [nuxt/nuxt#20884] opened 2023-05-16 15:51 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.14.2
- Nuxt Version:     3.5.0
- Nitro Version:    -
- Package Manager:  npm@9.2.0
- Builder:          vite
- User Config:      ssr, components, modules, pinia, svgo, css, tailwindcss
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, @nuxtjs/i18n@8.0.0-beta.12, nuxt-svgo@3.1.0, @vueuse/nuxt@10.1.2, @pinia/nuxt@0.4.10
- Build Modules:    -
------------------------------

### Reproduction

Run ``npx nuxi upgrade --force``, and after I got a lot of error. Then delete node_modules and run `npm i` and have error.

### Describe the bug

Bug after npm i command.

### Logs

```shell-script
> postinstall
> nuxt prepare

Nuxi 3.5.0                                                                                                                                                                                                 18:43:24  
ℹ Using Tailwind CSS from ~/assets/css/tailwind.scss                                                                                                                                      nuxt:tailwindcss 18:43:26  

 WARN  Vue I18n configuration file does not exist at i18n.config. Skipping...                                                                                                                 @nuxtjs/i18n 18:43:26  

 WARN  i18n:extend-messages is deprecated. That hook will be removed feature at the time of the v8 official release.                                                                          @nuxtjs/i18n 18:43:26  
If you're using it, please use i18n:registerModule instead.


 ERROR  Cannot read properties of undefined (reading 'replace')                                                                                                                                            18:43:27  

  at /C:/repo/qvant/contacts-front/node_modules/nuxt/dist/index.mjs:890:140
  at Array.map (<anonymous>)
  at Object.getContents (/C:/repo/qvant/contacts-front/node_modules/nuxt/dist/index.mjs:888:68)
  at compileTemplate (/C:/repo/qvant/contacts-front/node_modules/@nuxt/kit/dist/index.mjs:108:21)
  at /C:/repo/qvant/contacts-front/node_modules/nuxt/dist/index.mjs:3258:28
  at Array.map (<anonymous>)
  at generateApp (/C:/repo/qvant/contacts-front/node_modules/nuxt/dist/index.mjs:3257:101)
  at async _applyPromised (/C:/repo/qvant/contacts-front/node_modules/nuxt/node_modules/perfect-debounce/dist/index.mjs:54:10)

npm ERR! code 1
npm ERR! path C:\repo\qvant\contacts-front
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c nuxt prepare

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alexevi.av\AppData\Local\npm-cache\_logs\2023-05-16T15_43_22_386Z-debug-0.log
```

**Comment by danielroe** [comment] 2023-05-16 15:59
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by mcpanl** [comment] 2023-05-17 05:31
@vitjaz You can try changing the network environment and deleting nodes_ The module folder and lock file, and then install the dependencies. Yesterday, I encountered a similar problem, and after doing so, everything was normal.

**Comment by danielroe** [comment] 2023-10-20 11:02
Closing as I can't reproduce but if you're still encountering, please let me know and I'll investigate.

**Closed by danielroe** 2023-10-20 11:02 UTC
Labels: 3.x, pending triage, needs reproduction

**Comment by viswasakthi3** [comment] 2024-02-29 16:01
im getting the similar error whenever the system is abruptly stopped not sure its node issue o
r nuxt issue i tried
PS C:\Users\viswa\Desktop\nuxt-proj\theluvit> npm run dev

> dev
> nuxt

'nuxt' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\viswa\Desktop\nuxt-proj\theluvit>



PS C:\Users\viswa\Desktop\nuxt-proj\theluvit> npm install
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\viswa\\Desktop\\nuxt-proj\\theluvit\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\viswa\Desktop\nuxt-proj\theluvit\node_modules\@nuxt'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\viswa\\Desktop\\nuxt-proj\\theluvit\\node_modules\\@nuxt'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\viswa\Desktop\nuxt-proj\theluvit\node_modules\vue-demi
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node -e "try{require('./scripts/postinstall.js')}catch(e){}"
npm ERR! 'node' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in: C:\Users\viswa\AppData\Local\npm-cache\_logs\2024-02-29T15_08_05_358Z-debug-0.log
PS C:\Users\viswa\Desktop\nuxt-proj\theluvit> node -v
v20.11.1
PS C:\Users\viswa\Desktop\nuxt-proj\theluvit> npm list nuxt
nuxt-app@ C:\Users\viswa\Desktop\nuxt-proj\theluvit
└── (empty)

PS C:\Users\viswa\Desktop\nuxt-proj\theluvit>

**Comment by MHillier98** [comment] 2024-08-13 15:30
Did you end up fixing this?
