### ISSUE TITLE
Build process does not finish after completion (timeout-Netlify)

### ISSUE THREAD

**Issue by tobychidi** [nuxt/nuxt#29868] opened 2024-11-10 09:09 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/ui@3.0.0-alpha.8, @pinia/nuxt@0.7.0, @nuxt/image@1.8.1, @vueuse/nuxt@11.2.0, nuxt-gtag@3.0.1, @nuxt/eslint@0.6.1, @nuxtjs/leaflet@1.2.4
- Build Modules:    -
------------------------------

Also had this issue on Netlify deployment 

### Reproduction

https://github.com/tobychidi/nuxt-nitro-api-reprod

This a simpler project. 

### Describe the bug

This error happens, even on Netlify where I deploy and the build does not exist?

![Image](https://github.com/user-attachments/assets/8902e7ff-398a-490b-a0f5-833d32ca6585)

It gets to the end but never finishes until timeout.

### Additional context

```
WARN  [vite:css] Lexical error on line 1: Unrecognized text.                                                          7:22:01 AM

  Erroneous area:
1: infinity * 1px
^..^
3009|      &::after {
3010|        content: var(--tw-content);
3011|        border-radius: calc(infinity * 1px);
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3012|      }
3013|    }
```

I use NuxtUI alpha.  This warning shows up but it's supposedly not supposed to affect the build. 

_No response_

### Logs

```shell-script

```

**Comment by tobychidi** [comment] 2024-11-10 12:18
I have just done more testing. Locally, the project builds but the process did not exit. Like I show in the picture. I had to do `Ctrl+c` to manually exit the process then run the preview and it works. 

I am guessing the fact it doesn't exit is why Netlify is having a hard time with it.

**Comment by tobychidi** [comment] 2024-11-10 18:57
Apparently the reproduction I have deploys correctly. Digging deeper. 

![Image](https://github.com/user-attachments/assets/48a311ce-6b03-4700-8379-dbe957bee775)

This is what I am facing on my main project.

**Comment by obj63mc** [comment] 2024-11-11 21:08
I am also having this issue on my project, the build process never completes and stops at the same line noting where you can preview the build.

We had to revert back to nuxt 3.13.  We discovered this when deploying to heroku the 'nuxt build' command just will never complete.

> Σ Total size: 28.4 MB (10.3 MB gzip)
✔ You can preview this build using node .output/server/index.mjs                                                            nitro 3:05:27 PM

**Comment by obj63mc** [comment] 2024-11-11 21:42
Doing research I found the following issue from previous versions - https://github.com/nuxt/cli/issues/193

Adding in this work around mentioned in the bug does solve our build process.  Again as to what is causing the nitro's build process to hang I cannot determine.  We have commented out each feature on our site one by one and none seem to make a difference.

Modules we are using are the following - 

    "@nuxt/content": "^2.13.4",
    "@nuxt/image": "^1.8.1",
    "@nuxtjs/cloudinary": "^4.0.0",
    "@nuxtjs/robots": "^4.1.11",
    "@nuxtjs/sitemap": "^6.1.5",
    "@pinia/nuxt": "^0.7.0",
    "nuxt": "^3.14.159",
    "nuxt-gtag": "^3.0.1",
    "nuxt-schema-org": "^3.4.1",
    "nuxt-svgo": "^4.0.8",    
    "sass-embedded": "~1.79.5"

**Comment by mahapo** [comment] 2024-11-15 01:28
![Image](https://github.com/user-attachments/assets/260e4c8b-7ac4-4ffc-b896-3ee2dd465258)
I have similar issue after updating to 3.14.159

**Comment by danielroe** [comment] 2024-12-02 16:14
This is probably triggered by one of your modules registering a watcher or something else and not cleaning it up after the build finishes.

I can't reproduce with the linked reproduction and a local build, so possibly this has been resolved with a dependency.

If it is still occurring for you, let me know with a new reproduction and I'll happily reopen.

**Closed by danielroe** 2024-12-02 16:14 UTC
Labels: pending triage, nitro
