### ISSUE TITLE
The title tag is after the meta tag !!!

### ISSUE THREAD

**Issue by xiuxiumomo** [nuxt/nuxt#20406] opened 2023-04-20 02:10 UTC
### Environment

nuxt:  "nuxt": "^2.4.0",

linux-centos 7.x

or 

windows 11

### Reproduction

you can see here: https://www.cbi360.net/

### Describe the bug

1.we found the title tag is after the meta tag, so ite maked TDK wrong!
2.check source-code,it  show that

```
<html>
<body>


<meta data-n-head="ssr" name="viewport" content="width=device-width, initial-scale=1">
<meta data-n-head="ssr" data-hid="description" name="description" content="mmmmmm">
<title>xxx</title>

</body>
</html>

```
we can see title label is aftered the description label,i try many nuxt2.x verson but it doesnot work.

3.wish 
```
 <title>xxx</title>
<meta data-n-head="ssr" data-hid="description" name="description" content="mmmmmm">
```

### Additional context

page:

  head() {
    return {
      title: "aaa",
      meta: [
        {
          hid: "description",
          name: "description",
          content:
            "bbb",
        },

      ]
   
   
    };
  },

nuxt.config.js
export default {

...
 meta: [

      {
        name: "viewport",
        content: "width=device-width, initial-scale=1"
      },
      {
        hid: "description",
        name: "description",
        content: process.env.npm_package_description || ""
      }
    ],

}

**Comment by peterroe** [comment] 2023-04-20 05:01
Hi, As far as I know, the postion of the `<meta>` and `<title>` should not have any other impact. Have you meet any problems?

**Comment by manniL** [comment] 2023-04-20 08:28
Duplicate of https://github.com/nuxt/nuxt/issues/18936 I think

**Closed** 2023-04-20 08:30 UTC
Labels: pending triage, 2.x, needs reproduction

**Comment by xiuxiumomo** [comment] 2023-04-21 09:19
> Would you provide a reproduction, and ensure you're on the latest version of Nuxt? 🙏

the web url : https://www.cbi360.net/ and F12 you can see the title tag is aftered meta tag~
node --version 16.18.1
platForm win11, centos-7.x

**Comment by manniL** [comment] 2023-04-21 10:06
<img width="620" alt="image" src="https://user-images.githubusercontent.com/640208/233609446-d998f8d0-0e3d-4bce-9af3-da18f45c854b.png">

**Comment by luckilyhang** [comment] 2023-04-25 03:48
> <img alt="image" width="620" src="https://user-images.githubusercontent.com/640208/233609446-d998f8d0-0e3d-4bce-9af3-da18f45c854b.png">
<meta data-n-head="ssr" charset="utf-8"><meta data-n-head="ssr" name="viewport" content="width=device-width, initial-scale=1"><meta data-n-head="ssr" data-hid="description" name="Description" content="建筑业大型门户网站，提供建筑行业信息服务：包含建筑建设中标，诚信，荣誉，资质信息查询、政策资讯、建设招标、PPP项目、建筑工程众包等，建筑网以提升建筑行业信息化水平为己任。"><meta data-n-head="ssr" name="mobile-agent" content="format=xhtml; url=https://m.cbi360.net/"><meta data-n-head="ssr" name="mobile-agent" content="format=html5; url=https://m.cbi360.net/"><meta data-n-head="ssr" name="mobile-agent" content="format=wml; url=https://m.cbi360.net/"><title>建筑网—专业的建筑施工企业大数据征信查询平台</title>

**Comment by luckilyhang** [comment] 2023-04-25 03:48
> <img alt="image" width="620" src="https://user-images.githubusercontent.com/640208/233609446-d998f8d0-0e3d-4bce-9af3-da18f45c854b.png">

    <meta data-n-head="ssr" charset="utf-8"><meta data-n-head="ssr" name="viewport" content="width=device-width, initial-scale=1"><meta data-n-head="ssr" data-hid="description" name="Description" content="建筑业大型门户网站，提供建筑行业信息服务：包含建筑建设中标，诚信，荣誉，资质信息查询、政策资讯、建设招标、PPP项目、建筑工程众包等，建筑网以提升建筑行业信息化水平为己任。"><meta data-n-head="ssr" name="mobile-agent" content="format=xhtml; url=https://m.cbi360.net/"><meta data-n-head="ssr" name="mobile-agent" content="format=html5; url=https://m.cbi360.net/"><meta data-n-head="ssr" name="mobile-agent" content="format=wml; url=https://m.cbi360.net/"><title>建筑网—专业的建筑施工企业大数据征信查询平台</title>

**Comment by Majanecy** [comment] 2024-01-30 07:51
@xiuxiumomo Hi bro, How did you solve it in the end? Thank you~
