### ISSUE TITLE
 ERROR  Cannot start nuxt:  require() of ES Module ... /node_modules/wide-align/align.js not supported.

### ISSUE THREAD

**Issue by thomasbrodusch** [nuxt/nuxt#26402] opened 2024-03-20 12:48 UTC
### Environment

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      ssr, devtools, modules, i18n, supabase
- Runtime Modules:  @nuxtjs/i18n@8.2.0, @nuxtjs/supabase@1.1.7, @nuxtjs/tailwindcss@6.11.4, nuxt-icon@0.6.9, @pinia/nuxt@0.5.1, @element-plus/nuxt@1.0.7
- Build Modules:    -

### Reproduction

-

### Describe the bug

Cannot run nuxt anymore

### Logs

```shell-script
ERROR  Cannot start nuxt:  require() of ES Module /Users/thomas/Workspace/perso/testnuxt/node_modules/string-width/index.js from /Users/thomas/Workspace/perso/testnuxt/node_modules/wide-align/align.js not supported.
Instead change the require of index.js in /Users/thomas/Workspace/perso/testnuxt/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.

  Instead change the require of index.js in node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
  at Object.<anonymous> (node_modules/wide-align/align.js:2:19)
```

**Comment by flexbox** [comment] 2024-03-21 09:04
I successfully fixed my build with this resolution on `package.json`
```
"resolutions": {
    "jackspeak": "2.1.1"
 }
```
from https://github.com/nuxt/nuxt/issues/21231#issuecomment-1887664446

@thomasbrodusch do you think it could be a duplicate of #21231

**Closed** 2024-03-21 14:48 UTC
Labels: 3.x, pending triage, needs reproduction

**Comment by thomasbrodusch** [comment] 2024-03-29 11:14
Thanks a lot @flexbox it fixes the whole stuff!
