### ISSUE TITLE
extract window.__NUXT__ to <script>

### ISSUE THREAD

**Issue by andyyanlang** [nuxt/nuxt#8548] opened 2020-12-24 08:07 UTC
hello！ I want to extract window.__NUXT__ to <script> tag，It's friendly to SEO. today  I find https://nuxtjs.org/ has been implemented this function. please update the lastest doc.  show how to config, thanks!

**Comment by andyyanlang** [comment] 2020-12-24 08:35
hello! i want to put "window.NUXT=" in the <scipt> tag.  https://nuxtjs.org/  has achieved. you can see <script defer="" src="/_nuxt/static/1608754458/docs/2.x/get-started/installation/state.js"></script> in  the dome of  https://nuxtjs.org/ . so i want to know how to config

> I am not sure to understand what you want to achieve @andyyanlang

**Comment by andyyanlang** [comment] 2020-12-24 08:36
> I am not sure to understand what you want to achieve @andyyanlang

hello! i want to put "window.NUXT=" in the script tag. https://nuxtjs.org/ has achieved. you can see <script defer="" src="/_nuxt/static/1608754458/docs/2.x/get-started/installation/state.js"></script> in the dom of https://nuxtjs.org/ . so i want to know how to config

**Comment by andyyanlang** [comment] 2020-12-24 08:50
> I am not sure to understand what you want to achieve @andyyanlang

hello! i want to extract "window.NUXT=" into the external script links. as you can see https://nuxtjs.org/ has achieved. you can find <script defer="" src="/_nuxt/static/1608754458/docs/2.x/get-started/installation/state.js"></script> in the dom of https://nuxtjs.org/ . so i want to know how to config

**Comment by pi0** [comment] 2020-12-24 10:37
@andyyanlang This is possible when you set target to static.

- Article: https://nuxtjs.org/blog/going-full-static/
- Docs: https://nuxtjs.org/docs/2.x/features/deployment-targets

**Comment by andyyanlang** [comment] 2020-12-30 00:53
is there anyway to achieve when sse mode? besides when i config hooks.vue-renderer:ssr:context.  i override it (context.nuxt = { serverRendered: true, routePath, config }),  then "window.NUXT=" become very simple. this is friendly to SEO. but there is a question. i can see the ajax methods in ayncData . they request in server and  also request in client. there is useless and repeat in client. why  they request in client ?

**Comment by andyyanlang** [comment] 2020-12-30 00:55
is there anyway to achieve when ssr mode? besides when i config hooks.vue-renderer:ssr:context. i override it (context.nuxt = { serverRendered: true, routePath, config }), then "window.NUXT=" become very simple. this is friendly to SEO. but it bring another question. i can see the ajax methods in ayncData . they request in server and also request in client. they are useless and repeat in client. why they request in client ?

**Comment by wh4t3ver92** [comment] 2021-02-11 11:10
I have same problem, and I will add a bit of background for you to understand why sb might want to do this. We need this for SEO purposes. I'm using headless Wordpress with Nuxt as landing page. We want to use structured data from google, but cuz of window.NUXT our schema is duplicated, see here: https://search.google.com/structured-data/testing-tool/u/0/?hl=pl#url=https%3A%2F%2Fciekawecv.pl%2Fblog%2Frekrutacja-w-formie-ac-jak-wyglada-jak-sie-do-niej-przygotowac%2F 
As you can see FAQPage have 2 errors - duplicated FAQPage, cuz google see it in window.NUXT.
How I'm fetching data from Wordpress before generate (I'm using  target: "static").
`  fetchPosts : async (context) => {
    return await $axios.get(`${endpoint.posts}?per_page=50`).then((res) => {
      const apiPosts = res.data;
      let posts = [];
      for ( const post of apiPosts ){
        if( post.is_ready ){
          posts.push(post)
        }
      }

      context.commit('setPosts',posts);
      return res.data
    })
  },

   fetchPages : async (context) =>{
    return await $axios.get(`${endpoint.pages}?per_page=50`).then((res) => {
      context.commit('setPages', res.data);
      return res.data
    })
  },

  fetchCategories : async (context) => {
    return await $axios.get(`${endpoint.categories}`).then((res) => {
      const apiCategories = res.data;
      let categories = [];
      for ( const category of apiCategories ){
        if( category.slug !== 'inne' ){
          categories.push(category);
        }
      }

      context.commit('setCategories', categories);
      return res.data
    })
  },

  async nuxtServerInit ({ dispatch }, { req }) {
    await dispatch('fetchCategories');
    await dispatch('fetchPages');
    await dispatch('fetchPosts');
  }`
  
  example of commit `  setPosts (state, posts) {
    state.posts = posts
  },`

**Comment by HanOy** [comment] 2021-05-14 05:42
same problem, any solutions in ssr mode?

**Comment by hktom** [comment] 2021-10-21 15:58
You can try this, it worked for me: 
`// nuxt.config.js
{
...,
hooks: {
    'vue-renderer:ssr:context'(context) {
      const routePath = JSON.stringify(context.nuxt.routePath);
      context.nuxt = {serverRendered: true, routePath};
    }
  }
}`

**Comment by aokihu** [comment] 2022-02-08 04:14
why there is no official way to solve the problem, but the office site move "__NUXT__" into a isolate script file!

**Comment by hktom** [comment] 2022-02-08 08:04
> why there is no official way to solve the problem, but the office site move "**NUXT**" into a isolate script file!

https://nuxtjs.org/docs/configuration-glossary/configuration-build

The official way to solve the problem,

**Comment by xuzhengquan** [comment] 2022-03-18 03:43
> > why there is no official way to solve the problem, but the office site move "**NUXT**" into a isolate script file!
> 
> https://nuxtjs.org/docs/configuration-glossary/configuration-build
> 
> The official way to solve the problem,

How to config?

**Comment by geodou** [comment] 2022-06-21 12:34
> > why there is no official way to solve the problem, but the office site move "**NUXT**" into a isolate script file!
> 
> https://nuxtjs.org/docs/configuration-glossary/configuration-build
> 
> The official way to solve the problem,

After looking in the official Docs for nuxt config file, I couldn't find anything related to this problem. Could you please be a little bit more specific as to what the official solution is? Thank you in advance!

**Comment by landoephan** [comment] 2023-01-03 15:57
`target: 'static'` is removed in nuxt3, is there any way to move __NUXT__ inside a script in nuxt3? I'm using CSR

**Comment by danielroe** [comment] 2023-02-14 11:35
Duplicate of https://github.com/nuxt/nuxt/issues/6641.

**Closed by danielroe** 2023-02-14 11:35 UTC
Labels: enhancement, 2.x
