### ISSUE TITLE
No type completion support for components in a Nuxt layer

### ISSUE THREAD

**Issue by agenordebriat** [nuxt/nuxt#21877] opened 2023-06-30 23:42 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.1`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.3.1`
- Builder:          `vite`
- User Config:      `extends`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Impossible to reproduce online due to the nature of CodeSandbox/StackBlitz.
Need to run the project in VS Code w/ Volar.

### Describe the bug

When extending a Nuxt layer that's a npm package with a component inside of it, I don't get any type completion for props.

I do, in fact, have everything working fine If I extend the layer in the `.playground` folder directly inside the same project.
Let's say I create a simple `MyButton` component that accepts a `variant` prop that could be `"solid"` or `"ghost"`: I get `variant` autocompleted then it suggests `solid` or `ghost` as possible values.

Now, If I install the package and extend it in `nuxt.config.ts` and try to replicate this behavior, it doesn't work. Component works fine though. 

Plugins I provide are working fine. Example: `$toast` is suggested, the `success` property pops up if I try `$toast.s` and I get every available hint inside of it. Same thing for composables (custom one or imported from layer dependencies).

Is it a Volar issue? Should I do something in my `tsconfig` file?
I tried with my work project layer as well as other random layers available on npmjs and got the same outcome.

### Additional context

VS Code 1.79.2 w/ Volar 1.8.3.

**Comment by NozomuIkuta** [comment] 2023-07-02 17:41
I'm not sure what actually happens due to lack or reproduction (could you provide a GitHub repository instead of StackBlitz by which I can see the code in VSCode in my local?). 

But, as far as I see your description, it might be related to Volar's breaking change as of v1.8.2.
That is, Vue files that are not listed up in `include` option in `tsconfig.json` are no longer parsed by Volar.
It would be worth trying to add path(s) to your components in `include` option.

https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md#182-2023627

**Comment by agenordebriat** [comment] 2023-07-02 18:56
@NozomuIkuta Rolled back Volar to 1.8.0 and it works, so I'll definitely have a look at your solution first thing tomorrow and move the discussion to the right place then.

**Comment by agenordebriat** [comment] 2023-07-02 20:39
@danielroe Do you think it should be mentioned somewhere in the documentation, either in the Volar part or the authoring layers section? I'm down to suggest something if necessary.

**Comment by danielroe** [comment] 2023-07-03 11:37
Yes, I think that's a reasonable solution :+1:

**Comment by danielroe** [comment] 2023-07-03 19:53
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Closed by danielroe** 2023-07-03 19:53 UTC
Labels: 3.x, pending triage
