### ISSUE TITLE
Server assets in Nuxt 3.1.1 not mounted according to docs

### ISSUE THREAD

**Issue by mcrapts** [nuxt/nuxt#18587] opened 2023-01-27 21:50 UTC
### Environment

Nuxt project info:                                                               22:36:00

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `typescript`, `nitro`, `app`, `alias`, `css`, `vite`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-u78ses?file=server/api/test.ts

### Describe the bug

`test.txt` is not available with the key `server:assets:test.txt` according to https://nitro.unjs.io/guide/introduction/assets. 

It is available with keys `src:assets:test.txt` and `root:server:assets:test.txt`.

### Additional context

Perhaps it is more a bug related to Nitro than Nuxt, but upgrading to Nuxt 3 caused my project to fail due to undocumented changed behavior of server assets.

**Comment by manniL** [comment] 2023-01-27 22:49
@pi0 was that change intended? Also related: https://github.com/nuxt/nuxt/issues/18549

**Comment by mcrapts** [comment] 2023-01-28 08:41
After further investigation, the server assets don't end up in the production bundle at all. So using the different keys only works in development build and not in the production build.

**Comment by danielroe** [comment] 2023-01-28 22:48
For now, you can do this:

```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  nitro: {
    serverAssets: [
      {
        baseName: '',
        dir: 'assets',
      },
    ],
  },
});
```

https://stackblitz.com/edit/github-u78ses-2nplvr

**Comment by danielroe** [comment] 2023-01-31 14:34
This should be resolved in nitropack v2.1.1. which you can get by refreshing your lockfile or with `npm nuxt upgrade --force`.

Let me know if not and I'll reopen.

**Closed by danielroe** 2023-01-31 14:34 UTC
Labels: 3.x, workaround available, bug, upstream

**Comment by mcrapts** [comment] 2023-02-01 08:48
I had to use `npx nuxi upgrade --force`, but yes it works now. Thanks!

**Comment by maxdzin** [comment] 2023-05-11 20:33
Hi guys,

I have a similar problem and wondering if I did something wrong maybe.
The server assets are not available after building in production (in dev everything works perfectly).

I tried with next:

Nuxt v3.4.3

- Config:
```ts
  nitro: {
    serverAssets: [
      {
        baseName: '',
        dir: 'assets', // I tried different variations here
      },
    ],
  },
...
```

- Files:
`server\assets\templates\test.txt`

- Code:
```ts
const template = await useStorage().getItem('root:server:assets:templates:default.txt')
```

Tried with different settings (with or without specifying `serverAssets`), but cannot make it work yet on prod.

Reproduction is pretty simple. Can be used the one mentioned above (https://stackblitz.com/edit/github-u78ses-2nplvr) and make a build for prod.

**Comment by maxdzin** [comment] 2023-05-12 11:13
Hello!

I'm sorry if I disturbed you.

That issue was resolved: https://github.com/nuxt/nuxt/discussions/20790

I don't get it clearly while reading the Nitro documentation - it was some confusion about naming assets in the config and about how to use it then. So, maybe there's a need to make some clarifications in the docs.
