### ISSUE TITLE
Permission denied to /usr/home

### ISSUE THREAD

**Issue by Orygaw** [nuxt/nuxt#15700] opened 2022-12-06 17:13 UTC
### Environment

- Operating System: `FreeBSD`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.1-rc.0-27838776.d0c0cd7`
- Nitro Version:    `1.0.1-27838952.d04554a`
- Package Manager:  `npm@6.14.8`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. npx nuxi@latest init nuxt3-test-02
2. cd nuxt3-test-02
3. npm install
4. npm run build
### Describe the bug

After installing Nuxt3 I get an error where it shows trying to exit from my user's home directory. This is not allowed on my shared hosting. Why does Nuxt want to access /usr/home? I have access to my home directory /usr/home/USERNAME
Any ideas?

### Logs

```shell
[USERNAME@host.net]:<~/nuxt3-test-02>$ npm run build

> @ build /usr/home/USERNAME/nuxt3-test-02
> nuxt build

Nuxi 3.0.0                                                                                                                                                                                               18:36:56
Nuxt 3.0.0 with Nitro 1.0.0                                                                                                                                                                              18:36:56
ℹ Client built in 1873ms                                                                                                                                                                                 18:37:01
ℹ Building server...                                                                                                                                                                                     18:37:01
✔ Server built in 1065ms                                                                                                                                                                                 18:37:02
✔ Generated public .output/public                                                                                                                                                                  nitro 18:37:02
ℹ Building Nitro Server (preset: node-server)                                                                                                                                                      nitro 18:37:02

 ERROR                                                                                                                                                                                             nitro 18:37:03

undefined


 ERROR  EACCES: permission denied, readlink '/usr/home'                                                                                                                                                  18:37:03



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USERNAME/.npm/_logs/2022-12-06T17_37_03_647Z-debug.log

```

**Comment by michal-stachura** [comment] 2023-02-01 14:44
I have the same problem with `build`

**Comment by danielroe** [comment] 2023-02-01 22:59
> Are you by any chance able to point out which script file and code line is responsible for that behavior?

This is probably coming from https://github.com/unjs/pkg-types with `findWorkspaceDir`. It's looking for `.git/config` to identify your workspace root. But I can't replicate the issue even with a parent directory without permission to read.

**Comment by avkarenow** [comment] 2023-02-04 19:16
`Permission denied` comes from nitro/nitropack:
```
$ npx nitropack build
✔ Generated public .output/public                                                                                                                            nitro 19:46:34
ℹ Building Nitro Server (preset: node-server)                                                                                                                nitro 19:46:34

 ERROR  Error: EACCES: permission denied, readlink '/usr/home'                                                                                               nitro 19:46:35


undefined

[Error: EACCES: permission denied, readlink '/usr/home'] {
  errno: -13,
  code: 'PLUGIN_ERROR',
  syscall: 'readlink',
  path: '/usr/home',
  pluginCode: 'EACCES',
  plugin: 'node-externals',
  hook: 'buildEnd'
}
```

I couldn't find where exactly is the problem but commenting out `buildEnd` function in `node_modules/nitropack` allows to  run `nuxt build` without errors.
I hope that can help resolve this issue.

**Comment by danielroe** [comment] 2023-02-05 14:59
Thank you - that's good to know. Any chance you could provide a reproduction, please? 🙏 I'm a bit confused as to why you're running `npx nitropack build`, for example - which you shouldn't be calling in a nuxt project...

cc: @pi0

**Comment by avkarenow** [comment] 2023-02-05 19:13
@danielroe: `npx nitropack build` is a part of building process for `npx nuxt build`, but running it separatly produces a little more information.
I'm using FreeBSD system, you could try `chmod 711 /usr/home`.

I digged a little deeper today and the error is caused by:
```
      const _fileTrace = await nodeFileTrace(
        [...trackedExternals],
        opts.traceOptions
      );
```
from `nitropack/dist/shared/nitro.e7dc7fe5.mjs` (I guess this file is generated during instalation, I couldn't find it in repo)

`traceOptions` is defined here: https://github.com/unjs/nitro/blob/main/src/rollup/config.ts#L332

Changing `base` from `/` to `process.cwd()` helps but I don't see the option to do that without modifying the installed package. (`process.cwd()` is also the default value in `@vercel/nft` package from where `nodeFileTrace` function comes).

**Comment by danielroe** [comment] 2023-02-05 19:17
@avkarenow The reason you shouldn't call it directly is that Nuxt takes care of configuring nitro _for_ you, and you get none of that configuration if you call it yourself.

**Comment by danielroe** [comment] 2023-06-26 21:01
Closing the issue here to track upstream in nitro (and then perhaps further upstream in vercel/nft?).

**Closed by danielroe** 2023-06-26 21:01 UTC
Labels: 3.x, bug, upstream

**Comment by matmosci** [comment] 2025-06-19 12:57
```js
nitro: {
   externals: {
    traceOptions: { base: process.cwd() }
  }
}
```
adding this to ```nuxt.config.ts``` solved the problem in my case
thanks to [mydevil.net](https://www.mydevil.net/) admin who sorted it out 👌
