### ISSUE TITLE
A decorator parsing issue occurs.

### ISSUE THREAD

**Issue by Minseok0917** [nuxt/nuxt#25038] opened 2024-01-04 06:34 UTC
### Environment

I would like to use a decorator in a Frontend Client environment.

### Reproduction

```typescript
// components/user/user.class.ts
import { Expose, plainToInstance } from "class-transformer";

class IUserFactory {}

class User {
  @Expose({ name: "user_name" }) name!: string;
  @Expose({ name: "age" }) age!: number;
}

const users = [
  {
    user_name: "정민석",
    age: 21,
  },
  {
    user_name: "권규량",
    age: 21,
  },
  {
    user_name: "윤장혁",
    age: 21,
  },
];

export function init() {
  const a: User[] = plainToInstance(User, users);
  console.log(a);
}
```

### Describe the bug

[vite-node] [PARSE_ERROR] /components/user/user.class.ts

I used the decorator but it didn't work as it popped up in vite-node parser. The code above doesn't work.

**Comment by manniL** [comment] 2024-01-04 08:46
Duplicate of #14126

**Closed by manniL** 2024-01-04 08:46 UTC
Labels: 3.x, pending triage
