### ISSUE TITLE
Generated Source Map (TS)

### ISSUE THREAD

**Issue by tada5hi** [nuxt/nuxt#15523] opened 2022-11-17 17:48 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Create `.ts` files in the pages directory.

### Describe the bug

When running in dev mode, the cli prints warnings for missing source files for all typescript files:

```
WARN  Sourcemap for "xxx/pages/settings/index/security.ts" points to missing source files
```

**Comment by tada5hi** [comment] 2023-01-25 10:33
@pi0 any news on that ? Can we might just disable the warning.

**Comment by jakubhruby** [comment] 2023-02-17 07:42
Any update here?

**Comment by danielroe** [comment] 2023-02-17 07:49
I believe this is an upstream issue with vite + windows that is being addressed here: https://github.com/vitejs/vite/pull/12079

**Comment by jakubhruby** [comment] 2023-03-28 11:26
I have the latest version of vite@4.2.1 where the https://github.com/vitejs/vite/pull/12079 should be fixed according to https://github.com/vitejs/vite/blob/v4.2.1/packages/vite/CHANGELOG.md, but the warning messages in nuxt are still there.

**Comment by danielroe** [comment] 2023-03-28 11:49
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) in that case? 🙏

**Comment by jakubhruby** [comment] 2023-03-28 13:45
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) in that case? pray

https://codesandbox.io/p/sandbox/busy-dream-8xbxih?file=%2Fnuxt.config.js&selection=%5B%7B%22endColumn%22%3A14%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A14%2C%22startLineNumber%22%3A2%7D%5D
There is also an error with E_ACCESS in codesandbox output but it's IMHO related to this nuxt minimal reproduction stub only. 

It seems to me that the warning may could be related to that I don't use SFC (which I have chosen  due to several reasons)

**Comment by jakubhruby** [comment] 2023-04-26 04:28
Any update here?

**Comment by jakubhruby** [comment] 2023-05-26 07:42
any progress @danielroe ?

**Comment by manniL** [comment] 2023-12-25 23:46
Can't repro in non-windows env so far.

https://stackblitz.com/edit/nuxt-issues-15523?file=components%2FPage.ts,app.vue

**Comment by manniL** [comment] 2024-01-19 10:27
Yup, can't repro on windows either

**Closed by manniL** 2024-01-19 10:27 UTC
Labels: 3.x, vite, windows, upstream-bug

**Comment by jakubhruby** [comment] 2024-01-19 11:18
Confirm it's gone.

**Comment by rczdgbg** [comment] 2024-01-26 02:35
![image](https://github.com/nuxt/nuxt/assets/38928451/0ce85700-71c0-4933-8613-85951e38aee2)

**Comment by danielroe** [comment] 2024-01-26 12:56
@rczdgbg Perhaps you could provide a reproduction? 🙏
