### ISSUE TITLE
Latest nuxt version delays the load of CSS on SSR

### ISSUE THREAD

**Issue by popescuandrei9mai** [nuxt/nuxt#27148] opened 2024-05-10 10:06 UTC
### Environment

- Node Version:     v20.9.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/magical-joji-ynhtsr

### Describe the bug

While the server is running in preview mode, if you set your network to slow 3G, you can see that the CSS for the 4 simple components defined and used on homepage is loaded after the whole page is loaded. The CSS missing is only the one defined in components. This is a minimal reproduction but on a full size project, with a lot of components, loading them all first without CSS is a dealbreaker

### Additional context

https://github.com/nuxt/nuxt/assets/52782918/b674e625-d97c-4de8-a79f-da7b58a38fdc

_No response_

**Comment by popescuandrei9mai** [comment] 2024-05-10 10:13
https://github.com/nuxt/nuxt/assets/52782918/9212df86-fe40-4baf-add5-b541a7efb043

**Comment by manniL** [comment] 2024-05-10 12:10
Can you double check with the nightly channel by any chance?

**Comment by popescuandrei9mai** [comment] 2024-05-10 12:28
> Can you double check with the nightly channel by any chance?

Tried the nightly channel on my local machine and it indeed fixes the problem. This means that the next nuxt release will fix this problem?

**Comment by manniL** [comment] 2024-05-10 12:31
Yes, correct!

Closing as duplicate of https://github.com/nuxt/nuxt/issues/26514

**Closed by manniL** 2024-05-10 12:31 UTC
Labels: 3.x, pending triage
