### ISSUE TITLE
missing css stylesheets in production build

### ISSUE THREAD

**Issue by stefanprobst** [nuxt/nuxt#21840] opened 2023-06-28 14:37 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      css, devtools, experimental, modules, postcss
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -

### Reproduction

repo: https://github.com/stefanprobst/issue-nuxt-missing-css

follow the steps in https://github.com/stefanprobst/issue-nuxt-missing-css/blob/main/readme.md

the readme also mentions 3 workarounds
- setting `experimental: { inlineSSRStyles: false }` in `nuxt.config.ts`
- deleting `i18n.config.ts` (may be related to https://github.com/nuxt-modules/i18n/issues/2177)
- downgrading to v3.5.3

### Describe the bug

css stylesheets are not included in a production build.

**Comment by Hebilicious** [comment] 2023-06-29 11:38
Looks like a regression that got introduced when we introduced https://github.com/nuxt/nuxt/pull/21573 and https://github.com/nuxt/nuxt/pull/21763

Maybe we could look into setting up something similar to ecosystem-ci, but for visual regression testing ?
 
It's usually a commercial service (percy, applitools etc), however I did some research and found some OSS tools that would allow us to do that without costs : 

- https://github.com/reg-viz/reg-suit
- https://github.com/jaredpalmer/cypress-image-snapshot
- https://github.com/wildlyinaccurate/whoopsie
- https://github.com/garris/BackstopJS
- https://github.com/lost-pixel/lost-pixel

Lost Pixel looks very promising and OSS friendly, with a straightforward github action and a saas product that is free for OSS projects according to their (homepage)[https://lost-pixel.com/].

This might be a little overkill to run on every PR, but being sure that nothing unintentionally breaks between releases would be worth it imo.

**Comment by Hebilicious** [comment] 2023-06-29 12:05
This could also be the same bug as https://github.com/nuxt/nuxt/issues/21821

**Comment by danielroe** [comment] 2023-06-29 12:12
We already have a range of CSS testing within the Nuxt test suite and I'm also very happy for PRs to add new downstream repos with good test suites (which could include their own regression tests) to it.

Let's see what the issue is here. The thing that's a bit odd is that this is triggered by the presence of the i18n module, which suggests it's might not be a Nuxt core bug.

**Comment by terwer** [comment] 2023-06-30 02:02
Same issue, 3.5 is perfect, When i upgrade to 3.6.1 css disappears only in prod.

I defined css like this 

https://github.com/terwer/siyuan-plugin-blog/blob/487fbf5bece5d8bab94f5e90c28d4170a59589c5/nuxt.vercel.config.ts#L61

**Comment by terwer** [comment] 2023-06-30 02:14
finally， I use

```json
  experimental: {
    inlineSSRStyles: false,
  },
```

in `nuxt.config.ts` to fix.Thanks to https://github.com/stefanprobst/issue-nuxt-missing-css#workaround-2

**Comment by danielroe** [comment] 2023-06-30 04:26
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Closed** 2023-06-30 04:25 UTC
Labels: 3.x, workaround available, bug, 🔨 p3-minor-bug
