### ISSUE TITLE
Slot position gets shifted when using the out-in page transition

### ISSUE THREAD

**Issue by aditya1906** [nuxt/nuxt#25739] opened 2024-02-11 08:00 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, ssr, app, css
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-njpvcp

### Describe the bug

The following is a very common application layout(also shown in layouts/default.vue in the reproduction link):
```
<Header />
<slot /> <!-- References to the page -->
<Footer />
```
When we use 'out-in' mode in pageTransition in nuxt.config.ts:
```
pageTransition: { name: 'page', mode: 'out-in' }
```
And we **CLICK ON THE LINK** . This is what's rendered in the DOM.
```
<Header />
<Footer />
<slot /> <!-- References to the page -->
```
Also when we use the following layout:
```
<Header />
<div>
    <slot /> <!-- References to the page -->
    <p>More Content</p>
</div>
<Footer />
```
This is the result in the DOM, after the link is clicked:
```
<Header />
<div>
    <p>More Content</p>
    <slot /> <!-- References to the page -->
</div>
<Footer />
```
Nuxt v3 it seems that append the slot at the end of the parent element. Which seems a bug to me. Looks like there needs to be a handling in appending the slot in the correct order.

**Comment by manniL** [comment] 2024-02-11 09:36
Duplicate of https://github.com/nuxt/nuxt/issues/24632

**Closed by manniL** 2024-02-11 09:36 UTC
Labels: 3.x, pending triage
