### ISSUE TITLE
Styles defined in layout omitted from the server-rendered HTML, when Client- and Lazy component use the same package in their code

### ISSUE THREAD

**Issue by FreekVR** [nuxt/nuxt#22507] opened 2023-08-06 17:36 UTC
### Environment

```
[1:52:12 PM] Nuxi 3.6.5
[1:52:12 PM] 
[1:52:12 PM] RootDir: /home/freek/projects/the-july-frontend
[1:52:12 PM] Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.9
- Builder:          vite
- User Config:      extends, telemetry, ssr, fontMetrics, nitro, routeRules, runtimeConfig, build, modules, image, components, bugsnag, devtools, i18n, pwa, app, dnGraphqlClient, vite, plugins
- Runtime Modules:  @nuxtjs/fontaine@0.4.1, @pinia/nuxt@0.4.11, @nuxt/devtools@0.7.2, @vite-pwa/nuxt@0.1.0, nuxt-bugsnag@6.5.2, @digitalnatives/css-variables/nuxt@5.1.2, @digitalnatives/graphql-client@4.0.0, @nuxtjs/i18n@8.0.0-rc.1, @nuxt/image@1.0.0-rc.1
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-tqq5me?file=app.vue,layouts%2Fdefault.vue,pages%2Findex.vue,nuxt.config.ts,package.json

(run npm build, npm preview, then open the preview in a new window with JS disabled)

### Describe the bug

When a client-only component is defined within a layout somewhere (it can be nested) it seems to be removing all the CSS styles from any components defined in the layout (page-level components eg. within `NuxtPage` are fine!) in a very specific use case;

I had a LOT of trouble reproducing this issue, but it seems to only occur if a Lazy component is included within a Client component, and both of those are using the same npm library (in the repro - date-fns).

This is only observed in the server-rendered version of the page. Eg. we're getting a short burst of some unstyled layout-level components like the menu, then their CSS is only added upon hydration -- even though these are not client-only components! Their templates are rendered but their CSS is not added to the `<head>`

This further only seems to occur in the optimized production build -- not on `nuxt dev`, only on `build && preview`

No errors are shown, and hydration works fine, just the CSS is not being rendered in the HTML before hydration for some reason.

**Comment by manniL** [comment] 2023-08-17 13:09
I can't reproduce the issue in your StackBlitz. When running `npm run build && node .output/server/index.mjs` there, the correct style is shown on server-side (inlined).

<img width="646" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/31d7be72-ebd4-4ca2-97e1-57514c9effde">

**Comment by FreekVR** [comment] 2023-08-18 14:53
Sorry, I accidentally linked a wrong reproduction, I later decided to move it to CodeSandbox but linked the older StackBlitz one.

The issue should be reproducable here;
https://codesandbox.io/p/sandbox/elastic-paper-dxmfc5?file=/components/MyClientComponent.client.vue:1,1

1. Kill the default `yarn dev`
2. Run `yarn run build && yarn run preview`
3. Open the preview window in a new tab, and use devtools or some other method to disable JS

^This should make the issue reproducable, but let me know if more info is still needed :)

**Comment by SebbeJohansson** [comment] 2023-10-06 15:23
Hi! Instead of creating a new issue, I'm gonna take a gamble and assume that my issue is the same even tho the parameters are not exactly the same. They are similar enough I think!

We have noticed in our big e-commerce application that we are migrating to nuxt3 that when built, unstyled content flashes for a second before the actual styling is shown. The culprit to this stems from using a component in both a lazy-loaded component and a non-lazy-loaded component.

I have created a minimal reproduction version of this issue where I have recreated our setup to the best of my ability, without adding unnecessary stuff to make it easier to analyze. Here is the stackblitz: https://stackblitz.com/edit/nuxt-starter-rhcahb

When loading the app with two instances of the component we get this:
![image](https://github.com/nuxt/nuxt/assets/5083273/209f2e42-3c4b-41e3-9302-702d1dd4604b)
Before the lazy loaded component is rendered the styling is completely missing and only starts showing correctly when both instances are fully loaded and rendered.
When loading only with the instance that is NOT lazy loaded:
![image](https://github.com/nuxt/nuxt/assets/5083273/267d78c3-77ce-4918-8463-e83f05561a7a)

In the big app, it is obviously a lot more noticeable. In the reproduction you have to do a recording in chrome and it also helps to use slow 3G. Here is an example run from the big app.
![image](https://github.com/nuxt/nuxt/assets/5083273/7a413285-6b4d-44c3-b84c-28592c884ad4)
Sadly cant share much code from the big one!

The issue is happening with a very specific case where we need two layers of lazyloading it seems. If i remove it in `[...slug].vue` (or switch from `defineAsyncComponent`) or if i remove it from `compontents/pages/Default.vue` it seems to stop.

Sadly for a few different reasons the setup and the way the components are located is a requirement for our app that would require a much bigger rewrite than we are currently ready to do.

@danielroe let me know if this example is completely irrelevant or if it is more suited for a new stand alone issue.

**Comment by SebbeJohansson** [comment] 2023-10-09 09:03
Would it be possible to increase the priority on this somehow? This is currently fully stopping us from releasing our upgrade since we require the smaller bundle size before releasing.

**Comment by danielroe** [comment] 2023-10-11 14:00
Would you try with `experimental.inlineSSRStyles` turned off? 🙏

**Comment by FreekVR** [comment] 2023-10-11 14:12
Updated my repro with this change as well, after updating to the latest version, and still does not work for me either.

Updated reproduction: https://codesandbox.io/p/sandbox/morning-silence-vjkv29?file=%2Fnuxt.config.ts%3A6%2C1-8%2C5

(works in dev, make sure to run with build & preview comds)

**Comment by SebbeJohansson** [comment] 2023-10-11 14:23
I have also updated my repro with the change and it didnt help their either :(

**Comment by danielroe** [comment] 2023-10-11 14:37
Investigating this, the reason is the same for both of your situations. Layouts are dynamic imports so, just like a lazy-loaded component, their CSS can be included in a separate chunk rather than directly.

This behaviour isn't directly produced by Nuxt, but by Vite, which in the cases you've shown, such as when an auto-import is shared between a lazy component and the rest of the app, moves the CSS file out of the entrypoint CSS in the manifest it produces and into a dynamic chunk.

The result is that the stylesheet is not included in the initially rendered HTML.

As a workaround, you might try adding some code to force-include it, such as adding the below in your `app.vue`:

```vue
// ... rest of SFC

<script setup>
import './layouts/default.vue'
</script>
```

**Comment by SebbeJohansson** [comment] 2023-10-16 07:37
@danielroe Maybe I'm missing something (as always), but is that workaround really applicable for me when the styling is coming from the components and not from the layout? In my repro example the layout is completely empty except for the template with a slot.

**Comment by danielroe** [comment] 2023-10-16 08:30
@SebbeJohansson The workaround is to add that import to the `app.vue`, not to your components.

**Comment by SebbeJohansson** [comment] 2023-10-16 14:37
@danielroe I dont have an `app.vue` but i removed it for each of them except for the page slug component, but it didn't help either.
![image](https://github.com/nuxt/nuxt/assets/5083273/8082f159-80d0-4332-a042-fe6a8b5ea583)

So I still dont think that work around is applicable for me. Feel free to make a fork of my repro and let me know what works!

**Comment by engenes** [comment] 2023-10-29 08:35
@danielroe 
> Would you try with `experimental.inlineSSRStyles` turned off? 🙏
I have the same problem. Disabling inlineSSRStyles helped me. 

Please tell me, how to disable inlineSSRStyles only for some components. I would be grateful, if you could write a small example

**Comment by danielroe** [comment] 2024-01-28 21:27
resolved in https://github.com/nuxt/nuxt/pull/25455

**Closed by danielroe** 2024-01-28 21:27 UTC
Labels: 3.x, workaround available, bug, vite, 🔨 p3-minor-bug, inline styles
