### ISSUE TITLE
Error: [worker reload] Cannot read properties of null (reading 'address')

### ISSUE THREAD

**Issue by VladimirCores** [nuxt/nuxt#24423] opened 2023-11-23 06:41 UTC
### Environment

Operating System: Linux
Node Version: v18.15.0
Nuxt Version: 3.8.2
CLI Version: 3.10.0
Nitro Version: 2.8.0
Package Manager: yarn@1.22.19
Builder: -
User Config: devtools, ssr, telemetry, app, runtimeConfig, tailwindcss, nitro, imports, ui, eslint, modules, googleFonts, fontMetrics, colorMode
Runtime Modules: @nuxtjs/fontaine@0.4.1, @nuxtjs/google-fonts@3.0.2, @nuxtjs/eslint-module@4.1.0, @nuxt/ui@2.10.0
Build Modules: -

### Reproduction

1. Mounting local storage breaks Nuxt build

export default defineNitroPlugin(() => {
  // Mount driver
  useStorage().mount('local', fs({ base: './.data' }));
});

2. yarn dev

### Describe the bug

Nuxt wont start.

### Logs

```shell-script
ERROR [worker reload] Cannot read properties of null (reading 'address') 3:16:48 PM

at _reload (node_modules/nitropack/dist/shared/nitro.37241ef0.mjs:282:38)
at runNextTicks (node:internal/process/task_queues:60:5)
at process.processTimers (node:internal/timers:509:9)
at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10)
```

**Comment by pi0** [comment] 2023-11-23 10:21
When build fails or there is critical init error, Nitro seems has a regression and not showing proper error (https://github.com/unjs/nitro/issues/1947)

--- 

BTW for your specific issue @VladimirCores i would appreciate a runnable reproduction. Normally you should also configure storage using `nitro.storage` in `nuxt.config` rather than a nitro plugin + `data` is already mounted by nitro using `fs-lite` driver ([more](https://unjs.io/blog/2023-08-25-nitro-2-6?utm_source=unjs.io&utm_medium=home-hero#default-persistent-data-storage)).

**Comment by SveinnB** [comment] 2023-11-23 11:02
![image](https://github.com/nuxt/nuxt/assets/28686321/31305935-91e6-4376-bcdf-28a4b03b63fd)
I am also having the same error. Come with nuxt 3.8.2.
But this does not stop nuxt to start and the app works great

**Comment by zola33dsf** [comment] 2023-11-23 11:04
Hi guys 🙂 
I also have the same problem, 
I've made a plugin which is looking to **localStorage** and in my nuxt.config.ts I have the key **ssr : false**

You can find a quick reproduction :  
 https://stackblitz.com/edit/github-wfqgfw?file=plugins%2FinitApp.ts

If you can't reproduce run the commands : npx nuxi cleanup and npm run dev

**Comment by pi0** [comment] 2023-11-23 11:24
This issue will be resolved in the next patch version of nitro. In the meantime, you can safely ignore it.

**Comment by FranciscoKloganB** [comment] 2023-11-26 11:35
_I do not know if this can be safely ignored_.

My project starts up with this error and no others. Accessing the app on the browser results on a continous loop of 503. I hadn't touched this project in two months. But the only thing that changed between the before and the now was going from Nuxt 3.7.1 to Nuxt 3.8.2; I already did a clean install of the `node_modules`.

**Comment by mathieunicolas** [comment] 2023-11-28 02:07
Same error here, but when ` npm run dev`  the page stays blank. I can see this in the console : 

![image](https://github.com/nuxt/nuxt/assets/65437872/c5c6f43d-dcbf-4573-9637-7773b0fce2da)

**Closed** 2024-06-16 21:50 UTC
Labels: 3.x, pending triage, nitro, upstream
