### ISSUE TITLE
Generic was not found in vue component

### ISSUE THREAD

**Issue by aspitrine** [nuxt/nuxt#24233] opened 2023-11-10 10:36 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.0`
- Nuxt Version:     `3.8.1`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `pnpm@8.10.2`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/p/sandbox/dazzling-bush-jmznfc?file=%2Fcomponents%2Fgeneric.vue%3A5%2C19

The reproduction not showed directly the error but copy / paste in a vscode and the error pop out.

### Describe the bug

We can't use generic in vue component.

<img width="1562" alt="Screenshot 2023-11-10 at 11 35 59" src="https://github.com/nuxt/nuxt/assets/3731837/238fffe7-b129-441e-bed9-3c412c23f60c">

**Comment by warflash** [comment] 2023-11-10 20:57
This sounds like an issue on your end with your vscode config for example. Did you make sure volar is up to date? If it is - can you check whether it's also happening with a plain vue project?

**Comment by warflash** [comment] 2023-11-13 12:49
Closing this as I can't reproduce and it sounds like an IDE config issue. Feel free to leave a comment with instructions to reproduce and we can reopen 👍

**Closed by warflash** 2023-11-13 12:49 UTC
Labels: 3.x, pending triage
