### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by frama21** [nuxt/nuxt#22780] opened 2023-08-24 03:24 UTC
### Environment

- Operating System: Linux
- Node Version:     v16.20.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      ssr, spaLoadingTemplate, app, css, modules, gtag, googleFonts
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/google-fonts@3.0.2, nuxt-gtag@0.5.7, @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

1. I Install the google-auth-library in nuxtjs 3 with vite
2. then i make the separate helper call spreadsheet.ts for calling the method when i need it
3. this my inside spreadsheet.ts
![code](https://github.com/nuxt/nuxt/assets/22318828/b3b2ce5c-7734-478a-9d87-c7bd276461d9)
4. then i import spreadsheet.ts in another file to hit the method & i got the error like this
![image](https://github.com/nuxt/nuxt/assets/22318828/6a0f86ce-c2cb-4631-8cca-99f04349c327)
and also on error preview in browser
```bash
at node_modules/.pnpm/agent-base@7.1.0/node_modules/agent-base/dist/index.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:4899:36)
at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
at node_modules/.pnpm/https-proxy-agent@7.0.1/node_modules/https-proxy-agent/dist/index.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:5104:24)
at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
at node_modules/.pnpm/gaxios@6.1.0/node_modules/gaxios/build/src/gaxios.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:5223:31)
at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
at node_modules/.pnpm/gaxios@6.1.0/node_modules/gaxios/build/src/index.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:5521:20)
at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
at node_modules/.pnpm/gcp-metadata@6.0.0/node_modules/gcp-metadata/build/src/index.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:7525:20)
at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
```

this the link [https://stackblitz.com/edit/github-mxmr67?file=pages%2Findex.vue](https://stackblitz.com/edit/github-mxmr67?file=pages%2Findex.vue)

### Describe the bug

its error from the bundler or error from vite or maybe the package ?, if the error is from vite can you give me a suggest about the vite config ? to solve this

i try to fix from this [issue](https://github.com/vitejs/vite/issues/9703) but still not fix

also i report this to google-auth-library for making sure [1632](https://github.com/googleapis/google-auth-library-nodejs/issues/1632)

**Comment by frama21** [comment] 2023-08-25 02:28
this my stackblitz [reproduction](https://stackblitz.com/edit/github-mxmr67?file=pages%2Findex.vue)

**Comment by frama21** [comment] 2023-09-11 07:06
any idea for this issue ? or maybe the suggest ?

**Comment by satezmedia** [comment] 2023-09-13 16:13
Same issue for me

**Comment by frama21** [comment] 2023-09-19 05:42
@danielroe

**Comment by frama21** [comment] 2023-11-12 11:03
any update for this issue ? @danielroe

**Comment by tungpt244** [comment] 2023-11-13 07:52
I have catched a similar situation and tried searching, but it seems there hasn't been any update on this issue. It appears that the google-auth-library is not compatible with the client, and with Nuxt 3, it works on the server. Therefore, you can handle it in plugins with server customization or create an API in the server folder and use it.

Hope this helps someone experiencing this issue.

**Comment by danielroe** [comment] 2023-11-14 10:04
Thanks for updating. I think we should probably close this here then.

**Closed by danielroe** 2023-11-14 10:04 UTC
Labels: 3.x, pending triage, upstream

**Comment by Atulkumar112** [comment] 2024-01-18 07:09
> ### Environment
> * Operating System: Linux
> * Node Version:     v16.20.1
> * Nuxt Version:     3.6.5
> * Nitro Version:    2.5.2
> * Package Manager:  pnpm@8.6.12
> * Builder:          vite
> * User Config:      ssr, spaLoadingTemplate, app, css, modules, gtag, googleFonts
> * Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/google-fonts@3.0.2, nuxt-gtag@0.5.7, @pinia/nuxt@0.4.11
> * Build Modules:    -
> 
> ### Reproduction
> 1. I Install the google-auth-library in nuxtjs 3 with vite
> 2. then i make the separate helper call spreadsheet.ts for calling the method when i need it
> 3. this my inside spreadsheet.ts
>    ![code](https://private-user-images.githubusercontent.com/22318828/262850597-b3b2ce5c-7734-478a-9d87-c7bd276461d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjE2NzksIm5iZiI6MTcwNTU2MTM3OSwicGF0aCI6Ii8yMjMxODgyOC8yNjI4NTA1OTctYjNiMmNlNWMtNzczNC00NzhhLTlkODctYzdiZDI3NjQ2MWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA3MDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNzQwMGE4OTNkZTEzNjBhYTllNjgwMDgxMjA2ZGM1N2ExMjk1ZGZkNTBmNDJjMjg3NDgzNGE3OTJhNDAyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gL5zcerx0On7i2UeV5HCXvhbTP-_Lm7uahsy8YslqqU)
> 4. then i import spreadsheet.ts in another file to hit the method & i got the error like this
>    ![image](https://private-user-images.githubusercontent.com/22318828/262850826-6a0f86ce-c2cb-4631-8cca-99f04349c327.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjE2NzksIm5iZiI6MTcwNTU2MTM3OSwicGF0aCI6Ii8yMjMxODgyOC8yNjI4NTA4MjYtNmEwZjg2Y2UtYzJjYi00NjMxLThjY2EtOTlmMDQzNDljMzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA3MDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNzBkOTlhNTk2YTVjNmNmN2FkOWJhYzkzZTdmNjU4ZWM1MzQ4M2U1Mjg3OGNiY2JhNTg2ZDlhMzliYTJlYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KShxpGTfzxJuK0NrT2q-_hP8yb3ppaCjmy5PWON7RIE)
>    and also on error preview in browser
> 
> ```shell
> at node_modules/.pnpm/agent-base@7.1.0/node_modules/agent-base/dist/index.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:4899:36)
> at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
> at node_modules/.pnpm/https-proxy-agent@7.0.1/node_modules/https-proxy-agent/dist/index.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:5104:24)
> at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
> at node_modules/.pnpm/gaxios@6.1.0/node_modules/gaxios/build/src/gaxios.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:5223:31)
> at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
> at node_modules/.pnpm/gaxios@6.1.0/node_modules/gaxios/build/src/index.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:5521:20)
> at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
> at node_modules/.pnpm/gcp-metadata@6.0.0/node_modules/gcp-metadata/build/src/index.js (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/google-auth-library.js?v=6e413f2f:7525:20)
> at __require (http://localhost:3000/_sastrala-member/node_modules/.cache/vite/client/deps/chunk-DFKQJ226.js?v=35cede96:8:50)
> ```
> 
> this the link https://stackblitz.com/edit/github-mxmr67?file=pages%2Findex.vue
> 
> ### Describe the bug
> its error from the bundler or error from vite or maybe the package ?, if the error is from vite can you give me a suggest about the vite config ? to solve this
> 
> i try to fix from this [issue](https://github.com/vitejs/vite/issues/9703) but still not fix
> 
> also i report this to google-auth-library for making sure [1632](https://github.com/googleapis/google-auth-library-nodejs/issues/1632)

i am also getting same error in nuxt, when i am getting data from my composables to my components.

**Comment by Mateusr337** [comment] 2024-03-09 02:50
Eu estou com mesmo problema quando tentei usar, intalei a blibloteca "google-auth-library" e "google-spreadsheet" e coloquei os dados e quando o app inicializa exibe essa mensagem:

google-auth-library.js?v=629557de:1157 Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null

Meu codigo:

```
import google from "@/constants/google.json";
import { JWT } from "google-auth-library";
import { GoogleSpreadsheet } from "google-spreadsheet";

    try {
      const serviceAccountAuth = new JWT({
        email: google.client_email,
        key: google.private_key,
        scopes: [
          "https://www.googleapis.com/auth/spreadsheets",
        ],
      });
    } catch (error) {
      console.log("Error ------------------");
      console.log(error);
    }

    const doc = new GoogleSpreadsheet("<the sheet ID from the url>", serviceAccountAuth);
```

**Comment by giantpenguin** [comment] 2024-10-29 06:46
> I have catched a similar situation and tried searching, but it seems there hasn't been any update on this issue. It appears that the google-auth-library is not compatible with the client, and with Nuxt 3, it works on the server. Therefore, you can handle it in plugins with server customization or create an API in the server folder and use it.
> 
> Hope this helps someone experiencing this issue.

Could you please provide more details regarding your mention?

**Comment by giantpenguin** [comment] 2024-10-29 06:59
Is it the issue caused by the (google-auth-library) library still uses the require while others (e.g., @googleapis/sheets v4 or a vuejs component) depend on it have been changed to use the import for modules loading?

Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null
    at node_modules/google-auth-library/build/src/auth/authclient.js (authclient.js:31:35)
    at __require (chunk-WMTNK64S.js?v=40045171:15:50)
    at node_modules/google-auth-library/build/src/auth/oauth2client.js (oauth2client.js:22:22)
    at __require (chunk-WMTNK64S.js?v=40045171:15:50)
    at node_modules/google-auth-library/build/src/auth/computeclient.js (computeclient.js:19:24)
    at __require (chunk-WMTNK64S.js?v=40045171:15:50)
    at node_modules/google-auth-library/build/src/auth/googleauth.js (googleauth.js:36:25)
    at __require (chunk-WMTNK64S.js?v=40045171:15:50)
    at node_modules/google-auth-library/build/src/index.js (index.js:17:22)
    at __require (chunk-WMTNK64S.js?v=40045171:15:50)
