### ISSUE TITLE
`$fetch` proxy agent does not work in api endpoint

### ISSUE THREAD

**Issue by 289997171** [nuxt/nuxt#24799] opened 2023-12-17 13:19 UTC
### Environment

node: v20.9.0
nuxt: ^3.8.2

### Reproduction

server\api\test\google.get.ts

```javascript
import {HttpsProxyAgent} from "https-proxy-agent";
import {$fetch, ofetch} from "ofetch";
const agent = new HttpsProxyAgent('http://127.0.0.1:7890')

export default defineEventHandler(async (event) => {
    // const res = await ofetch('https://www.google.com', {
    //     agent: agent
    // })
    const res = await $fetch('https://www.google.com', {
        agent: agent
    })
    console.log(res);
    return res
})
```

### Describe the bug

curl test request

```cmd
curl http://localhost:3000/api/test/google

{"url":"/api/test/google","statusCode":500,"statusMessage":"","message":"[GET] \"https://www.google.com\": <no response> fetch failed","stack":"<pre><span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at async $fetchRaw2 (/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:228:14)</span>\n<span class=\"stack internal\">at async $fetch2 (/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)</span>\n<span class=\"stack\">at <anonymous> (\\server\\api\\test\\google.get.ts:9:1)</span>\n<span class=\"stack internal\">at async Object.handler (/node_modules/h3/dist/index.mjs:1675:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (/node_modules/h3/dist/index.mjs:1885:7)</span></pre>"}
C:\Users\Administrator>
```

I'm use 'Clash for windows', I have tested with java http proxy, and it work fine. but i dont know why it not work with ofetch or $fetch.

**Comment by 289997171** [comment] 2023-12-17 15:18
a node project
```javascript
import fetch from 'node-fetch';
import { HttpsProxyAgent } from 'https-proxy-agent';

(async () => {
    const targetUrl = 'https://ident.me/ip';
    {
        const response = await fetch(targetUrl);
        const text = await response.text();
        console.log(text);
    }
    {
        const response = await fetch(targetUrl, {
            agent: new HttpsProxyAgent('http://127.0.0.1:7890')
        });
        const text = await response.text();
        console.log(text);
    }
})();
```
result:
113.248.xxx.xxx
5.252.198.49
two ips are not the same

but if use nuxt
server\api\test\google.get.ts
```javascript
import {HttpsProxyAgent} from "https-proxy-agent";
import {$fetch, ofetch} from "ofetch";
import fetch from 'node-fetch'

export default defineEventHandler(async (event) => {
    const ip1 = await $fetch('https://ident.me/ip');
    console.log(ip1);

    const ip2 = await $fetch('https://ident.me/ip', {
        agent: new HttpsProxyAgent('http://127.0.0.1:7890')
    })
    console.log(ip2);

    const ip3 = await ofetch('https://ident.me/ip', {
        agent: new HttpsProxyAgent('http://127.0.0.1:7890')
    })
    console.log(ip3);

    const response = await fetch('https://ident.me/ip', {
        agent: new HttpsProxyAgent('http://127.0.0.1:7890')
    })
    const ip4 = await response.text();
    console.log(ip4);

    return {
        ip1,
        ip2,
        ip3,
        ip4
    }
})
```
{
    "ip1": "113.248.xxx.xxx",
    "ip2": "113.248.xxx.xxx",
    "ip3": "113.248.xxx.xxx",
    "ip4": "113.248.xxx.xxx"
}
the ips are the same, http proxy it's not work

**Comment by GalacticHypernova** [comment] 2023-12-17 19:06
Have you tried `routeRules`? They allow [proxying requests](https://nitro.unjs.io/config#routerules)

**Comment by manniL** [comment] 2023-12-20 10:15
I'd suggest using h3's [`proxyRequest`](https://www.jsdocs.io/package/h3#proxyRequest) instead if you need to make the call in your Nitro endpoint.

**Comment by manniL** [comment] 2023-12-20 10:29
Does that also happen when using https://github.com/unjs/ofetch in a simple node script?

**Comment by danielroe** [comment] 2024-02-13 10:06
Closing as this seems to be a possible upstream issue with `ofetch` rather than Nuxt.

Would you see if you can reproduce it - and if so raise it directly at https://github.com/unjs/ofetch? 🙏

**Closed by danielroe** 2024-02-13 10:06 UTC
Labels: 3.x, pending triage, upstream, needs reproduction

**Comment by blowsie** [comment] 2024-04-24 17:19
I created a PR for this topic over here 
https://github.com/unjs/ofetch/pull/389
https://github.com/unjs/ofetch/issues/379
