### ISSUE TITLE
Why it show json data and spa page when I refresh nuxt generate page

### ISSUE THREAD

**Issue by mouyong** [nuxt/nuxt#27517] opened 2024-06-11 05:42 UTC
### Environment

Working directory: /Users/example/Code/ssl-pc                                                                                 1:38:37 PM
Nuxt project info: (copied to clipboard)                                                                                              1:38:37 PM

------------------------------
- Operating System: Darwin
- Node Version:     v18.19.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  pnpm@8.14.0
- Builder:          -
- User Config:      devtools, runtimeConfig, alias, app, css, postcss, modules, i18n
- Runtime Modules:  nuxt-bootstrap-icons@2.0.0, @nuxtjs/i18n@8.3.0
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                           1:38:37 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

npm notice 
npm notice New minor version of npm available! 10.2.4 -> 10.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
npm notice Run npm install -g npm@10.8.1 to update!
npm notice 

### Reproduction

install fehepler, and visit in https://ssl.plugins-world.cn/dashboard

I doesn't want uninstall fehelper because it a tools for front develop.

### Describe the bug

When I install fehelper and generate project, use nginx to provider web static service. some times can see json data and spa page data. doesn't know reason.

<img width="1709" alt="image" src="https://github.com/nuxt/nuxt/assets/10336437/711ddb31-e7c4-4039-98dd-3b3d28fee9ec">

**Comment by mouyong** [comment] 2024-06-11 05:47
<img width="1508" alt="image" src="https://github.com/nuxt/nuxt/assets/10336437/4a25457e-cc4f-4851-8657-40c7ad429fc5">

When close this option, it will normal, but I doesn't want close the option. it very helpful.

**Comment by manniL** [comment] 2024-06-11 06:51
Duplicate of https://github.com/nuxt/nuxt/issues/24999

**Closed by manniL** 2024-06-11 06:51 UTC
Labels: 3.x, pending triage
