### ISSUE TITLE
Styles Delayed on Page Refresh with UnoCSS in Nuxt 3.9.2

### ISSUE THREAD

**Issue by huangyan321** [nuxt/nuxt#25252] opened 2024-01-17 09:42 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, unocss
- Runtime Modules:  @unocss/nuxt@0.58.3
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zoukhz?file=package.json

### Describe the bug

I am experiencing an issue with UnoCSS in a Nuxt 3.9.2 project where styles are not immediately applied upon page refresh during the development phase. Interestingly, this issue does not occur in Nuxt 3.9.1.

**Comment by oripka** [comment] 2024-01-17 10:01
I have the same issue using Nuxt UI.

**Comment by manniL** [comment] 2024-01-17 10:02
Duplicate of https://github.com/nuxt/nuxt/issues/25240

**Closed by manniL** 2024-01-17 10:02 UTC
Labels: 3.x, pending triage
