### ISSUE TITLE
How to copy file to folder .output after build

### ISSUE THREAD

**Issue by vanminhquangtri** [nuxt/nuxt#26623] opened 2024-04-03 11:24 UTC
Hello,

My app play some video content file .mp4, some of them is larger than 2GB so If I put these file inside folder public, the build will error file larger than 2GB.
But if remove these file, run yarn build, than copy to folder .output/public, it will error 404.
There some comments that nuxt only serve static file that is included before building. But I wonder if there is any workaround to make this work?

P/S: for some reason, I am not allowed to make another server to store these mp4 files. These files must be in folder of my app.

Version:
Nuxt: 3.10.3
Nodejs: 20.12.0
OS: Window 11, 64bit

Thanks you.

**Comment by manniL** [comment] 2024-04-03 11:46
Duplicate of https://github.com/nuxt/nuxt/issues/25926 and similar. There are various options, including server assets. But for the case of the videos, a separate CDN or S3 bucket would make more sense IMO.

**Closed by manniL** 2024-04-03 11:46 UTC
