### ISSUE TITLE
routeRules invalid regex

### ISSUE THREAD

**Issue by damianglazer** [nuxt/nuxt#24107] opened 2023-11-03 14:43 UTC
### Environment

- Operating System: Darwin
- Node Version:     v18.13.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, routeRules
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-sqjmpx?file=nuxt.config.ts

### Describe the bug

The rule for page with `/c/**` also applies to page with `/cart`. This can be seen in the `Cache-Control` header. After changing the routing from `/c` to another letter, everything works fine.

**Comment by danielroe** [comment] 2023-11-03 14:44
This is likely an upstream issue in nitro or radix3. Would you check if you can reproduce without Nuxt and if so, raise there? 🙏 

https://github.com/unjs/nitro
https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world

**Comment by pi0** [comment] 2023-11-03 17:51
thanks for reporting. i've self assigned to asset if there is an upstream issue.

**Comment by damianglazer** [comment] 2023-11-04 18:05
Without Nuxt in Nitro there is also a problem.

Reproduction
https://stackblitz.com/edit/github-hkf47y?file=nitro.config.ts

**Comment by danielroe** [comment] 2023-11-04 18:43
Thanks for the investigation and reproduction @damianglazer. ❤️

**Comment by pi0** [comment] 2023-11-07 14:43
Thanks for the investigation. Root cause is an issue in radix3 matcher you can track from https://github.com/unjs/radix3/issues/70

**Closed** 2023-11-07 15:07 UTC
Labels: 3.x, pending triage, nitro, upstream

**Comment by pi0** [comment] 2024-03-08 20:38
Should be fixed in the radix3 [`>=1.1.1`](https://github.com/unjs/radix3/releases/tag/v1.1.0).

Please upgrade your dependencies and lockfile using `npx nuxi upgrade --force` and ping me if still having issues. 🙏🏼

**Comment by damianglazer** [comment] 2024-03-08 22:16
Thanks @pi0, everything is ok now!
