### ISSUE TITLE
Can't use dependencies in nuxt layers

### ISSUE THREAD

**Issue by szulcus** [nuxt/nuxt#19426] opened 2023-03-03 14:53 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `^3.2.3`
- Nitro Version:    `-`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `ssr`, `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[dayjs-in-nuxt-layer-reporoduction.zip](https://github.com/nuxt/nuxt/files/10882990/dayjs-in-nuxt-layer-reporoduction.zip)
In `./nuxt-project`:
```bash
yarn && yarn dev
```
![image](https://user-images.githubusercontent.com/48328739/222752126-bbad1e76-f03a-4529-9958-d85b8e3d4496.png)

### Describe the bug

Can't use dependencies in package layer. So far I've noticed that the problem occurs with packages like: `axios`, `humps`, `qs`, `dayjs`, but I suspect there are many more.

### Additional context

Workaround (in `nuxt.config.ts`):
```ts
export default defineNuxtConfig({
	// ...
	extends: [
		'<layer-name>'
	],
	alias: {
		axios: 'axios',
		humps: 'humps',
		qs: 'qs',
		dayjs: 'dayjs',
	},
});
```

### Logs

```shell-script
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/dayjs/dayjs.min.js?v=17986f0a' does not provide an export named 'default' (at useDayjs.ts?v=17986f0a:1:8)
```

**Comment by johnfreytag-eos** [comment] 2023-03-20 17:12
Hey!

We've encountered similar issues and I'd like to add our findings to maybe narrow it down a bit:

- this only seems to happen if the layer is installed via an npm package
- the exact same setup within a monorepos where the layers are installed via symlinks (using pnpm workspaces) has no issues at all
   - this is mostly because Vite et al follow symlinks and the resolved path is outside node_modules, causing Nuxt to treat it as local code
- only dev mode is affected, production builds run flawlessly
- adding the third party dependencies shown in the error messages to `build.transpile` and / or `vite.optimizeDeps.include` helps most of the time, but messes up production builds

My first instinct was that layers code inside node_modules doesn't get transformed by Nuxt's internal tooling like local code does, however @danielroe seems to have considered that in [#5042](https://github.com/nuxt/framework/pull/5042)

To add additional confusion on the pile: We're getting this kind of error with valid ESM packages like `@splidejs/vue-splide`, which seems to be treated / imported as CJS when used inside a layer that's installed via `node_modules`, even though the file importing it is `.mjs` itself:

```
file:///<project>/node_modules/<layer>/index.mjs:2
import { Splide as w, SplideSlide as S } from "@splidejs/vue-splide";
                      ^^^^^^^^^^^
SyntaxError: Named export 'SplideSlide' not found. The requested module '@splidejs/vue-splide' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@splidejs/vue-splide';
const { Splide: w, SplideSlide: S } = pkg;
```

Here's their https://github.com/Splidejs/vue-splide/blob/master/package.json with valid exports definition.

Let me know if there is anything we can do to help.

**Comment by dargmuesli** [comment] 2023-04-25 03:39
Here is a stackblitz reproduction: https://stackblitz.com/edit/github-sbsspa-es9yjg?file=.playground%2Fnuxt.config.ts,.playground%2Fpackage.json

See `my-nuxt-layer-0.0.1.tgz` has been `pnpm pack`ed and `file:`d as playground dependency. Reloading the page yields an error in the browser console. Uncommenting the `alias` fixes the error.

**Comment by derHodrig** [comment] 2023-07-27 12:17
bump the issue. Upgrading to latest mermaid and nuxt (currently 10.3.0 and 3.6.5) does not solve the problem.

**Comment by wgbnyes** [comment] 2023-08-02 10:42
Same with me, optimizeDeps did nothing. The problem continues.
Besides, I don't think that forcing people who use my lib via NPM to make these configurations is wrong. I don't see other libs do this.

**Comment by derHodrig** [comment] 2023-08-03 08:44
@wgbnyes yes of course, this needs to be fixed. Is more a workaround. The alias workaround did not worked for me, since with Mermaid I had to provide an alias for all deps of mermaid. For that case, optimizeDeps helped me.

**Comment by szulcus** [comment] 2023-09-18 17:07
@marr yes 😕

**Comment by dargmuesli** [comment] 2024-01-30 22:32
In Nuxt 3.10 the `alias` workaround does not seem to work anymore with the now active bundler module resolution when running a `npm install && npm exec nuxt typecheck` as in: https://stackblitz.com/edit/github-gw9yxt?file=app.vue

![image](https://github.com/nuxt/nuxt/assets/4778485/1d92d5dc-94f5-4f52-b6f1-d0127c4792b6)

cc @danielroe

**Comment by danielroe** [comment] 2024-02-04 19:48
That is likely a bug in `sweetalert2` and should be raised with them. (They probably do not have types that are compatible with modern TypeScript, namely Node16+ module resolution.)

**Comment by danielroe** [comment] 2024-02-12 16:17
Checking the original reproduction, it is resolved by adding `dayjs` to `vite.optimizeDeps.include` (and the modified version with `sweetalert2` likewise). Why this is required is explained here: https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include.

There does not appear to be any issue once built.

Diving in, I think we can actually make this behaviour automatic for the end user with a small trick. (Raising PR.)

**Closed** 2024-02-13 09:54 UTC
Labels: 3.x, bug, ❗ p4-important, layers

**Comment by riddla** [comment] 2024-03-18 11:55
@danielroe, if I read the change in #2572 correctly, the automatic behaviour does not target layers installed via `node_modules` (yet) – could this be added?

**Comment by riddla** [comment] 2025-01-27 13:01
Just a check/ping to @danielroe for my comment above (as I just stumbled on the same error again).

**Comment by derHodrig** [comment] 2025-01-27 13:23
I dont have issues anymore.

In the layer i install the package as devDep and add it to the peerDeps

While local development of the layer i get the dependency via the devDeps and in the usage of the layer i install it as devDep oder dependcy (matters if you are in the app or other layer

**Comment by dargmuesli** [comment] 2025-01-28 18:23
Please open a new issue or discussion if you have questions on further improvement suggestions
