### ISSUE TITLE
ERROR  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shba007** [nuxt/nuxt#19783] opened 2023-03-18 05:56 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `modules`, `imports`, `runtimeConfig`, `typescript`, `app`, `nitro`
- Runtime Modules:  `@nuxt/devtools@0.2.5`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/tailwindcss@6.6.0`, `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`, `nuxt-icons@3.1.0`, `nuxt-vitest@0.6.8`
- Build Modules:    `-`
------------------------------

### Reproduction

On a large project small project does not have this problem

### Describe the bug

nuxt dev works fine but nuxt build failed

message
ERROR  Maximum call stack size exceeded

### Logs

```shell-script
Nuxi 3.3.1                                                                                                     11:23:50
Nuxt 3.3.1 with Nitro 2.3.1                                                                                    11:23:50
i Using default Tailwind CSS file from runtime/tailwind.css                                   nuxt:tailwindcss 11:23:51
i Building client...                                                                                           11:23:52
i vite v4.1.4 building for production...                                                                       11:23:52
i ✓ 400 modules transformed.                                                                                   11:23:55  

 ERROR  Maximum call stack size exceeded                                                                       11:23:55  


 ERROR  Maximum call stack size exceeded                                                                       11:23:55  

  at Set.has (<anonymous>)
  at ParameterVariable.deoptimizePath (/D:/Algostract/Orykit/store-web/node_modules/rollup/dist/es/shared/node-entry.js:6801:57)
  at Identifier.deoptimizePath (/D:/Algostract/Orykit/store-web/node_modules/rollup/dist/es/shared/node-entry.js:8149:24)
  at ObjectEntity.deoptimizeArgumentsOnInteractionAtPath (/D:/Algostract/Orykit/store-web/node_modules/rollup/dist/es/shared/node-entry.js:6051:22)
  at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (/D:/Algostract/Orykit/store-web/node_modules/rollup/dist/es/shared/node-entry.js:8597:36)
  at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (/D:/Algostract/Orykit/store-web/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
  at ParameterVariable.addEntityToBeDeoptimized (/D:/Algostract/Orykit/store-web/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
  at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (/D:/Algostract/Orykit/store-web/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
  at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (/D:/Algostract/Orykit/store-web/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
  at ParameterVariable.addEntityToBeDeoptimized (/D:/Algostract/Orykit/store-web/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
```

**Comment by danielroe** [comment] 2023-03-18 08:15
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by bcspragu** [comment] 2023-03-18 18:25
Not chiming in with anything particularly useful, but I hit the same thing after updating to 3.3.1:

```
 ERROR  Maximum call stack size exceeded                                                                                                                                                         11:12:39

  at ObjectEntity.deoptimizeArgumentsOnInteractionAtPath (node_modules/rollup/dist/es/shared/node-entry.js:6054:30)
  at ObjectExpression.deoptimizeArgumentsOnInteractionAtPath (node_modules/rollup/dist/es/shared/node-entry.js:11529:32)
  at node_modules/rollup/dist/es/shared/node-entry.js:6638:83
  at PathTracker.withTrackedEntityAtPath (node_modules/rollup/dist/es/shared/node-entry.js:1784:24)
  at LocalVariable.deoptimizeArgumentsOnInteractionAtPath (node_modules/rollup/dist/es/shared/node-entry.js:6638:26)
  at Identifier.deoptimizeArgumentsOnInteractionAtPath (node_modules/rollup/dist/es/shared/node-entry.js:8141:23)
  at ParameterVariable.addEntityToBeDeoptimized (node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
  at ArrowFunctionExpression.deoptimizeArgumentsOnInteractionAtPath (node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
  at ParameterVariable.addEntityToBeDeoptimized (node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
  at ArrowFunctionExpression.deoptimizeArgumentsOnInteractionAtPath (node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
```

It's unclear if it happens consistently on the same `transforming <module>` in Vite, just some module around `750` or so. It also failed on `3.3.0` and `3.2.3`, I had to downgrade to `3.1.2` to get it working again, at which point I hit https://github.com/nuxt/nuxt/issues/19717, which I fixed with https://github.com/nuxt/nuxt/issues/19717#issuecomment-1472328606. This is a pure Nuxt 3 project, no Nuxt 2 or bridge.

**Comment by danielroe** [comment] 2023-03-18 18:30
I have had a report that this is due to a rollup upgrade; we'll need to investigate but that is the most likely scenario.

**Comment by hex735184** [comment] 2023-03-19 03:51
In my case the reason was
import { useChangeCase } from '@vueuse/integrations/useChangeCase'

Replace with direct import resolve the error
import { camelCase } from "change-case";

**Comment by warflash** [comment] 2023-03-19 22:53
Related: https://github.com/unjs/nitro/issues/1063, https://github.com/rollup/rollup/issues/4904
Pinning rollup to 3.18.0 fixes the issue as a workaround

**Comment by hi-reeve** [comment] 2023-03-27 07:05
> Related: [unjs/nitro#1063](https://github.com/unjs/nitro/issues/1063), [rollup/rollup#4904](https://github.com/rollup/rollup/issues/4904) Pinning rollup to 3.18.0 fixes the issue as a workaround

this won't work with `v3.3.2`
upgrading to `3.3.2` breaks it even with pinning rollup to `3.18.0`

**Comment by danielroe** [comment] 2023-03-27 07:15
Would you please provide a reproduction? 🙏

**Comment by gorkie** [comment] 2023-03-27 13:14
<img width="1210" alt="Ekran Resmi 2023-03-27 16 13 06" src="https://user-images.githubusercontent.com/16632488/227947996-3832cde5-5834-4ef3-ba16-31cdf712a212.png">
 Is there any solution for this ? :(

**Comment by gorkie** [comment] 2023-03-27 13:14
<img width="1210" alt="Ekran Resmi 2023-03-27 16 13 06" src="https://user-images.githubusercontent.com/16632488/227947996-3832cde5-5834-4ef3-ba16-31cdf712a212.png">
 Is there any solution for this ? :(

**Comment by gorkie** [comment] 2023-03-27 13:17
<img width="1210" alt="Ekran Resmi 2023-03-27 16 13 06" src="https://user-images.githubusercontent.com/16632488/227947996-3832cde5-5834-4ef3-ba16-31cdf712a212.png">
 Is there any solution for this ? :(

**Comment by ddahan** [comment] 2023-04-03 12:59
> this won't work with `v3.3.2` upgrading to `3.3.2` breaks it even with pinning rollup to `3.18.0`

To be more specific about the workaround, it works with Nuxt 3.3.0 (not 3.3.1 nor 3.3.2) and rollup 3.18.0. Note that you may need to remove other packages like `nuxt-devtools` which requires Nuxt 3.3.1 as a dependency.

**Comment by danielroe** [comment] 2023-04-03 13:06
@ddahan Would you be able to provide a reproduction? 🙏 The workaround has worked for others running Nuxt 3.3.1, as you see above.

**Comment by hi-reeve** [comment] 2023-04-06 02:22
> @danielroe there is a reproduction: https://stackblitz.com/edit/nuxt-starter-6usrbo?file=components/TestFailing.vue (nuxt 3.3.3 + nuxt-lodash) You can run `yarn build` to see the error. There are two components, TestFailing.vue and TestWorking.vue, critical is this code `@click="emit('open', useCloneDeep(schema))"` if you remove it build will pass.

i can confirm this work now with 3.3.3 even with nuxt lodash

**Comment by danielroe** [comment] 2023-04-06 09:23
@hi-reeve Can you share more information? I can still reproduce with the provided reproduction even with latest Nuxt edge.

**Comment by hi-reeve** [comment] 2023-04-09 00:39
> @hi-reeve Can you share more information? I can still reproduce with the provided reproduction even with latest Nuxt edge.

updated to 3.3.3 and removing the pinned rollup 3.18 solved the issue for me. 

my package.json
```json
 "devDependencies": {
        "@commitlint/cli": "^17.5.1",
        "@commitlint/config-conventional": "^17.4.4",
        "@nuxt/eslint-config": "^0.1.1",
        "@nuxt/image-edge": "1.0.0-28008586.381b906",
        "@nuxt/kit": "^3.3.3",
        "@nuxt/test-utils": "^3.3.3",
        "@nuxtjs/eslint-module": "^4.0.2",
        "@nuxtjs/i18n": "8.0.0-beta.9",
        "@nuxtjs/tailwindcss": "^6.6.5",
        "@pinia-plugin-persistedstate/nuxt": "1.1.1",
        "@rushstack/eslint-patch": "^1.2.0",
        "@types/lodash-es": "^4.17.7",
        "@vee-validate/yup": "^4.8.4",
        "@vite-pwa/nuxt": "^0.0.7",
        "@vitest/coverage-c8": "^0.29.8",
        "@vue-macros/nuxt": "^1.2.8",
        "@vue/runtime-dom": "^3.2.47",
        "@vueuse/core": "^9.13.0",
        "@vueuse/nuxt": "^9.13.0",
        "eslint": "^8.37.0",
        "eslint-plugin-vuejs-accessibility": "^2.1.0",
        "husky": "^8.0.3",
        "nuxt": "^3.3.3",
        "nuxt-icon": "^0.3.3",
        "nuxt-lodash": "^2.4.1",
        "nuxt-typed-router": "^3.0.9",
        "nuxt-vitest": "^0.6.9",
        "prettier": "^2.8.7",
        "sass": "^1.60.0",
        "standard-version": "^9.5.0",
        "ts-toolbelt": "^9.6.0",
        "vite-plugin-vue-type-imports": "^0.2.4"
    },
    "dependencies": {
        "@casl/ability": "^6.4.0",
        "@casl/vue": "^2.2.1",
        "@firebase/app-types": "^0.9.0",
        "@huntersofbook/naive-ui-nuxt": "^0.7.1",
        "@nuxt-alt/proxy": "^2.2.3",
        "@nuxtjs/robots": "^3.0.0",
        "@pinia/nuxt": "^0.4.7",
        "@tanstack/vue-query": "^4.27.0",
        "@tanstack/vue-virtual": "3.0.0-beta.54",
        "@vueuse/motion": "2.0.0-beta.25",
        "axios": "^1.3.5",
        "change-case": "^4.1.2",
        "date-fns": "^2.29.3",
        "date-fns-tz": "^2.0.0",
        "firebase": "^9.19.1",
        "firebase-admin": "^11.5.0",
        "jwt-decode": "^3.1.2",
        "maska": "^2.1.7",
        "nanoid": "^4.0.2",
        "pinia": "^2.0.33",
        "pinia-plugin-persistedstate": "^3.1.0",
        "vee-validate": "^4.8.4",
        "yup": "^1.0.2",
        "zod": "^3.21.4"
    }
```

my nuxt.config.ts
```ts
import { i18n } from './config/i18n';
// https://nuxt.com/docs/api/configuration/nuxt-config

export default defineNuxtConfig({
    typescript: {
        includeWorkspace: true,
        tsConfig: {
            include: ['../**/*.d.ts'],
        },
    },
    runtimeConfig: {
        public: {
            firebase: {
                apiKey: process.env.NUXT_FIREBASE_API_KEY,
                authDomain: process.env.NUXT_FIREBASE_AUTH_DOMAIN,
                projectId: process.env.NUXT_FIREBASE_PROJECT_ID,
                storageBucket: process.env.NUXT_FIREBASE_STORAGE_BUCKET,
                messagingSenderId:
                    process.env.NUXT_FIREBASE_MESSAGING_SENDER_ID,
                appId: process.env.NUXT_FIREBASE_APP_ID,
            },
        },
    },
    //@ts-ignore
    modules: [
        '@nuxtjs/i18n',
        'nuxt-icon',
        '@nuxtjs/tailwindcss',
        '@vueuse/nuxt',
        '@nuxt/image-edge',
        'nuxt-typed-router',
        '@nuxtjs/robots',
        '@huntersofbook/naive-ui-nuxt',
        '@vue-macros/nuxt',
        [
            '@pinia/nuxt',
            {
                autoImports: [
                    // automatically imports `defineStore` as `definePiniaStore`
                    ['defineStore', 'definePiniaStore'], // import { defineStore as definePiniaStore } from 'pinia'
                ],
            },
        ],
        '@pinia-plugin-persistedstate/nuxt',
        '@vueuse/motion/nuxt',
        '~/modules/vee-validate',
        '~/modules/yup',
        '~/modules/vue-query/module.ts',
        '~/modules/vue-virtual.ts',
        'nuxt-vitest',
        '@nuxtjs/eslint-module',
        '@nuxt-alt/proxy',
        'vite-plugin-vue-type-imports/nuxt',
        'nuxt-lodash',
    ],
    extends: ['./auth'],
    tailwindcss: {
        cssPath: '~/assets/styles/main.scss',
    },
    lodash: {
        prefix: '_',
        upperAfterPrefix: false,
        prefixSkip: false,
    },
    image: {
        domains: ['images.unsplash.com'],
        alias: { unsplash: 'https://images.unsplash.com' },
    },
    i18n,
    naiveUI: {
        themeOverrides: {},
    },
    css: [],
    vite: {
        define: {
            // "process.env.DEBUG": false,
        },
        plugins: [],
    },
    imports: {
        dirs: ['store', 'services/**', 'composables/**'],
        imports: [
            {
                from: 'axios',
                name: 'axios',
            },
        ],
        injectAtEnd: true,
    },
    routeRules: {
        '/admin/**': { ssr: false },
        '/customer/**': { ssr: false },
        '/profile': { ssr: false },
        '/admin': { redirect: '/admin/dashboard' },
        '/customer': { redirect: '/customer/consignee-list' },
        '/api/auth/logout': { static: true },
    },
    components: [
        {
            path: '~/components',
            extensions: ['.vue'],
        },
        {
            path: '~/components/global',
            global: true,
        },
    ],
    proxy: {
        proxies: {
            '/proxy': {
                target: process.env.API_BASE_URL,
                changeOrigin: true,
                rewrite: (path: string) => path.replace(/^\/proxy/, 'v1/'),
            },
        },
    },
});

```

**Comment by hi-reeve** [comment] 2023-04-11 07:49
update once more, after few days not error, today i just got the error again on build.
pinning back nuxt to `3.3.1` and rollup to `3.18.0`

**Comment by kuizuo** [comment] 2023-04-12 10:54
> Related: [unjs/nitro#1063](https://github.com/unjs/nitro/issues/1063), [rollup/rollup#4904](https://github.com/rollup/rollup/issues/4904) Pinning rollup to 3.18.0 fixes the issue as a workaround

By following these steps, it is able to resolve this issue.

Add the following code in `package.json`:

```
"pnpm": {
    "overrides": {
      "rollup": "3.18.0"
    }
  }
}
```

**Comment by ddahan** [comment] 2023-04-13 22:00
Did someone find a workaround using Nuxt 3.4?
I'd like to use the new View Transitions API Support, but I'm currently stuck with nuxt 3.3.0 and rollup 3.18.0 as it's the only workaround I found. Thanks.

**Comment by danielroe** [comment] 2023-04-13 22:13
I can reproduce issue with just `lodash-es` on its own: https://stackblitz.com/edit/nuxt-starter-7hztxb.

The workaround is still working: https://stackblitz.com/edit/nuxt-starter-wunnhm.

**Comment by danielroe** [comment] 2023-04-14 08:42
A PR to fix this in rollup [has been opened](https://github.com/rollup/rollup/pull/4938).

You can test it by installing `rollup@3.20.3-0` or `rollup@beta`. It resolved the issue for me with the reproduction posted above, but I would be glad to hear other feedback. (Likely also worth commenting on https://github.com/rollup/rollup/issues/4904 if you can confirm it resolves the issue.)

**Comment by ddahan** [comment] 2023-04-14 08:59
@danielroe Nope :( Still the same error when running `npm run build`, using `nuxt 3.41` and `rollup 3.20.3-0`

**Comment by danielroe** [comment] 2023-04-14 09:00
@ddahan In that case it would be very helpful for you to provide a reproduction so your situation can be addressed. (Do ensure that you are using pnpm/npm overrides or yarn resolutions to install the new `rollup` version as otherwise you may not be testing the fix.)

**Comment by ddahan** [comment] 2023-04-14 11:19
@danielroe you were right I did not used `overrides` the right way. I don't have the issue anymore.

**Comment by danielroe** [comment] 2023-04-16 13:55
This issue has now been resolved in rollup@3.20.3 - you can refresh your lockfile to pull it in.

**Closed by danielroe** 2023-04-16 13:55 UTC
Labels: 3.x, workaround available, bug, upstream, upstream-bug

**Comment by davvvvsss** [comment] 2023-07-01 17:52
Nuxt 3.6.1 with Nitro 2.5.2  

ERROR  Maximum call stack size exceeded

**Comment by warflash** [comment] 2023-07-01 17:59
@davvvvsss I recommend opening a new issue along side a reproduction if you're running into that error message again
