### ISSUE TITLE
v3.4.1 nuxtApp.vueApp.config.errorHandler no work

### ISSUE THREAD

**Issue by YIngChenIt** [nuxt/nuxt#20347] opened 2023-04-18 11:02 UTC
### Environment

Nuxt 3.4.1

### Reproduction

https://stackblitz.com/edit/github-wfungx

### Describe the bug

nuxtApp.vueApp.config.errorHandler no work 
error in app.vue

**Comment by danielroe** [comment] 2023-04-18 11:04
Check out https://vuejs.org/api/application.html#app-config-errorhandler for the docs on what kind of errors the handler captures.

If you need assistance, the best way is to chat on our Discord (https://discord.nuxtjs.org) or open a GitHub Discussion rather than filing a bug report.

**Comment by YIngChenIt** [comment] 2023-04-19 00:38
> Check out https://vuejs.org/api/application.html#app-config-errorhandler for the docs on what kind of errors the handler captures.
> 
> If you need assistance, the best way is to chat on our Discord (https://discord.nuxtjs.org) or open a GitHub Discussion rather than filing a bug report.

[https://nuxt.com/docs/getting-started/error-handling](url)

I don't think there are any errors in usage, because it can run in V3.3.2(log errors)

**Comment by Hibrix-net** [comment] 2023-04-19 20:20
> Check out https://vuejs.org/api/application.html#app-config-errorhandler for the docs on what kind of errors the handler captures.
> 
> If you need assistance, the best way is to chat on our Discord (https://discord.nuxtjs.org) or open a GitHub Discussion rather than filing a bug report.

This is in fact true, the possible captures are as per the docs:

-     Component renders
-     Event handlers
-     Lifecycle hooks
-     setup() function
-     Watchers
-     Custom directive hooks
-     Transition hooks
- 
I don't this this will handle 500's, 404's etc.
Am I right?

So, in this case, how to handle them?

**Comment by danielroe** [comment] 2023-04-19 20:40
You can define render them in your `error.vue` file - should be explained elsewhere on the same page I linked.

**Comment by Hibrix-net** [comment] 2023-04-19 20:48
> You can define render them in your `error.vue` file - should be explained elsewhere on the same page I linked.

The problem is that whenever the 404 is triggered, even with the `error.vue` correctly setup, the dev console will show:
`[nuxt] error caught during app initialization Error: Page not found: (...)`

There's more people experiencing the same: https://stackoverflow.com/questions/75650321/nuxt-3-404-page-not-found-error-and-h3error-page-not-found

I'm not able to find a way to silent this, either using a middleware or a plugin or a combination of both.

**Comment by Hibrix-net** [comment] 2023-04-20 08:52
> > You can define render them in your `error.vue` file - should be explained elsewhere on the same page I linked.
> 
> The problem is that whenever the 404 is triggered, even with the `error.vue` correctly setup, the dev console will show: `[nuxt] error caught during app initialization Error: Page not found: (...)`
> 
> There's more people experiencing the same: https://stackoverflow.com/questions/75650321/nuxt-3-404-page-not-found-error-and-h3error-page-not-found
> 
> I'm not able to find a way to silent this, either using a middleware or a plugin or a combination of both.

What I mean here is that the non-existing routes aren't really triggering a 404 error but a Javascript error instead. I believe that should be fixed since the 404 error is not handled well.

**Comment by danielroe** [comment] 2023-04-20 10:36
The only issue I'm aware of is that you would prefer the console logging of the error not to take place, right?

I think the actual behaviour is working as expected: https://stackblitz.com/edit/github-izrmog

**Comment by Hibrix-net** [comment] 2023-04-20 10:49
> The only issue I'm aware of is that you would prefer the console logging of the error not to take place, right?
> 
> I think the actual behaviour is working as expected: https://stackblitz.com/edit/github-izrmog

Of course, I'm not against showing the 404 error, that's the common behavior as far as I'm concerned:
`[HTTP/1.1 404 Not Found 0ms]`

But it seems a bit strange to show this along with the nuxt error:
From your stackblitz: `[nuxt] error caught during application initialization Error: Page not found: /some-404-page`

I would prefer to avoid this additional bug which I don't remember from previous versions of Nuxt by the way.

Another thought I'd like and can't figure out how to do is to intercept those console errors specifically related to 404s etc.
Yes, I know there are some generic runtime hooks, but those aren't very 404-specific. For example, `app:error` is for all fatal errors that can occur, including 404s.

Am I right or am I too picky?
Thank you so much,

**Comment by manniL** [comment] 2023-12-23 16:28
Closing in favor of https://github.com/nuxt/nuxt/issues/22691 which also shows a workaround 👏🏻

**Closed by manniL** 2023-12-23 16:28 UTC
Labels: 3.x, pending triage
