### ISSUE TITLE
When a nuxt build is executed, there is a memory leak

### ISSUE THREAD

**Issue by ChinDer** [nuxt/nuxt#30401] opened 2024-12-28 07:37 UTC
### Environment

  "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
    "@pinia/nuxt": "^0.4.10",
    "@vueuse/core": "^10.1.2",
    "@vueuse/nuxt": "^10.1.2",
    "pinia": "^2.0.36",
    "unplugin-vue-components": "^0.24.1"

### Reproduction

https://github.com/ChinDer/nuxtDemo in this repo

### Describe the bug

I've had this issue in multiple nuxt versions, how can I fix this

### Logs

```shell-script
![Image](https://github.com/user-attachments/assets/4bd2b8c5-6b47-4183-9e35-a9d687c66654)
```

**Comment by cernymatej** [comment] 2024-12-28 10:16
Closing as a duplicate of #30400

**Closed by cernymatej** 2024-12-28 10:16 UTC
Labels: pending triage, possible regression
