### ISSUE TITLE
nuxt generate FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory 

### ISSUE THREAD

**Issue by safejace** [nuxt/nuxt#14168] opened 2022-06-15 21:16 UTC
### Environment

Nuxt CLI v3.0.0-rc.4
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `build`, `css`, `buildModules`, `modules`, `sanity`, `vite`
- Runtime Modules:  `@nuxtjs/sanity@1.2.2`, `@vueuse/nuxt@8.6.0`
- Build Modules:    `@pinia/nuxt@0.1.9`, `@safesoftware/safebase-vue/nuxt@0.4.0`
------------------------------

### Reproduction

yarn nuxt build

### Describe the bug

when trying to generate my site i get javascript heap allocation errors.

it hangs on `ℹ Initializing prerenderer` for a long time

my devops colleague said he had it running for the hour, and it finally failed (see logs). 

### Logs

```shell
yarn run v1.22.18
$ nuxt build
Nuxt CLI v3.0.0-rc.4                                                                                                                                       17:15:59
ℹ Running with Sanity project XXXXXX (production).                                                                                             @nuxtjs/sanity 17:16:14
ℹ Vite client warmed up in 77349ms                                                                                                                         17:17:46
 
 WARN                                                                                                                                                      17:18:46
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
 
ℹ Client built in 137160ms                                                                                                                                 17:18:46
ℹ Building server...                                                                                                                                       17:18:46
 
 WARN  @fortawesome/fontawesome-pro doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
 
✔ Server built in 65079ms                                                                                                                                  17:19:51
✔ Generated public .output/public                                                                                                                    nitro 17:19:54
start Building server...                                                                                                                             nitro 17:19:54
 
 WARN  rollup-plugin-inject: failed to parse /code/safecom-fmeuc/.nuxt/dist/server/server.mjs. Consider restricting the plugin to particular files via options.include
 
 
 ERROR  Rollup error: Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)   nitro 18:16:01
 
 
 ERROR  Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)                       18:16:01
 
  at error (node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12422:16)
  at Module.tryParse (node_modules/rollup/dist/es/shared/rollup.js:12799:25)
  at Module.setSource (node_modules/rollup/dist/es/shared/rollup.js:12704:24)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/rollup.js:22178:20)
 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by madebyfabian** [comment] 2023-02-07 03:39
Not willing to provide reprod, not reproducable by @danielroe, welp, let's close this! Gotta bring that issue count down my nuxt friends 💚

**Closed** 2023-02-07 06:58 UTC
Labels: 3.x, pending triage, upstream, needs reproduction, ⛔️ can be closed

**Comment by Andrew0914** [comment] 2023-02-09 22:05
It is still happening, when run `nuxt generate` and  in `nuxt.config.js` set 🤔 

`sourcemap: true`

or

```js
sourcemap: {
  client: true,
  server: false
}
```

My nuxt config:

```js
import { sentryVitePlugin } from "@sentry/vite-plugin";

require("custom-env").env(true);

function removeDataTestAttrs(node: any, _context: any) {
  if (node.type === 1 /* NodeTypes.ELEMENT */) {
    node.props = node.props.filter((prop: any) =>
      prop.type === 6 /* NodeTypes.ATTRIBUTE */
        ? prop.name !== "data-testid"
        : true
    );
  }
}

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  dev: process.env.NODE_ENV !== "production",
  ssr: false,
  sourcemap: {
    client: true,
    server: false,
  },
  modules: ["@nuxtjs/i18n", "@pinia/nuxt"],
  components: [
    {
      path: "~/components/",
      pathPrefix: false,
    },
  ],
  i18n: {
    vueI18n: {
      legacy: false,
      locale: "en",
      messages: {
        // TODO: Verificar que sea la forma correcta de importar
        en: require("./locales/en.json"),
      },
    },
  },
  vite: {
    plugins: [
      {
        ...sentryVitePlugin({
          org: 'some',
          project: 'some',
          include: './dist',
          ignore: ['node_modules'] // Auth tokens can be obtained from https://sentry.io/settings/account/api/auth-tokens/
          // and needs the `project:releases` and `org:read` scopes
          //authToken: env.VITE_SENTRY_AUTH_TOKEN,
        }),
        apply(_config, _ctx) {
          return process.env.NODE_ENV !== 'development'
        }
      }
    ],
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "@/assets/css/app.scss" as *;',
        },
      },
    },
    define: {
      "window.global": {},
    },
    vue: {
      template: {
        compilerOptions: {
          nodeTransforms:
            process.env.NODE_ENV == "production" ? [removeDataTestAttrs] : [],
        },
      },
    },
  },
  router: {
    options: { hashMode: true },
  },
});

```

Error output:
```

<--- Last few GCs --->

[7032:0x614e570]    84441 ms: Scavenge (reduce) 2022.7 (2082.0) -> 2022.5 (2082.3) MB, 9.6 / 0.0 ms  (average mu = 0.418, current mu = 0.352) allocation failure; 
[7032:0x614e570]    86150 ms: Mark-sweep (reduce) 2024.3 (2083.8) -> 2024.1 (2084.5) MB, 1159.6 / 0.0 ms  (average mu = 0.386, current mu = 0.356) allocation failure; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb7b150 node::Abort() [node]
 2: 0xa8c89a  [node]
 3: 0xd62ea0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd63247 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf40945  [node]
 6: 0xf52e2d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xf2d52e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xf2e8f7 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xf0faca v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x12d357d v8::internal::Runtime_AllocateInOldGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x17001f9  [node]
Aborted
```

I have to set sourcemap values as  false  in both cases in order to get work, but i need the sourcemaps to upload to my sentry instance. 😢

**Comment by bangjelkoski** [comment] 2023-02-14 13:22
Any update on this issue?

**Comment by danielroe** [comment] 2023-02-14 20:43
If you can provide a reproduction, we can reopen and investigate.

**Comment by bangjelkoski** [comment] 2023-02-14 22:16
The strange thing is that it doesn't happen on a local machine, only within a Github Action environment. Using `NODE_OPTIONS: '--max_old_space_size=4096'` within the `.env` of the Github Action worked and the issue is not happening anymore.

**Comment by danielroe** [comment] 2023-02-14 23:15
Probably because GitHub Actions has a limit of 7Gb - see https://github.com/vitejs/vite/blob/main/.github/workflows/ci.yml#L4-L6 for example.

**Comment by toniengelhardt** [comment] 2023-02-25 19:33
I also get it building on Digital Ocean when I enable client source maps. Locally build works.

**Comment by Reidond** [comment] 2023-05-23 17:33
> The strange thing is that it doesn't happen on a local machine, only within a Github Action environment. Using `NODE_OPTIONS: '--max_old_space_size=4096'` within the `.env` of the Github Action worked and the issue is not happening anymore.

this helped me

**Comment by Abdulhai-Mohamed** [comment] 2023-06-12 13:27
Any updates 😒

**Comment by SleepiestAdam** [comment] 2023-06-25 08:37
We're also getting this error when trying to prerender our site. Setting NODE_OPTIONS="--max_old_space_size= 8192" doesn't appear to help at all.

**Comment by toniengelhardt** [comment] 2023-06-25 09:29
> We're also getting this error when trying to prerender our site. Setting NODE_OPTIONS="--max_old_space_size= 8192" doesn't appear to help at all.

Not sure if this is a real fix or just coincidence, but I solved it in my case by reducing the `--max_old_space_size` flag to be less than the memory of the droplet + heap size (3072 in my case).

I know that for instance for postgres it just crashes if you reach the memory limit of the machine. Might this be a similar issue?

**Comment by dnndev** [comment] 2023-07-02 14:49
For others who may be in my boat - (Nuxt 3.6.1).  Even though I have 64GB memory and nothing else running, I got this error building locally for production as well as on Netlify. I noticed in my logs that the final `.nuxt/dist/server/server.mjs` file was about 20MB and the source map was about 25MB. I figured this may be why there was a memory allocation error.  

I hadn't yet cleaned up my project for production. I had all the Font Awesome libraries available and all were being transpiled (as configured in `nuxt.config.ts`). I removed the unused libraries from the transpile section and removed their imports elsewhere in the app.  This brought my `.nuxt/dist/server/server.mjs` file down to 5.9MB and map to 7.3MB. This was enough for the build to work locally and on Netlify.

I hope this helps someone, including my future self.

**Comment by bangjelkoski** [comment] 2023-07-02 17:09
> For others who may be in my boat - (Nuxt 3.6.1). Even though I have 64GB memory and nothing else running, I got this error building locally for production as well as on Netlify. I noticed in my logs that the final `.nuxt/dist/server/server.mjs` file was about 20MB and the source map was about 25MB. I figured this may be why there was a memory allocation error.
> 
> I hadn't yet cleaned up my project for production. I had all the Font Awesome libraries available and all were being transpiled (as configured in `nuxt.config.ts`). I removed the unused libraries from the transpile section and removed their imports elsewhere in the app. This brought my `.nuxt/dist/server/server.mjs` file down to 5.9MB and map to 7.3MB. This was enough for the build to work locally and on Netlify.
> 
> I hope this helps someone, including my future self.

Hey, how do you exclude libraries that you don't want to be transpiled?

**Comment by dnndev** [comment] 2023-07-02 18:13
It's not excluding per se. It's simply removing them from the transpile block in `defineNuxtConfig`. So, for Font Awesome, the recommended setup is to include the libraries there. When setting up my project, I put all the libraries in there since I was not sure which styling I'd go with. So to "exclude" them, I just removed or commented them out.

Example:

```
export default defineNuxtConfig({
  devtools: { enabled: false },

  css: ['@fortawesome/fontawesome-svg-core/styles.css'],

  modules: ['@nuxtjs/tailwindcss', '@pinia/nuxt'],

  build: {
    transpile: [
      '@fortawesome/vue-fontawesome',
      '@fortawesome/fontawesome-svg-core',
      // '@fortawesome/free-brands-svg-icons',
      // '@fortawesome/free-regular-svg-icons',
      // '@fortawesome/free-solid-svg-icons',
      // '@fortawesome/pro-duotone-svg-icons',
      '@fortawesome/pro-light-svg-icons',
      '@fortawesome/pro-regular-svg-icons',
      // '@fortawesome/pro-solid-svg-icons',
      // '@fortawesome/pro-thin-svg-icons',
      // '@fortawesome/sharp-light-svg-icons',
      // '@fortawesome/sharp-regular-svg-icons',
      // '@fortawesome/sharp-solid-svg-icons',
    ],
  },
  runtimeConfig: {
    public: {
...
```
Above I've commented the libraries out. I'll remove them before production.

HTH,
Kelly

**Comment by TingYu-Lee** [comment] 2024-04-09 08:26
Still have the same problem.

I tried changing the `IconName` of `fontawesome-common-types/index.d.s` from union type to `string`
- `pass`

Is this `union type` related?

P.S
for copy
> `node_modules/@fortawesome/fontawesome-common-types/index.d.ts`

**Comment by wilfredinni** [comment] 2024-12-09 14:01
Still the same problem, are there some updates on this? Thank you

**Comment by koushik-boinepally** [comment] 2025-01-05 13:12
Removing @nuxt/scripts did it for me. I'm on a 16GB system and ran out of memery around 5 gigs.

**Comment by mpgalaxy** [comment] 2025-01-08 11:53
I had the same issue in nuxt 3.8.0. Somehow nuxt seems to ignore the NODE_OPTIONS settings provided by the env environment in docker compose. Setting the flag in package.json did the trick for me:
```
...
"build": "NODE_OPTIONS='--max-old-space-size=4096' nuxt build",
"generate": "NODE_OPTIONS='--max-old-space-size=4096' nuxt generate"
...
```

**Comment by felixwollmann** [comment] 2025-02-12 18:59
I've encountered a similar issue. I tried to prerender a few pages, which resulted in Node running out of memory (logs seen below) only while building in Docker. The build ran perfectly with minmal memory consuption locally (in a DevContainer). As my repo (my diploma thesis) is open source, here you go: https://github.com/ScrumpliCity/ScrumpliCity/tree/454603497dcfa6fa300b4fab1cee4ea3bf1e3910
Running `docker compose build frontend` (in ./docker dir) fails, running `npm run build` (in the ./frontend dir) works out fine.

I tried running the docker build on my server with a limit of 28GB of heap storage, still failed.

```
13.85 ℹ .nuxt/dist/server/_nuxt/HomepageDesktopBackground-NsCDtCBn.js              91.42 kB │ map:  93.32 kB
13.85 ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-DTDxuj3j.js                    125.39 kB │ map:   0.11 kB
13.85 ℹ .nuxt/dist/server/server.mjs                                              412.56 kB │ map: 840.82 kB
13.87 ℹ ✓ built in 4.04s
13.88 ✔ Server built in 4044ms
13.88 [nitro] ℹ Initializing prerenderer
18.78 [nitro] ℹ Prerendering 6 routes
2213.9
2213.9 <--- Last few GCs --->
2213.9
2213.9 [19:0x37ea5630]  2199827 ms: Mark-Compact (reduce) 28195.0 (28719.9) -> 28194.0 (28719.9) MB, 6843.24 / 0.00 ms  (average mu = 0.526, current mu = 0.001) allocation failure; scavenge might not succeed
2213.9 [19:0x37ea5630]  2213755 ms: Mark-Compact (reduce) 28195.1 (28719.9) -> 28194.3 (28720.2) MB, 13889.22 / 0.02 ms  (average mu = 0.301, current mu = 0.003) allocation failure; scavenge might not succeed
```

**Comment by fsyntax** [comment] 2025-04-03 19:39
> Removing @nuxt/scripts did it for me. I'm on a 16GB system and ran out of memery around 5 gigs.

@nuxt/scripts is also the culprit in my app, with version `0.11.5` - but only if using `useScriptMetaPixel`. 
Altough I haven't had chance yet to inspect if it is because of a misconfiguration on my side.
