### ISSUE TITLE
layouts now require a single root node

### ISSUE THREAD

**Issue by rsm23** [nuxt/nuxt#21759] opened 2023-06-25 11:25 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, runtimeConfig, telemetry, css, modules, i18n, build, postcss, devtools, plugins
- Runtime Modules:  @vueuse/nuxt@10.1.2, @nuxtjs/i18n@8.0.0-beta.11, @vee-validate/nuxt@4.9.6, @nuxt/devtools@0.5.5, nuxt-lodash@2.4.1
- Build Modules:    -
------------------------------

### Reproduction

Can't share the project (private company project)

### Describe the bug

After the update the application won'y run, and I have this error on te console : 

`[Vue warn]: <Suspense> slots expect a single root node.`

<img width="518" alt="Capture d’écran 2023-06-25 à 03 37 58" src="https://github.com/nuxt/nuxt/assets/2084708/bbee0297-3052-4234-8bda-d71a521769b7">

**Comment by IsraelOrtuno** [comment] 2023-06-25 13:25
`<NuxtLayout>` can't have multiple child nodes, try to wrap everything inside within a `<div>`

**Comment by rsm23** [comment] 2023-06-25 18:52
> `<NuxtLayout>` can't have multiple child nodes, try to wrap everything inside within a `<div>`

Thank you now it works, but should note it as a breaking change in the `v3.6.0` version when upgrading from `3.0.0-3.5.3`

**Comment by danielroe** [comment] 2023-06-25 20:32
Do you also have transitions enabled?

**Comment by rsm23** [comment] 2023-06-25 20:41
> Do you also have transitions enabled?

No

**Comment by danielroe** [comment] 2023-06-25 21:13
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by dextersiah** [comment] 2023-06-26 06:36
Had the same issue after upgrading to `3.6.0`. However the issue only happens when the page does not have a layout. 

Reproduction
https://stackblitz.com/edit/github-utjch3-jwvzqj?file=layouts%2Fdashboard.vue

Test Case
- `/` (with layout) ✅
- `/products` (without layout) ❌
- `/products/[id] `(without layout) ✅

**Comment by IsraelOrtuno** [comment] 2023-06-26 08:03
Yes, it happens to me too only when using:

```ts
definePageMeta({ layout: false })
```

Solved for now by adding a unique root to the `<NuxtLayout>` component in `app.vue`:

```vue
<template>
  <NuxtLayout>
    <div>
      <NuxtLoadingIndicator />

      <NuxtPage />
    </div>
  </NuxtLayout>
</template>
```

**Comment by heikopaiko** [comment] 2023-06-26 14:40
And the Docs should be updated as well. [Loading Indicator DOCs](https://nuxt.com/docs/api/components/nuxt-loading-indicator)

**Comment by MrCheater** [comment] 2023-06-27 11:11
+1

**Comment by dargmuesli** [comment] 2023-06-27 19:59
Is it really only a minor bug when the whole app does not show just because one isn't using layouts? :eyes: Or is using layouts the default?

**Comment by tolgahanbeyazoglu** [comment] 2023-07-04 07:09
unnecessary !!

**Comment by huang-julien** [comment] 2024-04-08 20:48
closing as this is not an reproductible  in the current version with the stackblitz provided

**Closed by huang-julien** 2024-04-08 20:48 UTC
Labels: 3.x, workaround available, bug, ❗ p4-important
