### ISSUE TITLE
`useAsyncData`: `getCachedData` + `immediate: false` don`t work

### ISSUE THREAD

**Issue by or2e** [nuxt/nuxt#25341] opened 2024-01-19 21:50 UTC
### Reproduction

https://stackblitz.com/edit/nuxt-starter-g5apvu?file=pages%2Findex.vue

### Describe the bug

Composable `useAsyncData`.
`getCachedData` in combination with `immediate: false` don't behave as expected. 
In reproduction, when returning to the `/` page, the API request is still executed.

**Comment by manniL** [comment] 2024-01-19 22:48
Duplicate of https://github.com/nuxt/nuxt/issues/24332

**Closed by manniL** 2024-01-19 22:48 UTC
Labels: 3.x, pending triage
