### ISSUE TITLE
Only URLs with a scheme in: file, data are supported by the default ESM loade

### ISSUE THREAD

**Issue by edwinfadul** [nuxt/nuxt#15500] opened 2022-11-17 04:18 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `modules`, `typescript`, `build`, `css`, `vite`, `runtimeConfig`
- Runtime Modules:  `nuxt-security@0.7.0`
- Build Modules:    `-`
------------------------------

### Versions

- nuxt: v3.0.0 
- node: v18.12.1 
- windows: 10

By installing nuxt security and placing the dependency in nuxtjs config - **modules: ['nuxt-security'] -**
[https://nuxt.com/modules/security](https://nuxt.com/modules/security)

### Describe the bug

[worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

![image](https://user-images.githubusercontent.com/34517197/202352611-8edbdd89-2a82-4df7-b3cd-9504041ae53b.png)

### Additional context

It should be noted that I have tried several versions of nuxt and node - I have deleted node_modules - yesterday I upgraded nuxt and today again.

**Comment by dargmuesli** [comment] 2023-01-25 10:22
I've got a PR on `@dargmuesli/nuxt-cookie-control` which might not fix the root cause, I'm unsure. Just mentioning it in case it helps.

**Comment by ennioVisco** [comment] 2023-01-25 10:42
> I've got a PR on `@dargmuesli/nuxt-cookie-control` which might not fix the root cause, I'm unsure. Just mentioning it in case it helps: https://github.com/dargmuesli/nuxt-cookie-control/pull/22/files

Amazing catch! @dargmuesli.

This clarifies that it's an issue of nuxt-kit's `resolvePath`: https://github.com/nuxt/nuxt/blob/1211f62d41b54592dd3bc0d9db62ef9ca0296177/packages/kit/src/resolve.ts#L29
which is in fact using `normalize` from `unjs/pathe`: https://github.com/unjs/pathe/blob/main/src/path.ts#L22.

I just pushed the issue upwards there :) https://github.com/unjs/pathe/issues/117

**Comment by DeivisFelipe** [comment] 2023-01-26 14:10
me too with NUXT 3.1.0

**Comment by kaname-png** [comment] 2023-01-27 00:52
Hi, getting the same problem here.

```
Nuxi 3.1.1                                                                                                                                                                           18:50:45
                                                                                                                                                                                     18:50:46
RootDir: C:/Users/inmor/Documents/Proyectos/Naeko/dashboard                                                                                                                          18:50:46
Nuxt project info:                                                                                                                                                                   18:50:46

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.3.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@7.25.0`
- Builder:          `vite`
- User Config:      `modules`, `css`, `htmlValidator`, `app`, `runtimeConfig`, `colorMode`, `security`, `i18n`
- Runtime Modules:  `@nuxtjs/html-validator@1.2.3`, `@nuxtjs/fontaine@0.2.4`, `@nuxtjs/tailwindcss@6.3.0`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/i18n@8.0.0-beta.8-27909545.920a4fe`, `@nuxt/image-edge@1.0.0-27907872.f4dd19d`, `nuxt-security@0.10.1`, `nuxt-icon@0.2.10`, `@nuxtjs/robots@3.0.0`, `nuxt-typed-router@2.1.4`
- Build Modules:    `-`
------------------------------
```

![image](https://user-images.githubusercontent.com/56084970/214982884-759b4e40-40b2-426b-955b-d8302b6961ac.png)

**Comment by videmann** [comment] 2023-02-11 06:59
> > I've got a PR on `@dargmuesli/nuxt-cookie-control` which might not fix the root cause, I'm unsure. Just mentioning it in case it helps: https://github.com/dargmuesli/nuxt-cookie-control/pull/22/files
> 
> Amazing catch @dargmuesli!
> 
> This clarifies that it's an issue of nuxt-kit's `resolvePath`:
> 
> https://github.com/nuxt/nuxt/blob/1211f62d41b54592dd3bc0d9db62ef9ca0296177/packages/kit/src/resolve.ts#L29
> 
> which is in fact using `normalize` from `unjs/pathe`: https://github.com/unjs/pathe/blob/main/src/path.ts#L22.
> 
> I just pushed the issue upwards there :) [unjs/pathe#117](https://github.com/unjs/pathe/issues/117)

It works! Thnx!

**Comment by ennioVisco** [comment] 2023-02-11 07:05
> 

With which plugin it works? I'm still backtracking the changes to nuxt kit and pathe in order to find the exact cause of the issue, but I cannot find it yet :/

**Comment by videmann** [comment] 2023-02-11 07:13
> 

I tried to run nuxt 3.2.0 with nuxt-cookie-control... nuxt starts, but when i append CookieControl component on page, it crashes.. after fix path does not contain slashes... exploring an error...

**Comment by dargmuesli** [comment] 2023-03-01 00:13
Would you guys please try `nuxt v3.2.3` (and `@dargmuesli/nuxt-cookie-module v5.0.1`) and report if fixes in those releases resolve this issue as well?

**Comment by ennioVisco** [comment] 2023-03-01 00:21
> Would you guys please try `nuxt v3.2.3` (and `@dargmuesli/nuxt-cookie-module v5.0.1`) and report if fixes in those releases resolve this issue as well?

It doesn't work with nuxtjs/robots (I cannot tell about nuxt-cookie, but at some point I'll integrate it as well).

**Comment by misway** [comment] 2023-03-01 02:58
nuxt 3.2.3 with nuxt-mail still have this problem

**Comment by JulienChampagnol** [comment] 2023-03-01 08:24
> nuxt 3.2.3 with nuxt-mail still have this problem

Same with nuxt 3.2.3 and @dargmuesli/nuxt-cookie-control

**Comment by dargmuesli** [comment] 2023-03-01 23:25
The CI pipeline for `@dargmuesli/nuxt-cookie-module` runs fine for `v5.0.2` :partying_face: please try it again, it should now work.

**Comment by dargmuesli** [comment] 2023-03-01 23:37
I did research and found that this issue arises [when importing an absolute file url on Windows](https://github.com/nodejs/node/issues/31710). It can be resolved by importing `pathToFileUrl(path).href` [as done for `@dargmuesli/nuxt-cookie-module`](https://github.com/dargmuesli/nuxt-cookie-control/pull/57/files#diff-030fc083b2cbf5cf008cfc0c49bb4f1b8d97ac07f93a291d068d81b4d1416f70R113-R114).

I think this issue can be closed as "not planned". cc @danielroe

**Comment by ennioVisco** [comment] 2023-03-02 07:57
> I did research and found that this issue arises [when importing an absolute file url on Windows](https://github.com/nodejs/node/issues/31710). It can be resolved by importing `pathToFileUrl(path).href` [as done for `@dargmuesli/nuxt-cookie-module`](https://github.com/dargmuesli/nuxt-cookie-control/pull/57/files#diff-030fc083b2cbf5cf008cfc0c49bb4f1b8d97ac07f93a291d068d81b4d1416f70R113-R114).
> 
> I think this issue can be closed as "not planned". cc @danielroe

Well, actually if it works it should be done by nuxt/kit instead of relying on the individual modules!

**Comment by danielroe** [comment] 2023-03-02 10:11
In the example given above, Nuxt Kit can't solve this for the module author - this isn't coming from a kit issue (resolvePath is _meant_ to return an absolute path, and doesn't have any presuppositions how this is used). As  @dargmuesli said, module authors need to ensure that if they are dynamically _importing_ an absolute path that this is a file URL.

On the other hand, if kit utilities like `addServerHandler` are causing problems, we would need to fix them.

I'm going to close this now as resolved, but if anyone encounters an issue in future that is caused by kit, please do raise an issue with a reproduction. 🙏

**Closed by danielroe** 2023-03-02 10:11 UTC
Labels: 3.x, upstream, windows, ❗ p4-important

**Comment by tobiasdiez** [comment] 2023-03-04 17:37
One instance where I still hit this issue is in the context of an `alias` that is externalized. I've opened https://github.com/nuxt/nuxt/issues/19453 with more details.

**Comment by 15844229646** [comment] 2023-04-07 01:51
me too

**Comment by HassanKadhim** [comment] 2023-04-22 16:54
me too

**Comment by dosstx** [comment] 2023-06-15 16:08
I did not understand the "solution" to this. Can someone clarify or sum up the consensus in this thread?

In my case, I get the following error: 

` ERROR  [worker reload] [worker init] Only URLs with a scheme in: file and data are supported by the default ESM loader. Received protocol 'https:'`

I get that error when trying to run this code a Nuxt server api route (using Deno):

```JS

import { OpenAI } from "https://deno.land/x/openai/mod.ts"; //<--- what is correct way to import this????

const systemPrompts = [...]


export default defineEventHandler(async (event) => {


  const openAI = new OpenAI('<API_KEY>');

  const chatCompletion = await openAI.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages: [
      { "role": "system", "content": "You are a helpful assistant." },
      { "role": "user", "content": "Who won the world series in 2020?" },
      {
        "role": "assistant",
        "content": "The Los Angeles Dodgers won the World Series in 2020.",
      },
      { "role": "user", "content": "Where was it played?" },
    ],
  });

  console.log(chatCompletion);
})
```

**Comment by ennioVisco** [comment] 2023-06-16 05:56
> I did not understand the "solution" to this. Can someone clarify or sum up the consensus in this thread?
> 
> In my case, I get the following error:
> 
> ` ERROR [worker reload] [worker init] Only URLs with a scheme in: file and data are supported by the default ESM loader. Received protocol 'https:'`
> 
> I get that error when trying to run this code a Nuxt server api route (using Deno):
> 
> ```js
> import { OpenAI } from "https://deno.land/x/openai/mod.ts"; //<--- what is correct way to import this????
> 
> const systemPrompts = [...]
> 
> 
> export default defineEventHandler(async (event) => {
> 
> 
>   const openAI = new OpenAI('<API_KEY>');
> 
>   const chatCompletion = await openAI.createChatCompletion({
>     model: "gpt-3.5-turbo",
>     messages: [
>       { "role": "system", "content": "You are a helpful assistant." },
>       { "role": "user", "content": "Who won the world series in 2020?" },
>       {
>         "role": "assistant",
>         "content": "The Los Angeles Dodgers won the World Series in 2020.",
>       },
>       { "role": "user", "content": "Where was it played?" },
>     ],
>   });
> 
>   console.log(chatCompletion);
> })
> ```
> 
> Note: My use case for this code is so I can stream server data using edge functions on remote server platforms (Netlify, etc).

1) this is not related to the original issue, so you should create a new issue
2) nuxt does not officially support Deno
3) in classic node/js it's not common to import remote modules, you should either install it and call it locally or open a Deno issue about how this should work in a node package.

**Comment by luckycstar** [comment] 2023-07-20 12:06
I have just installed "@nuxtjs/robots": "^3.0.0" in Nuxt 3.4.3 but I have got same issue.

`[2:51:02 PM]  ERROR  [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

  at new NodeError (node:internal/errors:400:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1055:11)
  at defaultResolve (node:internal/modules/esm/resolve:1135:3)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
  at link (node:internal/modules/esm/module_job:76:36)`

![image](https://github.com/nuxt/nuxt/assets/75414108/e9d91de2-e19f-4384-99cf-cc52687a163e)

**Comment by ahmed7am1d** [comment] 2023-08-24 09:32
Any solutions ? I am trying to use https://histoire.dev/ for writing documentations for the components and get the exact same Error: 
`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)`

**Comment by ennioVisco** [comment] 2023-08-24 11:52
> I have just installed "@nuxtjs/robots": "^3.0.0" in Nuxt 3.4.3 but I have got same issue.
> 
> `[2:51:02 PM] ERROR [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
> 
> at new NodeError (node:internal/errors:400:5) at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1055:11) at defaultResolve (node:internal/modules/esm/resolve:1135:3) at nextResolve (node:internal/modules/esm/loader:163:28) at ESMLoader.resolve (node:internal/modules/esm/loader:842:30) at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18) at ModuleWrap. (node:internal/modules/esm/module_job:77:40) at link (node:internal/modules/esm/module_job:76:36)`
> 
> ![image](https://user-images.githubusercontent.com/75414108/254877405-e9d91de2-e19f-4384-99cf-cc52687a163e.png)

I'd recommend checking in the appropriate threads. Looks like it's a known problem of that module: https://github.com/nuxt-modules/robots/issues/99

**Comment by Foddie2** [comment] 2024-01-22 19:24
Getting the same error 

> Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'https:'

**Comment by miztizm** [comment] 2024-02-07 10:15
Encounter a similar issue with another package, as described here.

**Comment by danperks** [comment] 2024-02-29 14:50
I've just faced this issue myself, running with PM2. 
I could run it myself in the command line fine, but runing it with PM2 I got this error.


```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
     at new NodeError (node:internal/errors:405:5)
     at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:131:11)
     at defaultLoad (node:internal/modules/esm/load:82:3)
     at nextLoad (node:internal/modules/esm/loader:163:28)
     at ESMLoader.load (node:internal/modules/esm/loader:603:26)
     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
     at new ModuleJob (node:internal/modules/esm/module_job:64:26)
     at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I had no more terminal output besides this, so very hard to debug.
Disabling cluster mode in my PM2 ecosystem.config.js file fixed it, but no clue why.

**Comment by danielroe** [comment] 2024-03-01 09:48
That feels like something that should be reported to pm2.

**Comment by danperks** [comment] 2024-03-01 16:38
As the cluster setting seemed to be the resolving factor, and clusters are a Node.js feature and not PM2, I'd be surprised if PM2 was the source of the issue.

**Comment by surgiie** [comment] 2024-04-03 21:08
This appears to happen on 3.10.1 for me as well. Ive removed all `modules` from my nuxt config to rule out module issues and the issue persists so not sure what is causing it.

**Comment by danielroe** [comment] 2024-04-04 08:13
If you can reproduce, please do open a new issue 🙏

**Comment by TheDutchCoder** [comment] 2024-04-17 20:22
We've just experienced this exact same issue, and the underlying issue was actually the fact that some of our imports in **TypeScript** required `.js` extensions (we have mixed TS/JS in our project), otherwise the resolver would create paths like `C:/foo/bar` instead of `file://C:/foo/bar.mjs` in the `.nuxt` output.

I hope this can help others that run into this nearly undebuggable issue.

cc @danielroe

**Comment by danielroe** [comment] 2024-04-17 20:50
@TheDutchCoder Was this an issue in your code or in Nuxt?

**Comment by TheDutchCoder** [comment] 2024-04-17 21:03
> @TheDutchCoder Was this an issue in your code or in Nuxt?

I would say "Nuxt", but in quotes because it seems to be an underlying Node problem.
I've reported issues with mixed TS/JS before and this seems to fall under that (though Windows only).

So to illustrate, this will fail:
```ts
// A .ts file
import { foo } from ~/lib/constants` // JS file (fails)
import { bar } from ~/composables/useThing` // TS file (works)
```

This works:
```ts
// A .ts file
import { foo } from ~/lib/constants.js` // JS file (works)
import { bar } from ~/composables/useThing` // TS file (works)
```

**Comment by TheDutchCoder** [comment] 2024-04-22 14:26
@danielroe Do you want me to open a new issue for this, or can we re-open this issue?

I just verified that the problem _also_ occurs when importing any `/foo/index.js` file implicitly with `import { bla } from '/foo'` from a JavaScript file, so it doesn't seem to be limited to importing from a TS file, but just generally directory imports that resolve to index files.

My best guess is that the TS/JS mix plays a role in this, and there's a resolver issue for Windows specifically.

**Comment by danielroe** [comment] 2024-04-22 18:15
And this doesn't occur with nitro alone?

If you _can_ reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), we should raise it [there](https://github.com/unjs/nitro/issues/new/choose).

Otherwise I'll open it here.

**Comment by TheDutchCoder** [comment] 2024-04-22 21:09
Unfortunately I can't help make a repro, since I don't use Windows.
I can ask my colleague if he could find the time to repro it.

**Comment by nicky1038** [comment] 2024-07-22 22:10
Hi everyone!

I've managed to reproduce the issue in a blank project with nuxt 3.12, the only thing needed to be done is to put this option into the nuxt config object.

```typescript
alias: {
    vue: path.resolve(__dirname, './node_modules/vue'),
}
```

This option can look strange, but it still should work without errors.

**Comment by KoishiVI2035** [comment] 2024-08-15 08:19
hi everyone  I have got same issue. when i "pnpm dev"
"scripts": {
    "mysql": "npx prisma studio",
    "db_pull": "npx prisma db pull",
    "dev": "npx prisma generate && nuxt dev --dotenv .env.test",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "build": "nuxt build --dotenv .env.test",
    "build:test": "nuxt build --dotenv .env.test",
    "build:pre": "nuxt build --dotenv .env.pre",
    "build:prod": "nuxt build --dotenv .env.prod",
    "postinstall": "nuxt prepare",
    "test": "pnpm install && npx prisma generate && pnpm run build:test",
    "pre": "pnpm install && npx prisma generate && pnpm run build:pre",
    "prod": "pnpm install && npx prisma generate && pnpm run build:prod"
  },
  "dependencies": {
    "@alicloud/dysmsapi20170525": "^2.0.24",
    "@alicloud/openapi-client": "^0.4.8",
    "@mdi/font": "^7.4.47",
    "@nuxtjs/tailwindcss": "^6.11.4",
    "@prisma/client": "^4.11.0",
    "@splidejs/vue-splide": "^0.6.12",
    "axios": "^1.6.8",
    "cheerio": "1.0.0-rc.12",
    "flag-icon-css": "^4.1.7",
    "form-data": "^4.0.0",
    "jsonwebtoken": "^9.0.2",
    "node-schedule": "^2.1.1",
    "node-xlsx": "^0.24.0",
    "nodemailer": "^6.9.13",
    "nuxt": "^3.12.4",
    "nuxt-security": "2.0.0-rc.9",
    "postcss-loader": "^8.1.1",
    "qrcode.vue": "^3.4.1",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@types/node": "^20.11.30",
    "@types/node-schedule": "^2.1.7",
    "less": "^4.2.0",
    "nuxt-svgo": "^4.0.0",
    "postcss-custom-media": "^10.0.3",
    "prisma": "^4.11.0",
    "vite-plugin-vuetify": "^2.0.3",
    "vuetify": "^3.6.3"
  }
}
![image](https://github.com/user-attachments/assets/b1ff6ef3-31dd-4d6b-b2bb-e2d09929848b)

**Comment by Godofbrowser** [comment] 2024-08-27 11:46
Once I had this issue while I was working with WXT and weirdly, the following refactoring to not pass reference of context through setTimeout solved the issue (it might give you a clue too):

from:
```javascript
document.addEventListener('some-event', context => {
    mountApplication(context)
})

function mountApplication(context, retry = 5) {
    const node = document.querySelector('.my-element')
    if (!node) {
        setTimeout(() => mountApplication(context, retry - 1), 1000)
    }
    
    // some other logic here
    doSomethingWith(context)
}
```

to (as it seems the context is lost when executing after the timeout):
```javascript
document.addEventListener('some-event', context => {
    function mountApplication(retry = 5) {
        const node = document.querySelector('.my-element')
        if (!node) {
            setTimeout(() => mountApplication(retry - 1), 1000)
        }

        // some other logic here
        doSomethingWith(context)
    }

    mountApplication()
})
```

**Comment by ThibaultVlacich** [comment] 2024-11-06 07:42
I have this error now after migrating to Nuxt 3.14

**Comment by danielroe** [comment] 2024-11-06 11:19
if you can provide a reproduction, would you mind opening a new issue?

**Comment by ThibaultVlacich** [comment] 2024-11-06 15:37
> if you can provide a reproduction, would you mind opening a new issue?

I pinned the issue to come from nitro-application insights, I'll open an issue there

**Comment by mklueh** [comment] 2025-02-26 21:50
Running into this issue out of the sudden after the following upgrades

![Image](https://github.com/user-attachments/assets/7abc02d1-7851-4acf-bb7c-24907362bee8)

![Image](https://github.com/user-attachments/assets/434fd18a-cd97-4448-aa15-0376e49d394d)

![Image](https://github.com/user-attachments/assets/58464ed8-219f-425e-86b0-d7a8e32e490b)

Sorry for the pics, but not sure if there's an option to share diffs in plain text

Its a monorepo, so not everything is used.

Modules in use:

```
  modules: [
    "@unocss/nuxt",
    "@nuxt/content",
    "@vueuse/nuxt",
    "@nuxt/fonts",
    "@nuxt/image",
    "@nuxtjs/seo",
    "nuxt-umami"
  ],
```

**Comment by danielroe** [comment] 2025-02-27 09:16
@mklueh  see if you can boil it down into a minimal reproduction. it's probably an issue with one of those modules, but if it reproduces without any module, let me know and I'll reopen this issue

**Comment by mklueh** [comment] 2025-02-27 09:21
> @mklueh  see if you can boil it down into a minimal reproduction. it's probably an issue with one of those modules, but if it reproduces without any module, let me know and I'll reopen this issue 

Wouldn't it be possible to have more specific logs to at least identify the module? The cost of creating reproducers out of monorepos is often relatively high

**Comment by danielroe** [comment] 2025-02-27 13:59
this log isn't created by nuxt. it's node and it's a result of a difference between how node works on windows and other oses

**Comment by mklueh** [comment] 2025-02-27 17:19
> this log isn't created by nuxt. it's node and it's a result of a difference between how node works on windows and other oses

I see. Figured out after gradually upgrading the deps that it's unocss causing this issue

**Comment by xushnudbek20** [comment] 2025-04-09 11:36
I have same problem with `"@nuxt/icon": "^1.6.1",`
