### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/nuxt/dist/app/"

### ISSUE THREAD

**Issue by nethriis** [nuxt/nuxt#24795] opened 2023-12-17 09:28 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, css, modules, postcss
- Runtime Modules:  nuxt-icon@0.6.7, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.7.0
- Build Modules:    -
------------------------------

### Reproduction

I cannot reproduce

### Describe the bug

I'm working on a project with nuxt and I added a google oauth but when I implemented the refresh access token method on my server and i fetch it from nuxt my page indicates me a warning on all pages.
![Capture d'écran 2023-12-17 102704](https://github.com/nuxt/nuxt/assets/72009265/916a8e29-815c-488e-aab4-90f8c6cb52b8)

I've tried to make a nuxi cleanup but I still have the same warning

### Logs

```shell-script
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/nuxt/dist/app/"
```

**Comment by nethriis** [comment] 2023-12-17 09:34
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> More info

I can't

**Comment by robfuscator** [comment] 2023-12-22 11:03
This is probably not very helpful, but I get the same warnings. On the dev console I get it 16 times in a straight row. Can't reproduce in a new project. Will try to investigate.

**Comment by nethriis** [comment] 2023-12-22 11:33
> This is probably not very helpful, but I get the same warnings. On the dev console I get it 16 times in a straight row. Can't reproduce in a new project. Will try to investigate.

I noticed that it did that to me when I was tinkering in the dev console, I managed to remove these warnings by closing the tab and reopening another one.

**Comment by robfuscator** [comment] 2023-12-22 12:05
Oh, you're right. I've had the same browser tab open for quite a long time - closing and reopening the browser tab fixed it for me as well. Weird but I guess the issue can be closed then (?).

**Closed** 2023-12-22 12:19 UTC
Labels: 3.x, pending triage, needs reproduction
