### ISSUE TITLE
https://nuxt.com isn't working on firefox

### ISSUE THREAD

**Issue by existe-deja** [nuxt/nuxt#26946] opened 2024-04-25 14:58 UTC
### Environment

firefox 125.0.2 (64 bits) - ubuntu

### Reproduction

Go to [nuxt.com](https://nuxt.com) click on get stared

### Describe the bug

When I try to navigate I always get 500 error. For exemple on the get started page I have:

![Capture d’écran du 2024-04-25 16-52-41](https://github.com/nuxt/nuxt/assets/3015073/54f53b75-c1e5-4b91-bf96-5dd120927639)
It happens only on `/docs` pages and it's working fine on chrome.

### Additional context

It first happened couple of days ago. I thought it was a cache issue but even in privacy mode, the error occurs. I think you should see it in your error monitoring software. Please note it's working on chrome.

### Logs

```shell-script
404 GET https://nuxt.com/_nuxt/DjFr2qA8.js

Le chargement du module à l’adresse « https://nuxt.com/_nuxt/DjFr2qA8.js » a été bloqué en raison d’un type MIME interdit (« text/html »). introduction
TypeError: error loading dynamically imported module: https://nuxt.com/_nuxt/e5HDipEK.js C_yBCh_8.js:29:21487
    NuxtJS 19

[nuxt] error caught during app initialization Error: error loading dynamically imported module: https://nuxt.com/_nuxt/e5HDipEK.js
Caused by: TypeError: error loading dynamically imported module: https://nuxt.com/_nuxt/e5HDipEK.js
C_yBCh_8.js:23:26984

[nuxt] error caught during app initialization Error: error loading dynamically imported module: https://nuxt.com/_nuxt/e5HDipEK.js
Caused by: TypeError: error loading dynamically imported module: https://nuxt.com/_nuxt/e5HDipEK.js
C_yBCh_8.js:23:26984
```

**Comment by RomainMazB** [comment] 2024-04-25 15:21
Nuxt blog article page are broken too.

Like this one: https://nuxt.com/blog/looking-forward-2024

**Comment by manniL** [comment] 2024-04-25 16:01
Duplicate of https://github.com/nuxt/nuxt.com/issues/1569

**Closed by manniL** 2024-04-25 16:01 UTC
Labels: 3.x, pending triage
