### ISSUE TITLE
Nuxt3 - Transition appear Flag not working

### ISSUE THREAD

**Issue by rhernandog** [nuxt/nuxt#14715] opened 2022-08-26 04:47 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`
- Build Modules:    `-`

### Reproduction

**Repo**
https://github.com/rhernandog/nuxt3-transitions-issue

**Live Sample**
https://stackblitz.com/edit/nuxt-starter-d2z5mn

### Describe the bug

As mentioned in discussion #5717  there is an issue with the appear flag in the using transition, transition group and page transition. In the live sample you'll see that the first load the page doesn't appear. If you navigate you'll see the fade out/in transition between pages working as expected. In the users page you should see an animation for a list of items that never happens, but if you make a change in the file and save it, the animation will happen as expected after the hot reload.

As reported in the discussion I can confirm that all these animations work as expected in a Vue3 project.

**Comment by linspw** [comment] 2023-03-24 18:23
It still doesn't work 😢

**Comment by jaegar-wolf** [comment] 2023-04-03 20:08
Any news on this issue ?

**Comment by danielroe** [comment] 2023-04-03 20:16
This is an upstream issue in vue itself, as linked above. Please check that issue for updates.

**Comment by danielroe** [comment] 2023-10-25 00:50
This should now be resolved in vue 3.3.7.

**Comment by SvenWesterlaken** [comment] 2023-11-10 03:16
Unfortunately, after upgrading Nuxt to `3.8.1` (which uses vue `3.3.8`) it still seems to be an issue as I don't get a transition on the initial load using hooks or classes ([following the GSAP example on Stackblitz](https://stackblitz.com/edit/nuxt-starter-bthjlg?file=helpers%2FtransitionConfig.js)):

_Code snippet of transition configuration that is used in `definePageMeta()` on all pages:_
```ts
import { useTransitionComposable } from "../composables/useTransitionComposable";

const { toggleTransitionComplete } = useTransitionComposable();

export const pageTransitionConfig = {
  // name: 'general-transition',
  mode: 'out-in' as any,
  appear: true,
  onAppear(el: Element) {
    console.log('on appear')
    useGsap.set('.loading-screen', { top: -300 });
  },
  onBeforeEnter(el: Element) {
    console.log('on before enter');
    console.log(el);
    useGsap.set('.loading-screen', { top: -300 });
  },
  onEnter: (el: Element, done: () => void) => {
    const tl = useGsap.timeline({
      paused: true,
      onComplete: () => {
        toggleTransitionComplete(true)
        done()
      }
    });

    tl.to(".loading-screen", {
        duration: 0.65,
        top: window.innerHeight,
        ease: "expo.inOut",
        delay: 0.1,
    });

    tl.play();
  },
  onEnterCancelled(el: Element) {
    useGsap.set('loading-screen', { top: window.innerHeight });
  },
  onLeave(el: Element, done: () => void) {
    toggleTransitionComplete(false);

    const tl = useGsap.timeline({
      paused: true,
      onComplete: done 
    })

    tl.to(".loading-screen", {
      duration: 0.45,
      top: -300,
      ease: "power2.out",
    });

    tl.play();
  }
}

export default pageTransitionConfig;
```

Neither `on appear` nor `on before enter` appears in the console. Also, the position is not set. However, it does run on navigating between routes. Furthermore, I tried to get it to work by using hooks in `nuxt.config.ts` and adding the config to the transition property on the `NuxtPage` component. Unfortunately, both don't seem to show a difference; still no initial animation or console log.

Maybe as it's resolved in vue it now has something to do with Nuxt?

**Comment by SvenWesterlaken** [comment] 2023-11-14 19:32
Any chance of this being reopened for that matter, or should I make a new issue @danielroe?

**Comment by danielroe** [comment] 2023-11-15 08:57
In fact it does not seem to be resolved in Vue either, using the reproduction linked in https://github.com/vuejs/core/issues/6951.

Would you be willing to investigate and open a new issue in https://github.com/vuejs/core?

**Comment by SvenWesterlaken** [comment] 2023-11-15 17:08
Thanks for the notice @danielroe, will see if I can contribute to the issue within vue.

**Comment by SvenWesterlaken** [comment] 2023-11-16 22:36
For anyone visiting this issue before it gets fixed: this is a 'hacky' workaround that works for me:

_Make sure you set the 'from' state in your CSS to not have a delay_:

```ts
// plugins/initial_load.ts
const { toggleTransitionComplete } = useTransitionComposable();

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook('app:mounted', () => {
    const tl = useGsap.timeline({
      paused: true,
      onComplete: () => {
        toggleTransitionComplete(true)
      }
    });

    tl.to(".loading-screen", {
        duration: 2,
        top: window.innerHeight,
        ease: "expo.inOut",
    });

    tl.play();
  })
});
```

```scss
.loading-screen {
  position: relative;
  padding-left: 0;
  padding-right: 0;
  padding-top: 0;
  width: 100%;
  height: calc(100% + 300px);
  display: flex;
  flex-direction: column;
  // top: 100%; <-- this was before and is the state when the page is loaded (to reveal the page)
  top: -300px; // <-- this is the state in between pages

// [...]
}
```

**Comment by Lucas-Gruber** [comment] 2024-03-22 21:03
Any news about this issue? It doesn't work for me but the vue-issue says it should be solved.

**Comment by danielroe** [comment] 2024-03-25 10:12
Would you see if it is possible to reproduce with latest Vue 3 SSR?

https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter

And if so, raise again at https://github.com/vuejs/core/issues/new/choose 🙏

**Comment by ultimateshadsform** [comment] 2024-03-27 21:45
I just needed to wrap my <Transition name="fade" appear> with <ClientOnly> and now the animation is working for me.

**Comment by danielroe** [comment] 2024-03-28 18:09
I think that's not a solution - the issue is triggered by `<Transition>` with something that is SSR-rendered.

**Comment by ultimateshadsform** [comment] 2024-03-28 19:19
> I think that's not a solution - the bug is triggered by `<Transition>` with something that is SSR-rendered, and it sounds like it is still present in Vue upstream. If so, a reproduction and issue in vuejs/core would be very helpful. 🙏

I have created a brand new SSR app with vite with the vite -> others -> create-vite-extra and then picked the vue ssr option with typescript. So far I have page transitions working without any effort so I don't really know what's the issue is.

Here is [example](https://stackblitz.com/edit/vitejs-vite-uasqac?file=src%2FApp.vue) with the vite option

**Comment by danielroe** [comment] 2024-03-28 20:08
would you try using this starter instead?

https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter

The issue seems to be caused by the combination of Suspense and Transition.

**Comment by ultimateshadsform** [comment] 2024-03-28 20:37
> would you try using this starter instead?
> 
> https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter
> 
> The issue seems to be caused by the combination of Suspense and Transition.

Yes that seems to be the case?

[Example](https://stackblitz.com/edit/github-nfvccx?file=src%2FApp.vue)

If you remove the suspense the animation is working.

**Comment by ultimateshadsform** [comment] 2024-03-28 20:47
It's probably because the transition is inside the suspense but it needs to be outside?
[combining-with-other-components](https://vuejs.org/guide/built-ins/suspense.html#combining-with-other-components)

**Comment by danielroe** [comment] 2024-06-17 15:27
This appears to be working fine. It doesn't seem to in the reproduction because the parent element has `opacity-0` set.

**Closed by danielroe** 2024-06-17 15:27 UTC
Labels: 3.x, bug, upstream, upstream-bug

**Comment by DanyloIvashev** [comment] 2025-05-27 14:22
@danielroe still doesnt work properly, any updates?
