### ISSUE TITLE
3.14.0 Rollup errors, preventing build or run

### ISSUE THREAD

**Issue by tratteo** [nuxt/nuxt#29804] opened 2024-11-05 21:37 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  bun@1.1.27
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.2, @nuxtjs/google-fonts@3.2.0, @nuxt/icon@1.6.1, @vueuse/nuxt@10.11.1, @pinia/nuxt@0.5.5, nuxt-multi-cache@3.3.3, nuxt-security@2.0.0, @nuxtjs/seo@2.0.0-rc.23, @nuxtjs/robots@4.1.11, @nuxt/content@2.13.4, @nuxt/image@1.8.1, @nuxtjs/device@3.2.4
- Build Modules:    -
------------------------------

### Reproduction

A simple project using Nuxt ^3.13.2 updated to ^3.14.0 with bun update --save

### Describe the bug

Project worked perfectly. Updated **only** Nuxt to ^3.14.0, getting lot of Rollup errors that are preventing the build.
```
RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/unstorage/dist/index.mjs from node_modules/nitropack/dist/runtime/internal/storage.mjs]
```
And others related to external modules (that never gave these type of errors)
```
ERROR  RollupError: virtual:#nitro-internal-virtual/server-handlers-meta (29:7): Identifier "_BMjsRhMeta" has already been declared                                                                                                                                                                                   nitro 22:26:03  


27: import _rIuTp4Meta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-og-image/dist/runtime...
28: import _BMjsRhMeta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-og-image/dist/runtime...
29: import _BMjsRhMeta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-og-image/dist/runtime...
           ^
30: import _pr69QkMeta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-schema-org/dist/runti...
31: import _bHLnh6Meta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-seo-experiments/dist/...
```

### Logs

ERROR  RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/unstorage/dist/index.mjs from node_modules/nitropack/dist/runtime/internal/storage.mjs]

**Comment by danielroe** [comment] 2024-11-05 23:05
this was resolved in https://github.com/nuxt/nuxt/pull/29780 and will be included in the next patch release (expect it shortly!)

**Closed by danielroe** 2024-11-05 23:05 UTC
Labels: pending triage, nitro, possible regression

**Comment by BorisKamp** [comment] 2024-11-06 07:55
> this was resolved in [#29780](https://github.com/nuxt/nuxt/pull/29780) and will be included in the next patch release (expect it shortly!)

Great! Are we talking hours or days here?

**Comment by danielroe** [comment] 2024-11-06 09:42
hours

**Comment by zangetsu02** [comment] 2024-11-06 14:36
any updates?

**Comment by danielroe** [comment] 2024-11-06 20:12
that is a different issue and likely related to adding the same nitro handler twice - it's likely an issue with your configuration or dependencies - feel free to open a new issue with a minimal reproduction

**Comment by jsayer101** [comment] 2024-11-06 20:33
Hi, updated from 3.13.2 to 3.14.159 and got the same issue, has the feen already been released ?

**Comment by rpandyaescribe** [comment] 2024-11-06 22:23
Same for me after upgrading from 3.7.4 to 3.14.159. I will try ugrading progressively

**Comment by jontybrook** [comment] 2024-11-07 01:05
Ditto seeing rollup errors in 3.14.159

` RollupError: virtual:#nitro-internal-virtual/server-handlers-meta (83:7): Identifier "_e32yxeMeta" has already been declared`

**Comment by knirirr** [comment] 2024-11-07 08:43
I am still having a problem as well:

```
Nuxt 3.14.159 with Nitro 2.10.3       
...                                                                           
[nitro 08:42:15]  ERROR  RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/defu/dist/defu.mjs from node_modules/nitropack/dist/runtime/internal/route-rules.mjs]
```

**Comment by liamb0t** [comment] 2024-11-07 08:54
Same here

```
[nitro 08:50:42]  ERROR  RollupError: [plugin impound] This module cannot be imported in server runtime. [importing ../../node_modules/nuxt/node_modules/nitropack/node_modules/crossws/dist/adapters/node.mjs from ../../node_modules/nuxt/node_modules/nitropack/dist/presets/_nitro/runtime/nitro-dev.mjs]
```

**Comment by thorge** [comment] 2024-11-07 09:06
Here as well

```bash
RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/crossws/dist/adapters/node.mjs from node_modules/nitropack/dist/presets/_nitro/runtime/nitro-dev.mjs]
```

**Comment by jillshenshen** [comment] 2024-11-07 09:32
Same here Nuxt 3.14.159 with Nitro 2.10.3
`RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/ufo/dist/index.mjs from node_modules/nitropack/dist/runtime/internal/route-rules.mjs]`

**Comment by erichuxohl** [comment] 2024-11-07 12:25
@danielroe here is an example:

A simple catch all file in /server/routes/api/[...].js (I do not put my url in here)

`import { useLogger } from '@nuxt/kit'

export default defineEventHandler((event) => {
    const logger = useLogger()
    return $fetch(url, {
        onRequest: ({ request, options }) => {
            logger.info('[fetch request]', request, options)
        },
        onRequestError: ({ error, request, options }) => {
            logger.error('[fetch request error]', error, request, options)
        },
        onResponse: ({ response, request, options }) => {
            logger.info('[fetch response]', response, request, options)
        },
        onResponseError: ({ error, response, request, options }) => {
            logger.error('[fetch response error]', error, response, request, options)
        }
    })
})`

 ERROR  RollupError: [plugin impound] This module cannot be imported in server runtime. [importing @nuxt/kit from server/routes/api/[...].js]

**Comment by erichuxohl** [comment] 2024-11-07 12:27
Okay, thanks!

**Comment by thorge** [comment] 2024-11-07 15:10
I couldn't reproduce the error in a minimal example, so I suspected the issue might be with my local setup. Initially, I had simply updated the `package.json` to upgrade Nuxt and the Vite builder plugin. However, after running `npx nuxi@latest upgrade --force`, everything seems to be working as expected. 

Lesson learned: always follow the documentation when upgrading! The documentation also notes that this command refreshes your lockfile, ensuring that updates from other dependencies in the Nuxt ecosystem are pulled in properly.

**Comment by knirirr** [comment] 2024-11-07 16:20
Thanks, @thorge.
I tried the suggested upgrade and had no luck; the same error persists.
Unfortunately I can't see from it what part of the code I'm having to maintain might be causing it, so if anyone has any suggestions of how to investigate it then they would be most welcome.

**Comment by BorisKamp** [comment] 2024-11-07 17:06
> I couldn't reproduce the error in a minimal example, so I suspected the issue might be with my local setup. Initially, I had simply updated the `package.json` (running `npm install` afterwards) to upgrade Nuxt and the Vite builder plugin. However, after running `npx nuxi@latest upgrade --force`, everything seems to be working as expected.
> 
> Lesson learned: always follow the documentation when upgrading! The documentation also notes that this command refreshes your lockfile, ensuring that updates from other dependencies in the Nuxt ecosystem are pulled in properly.

works for me, thanks! I always used `ncu- u -t minor` and `npm i` afterwards. Seems I need to run `npx nuxi upgrade -f` first, to upgrade Nuxt and my `ncu` command to update other dependencies afterwards...

**Comment by pmcp** [comment] 2024-11-08 10:43
I'm getting the same issue, if it is of any help in looking into this, if I add

```
  nitro: {
    experimental: {
      // Enable Server API documentation within NuxtHub
      openAPI: true
    }
  },
```


to nuxt.config, it gives me the error

```
RollupError: virtual:#nitro-internal-virtual/server-handlers-meta (32:7): Identifier "_vtEFC3Meta" has already been declared

30: import _P2WQbkMeta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxthub+core@0.8.6_ioredis@5.4.1_magica...
31: import _vtEFC3Meta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
32: import _vtEFC3Meta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
           ^
33: import _vtEFC3Meta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
34: import _qfWoImMeta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...

```

This experimental feature is included in the nuxthub starter, it seems to only break if **nuxt content** is added.

Combining Nuxt Content and openAPI: true seems to be the issue (for me).

**Comment by pmcp** [comment] 2024-11-08 13:17
Done ([https://github.com/nuxt/content/issues/2839](url))

**Comment by avlisodraude** [comment] 2024-11-08 14:45
Having similar issue when updating to nuxt 3.14.159 with Nitro 2.10.4
RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/db0/dist/index.mjs from node_modules/nitropack/dist/runtime/internal/database.mjs]

**Comment by hrdyjan1** [comment] 2024-11-09 11:26
I faced a similar issue where using **Yarn** as the package manager caused a Rollup error, but everything worked fine with **npm**. The problem is likely due to how Yarn and npm handle dependencies differently. Yarn might have installed a conflicting or incompatible package version, causing the error during the build.

To fix it, I stuck with npm, as it resolved the dependencies correctly without any issues. You could try clearing the cache with `yarn cache clean` or regenerate the lockfiles by deleting `yarn.lock` and `package-lock.json`, but using npm, for now, is a simple workaround.

**Comment by tratteo** [comment] 2024-11-09 16:29
> I'm getting the same issue, if it is of any help in looking into this, if I add
> 
> ```
>   nitro: {
>     experimental: {
>       // Enable Server API documentation within NuxtHub
>       openAPI: true
>     }
>   },
> ```
> 
> to nuxt.config, it gives me the error
> 
> ```
> RollupError: virtual:#nitro-internal-virtual/server-handlers-meta (32:7): Identifier "_vtEFC3Meta" has already been declared
> 
> 30: import _P2WQbkMeta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxthub+core@0.8.6_ioredis@5.4.1_magica...
> 31: import _vtEFC3Meta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
> 32: import _vtEFC3Meta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
>            ^
> 33: import _vtEFC3Meta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
> 34: import _qfWoImMeta from "/Users/pmcp/Documents/GitHub/kdm/node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magic...
> ```
> 
> This experimental feature is included in the nuxthub starter, it seems to only break if **nuxt content** is added.
> 
> Combining Nuxt Content and openAPI: true seems to be the issue (for me).

Same here, setting the `openAPI` to `false` resolves the issue.

**Comment by Iheanemegregory-9** [comment] 2024-11-09 19:41
> I couldn't reproduce the error in a minimal example, so I suspected the issue might be with my local setup. Initially, I had simply updated the `package.json` (running `npm install` afterwards) to upgrade Nuxt and the Vite builder plugin. However, after running `npx nuxi@latest upgrade --force`, everything seems to be working as expected.
> 
> Lesson learned: always follow the documentation when upgrading! The documentation also notes that this command refreshes your lockfile, ensuring that updates from other dependencies in the Nuxt ecosystem are pulled in properly.

thanks for the suggestion.

This worked for me

**Comment by husayt** [comment] 2024-11-13 20:18
> Same here, setting the `openAPI` to `false` resolves the issue.

Same here `openAPI=true` breaks latest 3.14.x for me.

**Comment by TribeWeb** [comment] 2024-11-15 11:13
> I updated Nuxt to version `3.14.159` but I am still getting rollup errors:
> 
> ```
> ERROR  RollupError: virtual:#nitro-internal-virtual/server-handlers-meta (29:7): Identifier "_BMjsRhMeta" has already been declared                                                                                                                                                                                   nitro 19:44:30  
> 
> 
> 27: import _rIuTp4Meta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-og-image/dist/runtime...
> 28: import _BMjsRhMeta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-og-image/dist/runtime...
> 29: import _BMjsRhMeta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-og-image/dist/runtime...
>            ^
> 30: import _pr69QkMeta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-schema-org/dist/runti...
> 31: import _bHLnh6Meta from "C:/Users/matteo/Documents/Progetti/Dev/saas/depthlog/node_modules/nuxt-seo-experiments/dist/...
> ```

I had the same error on upgrading and setting `openAPI` to `false` resolves the issue.

**Comment by rainer85ah** [comment] 2024-12-02 01:53
I had the same issue and thanks to comments in this issue I realize it was a wrong import that my IDE webstorm suggest it as it didn't recognize it (it was in red)  useNuxtApp() on the server side code. So by just removing the import below everything started it working again.

`
import { useNuxtApp } from "nuxt/app"
`

**Comment by johnnyicon** [comment] 2025-02-19 19:24
I'm getting this error with the latest nuxt.

```
Node.js v18.20.6
ℹ Cleaning up generated Nuxt files and caches...                                                                                                                                                                                                                                                   nuxi 2:21:02 PM
ℹ Upgraded Nuxt version: 3.15.4                                                                                                                                                                                                                                                                    nuxi 2:21:02 PM
✔ You're already using the latest version of Nuxt. 
```
