### ISSUE TITLE
useAsyncData in middleware gives warning to use $fetch when changing route to the same pageComponent

### ISSUE THREAD

**Issue by MarijnFK** [nuxt/nuxt#25661] opened 2024-02-06 11:26 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-haznex?file=middleware%2Fsingle.ts

### Describe the bug

Not sure if this is a bug or something i use incorrectly.

we use a middleware to fetch data based on a dynamic route (slug)
this gives a warning to use $fetch, because the component is already mounted: 

[nuxt] [useAsyncData] Component is already mounted, please use $fetch instead. See https://nuxt.com/docs/getting-started/data-fetching

### Additional context

We use a middleware so we have access to the page data before entering the page.
This way we can get the localized slugs in the middleware and set them on the $i18n module like so: 
to.meta.nuxtI18n = localizedSlugs;

**Comment by danielroe** [comment] 2024-02-06 12:23
Is there a reason you don't want to use `$fetch`?

**Comment by MarijnFK** [comment] 2024-02-06 12:31
we are using @nuxtjs/strapi to fetch the data from strapi, and according to their specifications we should use useAsyncData to enable SSR. We suppose we cannot use $fetch in combination with @nuxtjs/strapi

See this documentation: https://strapi.nuxtjs.org/advanced#async-data

**Comment by c-schwan** [comment] 2024-02-06 21:56
Just use findOne<Restaurant> without useAsyncData in the middleware

**Comment by MarijnFK** [comment] 2024-02-07 09:52
does that work with SSR and payload extraction?

**Comment by MarijnFK** [comment] 2024-02-07 12:19
And the new shared async data cannot be used this way: https://nuxt.com/blog/v3-10?ref=dailydev

**Comment by GreenBabyBorn** [comment] 2024-02-08 15:03
I have the same issue with middleware in lucia-auth (https://github.com/lucia-auth/examples/blob/main/nuxt/username-and-password/middleware/auth.global.ts)

**Comment by kouts** [comment] 2024-02-11 07:00
Confirming I have the same issue with lucia-auth middleware.

**Comment by BBoehm** [comment] 2024-03-09 00:05
> Is there a reason you don't want to use `$fetch`?

@danielroe 
According to the [dollarfetch documentation](https://nuxt.com/docs/api/utils/dollarfetch), that would cause the data to be loaded twice - unless it works different in the middleware?

Also, the warning states, that the component would be already mounted - while the middleware should be independant of components? Is that just a confusing warning message then?

**Comment by danielroe** [comment] 2024-03-15 20:32
@BBoehm It really depends. But yes, every time you call `$fetch` the request will be made fresh. You could use useState to avoid that. Or directly access and manipulate `nuxtApp.payload`. I wouldn't call `useAsyncData` on each route navigation though... That _will_ perform additional requests every time you change page, even though it won't do so on initial load.

**Comment by Frallen** [comment] 2024-04-07 11:31
> nuxtApp.payload

To prevent repeated requests, you can use nuxt.payload or useState. 

In my case, I use pinia, which stores the data. To prevent a repeat request, I check if my storage is full and if the ID matches. If the storage is empty, then I make a request, if the id does not match, then I make a request (if it matches, then there will be no request).  The same can be done using user State.

I created a discussion about [this](https://github.com/nuxt/nuxt/discussions/26493) 

``` TS
import type { StateTree } from "pinia";

export default defineNuxtRouteMiddleware(async (to, from) => {
    const {payload}=useNuxtApp()
    const { Conversation } = storeToRefs(useChat());
    const { getDialog } = useChat();
    let state = payload.pinia as Record<string, StateTree>;
// inital load, check object or check id
    if (
        Object.keys(state.chat.Conversation).length < 1 ||
        to.params.id !== state.chat.Conversation.id.toString()
    ) {
        await getDialog(<string>to.params.slug, <string>to.params.id);
    }

//404
    if (Object.keys(Conversation.value).length < 1) {
        return abortNavigation();
    }
});

```

**Comment by kouts** [comment] 2024-04-07 13:17
> Confirming that I have the same issue with lucia-auth middleware.

I managed to fix it using `useRequestFetch()` instead.
https://github.com/nuxt/nuxt/issues/23423

**Comment by johankrijt** [comment] 2024-07-18 13:08
We are experiencing the same warning: `Component is already mounted, please use $fetch instead`. In our project we are using global route middleware to check some main attributes and user data (both fetched from our internal api using `useFetch`). There is no worry for additional requests as this should be caught by the `getCachedData` option, unless you intentionally change the usage like we do (custom useFetch adding ttl and force reload to the getCachedData function).

I couldn't find any reason reading through this issue why `useFetch` shouldn't or can't be used in route middleware (it even states it can be used in the documentation: 'meant to be called directly in a setup function, plugin, or route middleware'), so in my opinion the warning should not include the component instance check it does right now.

**Comment by ColonelBundy** [comment] 2024-08-09 18:42
To me, the warning in `useAsyncData` targets a specific use case. Our use case is not about fetching data that can be replaced using `$fetch`. According to the recommendations, `useAsyncData` should be used when `useState` cannot be used, which is precisely the case we're facing. While you ccertainly can work around the async issue of `useState` the boilerplate for each instance of this is quite large, which `useAsyncData` handles beautifully for you.
The warning is valid for situations where `$fetch` can be used, this does not apply to our case and works as intended.

Since the `$fetch` scenario is probably the most common one, either a slight revision to better detect this issue is in order, or an option to turn off this warning should be provided, as it can be quite cumbersome.

**Comment by danielroe** [comment] 2024-09-05 07:59
this was resolved in https://github.com/nuxt/nuxt/pull/28604.

**Closed by danielroe** 2024-09-05 07:59 UTC
Labels: pending triage
