### ISSUE TITLE
Css inline classes in template are not applied

### ISSUE THREAD

**Issue by sjokara** [nuxt/nuxt#18575] opened 2023-01-27 13:05 UTC
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.2`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `vite`, `components`, `modules`, `image`, `css`, `build`, `app`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.3.0`, `@nuxt/image-edge@1.0.0-27913696.5d122a3`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

The application runs okay locally and CSS is fine. 
After I run ```yarn build``` and the app is bundled for production, inline css in the template is not applied. 

**nuxt.config.js**
```
/* eslint-disable @typescript-eslint/ban-ts-comment */
import eslintPlugin from 'vite-plugin-eslint'
import { config } from './config'

const appEnv = process.env.ENV || 'development'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default {
  vite: {
    // @ts-ignore,
    plugins: [eslintPlugin()]
  },
  components: {
    global: true,
    dirs: ['~/components/atoms', '~/components/molecules', '~/components/organisms', '~/components/storyblok']
  },
  modules: ['@nuxtjs/tailwindcss', '@nuxt/image-edge', '@nuxtjs/robots'],
  image: {
    provider: 'storyblok',
    storyblok: { baseURL: 'https://a.storyblok.com' },
    screens: {
      xs: 375,
      sm: 576,
      md: 768,
      lg: 992,
      xl: 1201,
      xxl: 1401,
      hd: 1920
    }
  },
  css: ['~/assets/css/main.scss', '~/assets/fonts/redHatText.css', '~/assets/fonts/redHatDisplay.css'],
  build: {
    loaders: {
      scss: {
        implementation: require('sass')
      },
      postcss: {
        plugins: {
          tailwindcss: {},
          autoprefixer: {}
        }
      }
    }
  },
  app: {
    head: {
      title: 'BeeIT',
      meta: [{ name: 'viewport', content: 'width=device-width, initial-scale=1' }],
      link: [{ rel: 'shortcut icon', type: 'image/png', href: 'https://a.storyblok.com/f/155755/32x32/d6965832e1/favicon-32x32.png' }],
      htmlAttrs: {
        lang: 'en'
      }
    }
  },
  runtimeConfig: {
    server: config[appEnv].server,
    public: config[appEnv].client
  }
}

```

**vite.config.js**

```
import { defineConfig } from 'vite'

export default defineConfig({
  appType: 'custom',
  server: { middlewareMode: 'ssr' },
  build: {
    ssr: true,
    manifest: true,
    copyPublicDir: true,
    cssCodeSplit: true,
    sourcemap: true,
    minify: false
  }
})

```

**nitro.config.js**
```
import { defineNitroConfig } from 'nitropack'

export default defineNitroConfig({
  preset: 'aws-lambda',
  serveStatic: true
})

```

**tailwind.config.js - content part**

```
content: ['./components/**/*.{js,vue,ts}', './layouts/**/*.vue', './pages/**/*.vue', './plugins/**/*.{js,ts}'],
```

### Describe the bug

The application runs okay locally and CSS is fine. 
After I run ```yarn build``` and the app is bundled for production, inline css in the template is not applied. 
CSS that is in .scss files and in <style> is applied.

![Screenshot from 2023-01-27 14-02-51](https://user-images.githubusercontent.com/88772060/215093446-06b6110e-8f5e-45bf-a4b3-910916cbb532.png)

Also this error is 
![Screenshot from 2023-01-27 14-04-44](https://user-images.githubusercontent.com/88772060/215093848-e66e53d9-a523-4560-a631-6a6cb092e9eb.png)
displayed in console.

**Comment by Baroshem** [comment] 2023-01-27 14:42
Hey,

Could you create a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) on stackblitz preferably? I will take a look at it as it seems quite interesting :)

**Comment by sjokara** [comment] 2023-01-27 15:58
https://stackblitz.com/edit/github-cdnwth?file=app.vue , here is the reproduction. I imported main.scss into app.vue and inline css seems to work, but I am still getting console errors.

![Screenshot from 2023-01-27 16-56-45](https://user-images.githubusercontent.com/88772060/215130603-75dc88e4-bb09-4e7e-90aa-56d6c2404a5d.png)

**Comment by Baroshem** [comment] 2023-01-28 12:30
Hey, 

I checked the stackblitz repro but it does not seem to be related to the bug description (your screenshot does not match the stackblitz, I cannot reproduce it basically). I can reproduce an error in the console and I also managed to find a fix for that.

In your style just use `~` like following:

```vue
<style lang="scss">
@import '~/assets/css/main.scss';
</style>
```

**Comment by Baroshem** [comment] 2023-02-01 17:43
@sjokara 

I am closing the issue as the answer/fix was given and there is no further details. If the problem will occur, please reopen the issue :)

**Closed by Baroshem** 2023-02-01 17:43 UTC
Labels: 3.x, pending triage, needs reproduction
