### ISSUE TITLE
Set redirects when trailingSlash:true

### ISSUE THREAD

**Issue by Jesus82** [nuxt/nuxt#8472] opened 2020-12-11 07:57 UTC
### Is your feature request related to a problem? Please describe.

If I set `trailingSlash:true` in `mypage/` , that also means that `mypage` will not exist. It really frequent when somebody links to your page not to care much about trailing slashes. So if somebody links to `mypage` that page will not exist (and that really harms SEO). 

### Describe the solution you'd like

An option in `nuxt.config.js` so that you could set `trailingSlashRedirects:true` Setting that will automatically redirect from `mypage` to `mypage/` (It would be awesome to also be able to set which type of redirects, like for example `redirectType: 301`

### Describe alternatives you've considered

While it is easy to set some redirects for simple cases, when params comes in, things get a bit cumbersome (see [https://stackoverflow.com/questions/54346345/nuxt-js-force-trailing-slash-at-the-end-of-all-urls](https://stackoverflow.com/questions/54346345/nuxt-js-force-trailing-slash-at-the-end-of-all-urls)).

**Comment by pi0** [comment] 2020-12-11 10:14
We might introduce `trailingSlash: 'redirect'` alongside with #8423. For reference [here](https://github.com/nuxt/nuxt.js/pull/8423/files#diff-6e7f7fbcfacad474bd89e1880e10c724a46a90eec7b1949d7fa2176533b65fdfR31) is current behavior with `true`

**Comment by manniL** [comment] 2020-12-21 17:25
>     * We might introduce `trailingSlash: 'redirect'` alongside with #8423. For reference [here](https://github.com/nuxt/nuxt.js/pull/8423/files#diff-6e7f7fbcfacad474bd89e1880e10c724a46a90eec7b1949d7fa2176533b65fdfR31) is current behavior with `true`

I like the idea a lot! Though we'd need to have this as a separate option to enable both 'abc' -> 'abc/' and vice-versa.

**Comment by adamdehaven** [comment] 2020-12-28 20:48
So it looks like #8423 was already merged and does not address this issue. Any plans to resolve this separately? If you set `trailingSlash: true` I would think the expected behavior would be to support a missing trailing slash as the OP suggested:

Example: `/about => 301 => /about/`

**Comment by Jesus82** [comment] 2021-01-03 15:10
> So it looks like #8423 was already merged and does not address this issue. Any plans to resolve this separately? If you set `trailingSlash: true` I would think the expected behavior would be to support a missing trailing slash as the OP suggested:
> 
> Example: `/about => 301 => /about/`

In my example what I would expect is:
trailingSlash:true && trailingSlashRedirect:true
Example:  `/about => 301 => /about/`

trailingSlash:false && trailingSlashRedirect:true
Example:  `/about/ => 301 => /about`

**Comment by dotnetshadow** [comment] 2022-03-03 10:29
Any update on this feature? It's needed especially if someone types of the address directly

**Comment by danielroe** [comment] 2023-02-14 11:23
This is our latest plan: https://github.com/nuxt/nuxt/issues/15462#issuecomment-1418944206. We can track this in the linked issues.

**Closed by danielroe** 2023-02-14 11:23 UTC
Labels: enhancement, 2.x
