### ISSUE TITLE
Unexpected Token Error After Upgrading to Nuxt 3.15

### ISSUE THREAD

**Issue by hasan-ozbey** [nuxt/nuxt#30410] opened 2024-12-29 19:36 UTC
### Environment

Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v23.3.0
- Nuxt Version:     3.15.0
- CLI Version:      3.17.2
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.14.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/fonts@0.9.2, @nuxt/ui@2.20.0, @vueuse/nuxt@11.3.0, dayjs-nuxt@2.1.11, @nuxt/image@1.8.1, @nuxt/content@2.13.4, nuxt-og-image@3.1.1, nuxt-svgo@4.0.9, @nuxtjs/i18n@9.0.0-rc.2, nuxt-zod-i18n@1.11.2, @pinia/nuxt@0.9.0, @pinia/colada-nuxt@0.0.4, nuxt-auth-sanctum@0.5.2
- Build Modules:    -
------------------------------

### Reproduction

I currently have no time for creating reproduction.

### Describe the bug

After upgrading Nuxt from version `3.14.1592` to `3.15.0`, the application fails to start, throwing an `Unexpected token ';'` error. The error occurs during the build process and appears to be related to incompatibility with Vite 6.

### Additional context

Rolling back to `3.14.1592` resolves the issue.

### Logs

```shell-script
SyntaxError: Unexpected token ';'
  at new Script (node:vm:117:7)
  at createScript (node:vm:269:10)
  at Object.runInThisContext (node:vm:317:10)
  at ViteNodeRunner.runModule (node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:398:19)
  at ViteNodeRunner.directRequest (node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  at async ViteNodeRunner.cachedRequest (node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:206:14)
  at async ViteNodeRunner.dependencyRequest (node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:259:12)
  at async node_modules/.pnpm/@headlessui+vue@1.7.23_vue@3.5.13_typescript@5.6.3_/node_modules/@headlessui/vue/dist/headlessui.esm.js:11:32
  at async ViteNodeRunner.runModule (node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:5)


 WARN  [nuxt] Failed to stringify dev server logs. Received DevalueError: Cannot stringify arbitrary non-POJOs. You can define your own reducer/reviver for rich types following the instructions in https://nuxt.com/docs/api/composables/use-nuxt-app#payload.
```

**Comment by cernymatej** [comment] 2024-12-29 21:24
This is probably a duplicate of https://github.com/nuxt/nuxt/issues/30384.
It is an upstream issue in Vite, which you can track here: https://github.com/vitejs/vite/issues/19096

Please have a look at the possible workarounds suggested by Alex here: https://github.com/nuxt/ui/issues/2971#issuecomment-2562833118

**Closed by cernymatej** 2024-12-29 21:24 UTC
Labels: upstream, needs reproduction, possible regression
