### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'parentNode') when navigate from page with NuxtLayout as root node

### ISSUE THREAD

**Issue by RizkiNfs** [nuxt/nuxt#25214] opened 2024-01-15 15:06 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
- Vue Version: 3.4.9

### Reproduction

https://stackblitz.com/edit/nuxt-starter-vhqnzj

### Describe the bug

when navigate from page with NuxtLayout as root component to another page with NuxtLayout cause TypeError: Cannot read properties of null (reading 'parentNode').
Adding comment above NuxtLayout and still use NuxtLayout as root node doesn't cause this issue (only works in dev mode).
I believe this bug happened after [this](https://github.com/vuejs/core/pull/10055/files#diff-069bd39ee093a8545c4e26aa7264c6ba4561a28f07f3d7d7080f4c0f71710281) specific update in vue v3.4.9

### Additional context
condition that's trigger this bug :
- navigate from page with NuxtLayout as root node, to another page with NuxtLayout.
- [#issuecomment-1898592511](https://github.com/nuxt/nuxt/issues/25214#issuecomment-1898592511)

condition that's not trigger this bug : 
- navigate from page with NuxtLayout as root node, to another page with NuxtLayout and has pageTransition defined.
- navigate from page with NuxtLayout as root node, to another page without NuxtLayout.

**Comment by danielroe** [comment] 2024-01-15 20:58
Linking here also this repro from @Aareksio: https://stackblitz.com/edit/github-dbis9a.

> You need pages with 2 different layouts, one must be nested page. And then you need to call `useAsyncData`. Which must be `{ immediate: false }`...

**Comment by AndersCV** [comment] 2024-01-16 08:44
Same issue here

**Comment by manniL** [comment] 2024-01-16 09:13
@AndersCV Please refrain from posting comments that don't add additional context like "+1", "me too" or "bump". Instead, just upvote the issue through reactions *or* provide additional context like a reproduction, a new scenario where it happens or anything else that helps resolving the issue.

**Comment by manniL** [comment] 2024-01-16 09:14
If someone can reproduce it via https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main we could raise it upstream in Vue core ☺️

**Comment by danielroe** [comment] 2024-01-16 16:07
The issue here is that `<NuxtLayout>` cannot be the root node of a page (or component) because it uses Suspense. (This is also true of `<NuxtPage>`. We should document this (and have eslint configuration setup), unless we can remove this requirement in Nuxt itself.

Workaround is to do this:

```diff
  <template>
+   <div>
      <NuxtLayout name="test">
        <h1>unable navigate to home page</h1>
      </NuxtLayout>
+   </div>
  </template>
```

Related: https://github.com/nuxt/nuxt/issues/21759.

**Comment by agracia-foticos** [comment] 2024-01-17 08:08
With Vue 3.4.8 parentNode error dissapears, but with 3.4.13 and 3.4.14 error persists

**Comment by danielward** [comment] 2024-01-17 17:19
> The issue here is that `<NuxtLayout>` cannot be the root node of a page (or component) because it uses Suspense. (This is also true of `<NuxtPage>`. We should document this (and have eslint configuration setup), unless we can remove this requirement in Nuxt itself.
> 
> Workaround is to do this:
> 
> ```diff
>   <template>
> +   <div>
>       <NuxtLayout name="test">
>         <h1>unable navigate to home page</h1>
>       </NuxtLayout>
> +   </div>
>   </template>
> ```
> 
> Related: #21759.

I spent literally hours looking into this over the weekend! The error in the console was somewhat vague, so didn't give much in the way of insight into this. Is this in any way related to the following appearing repeatedly also?

```
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
```

**Comment by agenordebriat** [comment] 2024-01-18 12:21
Workaround doesn’t work for me. I suspect it has something to do with swapping layouts.

**Comment by AndersCV** [comment] 2024-01-18 14:32
The same error happens when you're switching between pages that has the `<NuxtLayout>` while a promise is still resolving. 
Happens even when only using default layout and even with a single root node inside page templates. No workaround available for this one im afraid. 

Reproduction here: 
https://stackblitz.com/edit/nuxt-starter-dtnaui

**Comment by BroJenuel** [comment] 2024-01-21 10:06
I have a working website its working pretty fine until upgrading to 3.9.3, now It's not letting go to other pages. Its basically shows this error.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
```

 I have not changed anything. I have not touched layout. Everything is working before. But now its navigating to different pages does not work anymore after the upgrade.

**Comment by szadave** [comment] 2024-01-21 18:52
+1 for this.

**Comment by becem-gharbi** [comment] 2024-01-22 12:09
> If someone can reproduce it via https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main we could raise it upstream in Vue core ☺️

Hi @manniL, I have created a reproduction on vue. The navigation between pages without waiting for Suspense to resolve causes this issue. I'm not sure if this is related to `vue` or `vue-router` but certainly related to this PR on vue@3.4.9 https://github.com/vuejs/core/pull/10055.

https://stackblitz.com/edit/vitejs-vite-2fvdtp?file=src%2FApp.vue

**Comment by agenordebriat** [comment] 2024-01-22 13:36
> > If someone can reproduce it via https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main we could raise it upstream in Vue core ☺️
> 
> Hi @manniL, I have created a reproduction on vue. The navigation between pages without waiting for Suspense to resolve causes this issue. I'm not sure if this is related to `vue` or `vue-router` but certainly related to this PR on vue@3.4.9 [vuejs/core#10055](https://github.com/vuejs/core/pull/10055).
> 
> https://stackblitz.com/edit/vitejs-vite-2fvdtp?file=src%2FApp.vue

I don't have any issue as soon as Vue is <3.4.0 (3.3.13 currently).

**Comment by manniL** [comment] 2024-01-22 13:38
@becem-gharbi Thanks!

BTW: https://github.com/vuejs/core/pull/10184 might resolve it 👍

**Comment by fosterdouglas** [comment] 2024-01-23 05:01
Can anyone confirm which specific Vue version + Nuxt version will prevent this in the meantime ? I've tried a few combos without great results. Wrapping layout tags in divs didn't seem to solve it for me as a workaround.

**Comment by pheeque1** [comment] 2024-01-23 08:07
> Can anyone confirm which specific Vue version + Nuxt version will prevent this in the meantime ? I've tried a few combos without great results. Wrapping layout tags in divs didn't seem to solve it for me as a workaround.

@fosterdouglas I've had luck downgrading to Nuxt `3.9.0` and Vue `3.4.4` in the meantime.

**Comment by Aareksio** [comment] 2024-01-23 08:13
There is already a comment in this regard above: https://github.com/nuxt/nuxt/issues/25214#issuecomment-1895292578

You need Vue `3.4.8` or earlier. You can use your package manager ([npm](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides), [pnpm](https://pnpm.io/package_json#pnpmoverrides), [yarn](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)), example for pnpm:
```json
{
  "pnpm": {
    "overrides": {
      "vue": "3.4.8"
    }
  }
}
```

No need to downgrade Nuxt.

**Comment by palaxius** [comment] 2024-01-30 12:40
In Nuxt3 after overriding the vue version to 3.4.8, we observe a memory leak in the component when the ssr is enabled. The component has complex logic with watchers and computers. Had someone the same?

**Comment by McPizza0** [comment] 2024-02-08 14:35
this may not be useful for all
we have a redirect page that we trigger just before changing layout

adding the following overcomes the issue

```ts 
reloadNuxtApp({
    path: `/${orgSlug}/convo`,
    force: true,
    ttl: 5000
  });
  ```
  
if you've only got a couple of layouts with single entry points, you could add this to the first page that loads (remove the path property)
or create a redirect page as we have in UnInbox

**Comment by nethriis** [comment] 2024-02-09 18:28
same issue

**Comment by norbertSG** [comment] 2024-02-13 15:29
Same issue

**Comment by manniL** [comment] 2024-02-13 17:25
@norbertSG @nethriis Please refrain from posting comments that don't add additional context like "+1", "me too" or "bump". Instead, just upvote the issue through reactions *or* provide additional context like a reproduction, a new scenario where it happens or anything else that helps resolving the issue.

**Comment by ghartemann** [comment] 2024-02-19 16:23
It would seem that this is indeed linked to layout swapping in some way. Our app breaks when navigating from a page with a layout to a nested page with a different layout.

We managed to fix it in e few cases by doing this in the script part:

```diff
definePageMeta({
-   layout: 'custom'
+   layout: false
});
```

and wrapping our whole page with a <NuxtLayout> tag like this:

```diff
<template>
+   <NuxtLayout name="custom">
        <!-- our code -->
+   <:NuxtLayout>
</template>
```

I don't know if it's the best way but this works for us right now in most components. In others, it simply won't work and keeps on breaking navigation.

**Comment by FatNerdPeng** [comment] 2024-02-20 09:01
I encountered the same problem and I'm not sure if it's related to dynamic components. In my case, this is my version of nuxt and vue:
![FC0F7D94EE56A204819B0B1FCE20E935](https://github.com/nuxt/nuxt/assets/33616855/55ac58b0-fa24-49b3-af88-0ec1111f85ae)
my page is dynamic routing `/pages/user/main/[id].vue`
Initially, I used a dynamic component on this page:
![4C41F3DAA3060CB42CAEEDA5825A81D6](https://github.com/nuxt/nuxt/assets/33616855/bf2b3192-0fce-41d4-aac4-79cc2709ec8a)
It will return this component `<UserThemeDefault>`:
![626A36EC81FE7114398055FA38C1EF20](https://github.com/nuxt/nuxt/assets/33616855/7512a76c-6f24-4001-8676-fb8be85b4622)
Then the browser will report an error `Cannot read properties of undefined (reading 'parentNode')` , and my page will not display any content,and my route will get stuck on this page, making it impossible for me to navigate to other pages through `navigateTo`
![image](https://github.com/nuxt/nuxt/assets/33616855/9e105605-5743-4419-b9d2-5f552b7fdd1e)
But if I use this component directly, there is no problem(including routing redirection `navigateTo`):
![4EA8450FB2582D71A83AB57600205D10](https://github.com/nuxt/nuxt/assets/33616855/e9db4539-945f-46cd-afe6-cab83d7c55b4)
![image](https://github.com/nuxt/nuxt/assets/33616855/8a5f7940-d242-4740-aec4-f299046a694e)
So what I want to express is, maybe this issue is not related to the `Vue` or `Nuxt` versions, maybe it's related to dynamic components?

**Comment by sa8ab** [comment] 2024-02-25 08:42
I had this issue in my page:
```vue
<script setup lang="ts">
definePageMeta({
  layout: 'myLayout'
});
</script>

<template>
  // my page content
</template>
```

And my `app.vue`
```vue
<template>
 <div>
   <NuxtLayout>
     <NuxtPage />
   </NuxtLayout>
 </div>
  // my page content
</template>
```

It looks like in this scenario we can not wrap the page layout with a div, so I had to do the following in my 
I had to use the actual NuxtLayout component instead of setting it on definePageMeta,
The result that resolved the issue looks like this:
In my page
```vue
<script setup lang="ts">
definePageMeta({
  // disables the layout coming from app.vue
  layout: false,
});
</script>

<template>
  <div>
  // manually add layout so we can wrap in a div
    <NuxtLayout name="myLayout">
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```

**Comment by warflash** [comment] 2024-02-26 02:25
Vue 3.4.20 just landed which inludes https://github.com/vuejs/core/pull/10184
Based on personal testing and the [updated initial reproduction](https://stackblitz.com/edit/nuxt-starter-7jwc1r?file=package.json) provided this seems to have solved the issue.

**Comment by sa8ab** [comment] 2024-02-26 06:07
Confirming issue being fixed on Vue v3.4.20.
On my project I had to update the vue version on dev dependency
```json
  "devDependencies": {
    "nuxt": "^3.10.1",
    "vue": "^3.4.20",  /* <-- updated vue version */
  },
```

**Comment by nethriis** [comment] 2024-03-05 13:52
> Confirming issue being fixed on Vue v3.4.20. On my project I had to update the vue version on dev dependency
> 
> ```json
>   "devDependencies": {
>     "nuxt": "^3.10.1",
>     "vue": "^3.4.20",  /* <-- updated vue version */
>   },
> ```

No

**Comment by sanjarbarakayev** [comment] 2024-05-27 06:30
In my case, the issue was fixed by checking the `Teleport` component with v-if on mount.
```
<template>
  ...
  <Teleport v-if="mounted" to="#target">
    ...
  </Teleport>
...
</template>

<script setup lang="ts">
const { mounted } = useMounted()
</script>
```

**Comment by danielroe** [comment] 2024-05-29 13:56
Closing this issue as I believe it's been resolved in Vue v3.4.20.

If someone experiences this again, please open a new issue with a reproduction.

**Closed by danielroe** 2024-05-29 13:56 UTC
Labels: documentation, good first issue, 3.x, workaround available, dx

**Comment by ShiriCZ** [comment] 2024-07-25 10:43
I run again into this problem with Nuxt 3.14.2 and Vue 3.4.34. Rollback to Nuxt 3.10.1 and Vue 3.4.20 fixed the problem. So its looks like it got broken again in new version of Vue/Nuxt.

**Comment by anyongjin** [comment] 2024-07-30 04:54
I'm facing this issue today with

Nuxt version - 3.12.4
Vue version - 3.4.34

It happens when it navigateTo from a page with a custom layout to another page with same layout. 

i tried making sure NuxtLayout is in a div and not the root page element, but it didn't work for me.

Finally, i temporarily solved it by disable ssr, it actually behaviour like `window.location.href = '/'`

I guess this should be a bug from Vue3 and we have to wait for it to be resolved
```javascript
// nuxt.config.ts
export default defineNuxtConfig({
  ssr: false,
});
```

**Comment by BlazingTide** [comment] 2024-07-31 17:08
Running into this problem, using the latest version of Nuxt.

Only happens in production build, and not during development.

**Comment by agracia-foticos** [comment] 2024-08-01 05:49
https://stackblitz.com/edit/nuxt-starter-fynqph in PROD mode must be fail if navigates between 1 and 2 link

**Comment by manniL** [comment] 2024-08-01 07:38
@BlazingTide @agracia-foticos @anyongjin 

> This is likely to be a regression in Vue in that case.
> 
> Would you see if you can reproduce this in pure Vue SSR without Nuxt ([reproduction sandbox](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter)), and if so, raise [there](https://github.com/vuejs/core/issues/new/choose)? 🙏

**Comment by liaow-ww** [comment] 2024-08-06 02:57
I also faced this problem in my project yesterday, so I specified my Vue and Nuxt versions
use my origin versions Vue 3.4.3 and Nuxt 3.9.3

**Comment by wongyat88** [comment] 2024-08-15 07:39
"nuxt": "^3.12.4",
"vue": "^3.4.21",

Getting the same problem, downgrade to 3.4.20 seem fix the problem.

**Comment by CorrM** [comment] 2025-02-17 00:19
Same problem:
when i use navigateTo cant load the page.
Navigate using user action(navigation menu mouse click) can't load the page

```
"nuxt": "^3.15.4",
"vue": "^3.5.13",
"vue-router": "^4.5.0",
```

![Image](https://github.com/user-attachments/assets/6dfb0833-4be7-458a-9f46-ec915107bdf5)

@TheAlexLichter

**Comment by kieuminhcanh** [comment] 2025-02-18 06:57
"nuxt": "^3.15.4",
"vue": "^3.5.13",

Still getting the same problem.

**Comment by OOO-li-ooo** [comment] 2025-02-21 13:11
The problem seems to disappear when I downgrade `Nuxt` to `3.14.1592`.

> "nuxt": "^3.15.4", "vue": "^3.5.13",
> 
> Still getting the same problem. I did add div wrap the layout but still error.
> 
> <div>
>       <NuxtLayout name="test">
>         <h1>unable navigate to home page</h1>
>       </NuxtLayout>
> </div>

**Comment by Dino-Kupinic** [comment] 2025-03-03 11:00
Issue still persists with `"nuxt": "^3.15.4"` and `"vue": "3.5.13"`

app.vue:
```vue
<template>
  <div>
    <NuxtLoadingIndicator />
    <NuxtRouteAnnouncer />
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
    <UNotifications />
  </div>
</template>
```

layout default.vue:
```vue
<template>
  <div class="flex h-dvh p-2 pb-0">
    <TheSideNavigation />
    <BasePageWrapper>
      <slot />
    </BasePageWrapper>
  </div>
</template>
```

<img width="964" alt="Image" src="https://github.com/user-attachments/assets/771fd887-d279-4d62-a061-9feb52d4c71b" />

**Comment by OOO-li-ooo** [comment] 2025-03-16 15:30
Use `await useFetch()` will definitely encounter this problem.
with 
```json
"dependencies": {
  "nuxt": "^3.16.0",
  "vue": "^3.5.13",
  "vue-router": "^4.5.0"
}
```
try it: https://stackblitz.com/edit/github-vz57fud9?file=pages%2Findex.vue
open browser console, `modify` the code and save，like:

![Image](https://github.com/user-attachments/assets/82b1996c-35a2-4bdd-8e7b-f907bab54723)

![Image](https://github.com/user-attachments/assets/953e740e-22df-47f1-86fc-283f835b5a59)
then routing doesn’t work anymore.

---
Only downgrade `Nuxt` to `3.14.1592`, this problem didn't happen:
```json
"dependencies": {
  "nuxt": "3.14.1592",
  "vue": "^3.5.13",
  "vue-router": "^4.5.0"
}
```
try: https://stackblitz.com/edit/github-vz57fud9-fu7h8qx7?file=pages%2Findex.vue

**Comment by gaisinskii** [comment] 2025-03-21 11:28
@OOO-li-ooo Also encountered this problem, try to add `lazy` option, seems to fix the issue

```
const { data } = await useFetch('/some-api-route', {
  lazy: true,
})

```

Or maybe you will open a new issue to bump the problem:) ?
