### ISSUE TITLE
Question/Feature: Critical CSS when extract CSS flag is true on Nuxt Generate

### ISSUE THREAD

**Issue by bovas85** [nuxt/nuxt#3091] opened 2018-03-22 08:11 UTC
I saw vue cli 3 has now got some config options that would be nice to have on nuxt.
Particularly I saw this plugin
https://github.com/anthonygore/vue-cli-plugin-critical/blob/master/README.md

Which would be nice to have particularly for static sites 

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2676">#c2676</a>)</em></sub></div>

**Comment by bovas85** [comment] 2018-03-22 08:11
Ps. This is more a question or feature request rather than issue.

**Comment by chymz** [comment] 2018-04-03 20:30
Hi, I've done a webpack plugin for this: https://github.com/chymz/nuxt-starter/blob/critical-css/internals/webpack/critical.js

It's a bit hacky, but works... only in SPA mode...

I don't know how to handle that with SSR index.html

**Comment by bovas85** [comment] 2018-04-04 13:39
Thanks for this, but I'd need it to work on SSR or static

**Comment by AdsonCicilioti** [comment] 2018-09-24 17:10
Nice feature! i also need this!

**Comment by remarks** [comment] 2018-11-01 05:05
I'd also be interested in this feature.

**Comment by bovas85** [comment] 2018-11-01 07:29
There's a nuxt-purgecss package that will strip unused css, but this is related to the css in the head. Not sure if that package would help here.

**Comment by manniL** [comment] 2018-11-01 10:33
@bovas85 The problem is that it will only remove *unused* CSS. If you still have a lot of CSS left you might want to extract the critical CSS to head anyway to improve perf 🙈

**Comment by bovas85** [comment] 2018-11-01 12:29
Yes precisely. That's why I meant it wouldn't be the best option

**Comment by manniL** [comment] 2019-01-24 22:43
For the record: Nuxt.js already loads just the critical CSS per page (but includes *all* of the global one).

**Comment by florinesueur** [comment] 2019-01-27 09:07
I'd also be interested in this feature.

**Comment by bro-strummer** [comment] 2019-03-06 23:12
To the best of my knowledge, Nuxt (2.4.5) effectively does what is asked in this issue–it loads CSS needed for the critical rendering path.**

Put plainly, you won't have any render-blocking CSS when using Nuxt with the `build.extractCSS` config option set to `true`.

That's because when that option is `true`, Nuxt auto-injects a preload link for your global CSS as well as your component CSS (which is code-split per page).

They'll look something like this:
```html
<link rel="preload" href="/_nuxt/8675309.css" as="style">
``` 

** That being said, not all browsers support preload links (e.g. IE, Firefox). See [Can I Use](https://caniuse.com/#feat=link-rel-preload) to determine if preload links will work for your user-base.

**Comment by bovas85** [comment] 2019-03-07 07:53
So the issue is if you have several globals like variables and mixins as well as helpers, which minified at the head will take a lot of space and be repeated. I think I'd prefer a cleaner page and was wondering what the best approach would be then to load styles as links but still have the critical css for that specific page in the head.

**Comment by williamchong007** [comment] 2019-05-07 06:29
@bro-strummer It seems to me nuxt does not add `preload` to component CSS when `extractCSS == true`, are there additional settings needed?

**Comment by phillipcurl** [comment] 2019-10-28 20:36
@williamchong007 I'm seeing the exact same thing. All of my global CSS is preloaded correctly when enabling `extractCSS`, but component-specific styles (scoped or not) are extracted without preloading. I'm using `nuxt generate` to build, but haven't tested other modes.

<img width="664" alt="Screen Shot 2019-10-28 at 4 22 25 PM" src="https://user-images.githubusercontent.com/1772856/67715818-f1e65b00-f9a0-11e9-88a3-0671df3f1595.png">

**Comment by tjkohli** [comment] 2021-02-12 21:15
Has there been any progress made to this? We're trying to improve Performance on high-speed static generated Nuxt websites.

**Comment by williamchong** [comment] 2021-02-12 21:32
For the issue I mentioned, https://github.com/nuxt/nuxt.js/issues/8060 should have fixed it

**Comment by hereiscasio** [comment] 2021-04-21 20:00
> To the best of my knowledge, Nuxt (2.4.5) effectively does what is asked in this issue–it loads CSS needed for the critical rendering path.**
> 
> Put plainly, you won't have any render-blocking CSS when using Nuxt with the `build.extractCSS` config option set to `true`.
> 
> That's because when that option is `true`, Nuxt auto-injects a preload link for your global CSS as well as your component CSS (which is code-split per page).
> 
> They'll look something like this:
> 
> ```
> <link rel="preload" href="/_nuxt/8675309.css" as="style">
> ```
> 
> ** That being said, not all browsers support preload links (e.g. IE, Firefox). See [Can I Use](https://caniuse.com/#feat=link-rel-preload) to determine if preload links will work for your user-base.

@tylerbrostrom 
I would say this is totally not true

.
There're 2 definitions about "critical CSS" on the internet
Lots of people just don't understand the differences
(Google mentioned these ideas, but it seems people misunderstand about that, btw)

.
**① Critical Path CSS**
* used by Nuxt official (see [here](https://www.npmjs.com/package/nuxt-edge
), "Feature" section) 
* some people just simplify it to "Critical CSS", which make us confused

.
**② Critical CSS**
it means you separate CSS in a page to 2 files, that's, critical.css & non-critical.css
here, the so called "Critical CSS" is the css in the visible viewport in the initial page load without scrolling !!!

So, I'm just wondering...
does anyone have the solution about how to integrate [Critical](https://github.com/anthonygore/html-critical-webpack-plugin) (well, what i mean here, is ② ) into Nuxt SSR ?

PLEASE GIVE A HELP 🙏

**Comment by Kolobok12309** [comment] 2021-08-02 10:53
@hereiscasio, how are your search results? Mb at least inline global styles (in `nuxt.config.js` css), and all other linked?

**Comment by danielroe** [comment] 2024-06-14 16:10
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉

**Closed by danielroe** 2024-06-14 16:10 UTC
Labels: enhancement, 2.x
