### ISSUE TITLE
active class not removed on iPad

### ISSUE THREAD

**Issue by krisskovacs** [nuxt/nuxt#21288] opened 2023-05-31 15:11 UTC
### Environment

9th Generation iPad - iOS 15.5

### Reproduction

https://github.com/nuxt/nuxt/assets/7904174/67e98b91-fb9d-47c4-b05b-533f1c39959e

### Describe the bug

When clicking through navigation and then pressing the back button, active link styles are not removed on iPad

From video:
Go to a site using Nuxt
Click on an item in the nav bar "Guide"
Click on the next item in nav bar "API"
Click the back button

Both of the navbar items still have the same style.

**Comment by krisskovacs** [comment] 2023-05-31 16:00
> Since the video is even taken from the vue-router docs I recommend opening an upstream issue there instead: https://github.com/vuejs/router/issues

Same thing is happening on nuxt.com but it's more clearer on the vue-router docs. Our QA team caught it happening on our sites so I went to see if it's also happening on other sites using nuxt

**Comment by warflash** [comment] 2023-05-31 16:03
The vue router docs where the video is from is not using nuxt though, it's using vitepress. Nuxt does use vue-router under the hood which is why you might see this error on nuxt apps as well, the root cause comes from vue-router though, not nuxt - hence the upstream issue

**Comment by manniL** [comment] 2023-12-25 23:38
Closing here - follow-up might (one day) happen in https://github.com/vuejs/router/issues/1867 if @krisskovacs provides another reproduction 😋

**Closed by manniL** 2023-12-25 23:38 UTC
Labels: 3.x, upstream, upstream-bug
