### ISSUE TITLE
Server auto-import not work

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#30098] opened 2024-11-29 08:55 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-xpmtid

### Describe the bug

I ran' pnpm update` in a new Nuxt project and found that auto-import no longer works on the Nitro server. I'm not sure which sub-dependency causes this bug.

In the reproduction, you can see I define a server utils function `foo`, but it is not auto-imported:
```
ERROR  [nuxt] [request error] [unhandled] [500] foo is not defined
```

### Logs

```shell-script

```

**Comment by DotwoodMedia** [comment] 2024-11-29 13:53
There is a bug in `unimport` version `^3.14`. To resolve this, update your `package.json` to the following configuration. This will ensure the server imports work correctly:
```
"overrides": {
    "unimport": "3.13.4"
}
```

**Comment by IsraelOrtuno** [comment] 2024-11-29 18:06
Nice catch @DotwoodMedia. I had to nest `overrides` under `pnpm` property in order to make it work with pnpm.

```
  "pnpm": {
    "overrides": {
      "unimport": "3.13.4"
    }
  }
```

**Comment by ayberk-yilmaz** [comment] 2024-11-29 19:01
It seems the auto-scan in Nitro for the `server/utils` folder isn't working. 

You can explicitly add the following configuration in your `nuxt.config.ts` file to auto-import utils:

```ts
export default defineNuxtConfig({
  nitro: {
    imports: {
      dirs: ["server/utils"],
    },
  },
});
```

This configuration auto-imports utility functions in the server/utils directory.

**Comment by tobychidi** [comment] 2024-11-29 22:25
This is such a painful regression. All of a sudden project break. Newbies would find this frustrating 🥲. But no wahala. I am sure it is being worked on. These kind of things should no longer be happening cuz Nuxt is now a big framework. I am selling all my circle on Nuxt. 😅

Best framework ever still.

**Comment by aligzl** [comment] 2024-12-03 03:46
> Thank you all for the investigation. This is a resolved bug in a dependency of Nuxt, not Nuxt itself, so we can close it here. (Nuxt doesn't pin `unimport` to any specific minor/patch version, so it doesn't require a release of Nuxt itself.)
> 
> Refreshing your lockfile or running `pnpm upgrade unimport` should also resolve the issue.

Hi @danielroe 
this issue still  has not fixed yet. 

[Reproduction](https://stackblitz.com/edit/github-rdmiwt)

**Comment by Akryum** [comment] 2024-12-03 08:21
Workaround for people using pnpm:

```json
{
  "pnpm": {
    "overrides": {
      "unimport": "~3.13"
    }
  }
}
```

**Comment by danielroe** [comment] 2024-12-03 08:29
Ah, I misread the override.

Reopening until it is fixed in nitro or unimport.

cc: @pi0 @antfu

**Comment by danielrentz** [comment] 2024-12-03 08:33
it is https://github.com/unjs/unimport/issues/399, hopefully fixed with PR https://github.com/unjs/unimport/pull/400

**Comment by antfu** [comment] 2024-12-03 13:31
This should be fixed by `unimport@3.14.3`, please update the lock. Sorry for the inconveniences

**Closed** 2024-12-03 13:40 UTC
Labels: nitro, upstream-bug, possible regression

**Comment by PhilMataz** [comment] 2024-12-03 14:34
@antfu can confirm that it seems to not be fixed ([Stackblitz reproduction](https://stackblitz.com/edit/github-7j2lvy?file=server%2Fapi%2Findex.get.ts)

**Comment by Vincentdevreede** [comment] 2024-12-04 07:29
@tobychidi are you sure you're on version 3.14.3? I just updated to 3.14.3, and it's all working fine for me. You can run `npm list unimport` to confirm your version.

@PhilMataz your Stackblitz reproduction is installing `unimport@3.14.2`. You can confirm this by running `npm list unimport`. After removing `node_modules` and `package-lock.json`, it installs unimport@3.14.3 instead.

**Comment by Perdolique** [comment] 2024-12-04 20:15
I'm not sure if this is a regression or not, but with `unimport` `v13.3` it was possible to use auto-import from a subdirectory. But since `unimport` `v13.4.3` it's importing only from top level of the `utils` directory. I know the documentation said "it works similar to `composables` auto-import (only one level deep)". @danielroe 

[Reproduction.](https://stackblitz.com/edit/github-7j2lvy-4jteyp?file=server%2Fapi%2Findex.get.ts)

**Comment by xmatthias** [comment] 2025-01-03 17:13
@Perdolique that's working with the following nuxt config:

```
export default defineNuxtConfig({
  nitro: {
    imports: {
      dirs: ["server/utils/**"],
    },
  }
}
```

Not sure if this is intended behavior though (@danielroe, maybe?) - I for myself do like to group my utils in folders ...

**Comment by danielroe** [comment] 2025-01-03 17:35
this was not a nuxt change

if it is indeed a regression, would you raise in nitro repo?

**Comment by pi0** [comment] 2025-01-03 17:39
It is a behavior change of unimport in same semver-major, which nitro will adopt in next release (context: https://github.com/nitrojs/nitro/issues/2918)

**Comment by xmatthias** [comment] 2025-01-04 12:26
well fixed in the next nitro release is the best answer we could hope for 👍 
(not pinging people here in hopes of avoiding unnecessary pings - while still thanking them for their efforts should they watch!)

**Comment by dinoluck** [comment] 2025-01-10 15:59
> [@Perdolique](https://github.com/Perdolique) that's working with the following nuxt config:
> 
> ```
> export default defineNuxtConfig({
>   nitro: {
>     imports: {
>       dirs: ["server/utils/**"],
>     },
>   }
> }
> ```
> 
> Did you report this separately (like, as explicit issue here or against unimport)?
> 
> Not sure if this is intended behavior though ([@danielroe](https://github.com/danielroe), maybe?) - I for myself do like to group my utils in folders ... so i would see this as regression myself

Indeed the only way to get stuff from ~/utils to auto import to files inside ~/server was to add the nitro setting up there.
