### ISSUE TITLE
`useRuntimeConfig()` returns `NitroRuntimeConfig` and does not include keys defined in `nuxi.config.ts`

### ISSUE THREAD

**Issue by imding** [nuxt/nuxt#26028] opened 2024-03-01 10:49 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[CodeSandbox](https://codesandbox.io/p/devbox/runtime-config-mnc5y4?file=%2Fserver%2Fapi%2Ftest.ts%3A11%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt8too5m00093b6efg63z2y3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt8too5l00043b6e3jlxy9ek%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt8too5l00063b6exwixab06%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt8too5l00083b6e4x4b8o4h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt8too5l00043b6e3jlxy9ek%2522%253A%257B%2522id%2522%253A%2522clt8too5l00043b6e3jlxy9ek%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt8too5l00083b6e4x4b8o4h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt8too5l00073b6eobbipcl3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clt8too5l00083b6e4x4b8o4h%2522%252C%2522activeTabId%2522%253A%2522clt8too5l00073b6eobbipcl3%2522%257D%252C%2522clt8too5l00063b6exwixab06%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt8too5l00053b6eiirrpcc6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clt8too5l00063b6exwixab06%2522%252C%2522activeTabId%2522%253A%2522clt8too5l00053b6eiirrpcc6%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

The return value of the `useRuntimeConfig` hook does not include the keys defined in `nuxt.config.ts` on the server, while they are present on the client, even the private keys are included.

### Additional context

<img width="1130" alt="image" src="https://github.com/nuxt/nuxt/assets/20434337/6855d276-cb4e-469d-9e87-541266cc2c9e">

_No response_

**Comment by manniL** [comment] 2024-03-01 17:06
Can't access the codesandbox

**Comment by imding** [comment] 2024-03-01 22:56
> Can't access the codesandbox

hey sorry about that, I forgot to make it public

here is the [link](https://codesandbox.io/p/devbox/runtime-config-mnc5y4?file=%2Fserver%2Fapi%2Ftest.ts%3A11%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt8too5m00093b6efg63z2y3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt8too5l00043b6e3jlxy9ek%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt8too5l00063b6exwixab06%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt8too5l00083b6e4x4b8o4h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt8too5l00043b6e3jlxy9ek%2522%253A%257B%2522id%2522%253A%2522clt8too5l00043b6e3jlxy9ek%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt8too5l00083b6e4x4b8o4h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt8too5l00073b6eobbipcl3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clt8too5l00083b6e4x4b8o4h%2522%252C%2522activeTabId%2522%253A%2522clt8too5l00073b6eobbipcl3%2522%257D%252C%2522clt8too5l00063b6exwixab06%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt8too5l00053b6eiirrpcc6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clt8too5l00063b6exwixab06%2522%252C%2522activeTabId%2522%253A%2522clt8too5l00053b6eiirrpcc6%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) again

**Comment by adrienZ** [comment] 2024-03-05 12:36
Hello @imding, for the `any` type, you need to add the type yourself as per the docs: https://nuxt.com/docs/guide/going-further/runtime-config#typing-runtime-config

```ts
declare module 'nuxt/schema' {
  interface RuntimeConfig {
    apiSecret: string
  }
  interface PublicRuntimeConfig {
    apiBase: string
  }
}
// It is always important to ensure you import/export something when augmenting a type
export {}
```

**Comment by imding** [comment] 2024-03-05 19:16
> Hello @imding, for the `any` type, you may need to add the type as per the docs: https://nuxt.com/docs/guide/going-further/runtime-config#typing-runtime-config (workaround)
> 
> ```ts
> declare module 'nuxt/schema' {
>   interface RuntimeConfig {
>     apiSecret: string
>   }
>   interface PublicRuntimeConfig {
>     apiBase: string
>   }
> }
> // It is always important to ensure you import/export something when augmenting a type
> export {}
> ```
> 
> EDIT: in `test.ts` it is also advised to pass the `event` params in `useRuntimeConfig` as shown [here](https://nuxt.com/docs/guide/going-further/runtime-config#server-routes) to handle environment variables conflicts :
> 
> ```ts
> export default defineEventHandler((event) => {
>   const config = useRuntimeConfig(event)
> })
> ```

hi Adrian, thanks for the reply.

the `index.d.ts` file in the docs is for adding typing to the `RuntimeConfig` interface, which already infers from `nuxt.config.ts` albeit without hiding the private ones (just types, their values are correctly withheld from the client), while the `useRuntimeConfig` hook returns the `NitroRuntimeConfig` interface outside of Vue components, and it does not have any of the config keys defined in `nuxt.config.ts`, I believe the intended behaviour is to includes all of them (like with `RuntimeConfig` but with all the values too).

![image](https://github.com/nuxt/nuxt/assets/20434337/84ae6e41-cd5b-430a-bc62-f6f45d72df32)

**Comment by adrienZ** [comment] 2024-03-06 11:50
I see your problem, it's weird...

using last version of nuxt (`npx nuxt upgrade --force`) AND **Stackblitz** works: https://stackblitz.com/edit/github-gjiyuu?file=server%2Fapi%2Ftest.ts

any attempt on codesandbox is not working, maybe skill issue from me but it is what it is  ¯ \ _ (ツ) _ / ¯

**Comment by imding** [comment] 2024-03-07 04:30
> I see your problem, it's weird...
> 
> using last version of nuxt (`npx nuxt upgrade --force`) AND **Stackblitz** works: https://stackblitz.com/edit/github-gjiyuu?file=server%2Fapi%2Ftest.ts
> 
> any attempt on codesandbox is not working, maybe skill issue from me but it is what it is ¯ \ _ (ツ) _ / ¯

I tried your link but I get this

![image](https://github.com/nuxt/nuxt/assets/20434337/b9f56c1d-9cea-457f-859e-fe8d1c8e500b)

There is no `.nuxt` folder and I can't type `pnpm postinstall` (actually I can't type anything) in the terminal.

Do I have to do something after opening the link?

**Comment by madebyfabian** [comment] 2024-03-29 18:54
Just tested it and the Stackblitz Reprod works for me. Do you still encounter an issue @imding ?

**Comment by imding** [comment] 2024-03-30 15:48
> Just tested it and the Stackblitz Reprod works for me. Do you still encounter an issue @imding ?

I'm not sure what changed on Stackblitz but I still get this when I use `useRuntimeConfig` in server/* files
<img width="739" alt="image" src="https://github.com/nuxt/nuxt/assets/20434337/3a1322f2-b9ed-481a-b93d-6d8fe9fc5fa5">

**Comment by madebyfabian** [comment] 2024-03-31 05:51
@imding That's interesting, since on StackBlitz it definitely works:
  
![Bildschirmfoto 2024-03-31 um 07 49 29](https://github.com/nuxt/nuxt/assets/32813692/26566fde-6501-4cc5-a60a-9f08a3278e47)

You coul try to remove the .nuxt folder and restart your server, to let the types regenerate.

Are you on the latest Nuxt version? And do you have this issue when starting a new project?

**Comment by imding** [comment] 2024-03-31 09:09
> @imding That's interesting, since on StackBlitz it definitely works:
> 
> ![Bildschirmfoto 2024-03-31 um 07 49 29](https://private-user-images.githubusercontent.com/32813692/318244473-26566fde-6501-4cc5-a60a-9f08a3278e47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NzU2MTYsIm5iZiI6MTcxMTg3NTMxNiwicGF0aCI6Ii8zMjgxMzY5Mi8zMTgyNDQ0NzMtMjY1NjZmZGUtNjUwMS00Y2M1LWE2MGEtOWYwOGEzMjc4ZTQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA4NTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMjE0Y2VmNGZlYzRjMTg2ZmYxNzM1ODkzZDNiYzAxY2MzMDJmNDhiNjA4OWNlNTU1MDkwMjZlMjhmNDkzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GdjQtz23o0R1gj4zNkz2iS-41fzewSdWc40zaZf_1tI)
> 
> You coul try to remove the .nuxt folder and restart your server, to let the types regenerate.
> 
> Are you on the latest Nuxt version? And do you have this issue when starting a new project?

Hey, I updated my project to nuxt 3.11.1 and it seems to work.

I am still getting the `NitroRuntimeConfig` type but it does have all the keys and autocomplete now.

How about the `RuntimeConfig` type, it still includes keys outside `runtimeConfig.public` from `nuxt.config.ts`, should they be omitted or is it up the the developer to know they're not accessibleV

**Comment by madebyfabian** [comment] 2024-04-01 10:38
@imding You mean that on the client-side `useRuntimeConfig()` in  `app.vue`, you get types for keys outside of `runtimeConfig.public` that aren't available? Yeah I can reproduce that. The value of `apiSecret` isn't available on client-side in runtime, but I get auto-suggestions (not on StackBlitz, but on the same code running locally in VSCode).
![Bildschirmfoto 2024-04-01 um 12 33 45](https://github.com/nuxt/nuxt/assets/32813692/060d32c7-f3bd-487e-acd6-fa03d5f6c514)

I think it loads the server types of `useRuntimeConfig` on the client, because of the `event` parameter, that is only available for `defineEventHandler(event => ...` on server-side.
![Bildschirmfoto 2024-04-01 um 12 34 18](https://github.com/nuxt/nuxt/assets/32813692/6d816dd3-7115-4ea6-887b-edb9f24c8ff6)

Let's open another issue for this specific bug, and close this one. What do you think?

**Comment by manniL** [comment] 2024-04-01 11:29
@madebyfabian this is not necessarily wrong as the "secret" variables are available during SSR but not on the client. So using that + `process.server` or an `if` can be valid.

**Comment by madebyfabian** [comment] 2024-04-01 11:40
@manniL I see, true! Though I am still confused about the fact the there is the `_event` param available on the client `useRuntimeConfig(_event?: ...)`. I see it was added with this commit https://github.com/nuxt/nuxt/commit/f40e5dcc8b5e62db91d0f954c02abb9cf66749f8. But I get you, it's not a bug, just something you have to keep in mind.

**Closed** 2024-04-01 19:06 UTC
Labels: 3.x, pending triage, needs reproduction, ⛔️ can be closed
