### ISSUE TITLE
Id from `useId()` changes on hydration.

### ISSUE THREAD

**Issue by lutejka** [nuxt/nuxt#30289] opened 2024-12-17 17:25 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-bra69axh?file=app.vue&file=components%2FComp.vue

### Describe the bug

Once I use `useAsyncData` in `app.vue` or some layout, `useId()` within child components return different Id's after hydration.  As soon as I remove `useAsyncData`, everything works as intended. 

The error from the reproduction looks like this: 
```
Vue warn]: Hydration text content mismatch on 
<div data-v-inspector="components/Comp.vue:2:3"> 
  - rendered on server: v-0-0
  - expected on client: v-1 
  at <Comp> 
  at <App key=4 > 
  at <NuxtRoot>
```

### Additional context

Maybe relates to this issue: https://github.com/nuxt/nuxt/issues/27378

### Logs

```shell-script

```

**Comment by huang-julien** [comment] 2024-12-18 18:40
Hello, you forgot to await useAsyncDFata

**Comment by cernymatej** [comment] 2024-12-18 18:55
@huang-julien you shouldn't need to await it
or am i missing something?

**Comment by huang-julien** [comment] 2024-12-18 19:57
We do need to await it. Because this will be transformed by unctx to bind the context to the handler of `useAsyncData`. 
... Is there a place in the doc where we say to not await it ?

**Comment by cernymatej** [comment] 2024-12-18 20:19
I would think that the option to await it is there only so that you can access the data further down in the script setup if you need to. Even Daniel (cc @danielroe) often recommends not awaiting it when the data is only needed in the template, to avoid creating an unnecessary async setup function.

There is even a test case to verify that the data is available directly on the Promise itself:
https://github.com/nuxt/nuxt/blob/1f09e69335426c221617994aaeec556671c23aa4/test/nuxt/composables.test.ts#L128-L146

**Comment by lutejka** [comment] 2024-12-18 20:56
The documentation states neither that it is needed nor that it is not needed. But this note at least implies that it is optional.

https://github.com/nuxt/nuxt/blob/1f09e69335426c221617994aaeec556671c23aa4/docs/3.api/2.composables/use-async-data.md?plain=1#L102-L104

**Comment by huang-julien** [comment] 2024-12-18 22:47
Yeah, I get what both of you means.
I think the fact that both composables are retrieving the component instance using `ghetCurrentInstance` must probably break something 🤔 . 

Let's re-open it and see if we can dig deeper nto this issue.

**Comment by cernymatej** [comment] 2024-12-18 22:51
I don't think that this was happening before - it might be a regression, but I wouldn't bet on that.

**Comment by huang-julien** [comment] 2024-12-21 21:31
hm... I still think this is a vue/core issue. But i haven't been able to reproduce it...yet
A fix has been made to useId which probably cause this issue 🤔

**Comment by danielroe** [comment] 2024-12-24 14:25
resolved in https://github.com/nuxt/nuxt/pull/30343

**Closed by danielroe** 2024-12-24 14:25 UTC
Labels: upstream, upstream-bug

**Comment by cernymatej** [comment] 2025-02-15 19:21
I've noticed some hydration mismatches related to `useId` again. I haven't had a chance to have a look at it in more detail just yet, though.
I'll try to reproduce it in playground in a few days.

Do any of you have an idea, what might be the cause? It seems that there might be one more edge case, doesn't it? (since the id differs only by 1)

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/3c7d2163-09b1-4234-93d8-c6675bf309b0" />
