### ISSUE TITLE
Weird truncation of public runtime variables

### ISSUE THREAD

**Issue by andreasvirkus** [nuxt/nuxt#24936] opened 2023-12-28 05:15 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.7.0`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.1.0`
- Builder:          `-`
- User Config:      `devtools`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Repricable in a vanilla Nuxt project – simply set a public runtime config 

```js
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  runtimeConfig: {
    public: {
      TRUNCATE_TEST: '',
    },
  },
})
```

And in a `.env` file set a variable with only numbers and a dot in it:
```
NUXT_PUBLIC_TRUNCATE_TEST="3764781224009.4594925821288"
```

### Describe the bug

The variable gets truncated, so `3764781224009.4594925821288` becomes `3764781224009.4598`. But if I append an alphabetical character (e.g. `x`) to the end of the variable, then I get a full value back.

### Additional context

The value is a Slack client ID that I'd need to pass in order to configure an "Add to Slack" button. If the variable is only numeric, it weirdly always takes the first 3 characters **and** the very last character and strips the rest 🤔 So basically:

```
3764781224009.4594925821288
XXXXXXXXXXXXX.YYYstripppedY

3764781224009.4598 # output
```

**Comment by manniL** [comment] 2023-12-28 09:53
Duplicate of https://github.com/nuxt/nuxt/issues/24812

**Closed by manniL** 2023-12-28 09:53 UTC
Labels: 3.x, pending triage

**Comment by andreasvirkus** [comment] 2023-12-29 09:19
Oh, thanks! 🎉
