### ISSUE TITLE
Nuxt 3.7.0 Two component files resolving to the same name ProsePre

### ISSUE THREAD

**Issue by nurRiyad** [nuxt/nuxt#22971] opened 2023-09-03 14:27 UTC
### Environment

- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxt/content@2.8.2
- Build Modules:    -

### Reproduction

package.json

```json
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/content": "^2.8.2",
    "@nuxt/devtools": "latest",
    "nuxt": "^3.7.0"
  }
}

```

nuxt.config.ts

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@nuxt/content"]
})
```

### Describe the bug

Nuxt 3.7.0 With Nuxt Content 2.8.2 Show warning in terminal **Two component files resolving to the same name ProsePre**

`node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue`
`node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue`

**Comment by wokalek** [comment] 2023-09-03 16:05
Have same Error.

**Comment by wokalek** [comment] 2023-09-03 16:27
This is because nuxt/content assumes the creation of files like ProseImg, ProseP and others. But Nuxt implements experimental support for components on the server and a check for the same names is written in the component auto-registrar. This needs to be edited on the `nuxt/content` side I think.

Create there issue for this https://github.com/nuxt/content/issues/2285

**Comment by manniL** [comment] 2023-09-03 19:26
This might be a duplicate of https://github.com/nuxt/nuxt/issues/22876 🤔

**Closed by manniL** 2023-09-03 19:26 UTC
Labels: 3.x, pending triage

**Comment by wokalek** [comment] 2023-09-03 19:27
@manniL duplicate, but not solved at all

**Comment by manniL** [comment] 2023-09-03 20:59
@wokalek did you try it on the edge channel? The linked PR should solve the issue but is not yet released.

**Comment by wokalek** [comment] 2023-09-04 07:41
> @wokalek did you try it on the edge channel? The linked PR should solve the issue but is not yet released in a stable version.

It looks like the problem with the 502 error was due to the fact that Nuxt now requires the --host flag to be specified when creating the server. And since I have it inside Docker, it was necessary.

However, warnings about duplicate components remain, but they do not carry any danger, they only inform about it.

**Comment by manniL** [comment] 2023-09-04 07:50
> It looks like the problem with the 502 error was due to the fact that Nuxt now requires the --host flag to be specified when creating the server. And since I have it inside Docker, it was necessary.

See https://github.com/nuxt/nuxt/issues/22150

> However, warnings about duplicate components remain, but they do not carry any danger, they only inform about it.

Exactly 👍

**Comment by manniL** [comment] 2023-09-14 09:17
If you use Nuxt content, you want to follow https://github.com/nuxt/content/issues/2266. A fix PR is up already but it should not influence your code.
