### ISSUE TITLE
`getQuery()` outputs nested objects as string

### ISSUE THREAD

**Issue by codeflorist** [nuxt/nuxt#30249] opened 2024-12-13 10:08 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-papyryeu?file=server%2Fapi%2Ftest.ts

### Describe the bug

I state query params with a nested object using `$fetch` like this:

```js
const stories = await $fetch(`/api/test`, {
  query: {
    sort_by: 'position:asc',
    filter_query: {
      component: {
        in: 'my-components',
      },
    },
    version: 'draft',
    language: 'en',
  },
});
```

On the API route i use `getQuery` to resolve the quere params to a JS object:
```js
const query = getQuery(event);
```

This however results in the nested `filter_query` object to not get parsed into an object, but staying a string:

```js
{
  sort_by: 'position:asc',
  filter_query: '{"component":{"in":"my-components"}}',
  version: 'draft',
  language: 'en'
}
```

I would expect all params to be resolved just like i handed them over in `$fetch`.

### Logs

```shell-script

```

**Comment by amandesai01** [comment] 2024-12-14 18:47
This is a bug in unjs/ufo. I have created failing test case. You can track your resolution there.

**Comment by amandesai01** [comment] 2024-12-14 19:25
@codeflorist, my bad. See the following test:

https://github.com/unjs/ufo/blob/aa6d406587eafab106fa2cbee7406605903b02a7/test/query.test.ts#L85-L87

Seems like it is a desired behaviour. When you send query, obviously, it will serialise it correctly. But, on the other hand, `ufo` only deserialises at first level. So what you are getting is not a bug, rather a desired behaviour. You can close this issue (I believe), and we can have a discussion on whether we should allow nested parsing or not.

**Closed** 2024-12-15 10:47 UTC
Labels: pending triage, upstream

**Comment by codeflorist** [comment] 2024-12-15 10:57
@amandesai01 Many thanks for your initiative! I think it would definitely be a handy functionality - maybe via an optional parameter so it won't be a breakting change.
