### ISSUE TITLE
 ERROR  Error: Failed to download template from registry: Invalid URL

### ISSUE THREAD

**Issue by dark-noob83** [nuxt/nuxt#24453] opened 2023-11-24 13:08 UTC
### Environment

npx nuxi info

### Reproduction

Init new project using Nuxi.

npx nuxi init test

![Uploading alan.png…]()

### Describe the bug

when i use 
```
npx nuxi init nuxt-auth
```
get me this error how can fix it

**Comment by DamianGlowala** [comment] 2023-11-24 13:33
Duplicate of https://github.com/nuxt/nuxt/issues/24452

**Closed by DamianGlowala** 2023-11-24 13:33 UTC
Labels: 3.x, pending triage
