### ISSUE TITLE
Returns error while trying to use "npm run dev" on fresh installation

### ISSUE THREAD

**Issue by unnaturalistic** [nuxt/nuxt#19649] opened 2023-03-13 15:58 UTC
### Environment

Nuxt project info:                                                                             19:26:59

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `2.16.2`
- Nitro Version:    `-`
- Package Manager:  `npm@8.19.2`
- Builder:          `webpack`
- User Config:      `ssr`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `pwa`, `content`, `build`
- Runtime Modules:  `bootstrap-vue/nuxt`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/pwa@3.3.5`, `@nuxt/content@1.15.1`
- Build Modules:    `-`
------------------------------

### Reproduction

`npm run dev`

### Describe the bug

while trying to run a fresh installation of nuxt js problem encountered when using `npm run dev`

### Additional context

judging by the logs, this might be a webpack or babel issue 🤷‍♀️

### Logs

```shell-script
ERROR  Rule can only have one resource source (provided resource and test + include + exclude) in {     
  "type": "javascript/auto",
  "use": [
    {
      "loader": "E:\\project agora\\projectagora\\project_agora_nuxt_js\\node_modules\\babel-loader\\lib\\index.js",
      "options": {
        "configFile": false,
        "babelrc": false,
        "cacheDirectory": true,
        "envName": "client",
        "presets": [
          [
            "E:\\project agora\\projectagora\\project_agora_nuxt_js\\node_modules\\@nuxt\\babel-preset-app\\src\\index.js",
            {
              "corejs": {
                "version": 3
              }
            }
          ]
        ]
      },
      "ident": "clonedRuleSet-4.use[0]"
    }
  ]
}

  "type": "javascript/auto",
  "use": [
  {
  "loader": "E:\\project agora\\projectagora\\project_agora_nuxt_js\\node_modules\\babel-loader\\lib\\index.js",
  "options": {
  "configFile": false,
  "babelrc": false,
  "cacheDirectory": true,
  "envName": "client",
  "presets": [
  [
  "E:\\project agora\\projectagora\\project_agora_nuxt_js\\node_modules\\@nuxt\\babel-preset-app\\src\\index.js",
  {
  "corejs": {
  "version": 3
  }
  }
  ]
  ]
  },
  "ident": "clonedRuleSet-4.use[0]"
  }
  ]
  }
  at checkResourceSource (node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:167:11)
  at RuleSet.normalizeRule (node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:198:4)        
  at node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:110:20
  at Array.map (<anonymous>)
  at RuleSet.normalizeRules (node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:109:17)      
  at new RuleSet (node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:104:24)
  at new NormalModuleFactory (node_modules\@nuxt\webpack\node_modules\webpack\lib\NormalModuleFactory.js:115:18)
  at Compiler.createNormalModuleFactory (node_modules\@nuxt\webpack\node_modules\webpack\lib\Compiler.js:636:31)
  at Compiler.newCompilationParams (node_modules\@nuxt\webpack\node_modules\webpack\lib\Compiler.js:653:30)
  at Compiler.compile (node_modules\@nuxt\webpack\node_modules\webpack\lib\Compiler.js:661:23)
  at node_modules\@nuxt\webpack\node_modules\webpack\lib\Watching.js:77:18
  at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules\@nuxt\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:33:1)
  at AsyncSeriesHook.lazyCompileHook (node_modules\@nuxt\webpack\node_modules\tapable\lib\Hook.js:154:20)  at Watching._go (node_modules\@nuxt\webpack\node_modules\webpack\lib\Watching.js:41:32)
  at node_modules\@nuxt\webpack\node_modules\webpack\lib\Watching.js:33:9
  at Compiler.readRecords (node_modules\@nuxt\webpack\node_modules\webpack\lib\Compiler.js:529:11)       

```
```

**Comment by danielroe** [comment] 2023-03-13 16:25
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by orangeman12** [comment] 2023-03-13 16:49
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

sure!

**Comment by ndragun92** [comment] 2023-03-13 19:15
I literally have the same error with both 18.x and 16.x versions on clean npx create-nuxt-app

Node 18.12.1 and 16.19.1 both throw the same error (Feels like webpack 4/5 issue)

@danielroe 

package.json
```
{
  "name": "node-18",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint:js": "eslint --ext \".js,.ts,.vue\" --ignore-path .gitignore .",
    "lint:prettier": "prettier --check .",
    "lint": "npm run lint:js && npm run lint:prettier",
    "lintfix": "prettier --write --list-different . && npm run lint:js -- --fix"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "core-js": "^3.25.3",
    "nuxt": "^2.15.8",
    "vue": "^2.7.10",
    "vue-server-renderer": "^2.7.10",
    "vue-template-compiler": "^2.7.10"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.19.1",
    "@nuxt/types": "^2.15.8",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/eslint-config-typescript": "^11.0.0",
    "@nuxtjs/eslint-module": "^3.1.0",
    "eslint": "^8.24.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-vue": "^9.5.1",
    "prettier": "^2.7.1"
  }
}

```

**Comment by danielroe** [comment] 2023-03-13 19:31
Try setting your nuxt/types version either pinned to 2.15.8 or 2.16.2. There was a regression in one of our type dependencies that brought in the entirety of webpack 5.

**Comment by ndragun92** [comment] 2023-03-13 20:36
> Try setting your nuxt/types version either pinned to 2.15.8 or 2.16.2. There was a regression in one of our type dependencies that brought in the entirety of webpack 5.

Sticking to 2.16.2 did work for me indeed

**Comment by danielroe** [comment] 2023-03-13 22:38
Okay, this will be resolved on the next release. (The issue is that the version of `@nuxt/types` with the fix was released as `2x` tag rather than `latest`.)

**Comment by unnaturalistic** [comment] 2023-03-14 11:18
thanks for the help!

**Comment by unnaturalistic** [comment] 2023-03-14 11:38
what i did to fix it was:
use `npx nuxi init project_name`
and `cd project_name`
and `npm install`
and `npm run dev`
and that worked
i think using `npx nuxi` will make an installation of nuxt 3.x
anyway now we can continue our work

**Closed** 2023-03-14 11:41 UTC
Labels: pending triage, 2.x
