### ISSUE TITLE
CSS from multiple layouts is being included on individual pages

### ISSUE THREAD

**Issue by markplewis** [nuxt/nuxt#3877] opened 2018-09-11 21:26 UTC
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2) - v2.4.2 (see below).

### Reproduction link

[https://github.com/markplewis/nuxt-layout-css-issue](https://github.com/markplewis/nuxt-layout-css-issue)

### Steps to reproduce

1. Clone the following example repo.
2. Run `npm install` then `npm run dev`.
3. Navigate between the pages and inspect the CSS that's applied to the `<body>` element via your browser's dev tools.

https://github.com/markplewis/nuxt-layout-css-issue

### What is expected ?

When a page specifies a layout, like this:

**pages/index.vue:**
```
<script>
  export default {
    layout: "home"
  }
</script>
```

Only the CSS from the corresponding layout file should be included in the page:

**layouts/home.vue:**
```
<style>
  body {
    background-color: steelblue;
  }
</style>
```

### What is actually happening?

The CSS from every layout file is being included on every page, regardless of which layout is specified in the page's `.vue` file.

<img width="423" alt="screenshot" src="https://user-images.githubusercontent.com/2489555/45423911-d0be9000-b662-11e8-93c9-3c6def7a6fb7.png">

### Additional comments?

My example repo is using Nuxt Edge.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7723">#c7723</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-09-11 22:03
Can confirm this bug.

Workaround:

```js
 build: {
    splitChunks: {
      layouts: true
    }
}
```

**Comment by markplewis** [comment] 2018-09-12 12:00
This is also a problem in Nuxt v1 (see [the `v1` branch of my demo repo](https://github.com/markplewis/nuxt-layout-css-issue/tree/v1)). Styles from multiple layouts are still being pulled into the page, but at least I'm not seeing styles from the `default` layout:

<img width="401" alt="screen shot 2018-09-12 at 7 55 33 am" src="https://user-images.githubusercontent.com/2489555/45423507-8e488380-b661-11e8-98b2-0f9208647952.png">

**Comment by hareku** [comment] 2018-09-27 03:06
I have same issue.

**Comment by Legym** [comment] 2018-09-27 19:56
@hareku I was able to solve my issue using

 build: {
    splitChunks: {
      layouts: true
    }
}

**Comment by hareku** [comment] 2018-10-01 02:30
@Legym
Thanks!!!

**Comment by markplewis** [comment] 2018-10-02 12:31
I upgraded [my demo project](https://github.com/markplewis/nuxt-layout-css-issue) to Nuxt 2.1.0 and I'm still experiencing this problem. As @manniL stated above, adding `splitChunks: { layouts: true }` solves the problem for first render (i.e. loading the page directly or hard refreshing your browser), but the problem persists when navigating back and forth between pages after that.

My actual, real-world project only uses 2 layouts and it doesn't seem to be affected by this issue. I've also added `splitChunks: { layouts: true }` to that project. The problem persists in [my demo project](https://github.com/markplewis/nuxt-layout-css-issue), however, which uses 3 layouts. So, I wonder if the problem only crops up when there are more than 2 layouts?

**Comment by Legym** [comment] 2018-10-03 00:13
@markplewis I had a different folder setup than you. We created a theme system inside our nuxt build and each theme was locked into their own URL. We didn't go from one theme to another directly and so we didn't run into your issue. 

<img width="265" alt="screen shot 2018-10-02 at 7 50 31 pm" src="https://user-images.githubusercontent.com/4462368/46383091-8f773a00-c67c-11e8-8b6d-7b7ecef8152c.png">

`splitChunks: { layouts: true }`  did solve our issue because originally our styles in Layout would bleed into other themes. I.e Styles from Desktop were leaking into Mobile. 

However I would say the issue you are having is definitely a bug. The only suggestion I have is to do something like this

Layout 1
```
<template>
  <div>
    <nuxt/>
  </div>
</template>

<script>
export default {
  head() {
    return {
      bodyAttrs: {
        class: 'layout1'
      }
    }
  }
}

</script>

<style>
  .layout1 {
    background-color: steelblue;
  }
</style>
```


Layout 2
```
<template>
  <div>
    <nuxt/>
  </div>
</template>

<script>
export default {
  head() {
    return {
      bodyAttrs: {
        class: 'layout2'
      }
    }
  }
}

</script>

<style>
  .layout2 {
    background-color: steelblue;
  }
</style>
```

**Comment by sumeshkmp** [comment] 2018-10-12 14:07
The same issue happening for me also while loading loading layout dynamically

**Comment by fbrbovic** [comment] 2018-10-25 21:55
Still experiencing this problem too,  any solutions? ,  layouts true doesn't fix it.

**Comment by Atinux** [comment] 2018-11-09 09:46
We are currently working on a solution that could work without any changes, for both critical CSS and extractCSS modes. Stay tuned :)

**Comment by fbrbovic** [comment] 2018-11-09 15:05
Thanks,  my temporary solution was to import scss or styl file inside <script> tag which doesn't seem to leak css

**Comment by hareku** [comment] 2018-11-16 08:19
I want to use splitChunks with extractCSS option.

**Comment by rikoz** [comment] 2018-11-17 10:50
Any solution yet, I'm experiencing same here. Please I'm seeing a lot of temporaty fix but no detailed explanation of them. I need your help

Thanks

**Comment by jaredreich** [comment] 2018-12-17 19:17
> Issues that are labeled as 🕐Pending will not be automatically marked as stale.

Oops Stale Bot - you had one job! 😂 

Really excited for the Nuxt team to fix this one. Go team go! 😄 
(please don't stale/expire this issue...)

**Comment by menthol** [comment] 2018-12-22 09:58
I find a way to make it work on production, (no way yet for development).

in `nuxt.config.js`
```javascript
import crypto from 'crypto';

const BUILDID = crypto.randomBytes(10).toString('hex');

module.exports = {
   // ...
  build: {
    extractCSS: true,
    // ...
    filenames: {
      css: `${BUILDID}.[name].css`,
    },
    // ...
  },
  env: {
    BUILDID,
  },
};
```

in `layouts/*.vue`

```vue
<template>
  <nuxt />
</template>
<script>
  // Fake import, make extract css create a new file with specific chunkName
  export function css() { import(/* webpackChunkName: 'theme-pdp' */ '~~/themes/pdp/assets/style.css'); }

  export default {
    head() {
      return {
        link: [
          // integrate compiled file into current layout
          { type: 'text/css', rel: 'stylesheet', href: `/_nuxt/${process.env.BUILDID}.theme-pdp.css` },
        ],
      };
    },
  };
</script>
```

As the dev server use in-memory compilation, i wasn't able to find the correct path for integrate compiled css file into current page in development. If you want to try, make sure you freeze the extractCSS property, ex: `...Object.freeze({ extractCSS: true }),`;

**Comment by menthol** [comment] 2018-12-22 21:04
So, after some investigation, I succeeded make it work in dev :

in `nuxt.config.js`
```javascropt
import crypto from 'crypto';

const BUILDID = crypto.randomBytes(10).toString('hex');

module.exports = {
  // ...
  modules: [
    // ...
    '~/modules/ForceExtractCSS',
  ],
  // ...
  build: {
    extractCSS: true,
    // ...
    filenames: {
      css: `${BUILDID}.[name].css`,
    },
    // ...
  },
  env: {
    BUILDID,
  },
};
```

in `modules/ForceExtractCSS.js`
```javascript
export default function ForceExtractCSSModule() {
  this.nuxt.hook('ready', () => {
    this.options.build.extractCSS = true;
  });
}
```

and in `layouts/*.vue`
```javascript
<template>
  <nuxt />
</template>
<script>
  // Fake import, make extract css create a new file with specific chunkName
  export function css() { import(/* webpackChunkName: 'theme-default' */ '~/assets/style.css'); }

  export default {
    head() {
      return {
        link: [
          // integrate compiled file into current layout
          { type: 'text/css', rel: 'stylesheet', href: `/_nuxt/${process.env.BUILDID}.theme-default.css` },
        ],
      };
    },
  };
</script>
```

Canvas : HMR isn't working, `head()` isn't recalculated after HRM call

**Comment by fbrbovic** [comment] 2019-01-30 15:19
This is still broken in 2.4.0

**Comment by markplewis** [comment] 2019-02-17 18:17
FYI: I just updated [my demo project](https://github.com/markplewis/nuxt-layout-css-issue) to Nuxt 2.4.3.

**Comment by nick-lawrence** [comment] 2019-02-27 19:27
@markplewis Are you still experiencing this issue in the latest version?

I am currently in the middle of build using Nuxt 2.4.0 and undesired multiple Layout/CSS cross-compilation is still an issue.

**Comment by markplewis** [comment] 2019-03-21 14:29
@nick-lawrence I just upgraded my demo project to Nuxt 2.5 and I'm still experiencing this issue.

**Comment by ryanwinchester** [comment] 2019-03-29 20:55
So, I wanted my login page to have a coloured background and the default layouts to have a white background.

This silly workaround does the trick for me.

```js
  // login.vue
  beforeCreate() {
    document
      .getElementsByTagName('html')[0]
      .setAttribute('style', 'background-color: #4fc08d')
  }
```

```js
  // default.vue
  beforeCreate() {
    document.getElementsByTagName('html')[0].removeAttribute('style')
  }
```

**Comment by er1x** [comment] 2019-04-04 13:56
+1 (Nuxt v 2.4.0)

In my case not only the layout "leaks" CSS, "pages/index.vue" too.
I'm adding an extra layout and extra pages (using this layout) through a Nuxt module, as a some sort of sub-application:

`this.addLayout(path.resolve(__dirname, 'custom/layout.vue'), 'custom')
this.extendRoutes((routes, resolve) => {
  routes.push({
    path: '/subapp',
    name: 'subapp',
    component: resolve(__dirname, 'custom/subapp.vue')
  })
})`

**Comment by padinko** [comment] 2019-04-05 09:00
my workaround for now is

`nuxt.config.js`
```js
build: {
    splitChunks: {
      layouts: true
    }
}
```

and then reload page beafore each layout change, mixin in all layouts:
```js
    beforeCreate() {
        if (!process.server) {
            if (window.__NUXT_LAYOUT__ && window.__NUXT_LAYOUT__ !== this) {
                window.location.reload();
            }
            window.__NUXT_LAYOUT__ = this;
        }
    },
```

**Comment by christopherblack** [comment] 2019-10-03 16:19
Hello!
Is there any solution yet? Still experiencing the issue in Nuxt 2.9.2

**Comment by donni106** [comment] 2019-10-14 09:25
We have the same problem. It seems to work for us with scoping every layout <style>s. Can there be a problem with `<style scoped>` per layout?

**Comment by fachreza73** [comment] 2019-10-25 17:24
+1 

Nuxt 2.10.1

**Comment by UtopiaBe** [comment] 2019-10-30 07:37
I am having 2 languages, with RTL and LTR...
So i wanted to build 2 layouts to load RTL.CSS or LTR.CSS
And it uploads both of them :( so the website brokes...

Waiting for a solution.

**Comment by matrunchyk** [comment] 2019-11-04 08:37
Without this feature layouts are unusable for our projects.... Can we help you guys somehow?

**Comment by fachreza73** [comment] 2019-11-05 09:38
for now i m using this way.

give each layout a middleware.

each layout middleware should have code like this :

```
export default function(ctx) {
  const { redirect, app, from } = ctx;

  const link = [
    { rel: "icon", href: "admin-layout/img/icon.ico", type: "image/x-icon" },
    {
      rel: "stylesheet",
      href: "/admin-assets/css/bootstrap.min.css"
    },
    {
      rel: "stylesheet",
      href: "/admin-assets/css/atlantis.min.css"
    },
    {
      rel: "stylesheet",
      href: "/admin-assets/css/fonts.min.css"
    },
  ]
  
  const script = [
    { src: "/admin-assets/js/core/jquery.3.2.1.min.js" , body: true },
    { src: "/admin-assets/js/core/popper.min.js", body: true },
    { src: "/admin-assets/js/core/bootstrap.min.js", body: true },
    { src: "/admin-assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js", body: true },
    { src: "/admin-assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js", body: true }
  ]
  
  app.head.link = link;
  app.head.script = script;
}
```

for navigation between layout you should use `window.location.href`

**Comment by SHxKM** [comment] 2019-11-28 21:43
Any progress on this? I was sure I was doing something wrong. It's pretty much useless to use more than one default layout if CSS is getting merged...

**Comment by paulvonber** [comment] 2019-12-03 09:31
> Without this feature layouts are unusable for our projects.... Can we help you guys somehow?

exactly same here, we stuck totally with this, I already blaming myself for switching to nuxt. 
Overall layout styles should be scoped for everything what is included in that particular layout, otherwise they are just unusable.

**Comment by necony286** [comment] 2019-12-09 00:08
is this going to be fixed anytime soon please?

**Comment by matrunchyk** [comment] 2019-12-09 08:44
> We are currently working on a solution that could work without any changes, for both critical CSS and extractCSS modes. Stay tuned :)

Dear @Atinux, @alexchopin, @manniL, would you mind to give some feedback on this ticket. I'm sorry I'm and others bothering you here, but as you could probably see, this is a very important feature for us. For someone like me, it's a show-stopper. 

Please note, that I'm just asking about some feedback, not the implementation itself. For a project with 24k stars a year w/o a feedback doesn't make it trustworthy.

Have you started working on it? Could you please share some details of the implementation so we could potentially join? Or if you haven't, we would know that we can start our own research and potentially propose some PR?

Again, thank you guys for all you work you're doing here! This is worthless and today it is the best SSR framework for Vue. Sorry for my impatience and curiosity.

**Comment by MLDMoritz** [comment] 2019-12-15 14:03
I would love to help too, if there's anything people can do please tell us.

**Comment by gambolputty** [comment] 2020-01-04 22:26
This is still broken in 2.11.0

**Comment by julpat** [comment] 2020-01-05 16:57
I think this is related with [Issue with template styles not unmounting on programmatic navigation #2561](https://github.com/nuxt/nuxt.js/issues/2561#issuecomment-357179682) and the problem is in `vue-loader` when does not remove unused css in different layout/page (when you have `build.splitChunks.layouts === true` ).

**Comment by gambolputty** [comment] 2020-01-05 17:25
Another workaround could be to assign a class to the `<body>`-element and make sure, that all layout-related styles are part of that class-scope, e. g.
```css
body.layout1 .menu {  }
```

**Comment by Atinux** [comment] 2020-01-06 09:44
Hi there,

Sorry for the late answer and happy new year at the same time!

Actually one possibility is to use @gambolputty suggestion with `bodyAttrs`:

```js
<script>
// layouts/dark.vue
export default {
  head: {
    bodyAttrs: {
      class: "dark-theme"
    }
  }
};
</script>
```

And to prefix your style with `.dark-theme .my-class { ... }`.

Please find a live example here: https://codesandbox.io/s/nuxt-layouts-theming-ru954

We will beta test Vue 3 to test better layout scoping, will keep this thread updated.

**Comment by aloiki** [comment] 2020-01-09 09:27
I am using nuxt v.2.10 for a project and unfortunately it does not work with style files included in different layouts.

**Layout A:**
```
<template />

<style lang="scss">
  @import '@/assets/scss/layout-a.scss';
</style>
```

**Layout B:** 
```
<template />

<style lang="scss">
  @import '@/assets/scss/layout-b.scss';
</style>
```

I tried it with the options in **nuxt.config**  splitChunks.layout and extractCss but both configurations do not work. If the user switches the layout from **Layout A** to **Layout B** 
the style of the former layout is loaded. Our workaround at the moment is a hard page reload.

**Comment by AntonMoskalchenko** [comment] 2020-02-16 19:20
Still broken ^2.11.0

**Comment by moeinrahimi** [comment] 2020-03-21 14:32
@pi0 any idea on this if it's on the roadmap to fix or anything?

**Comment by stouch** [comment] 2020-03-28 08:20
Still broken (^2.0.0)

**Comment by stouch** [comment] 2020-03-28 08:21
I hope the guys who were working on it did not died of Covid  🤞

**Comment by stouch** [comment] 2020-03-28 08:48
any news on this ? 😢

**Comment by Atinux** [comment] 2020-03-28 21:39
After multiple investigations, we won’t be able to fix this in 2.X, better is to use a normal link (not Nuxt-link) if you really want to have a completely different CSS for each layout when switching.
The issues comes with vue-loader that include the <style> and we cannot track it to remove it dynamically at the moment :(

We are going to work with Vue 3 integration next week and see how we can enable this feature with it at the same time ☺️

**Comment by icai** [comment] 2020-03-29 04:07
Next.js also has this problem. Don't tangle. Caused by webpack hot update and history api.   one project try to use one reset css. one common css.  Or don't use <nuxt-link>, that should be ok. Or try listen to router change  to `add` or `remove` root className

**Comment by NotMoni** [comment] 2020-03-29 13:16
@icai mean Nuxt.js not Next.js

**Comment by iamareebjamal** [comment] 2020-03-29 13:34
@NotMoni And @icai means that Next.js (react) also has the same problem. It's not exclusive to Nuxt

**Comment by NotMoni** [comment] 2020-03-29 14:16
Oh sorry. Misunderstood that

**Comment by Jaynam07** [comment] 2020-04-08 09:46
Have multiple layouts, and each layout has it css - issue css gets overlapped all layouts.

Example
Layout A
Layout B

Layout A css get added to layout B css to

How to avoid this ?

**Comment by Flaviien** [comment] 2020-04-26 14:03
**This issue is now resolved in 2.12.2 !**
Patch note: https://fr.nuxtjs.org/guide/release-notes/#v2.12.2
"#7139 Sanitize layouts after resolve for splitChunks.layout"

Now you can use this in your nuxt.config.js:
`build: {
    splitChunks: {
      layouts: true
    }
}`

**Comment by Atinux** [comment] 2020-04-30 08:30
Well actually it won’t remove the cas injected by Layout A when moving to Layout B 😬

We are looking to add this feature in Nuxt 3 / Vue 3, it is something I would like to have inside Nuxt :)

**Comment by ronnidc** [comment] 2020-05-01 22:39
This example by @Atinux and @gambolputty below will work fine. But it's important to define the `bodyAttrs` `class` in **all** your layout files. 
> ```js
> <script>
> // layouts/dark.vue
> export default {
>   head: {
>     bodyAttrs: {
>       class: "dark-theme"
>     }
>   }
> };
> </script>
> ```

If you in some layouts don't want to define a classname you can add an empty classname in those layouts.

> ```js
> <script>
> // layouts/default.vue
> export default {
>   head: {
>     bodyAttrs: {
>       class: ""
>     }
>   }
> };
> </script>
> ```

**Comment by FarhanKhalid** [comment] 2020-05-21 15:10
Really big issue for me too, have tried all the things mentioned in this thread. The bodyAttrs workaround is too cumbersome and impractical for me since I have many CSS properties.

**Comment by vuhrmeister** [comment] 2020-05-27 12:19
Prefixing styles with a class added through `bodyAttrs` doesn't help me since I need to `@import` a generic file 🤷‍♂️
Too bad … my solution will be to add it in every page where necessary.

**Comment by myriky** [comment] 2020-07-05 16:40
any updates?

**Comment by ImSeaWorld** [comment] 2020-07-12 20:21
I think all of this could be saved by `vue-meta` if we were only allowed to include assets within `head()`. I'm considering rewriting in PHP because this is a bigger issue than I ever expected. Shame I have to have this issue near the end of my project. My frustrations with Nuxt goes further than this issue and my only hope is that some day I can come back to it, but this is the third major strike out for me.

**Comment by sqram** [comment] 2021-11-17 15:51
Bug still going strong

**Comment by gregg-cbs** [comment] 2022-07-13 12:34
I have fixed this by disabling `extractCSS`.

I also noticed a performance boost in lighthouse.

```javascript
  // nuxt.config.js
  build: {
    extractCSS: false, // true causes duplicate css
    splitChunks: {
      layouts: true
    },
  },
```

**Comment by justintien** [comment] 2022-12-30 05:12
So do @nuxt plan to solve this problem?

**Comment by muzafferkadir** [comment] 2023-02-18 13:13
still same

**Comment by trylovetom** [comment] 2023-03-14 12:48
3 years age, bug still here

**Comment by tleperou** [comment] 2023-05-01 23:51
👍 on here

**Comment by Joscha95** [comment] 2023-07-28 09:11
i have the same issue with nuxt keeping the css from the previous pages after navigation in nuxt 3.6.3

**Comment by danielroe** [comment] 2023-08-25 16:47
@matthew-dean I suspect you're talking about the browser behaviour that respects the first definition of a global style. (Also, once loaded, CSS won't be unloaded from the browser.)

It's not a Nuxt bug, or indeed a bug at all.

Rather, you should probably use scoped styles or CSS modules to avoid this kind of specificity issue.

**Comment by danielroe** [comment] 2023-08-25 16:58
@matthew-dean Would you open a new issue with a reproduction, so we can discuss it better? This issue is about layout CSS and is not related to Nuxt 3 - it was opened 5 years ago.

**Comment by manniL** [comment] 2023-12-11 18:40
I wonder if this wouldn't be the same solution as #22871 - treating it not as a bug but possible expecting behavior which can be resolved by using the `deep` selector (Nuxt 2/Vue2) 🤔

**Closed** 2023-12-11 18:46 UTC
Labels: pending, pending triage, 2.x
