### ISSUE TITLE
Hydration mismatch warning when using a rich-text renderer

### ISSUE THREAD

**Issue by willylatorre** [nuxt/nuxt#22128] opened 2023-07-13 15:03 UTC
### Environment

Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.1.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/dreamy-mcclintock-3j327f

### Describe the bug

Using a rich-text renderer causes an hydration mismatch in nuxt3. It did not happen in nuxt2.

Looking at the [source code of the library](https://github.com/paramander/contentful-rich-text-vue-renderer/blob/master/src/index.js), shows that it does nothing special, just renders a series of elements. But the output that the server throws is a mismatch with the one that the client throws. Seems like the server only renders the first child?

Do you have any hints to what I should investigate?

### Logs

```shell-script
Vue warn]: Hydration text mismatch:
- Client: "When we launched in 2006, our ambition was simple: help businesses grow. We started with payments, taking an engineering-first approach to solving some of the most complex challenges. Today, we are the preferred financial technology platform of many of the world's leading brands. We did this by working with exceptional talent, prioritizing success over ego, and having fun along the way."
- Server: "When we launched in 2006, our ambition was simple: help businesses grow. We started with payments, taking an engineering-first approach to solving some of the most complex challenges. " 
  at <RichText document= Objectcontent: Array(2)0: {data: {…}, content: Array(6), nodeType: 'paragraph'}content: (6) [{…}, {…}, {…}, {…}, {…}, {…}]data: {}nodeType: "paragraph"[[Prototype]]: Object1: {data: {…}, content: Array(1), nodeType: 'paragraph'}length: 2[[Prototype]]: Array(0)data: {}nodeType: "document"[[Prototype]]: Object > 
  at <RichText> 
  at <App key=2 > 
  at <NuxtRoot>
warn2 @ chunk-Q53DPCWL.js:1381
```
```

**Comment by manniL** [comment] 2023-07-13 15:38
It seems there *is* a mismatch 🤔

Server result:

```
<p>When we launched in 2006, our ambition was simple: help businesses grow. We started with payments, taking an
          engineering-first approach to solving some of the most complex challenges. Today, we are the preferred
          financial technology platform of many of the world&#39;s leading brands. We did this by working with
          exceptional talent, prioritizing success over ego, and having fun along the way.</p>
        <p>To continue driving towards our long-term ambitions, we’re looking for innovative problem solvers, strategic
          thinkers, and colleagues we can count on.</p>
```

Client:

```
<p>When we launched in 2006, our ambition was simple: help businesses grow. We started with payments, taking an
          engineering-first approach to solving some of the most complex challenges. Today, we are the preferred
          financial technology platform of many of the world's leading brands. We did this by&nbsp;working with
          exceptional talent, prioritizing success over ego, and having fun along the way.</p>
        <p>To continue driving towards our long-term ambitions, we’re looking for innovative problem solvers, strategic
          thinkers, and colleagues we can count on.</p>
          ```

(On the train so only limited debugging capabilities due to wifi)

**Comment by willylatorre** [comment] 2023-07-13 15:44
Hmmm, I cannot pinpoint what could cause the mismatch as it is the same data. And same code executed.
In your example I see the ` the world&#39;s ` vs ` the world's`, although in the warning message it seemed like it was missing a whole block:

>- Client: "When we launched in 2006, our ambition was simple: help businesses grow. We started with payments, taking an engineering-first approach to solving some of the most complex challenges. Today, we are the preferred financial technology platform of many of the world's leading brands. We did this by working with exceptional talent, prioritizing success over ego, and having fun along the way."
- Server: "When we launched in 2006, our ambition was simple: help businesses grow. We started with payments, taking an engineering-first approach to solving some of the most complex challenges. "

**Comment by willylatorre** [comment] 2023-07-13 15:45
Only reason that I can think, is that now it uses `import { h } from 'vue'` instead of the `createElement` function that was passed before.

**Comment by danielroe** [comment] 2023-07-13 17:33
Neither of these is a Nuxt issue, from what I can tell. Check if you can reproduce with https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter. This may be a difference with how Vue 3 handles whitespace.

**Comment by willylatorre** [comment] 2023-07-14 08:11
@danielroe Correct, it does also throw the error in the vue3-ssr-starter https://stackblitz.com/edit/github-6za3kr?file=src%2Fpages%2FHome.vue

Where should I report it?

**Comment by danielroe** [comment] 2023-07-14 13:58
Thanks for opening that issue. ❤️ I'm going to close it here as it's not an issue with Nuxt.

**Closed by danielroe** 2023-07-14 13:58 UTC
Labels: 3.x, pending triage, upstream

**Comment by MuhammadKhizar7** [comment] 2023-10-04 12:44
I am not sure its same issue but I think but when we use textarea to save text it throw same mismatch issue
here is example can be reproduce 
```
<p> Some text without any new line or spaces </p> 
```
works find but when we do 
```
<p> Some text with new line and space  
 Some text with new line and space 

Some text with new line and space 
Some text with new line and space 

Some text with new line and space </p>
```
Now it throw error hydration mismatch issue
