### ISSUE TITLE
postcss-px-to-viewport这个插件不能配置参数传入？

### ISSUE THREAD

**Issue by wlinglinux** [nuxt/nuxt#8401] opened 2020-11-26 07:21 UTC

**Comment by wlinglinux** [comment] 2020-11-26 07:24
postcss-px-to-viewport这个插件在vue中可以通过配置postcss.config.js文件中的
module.exports = ({ file }) => {
  const designWidth = file.dirname.includes(path.join('node_modules', 'vant')) ? 375 : 750;
  return {
    plugins: {
      autoprefixer: {},
      "postcss-px-to-viewport": {
        unitToConvert: "px",
        viewportWidth: designWidth,
}}将参数传入，但是nuxt中怎么配置？

**Comment by danielroe** [comment] 2020-11-26 07:26
@wlinglinux You should normally configure postcss plugins within your nuxt configuration like this:

https://nuxtjs.org/faq/postcss-plugins/#recommended-method

Does that hello?

**Comment by wlinglinux** [comment] 2020-11-26 07:30
![Uploading image.png…]()

**Comment by wlinglinux** [comment] 2020-11-26 07:31
![git](https://user-images.githubusercontent.com/286261/100320678-7f5d0a00-2ffc-11eb-8826-1a27a63b145b.png)

**Comment by wlinglinux** [comment] 2020-11-26 07:36
![git_](https://user-images.githubusercontent.com/286261/100320945-e8448200-2ffc-11eb-80c3-f2ac3dd9c5dc.png)
这样配置在nuxt中是不能正常执行的，我想知道在nuxt中应该如何配置可以将file这个参数传入，并能正确执行，谢谢！！

**Comment by danielroe** [comment] 2020-11-26 07:36
@wlinglinux I do not know what the text in the image says. Could you write it in your comment?

**Comment by danielroe** [comment] 2020-11-26 07:39
@wlinglinux You can import `path` into your nuxt config, and you can access the directory with `__dirname`

**Comment by wlinglinux** [comment] 2020-11-26 07:54
**const designWidth = file.dirname.includes(path.join('node_modules', 'vant')) ? 375 : 750;**   这里的file.dirname是需要处理的css的文件，不是__dirname这个值；
这样配置   **viewportWidth: __dirname.includes(path.join('node_modules', 'vant')) ? 375 : 750**   得到的永远都是750；

**Comment by danielroe** [comment] 2020-11-26 09:48
@wlinglinux You should be able to pass a function as the config for the postcss loader - details [here](https://github.com/webpack-contrib/postcss-loader#function).

**Comment by wlinglinux** [comment] 2020-11-27 11:27
如果在nuxt.config.js中配置postcss-loader的rules属性，console就提示 ### You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js. 但是nuxt不是不支持在单独的文件中配置postcss属性？

**Comment by danielroe** [comment] 2020-11-29 11:24
@wlinglinux Seems to be working fine for me:

https://codesandbox.io/s/wizardly-cdn-ts7sq?file=/pages/index.vue

**Comment by wlinglinux** [comment] 2020-11-30 02:10
![px_viewport_0](https://user-images.githubusercontent.com/286261/100561350-b03a8900-32f3-11eb-8c75-fc4894321901.png)
![px_viewport_1](https://user-images.githubusercontent.com/286261/100561359-b4ff3d00-32f3-11eb-9939-0c15f4cee437.png)
按照你给的配置显示的页面是第一个图，但是这个显示是不对的。

正确的显示如下图：
![px_viewport_2](https://user-images.githubusercontent.com/286261/100561420-d52efc00-32f3-11eb-9bcb-c39c9161eabf.png)
![px_viewport_3](https://user-images.githubusercontent.com/286261/100561424-d829ec80-32f3-11eb-9109-3ed3d1279de8.png)

我测试的结果就是，通过参数传递 file的配置 显示是不对的。

**Comment by danielroe** [comment] 2020-11-30 07:55
@wlinglinux Would you provide a reproduction? Are you sure this is an issue with Nuxt?

**Comment by wlinglinux** [comment] 2020-11-30 13:31
https://codesandbox.io/s/runtime-wind-n31k1?file=/nuxt.config.js，你帮忙看看，我在nuxt.config.js注释掉的是传入file参数的配置，开启这个配置，页面转化的vw是不对的。

**Comment by wlinglinux** [comment] 2020-11-30 13:32
[https://codesandbox.io/s/runtime-wind-n31k1?file=/nuxt.config.js](https://codesandbox.io/s/runtime-wind-n31k1?file=/nuxt.config.js)，你帮忙看看，我在nuxt.config.js注释掉的是传入file参数的配置，开启这个配置，页面转化的vw是不对的。

**Comment by Xiamer** [comment] 2020-12-01 01:51
> https://codesandbox.io/s/runtime-wind-n31k1?file=/nuxt.config.js，你帮忙看看，我在nuxt.config.js注释掉的是传入file参数的配置，开启这个配置，页面转化的vw是不对的。

Speak english as much as possible so that others can help you.

**Comment by Xiamer** [comment] 2020-12-01 01:53
> @wlinglinux Would you provide a reproduction? Are you sure this is an issue with Nuxt?

i think this is not nuxt problem O(∩_∩)O

**Comment by wlinglinux** [comment] 2020-12-01 02:07
I just want to ask if NUXT doesn't support passing in parameters for postCSS-Px-to-Viewport? If not, can it be supported in the next release? Because the result of my test is that the parameters passed in are invalid, even if the configuration is correct.

**Comment by wlinglinux** [comment] 2020-12-01 02:10
The result of my test is that configuration in postcss.config.js is passable in the vue environment, but not in nuxt how it should be configured to work.

**Comment by Ryan2018-js** [comment] 2020-12-03 01:20
the same questions，file.dirname  ineffectiveness

**Comment by wlinglinux** [comment] 2020-12-03 02:00
Can this problem be fixed?

**Comment by CeliaYang** [comment] 2020-12-24 04:08
![image](https://user-images.githubusercontent.com/28923735/103058565-6f295200-45dd-11eb-81dc-b964cbfbb25c.png)

The postcss-px-to-viewport parameter only supports objects. In addition, the options of postcss can only be objects. Therefore, I created postcss.config.js and it seems to work well.

![image](https://user-images.githubusercontent.com/28923735/103059460-2757fa00-45e0-11eb-968c-c5ca06dfb6f6.png)

**Comment by wlinglinux** [comment] 2021-01-12 09:04
The configuration in the postcss.config.js file is incorrect, as shown in the figure
![image](https://user-images.githubusercontent.com/286261/104291896-1a4f6c00-54f7-11eb-8f46-df5ddab2cf6c.png)
￼
Also, configuring in postcss.config.js will prompt the figure in console
![image](https://user-images.githubusercontent.com/286261/104292656-0d7f4800-54f8-11eb-81ea-f00295f48ece.png)


The correct page displays as shown in the picture
![image](https://user-images.githubusercontent.com/286261/104292131-669aac00-54f7-11eb-8d3e-21076df5c5f6.png)

**Comment by abelshare** [comment] 2021-04-07 06:47
Is there a better solution?

**Comment by geng130127** [comment] 2021-11-09 08:19
请问这个问题最后解决了吗。

**Comment by danielroe** [comment] 2023-02-15 00:53
With 2.16.0 release with PostCSS 8 support, I think we can close this. Let me know if not and if it is still an issue for you.

**Closed by danielroe** 2023-02-15 00:53 UTC
Labels: enhancement, 2.x, needs reproduction
