### ISSUE TITLE
The ref value in the template must be added with .value before it can respond

### ISSUE THREAD

**Issue by cdwmhcc** [nuxt/nuxt#26485] opened 2024-03-26 05:21 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      runtimeConfig, colorMode, devtools, vite
- Runtime Modules:  @nuxtjs/color-mode@3.3.3, @nuxt/image@1.4.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-uwqn1p?file=app.vue

### Describe the bug

Normally, there is no need to add .value to the ref value in the template, but now there is a problem that .value must be added to respond.

I'm not sure if this is a nuxt3 issue or a vue3 issue.

**Comment by bargel** [comment] 2024-03-26 06:13
not really a bug
https://vuejs.org/guide/essentials/reactivity-fundamentals#caveat-when-unwrapping-in-templates

**Comment by cdwmhcc** [comment] 2024-03-26 08:37
> not really a bug
> 
> https://vuejs.org/guide/essentials/reactivity-fundamentals#caveat-when-unwrapping-in-templates

thank you！

**Comment by huang-julien** [comment] 2024-03-26 09:16
It's indeed not a bug. I'm closing it :)

**Closed by huang-julien** 2024-03-26 09:16 UTC
Labels: 3.x, pending triage
