### ISSUE TITLE
Layer not working when published to npm

### ISSUE THREAD

**Issue by wgbnyes** [nuxt/nuxt#22419] opened 2023-07-31 17:56 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      ssr, extends, modules, vuefire, runtimeConfig, css, build
- Runtime Modules:  @formkit/nuxt@0.16.5
- Build Modules:    --

### Reproduction

- Create a normal nuxt 3 app project
- Create a nuxt 3 layer project
- Add some libraries in the layer project, example: vueuse, firebase, vuefire, atob, crypto.js, etc...
- Create composables on layer project to share
- In the app project, extend from the project layer using a local path
- npm run dev and everything will be fine

- Now in layer project run npm run build
- Then run npm publish --access public
- In app project do npm intall your-layer-package

### Describe the bug

- Replace the app project extends with the name of the newly installed lib, example: extends: ['your-layer-package']
- Try npm run dev on the app project again and you will get some errors for some of the installed packages.
In my case it was the atob and btoa packages.
I also get nuxt cache error when enabling ssr: true in app project.

### Logs

```shell-script
The requested module '/_nuxt/node_modules/crypto-js/aes.js?v=0e140044' does not provide an export named 'default'
```

**Comment by derHodrig** [comment] 2023-08-01 11:44
At the `nuxt.config.ts` of your app layer (the top)
add the vite section as shown


```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  extends: ['YOUR_LAYER'],
  vite: {
    optimizeDeps: {
      include: [
        'crypto-js' // or other packages, which lead to this issue
      ]
    }
  },
})
```

**Comment by derHodrig** [comment] 2023-08-01 11:45
Duplicate of https://github.com/nuxt/nuxt/issues/19426

**Comment by wgbnyes** [comment] 2023-08-02 10:29
But this is counterproductive! Imagine I'm developing a lib and I want to share it publicly with other people via NPM. I cannot require this level of configuration for anyone wanting to use my lib! I don't need to do this with any other lib in any other development stack I've ever used.

**Comment by wgbnyes** [comment] 2023-08-02 10:40
@derHodrig However, including the package in optimizeDeps did nothing.

**Comment by danielroe** [comment] 2023-08-03 16:49
Let's track in https://github.com/nuxt/nuxt/issues/19426.

Note that you can add configuration (optimizeDeps) in the layer itself so your consumers don't need to add it.

**Closed by danielroe** 2023-08-03 16:49 UTC
Labels: 3.x, pending triage, layers
