### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '__asyncLoader') on this.$router.push(menu.url)

### ISSUE THREAD

**Issue by muhammad-grayphite** [nuxt/nuxt#20363] opened 2023-04-18 15:13 UTC
### Environment

This is my package.json dependencies

{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "engines": {
    "node": ">=18.0.0"
  },
  "devDependencies": {
    "nuxt": "^3.4.1"
  },
  "dependencies": {
    "@mdi/font": "^7.1.96",
    "@mdi/js": "^7.1.96",
    "@pinia/nuxt": "^0.4.6",
    "@vuepic/vue-datepicker": "^4.2.3",
    "axios": "^1.2.2",
    "pinia": "^2.0.29",
    "sass": "^1.58.0",
    "vuetify": "^3.1.14"
  },
  "overrides": {
    "vue": "latest"
  }
}

### Reproduction

Ah I dont have it right now

### Describe the bug

Basically we are migrating from nuxt2 to nuxt3, we have a menu bar in the left corner, by clicking on them user can go to the other pages of the site. on clicking the menu we are using nuxt this.$router.push(slug), but when for some reason it throws an error 
`peError: Cannot read properties of undefined (reading '__asyncLoader')`

This is the code that run after selecting the nav item. I have checked if I comment out this.$router.push it works fine.
`       onNavClick(menu) {
            try{
                this.isHidden = !this.isHidden;
                if (menu.url.match('http')) {
                    window.open(menu.url, '_blank');
                } else {
                    this.$router.push(menu.url);
                }
            }catch(e){
                console.error(e)
            }   `

I am clueless here, I'll appreciate if you guys can give me some hints. Also attaching screenshot and a gif to clerify 
<img width="1398" alt="Screenshot 2023-04-18 at 7 36 22 PM" src="https://user-images.githubusercontent.com/85872908/232811810-bfda8808-8d57-48f9-9a55-13407b4ada12.png">
 
![routerbug](https://user-images.githubusercontent.com/85872908/232820764-840fbc7b-1920-4aad-bbfc-f83f227b6474.gif)

### Logs

```shell-script
caught (in promise) TypeError: Cannot read properties of undefined (reading '__asyncLoader')
    at isAsyncWrapper (chunk-FGDF3JHL.js:7497:1)
    at unmount (chunk-FGDF3JHL.js:5867:1)
    at unmountComponent (chunk-FGDF3JHL.js:5959:1)
    at unmount (chunk-FGDF3JHL.js:5873:1)
    at unmountChildren (chunk-FGDF3JHL.js:5979:1)
    at unmount (chunk-FGDF3JHL.js:5888:1)
    at unmountComponent (chunk-FGDF3JHL.js:5959:1)
    at unmount (chunk-FGDF3JHL.js:5873:1)
    at unmountChildren (chunk-FGDF3JHL.js:5979:1)
    at unmount (chunk-FGDF3JHL.js:5886:1)
```

**Comment by danielroe** [comment] 2023-04-18 15:19
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by ckouder** [comment] 2023-04-18 16:52
I'm having the same problem. In my case, the problem is solved when I comment out the `v-toolbar-title` and `v-app-bar-title` line. It might be a bug of Vuetify I think

**Comment by pavloniym** [comment] 2023-04-27 19:44
Same error
Reproduction steps:
1. Open fresh page with NOT `default layout`
2. Make $router.replace({name: 'home'}) to get to home page with `default layout`
3. Catch an error

```js
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <FragmentWrapper > 
  at <NuxtLayout> 
  at <VApp> 
  at <App key=3 > 
  at <NuxtRoot>
```

```js
chunk-LGAZO65B.js?v=c0b43372:3361 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__asyncLoader')
```


BUT
1. Load home page (with `default layout`)
2. Go to login screen (`clean layout`)
3. Make $router.replace({name: 'home'}) to return back to home page with `default layout`
4. No error ...

**Comment by danielroe** [comment] 2023-04-28 08:42
@pavloniym If would be very helpful if you would create a reproduction from https://stackblitz.com/github/nuxt/starter/tree/v3.

**Comment by bilal-grayphite** [comment] 2023-05-01 15:16
So I fixed this issue by adding **defineAsyncComponent**. if you are importing components dynamically like ()=> import() you need import like this.
`component: defineAsyncComponent(() => import('component'))`
I had some dynamic imports like this `comp: () => import('../../comp.vue')`, I changed them like above and it is working fine now. here is from official doc https://vuejs.org/guide/components/async.html#basic-usage.

this https://github.com/nuxt/nuxt/issues/13309 thread helped me specially https://github.com/nuxt/nuxt/issues/13309#issuecomment-1398427660

**Comment by pavloniym** [comment] 2023-05-02 16:31
@bilal-grayphite Thanks, but not working for me ...

My routing file
```js

import {defineAsyncComponent} from 'vue'

// Routes
export const HOME_ROUTE = 'HOME_ROUTE'

export default [
    {
        path: '/',
        name: HOME_ROUTE,
        meta: { layout: 'app' },
        component: defineAsyncComponent(() => import('~/pages/home/HomePage'))
    }
]

```

Console warning from nuxt
```
vue-router.js?v=b113b80d:43 [Vue Router warn]: Component "default" in record with path "/home" is defined using "defineAsyncComponent()". Write "() => import('./MyPage.vue')" instead of "defineAsyncComponent(() => import('./MyPage.vue'))".
```

**Comment by bilal-grayphite** [comment] 2023-05-10 09:08
@pavloniym sorry for late reply. are you still getting this error?
basically we were using some dyanamic imports without defineAsyncComponent and some with it. I simply changed them using defineAsyncComponent in the whole project and its working fine. try using `defineComponent` if that works. maybe there is am issue with using different layouts.

**Comment by pavloniym** [comment] 2023-05-11 11:22
After my recovery and some code research i have found an issue:

This variant produces an error:
```vue
<v-list-subheader v-text='"OR"' />
```

This variant works correct, without error:
```vue
<v-list-subheader>OR</v-list-subheader>
```

`v-list-subheader` - vuetify component (test on vuetify v3+).
Do not know why this syntax `'"OR"'` crashes vue/nuxt ...

**Comment by 5e** [comment] 2023-08-01 09:33
I have updated to:

"vue-router": "^4.2.4",
 "vuetify": "^3.3.10",

and I no longer get this problem

**Comment by danielroe** [comment] 2023-08-01 09:34
Closing as this is not a Nuxt issue.

**Closed** 2023-08-01 09:34 UTC
Labels: 3.x, pending triage, needs reproduction
