### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'plugins')

### ISSUE THREAD

**Issue by hi-huonsokly** [nuxt/nuxt#18798] opened 2023-02-06 03:53 UTC
### Environment

npm: 9.3.1 
node: 14.17.5

### Reproduction

/

### Describe the bug

I've got this message when I: npm run dev

**Comment by wwwwfeng** [comment] 2023-02-06 05:43
I also ran into this problem, did you solve it

**Comment by hi-huonsokly** [comment] 2023-02-06 06:29
@wwwwfeng Currently I don't know how to solve, but now I'm using node_modules from my other project for temporary.

**Comment by manniL** [comment] 2023-02-06 08:59
Hey! Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by vanminhquangtri** [comment] 2023-02-06 10:36
Hi @manniL, @hi-huonsokly, this error will happen when we run npm install for the whole project, like when we deploy.

This is because the new version of @nuxt/config 2.16.0 generates a new config file different with the old version, file path: node_modules\@nuxt\config\dist\config.js

The problem is caused by these codes:
```
if (options.build.postcss.plugins) {
    consola.warn("`postcss.plugins` option has been moved to `postcss.postcssOptions.plugins` for aligning `postcss-loader` format.");
    options.build.postcss.postcssOptions.plugins = options.build.postcss.plugins;
    delete options.build.postcss.plugins;
  }
```
So if the options.build.postcss === null, the error will occur.

My old version: 2.15.8 doesn't have this error.

You can check your nuxt.config.js about postcss of build property . In my case, I remove postcss and it works because I currently set it === null

I think @nuxt/config should use optional chaining, such as if (build?.postcss?.plugins) to avoid cases like me.

![image](https://user-images.githubusercontent.com/70369658/216949957-a77a710c-3002-401e-baea-c504beb0b258.png)

**Comment by hi-huonsokly** [comment] 2023-02-06 13:42
> Hey! Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Thank you for your reply.

**Comment by hi-huonsokly** [comment] 2023-02-06 13:45
> Hi @manniL, @hi-huonsokly, this error will happen when we run npm install for the whole project, like when we deploy.
> 
> This is because the new version of @nuxt/config 2.16.0 generates a new config file different with the old version, file path: node_modules@nuxt\config\dist\config.js
> 
> The problem is caused by these codes:
> 
> ```
> if (options.build.postcss.plugins) {
>     consola.warn("`postcss.plugins` option has been moved to `postcss.postcssOptions.plugins` for aligning `postcss-loader` format.");
>     options.build.postcss.postcssOptions.plugins = options.build.postcss.plugins;
>     delete options.build.postcss.plugins;
>   }
> ```
> 
> So if the options.build.postcss === null, the error will occur.
> 
> My old version: 2.15.8 doesn't have this error.
> 
> You can check your nuxt.config.js about postcss of build property . In my case, I remove postcss and it works because I currently set it === null
> 
> I think @nuxt/config should use optional chaining, such as if (build?.postcss?.plugins) to avoid cases like me.
> 
> ![image](https://user-images.githubusercontent.com/70369658/216949957-a77a710c-3002-401e-baea-c504beb0b258.png)

That's nice advice, you make my day @vanminhquangtri . Many thanks!

**Comment by manniL** [comment] 2023-02-06 13:54
I'd leave it open so it can be fixed 😋

**Comment by hi-huonsokly** [comment] 2023-02-06 13:58
Ok Ok 😄

**Comment by wwwwfeng** [comment] 2023-02-06 14:20
Thank you so much for sharing your experience, it works

**Comment by danielroe** [comment] 2023-02-06 22:59
resolved in https://github.com/nuxt/nuxt/pull/18839

**Closed by danielroe** 2023-02-06 22:59 UTC
Labels: workaround available, 2.x, bug, ❗ p4-important
