### ISSUE TITLE
`Unknown component mode: null` after upgrading to Nuxt `v3.4.3`

### ISSUE THREAD

**Issue by aa-ndrej** [nuxt/nuxt#20650] opened 2023-05-03 12:44 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-28uc9k?file=app.vue

### Describe the bug

After upgrading to Nuxt `v3.4.3` I get the following error:
```shell
 ERROR  Internal server error: Unknown component mode: null, this might be an internal bug of Nuxt.
  Plugin: nuxt:components:imports
  File: /Users/.../assets/placeholder.svg?component
      at TransformContext.transform (file:///Users/.../node_modules/nuxt/dist/index.mjs:1289:17)
      at plugin.transform (file:///Users/.../node_modules/unplugin/dist/index.mjs:1158:25)
      at Object.transform (file:///Users/.../node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42871:44)
      at async loadAndTransform (file:///Users/.../node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:53335:29)
```

I am using the [Vite SVG Loader](https://github.com/jpkleemans/vite-svg-loader) plugin
and the error is thrown when importing a SVG files with
```ts
import Logo from 'assets/placeholder.svg?component';
```
In Nuxt version `v3.4.2` everything is working.

### Additional context

https://github.com/nuxt/nuxt/blob/da3357449f456632bb2f07893c5d24065b081f53/packages/nuxt/src/components/transform.ts#L73

**Comment by davidglezz** [comment] 2023-05-03 13:08
Same error. I have also `vite-svg-loader`

**Comment by danielroe** [comment] 2023-05-03 13:42
Yes, this is an unintended regression in the latest version. I wonder if we can just silently ignore modes that aren't picked by nuxt - or maybe use a query that is more nuxt-specific (e.g. `nuxt-component`)? What do you think @antfu?

**Comment by antfu** [comment] 2023-05-03 14:03
We already made it nuxt-specific:
https://github.com/nuxt/nuxt/blob/da3357449f456632bb2f07893c5d24065b081f53/packages/nuxt/src/components/transform.ts#L53

**Comment by danielroe** [comment] 2023-05-03 14:06
Quite right. 😆

**Comment by LarsDol** [comment] 2023-05-03 14:56
Same issue for us. Breaks all `svg` icons on our website(s) after a routine software update.

Could this be patched ASAP? Or is a workaround available?

**Comment by antfu** [comment] 2023-05-03 14:58
@danielroe Maybe we should do that patch? If I understand correctly our main branch is for next minor right?

**Comment by danielroe** [comment] 2023-05-03 15:08
We'll be releasing a prerelease this week for next week's minor (`3.5-beta`). There will also be the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) as soon as a fix is merged.

@antfu if you think it's more urgent than that we could also make a patch release.

**Comment by antfu** [comment] 2023-05-03 15:50
Yeah, good point - I do consider it's not that urgent, as we only get conflicts with vite-svg-loader right?

@LarsDol do you think pining the version to 3.4.2 and waiting until 3.5 a feasible workaround to you?

**Comment by LarsDol** [comment] 2023-05-03 19:48
@antfu this seems to be working for now! Looking forward to the upcoming release 👍

Thanks for the swift response!

**Comment by lammerfalcon** [comment] 2023-05-04 08:02
i have the same issue on production when docker build
<img width="781" alt="image" src="https://user-images.githubusercontent.com/47675540/236145125-f5a39c58-164b-4e9a-9762-aa8971b33543.png">

**Comment by Vsevosemnog** [comment] 2023-05-10 15:41
Hello

has the same issue 
![image](https://github.com/nuxt/nuxt/assets/37411749/0cc946c9-baa8-4f5d-94b4-11547306f2ba)

how to resolve it?

**Comment by danielroe** [comment] 2023-05-10 15:45
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Closed by danielroe** 2023-05-10 15:45 UTC
Labels: 3.x, bug, 🔨 p3-minor-bug
