### ISSUE TITLE
useFetch bug when watch query

### ISSUE THREAD

**Issue by DJafari** [nuxt/nuxt#24345] opened 2023-11-16 20:27 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.7.0`
- Nuxt Version:     `3.8.1`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `npm@10.1.0`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-8eshfb?file=app.vue

### Describe the bug

When I want to automatically reload the useFetch when the query string changes, I encountered a bug. This only happens when SSR (Server-Side Rendering) is active. When the page is supposed to load for the first time, the request is not only executed on the server side but also on the client side, resulting in a [Vue warn]: Hydration error.

**Comment by manniL** [comment] 2023-11-16 20:36
Duplicate of https://github.com/nuxt/nuxt/issues/24294

**Closed by manniL** 2023-11-16 20:36 UTC
Labels: 3.x, pending triage

**Comment by DJafari** [comment] 2023-11-16 20:49
@manniL thanks for your answer
can you help me to use nuxt from nightly channel ?

i changed `"nuxt": "^3.8.1",` to `"nuxt": "npm:nuxt-nightly@latest"` and remove `package-lock.json` and `npm install`

but this problem exists yet and i have hydration mismatch error again

**Comment by manniL** [comment] 2023-11-16 21:07
@DJafari Yes, it should work like you said (and as [described here](https://github.com/nuxt/nuxt/issues/24294))

**Comment by DJafari** [comment] 2023-11-16 21:26
thanks again! @manniL 

because my project has some packages that depends to nuxt, it's must add this to my packages.json

```json
"overrides": {
    "nuxt": "npm:nuxt-nightly@latest"
  }
```
