### ISSUE TITLE
Calling `useHead` after an asynData cause freezing head tags

### ISSUE THREAD

**Issue by farnabaz** [nuxt/nuxt#19244] opened 2023-02-23 15:12 UTC
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
---
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ezanbf?file=components%2FTest.vue,pages%2Findex.vue,pages%2Finvalid.vue,app.vue

Originally reported in https://github.com/nuxt/content/issues/1919

### Describe the bug

- Open reproduction, click on `invalid` link
- Check `<title>` tag in head
- Click in index link
- Check title, still shows `invalid` page's title

**Comment by harlan-zw** [comment] 2023-02-23 15:14
Thanks, looks like a regression in the latest minor patch of Unhead. Have a release coming soon

**Comment by harlan-zw** [comment] 2023-02-27 07:42
On further investigation, it seems like this isn't fixed with the latest version.

This reproduction isn't exactly right, it's using the nuxt apps `useHead` which isn't going to have any sort of lifecycle events. We want the title to be removed so we need to use the `useHead` composable directly. Here's a more accurate one: https://stackblitz.com/edit/nuxt-starter-yqtvc1?file=app.vue

The specific issue is that the Vue `getCurrentInstance` isn't available after the async is resolved. It needs this scope to attach the `onBeforeUnmount` listener which disposes of the entry.

Are you aware of any ways around this @danielroe?

Getting around is easy enough, similar to the Nuxt app usage, just define the `useHead` upfront with the reactive data. But it may be confusing for end users.

```ts
const title = ref('')

useHead({
  title,
})

const { data } = await getTitle()
title.value = data
```

**Comment by danielroe** [comment] 2023-02-27 15:08
This is a limitation of Vue 3 script setup - the instance is only preserved in `<script setup>` blocks. In this case, you must use all composables that require access to the Vue or Nuxt contexts synchronously (or before the first await).

**Comment by harlan-zw** [comment] 2023-02-27 22:35
Thanks for the explanation! I think this can be closed once there's documentation available on the useHead or seo / meta page then

**Comment by harlan-zw** [comment] 2023-03-22 23:06
> @harlan-zw did you find a workaround for this?

See

>  If you are wanting to use a <script> block, you must use all composables that require access to the Vue or Nuxt contexts synchronously (or before the first await).

**Comment by harlan-zw** [comment] 2023-08-01 21:39
Should be fixed with https://github.com/nuxt/nuxt/pull/20918

**Comment by command-tab** [comment] 2023-08-31 22:38
I'm experiencing this as well, and I put together this repro:

https://stackblitz.com/edit/nuxt-starter-73ucyh?file=pages%2Fuser.vue

I'm not sure that using contexts synchronously is an option in my case because I want the page title to be set from data that I must `await` a `useFetch` for.

**Comment by command-tab** [comment] 2023-09-01 16:15
@harlan-zw Oh my gosh, you'd think I'd have caught that, having built and shipped several decent-sized Nuxt 3 apps, but Vue 3's use of refs continues to catch me off guard. Thank you for pointing it out! It indeed addressed the issue I was experiencing. Was your issue resolved with the linked PR?

**Comment by harlan-zw** [comment] 2023-09-01 21:11
No problem, they still catch me out as well :laughing: 

https://github.com/nuxt/nuxt/pull/20918 is intended to fix this issue, I've also opened https://github.com/unjs/unhead/issues/208 to track upstream.

I think we can close this for now given the above and the workaround.

**Closed by harlan-zw** 2023-09-01 21:11 UTC
Labels: documentation, 3.x, workaround available
