### ISSUE TITLE
useAsyncData break pages if multiple navigation during page change

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#22900] opened 2023-08-30 07:57 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-suvj1g?file=pages%2Fasyncdata.vue,pages%2Findex.vue,app.vue

- click 10 time within a second on the link
- don't get navigated and the page breaks
- open your console
- see an error

### Describe the bug

when clicking a lot of time on a link with a navigation to a page which requires a long asyncData, nuxt breaks with an vue error when navigating and mounting the new page

### Additional context

I think this issue can happens a lot on slow pages with users double/triple clicking on a nav link but not on pages that has a fast useAsyncData. It can also depend on the user network speed

**Comment by danielroe** [comment] 2023-08-30 14:00
Let's track in https://github.com/nuxt/nuxt/issues/13309.

**Comment by bombasticseahorse** [comment] 2023-09-04 11:38
@danielroe This bug was introduced in **v3.6.2**. **v3.6.1** with the same Vue version (**v3.3.4**) doesn't have this bug. It looks like it's related to Nuxt.

**Comment by danielroe** [comment] 2023-09-04 11:39
Yes, it did start then, but that's likely because we fixed an upstream bug, and began awaiting suspense resolution properly.

The root cause is upstream.

**Comment by agracia-foticos** [comment] 2023-09-05 09:47
> Yes, it did start then, but that's likely because we fixed an upstream bug, and began awaiting suspense resolution properly.
> 
> The root cause is upstream, as far as I can tell.
> 
> We're currently investigating a possible solution in Vue itself.

Perfect!!!

**Comment by MarioC3** [comment] 2023-09-16 02:51
Has someone found a workaround for this issue?

**Comment by agracia-foticos** [comment] 2023-09-22 08:43
Same issue

**Comment by Josepdal** [comment] 2023-09-26 14:07
Same here

**Comment by firsttarhan** [comment] 2023-09-29 07:50
Same issue

**Comment by hendrikheil** [comment] 2023-10-02 16:24
Can you try disabling transitions?

You can see how to do that here:
https://nuxt.com/docs/getting-started/transitions#disable-transitions

This is possibly fixed by https://github.com/vuejs/core/pull/9309, but disabling the transitions should lead to the same result.

**Comment by Josepdal** [comment] 2023-10-02 17:15
> Can you try disabling transitions?
> 
> You can see how to do that here: https://nuxt.com/docs/getting-started/transitions#disable-transitions
> 
> This is possibly fixed by [vuejs/core#9309](https://github.com/vuejs/core/pull/9309), but disabling the transitions should lead to the same result.

Hello, I have tried but got the same result.

In my case I am using <slot /> inside the layout to load pages.
https://nuxt.com/docs/migration/pages-and-layouts

Thanks!

**Comment by tolgahanbeyazoglu** [comment] 2023-10-02 17:56
@Josepdal  It doesn't matter if usefetch or useasyncdata, the problem will be solved if the lazy feature is used. Do you know this?

**Comment by Josepdal** [comment] 2023-10-02 18:07
> @Josepdal It doesn't matter if usefetch or useasyncdata, the problem will be solved if the lazy feature is used. Do you know this?

Yes thanks, but I don't want to handle a pending state. I prefer getting the data before hydration.

**Comment by tolgahanbeyazoglu** [comment] 2023-10-02 18:15
> > @Josepdal It doesn't matter if usefetch or useasyncdata, the problem will be solved if the lazy feature is used. Do you know this?
> 
> Yes thanks, but I don't want to handle a pending state. I prefer getting the data before hydration.

I have the same problem and I couldn't find a solution.

**Comment by NtchPlayer** [comment] 2023-10-27 09:40
Running into same error here o/ I could event reproduce it on https://nuxt.com if you navigate to fast on showcase or blog page from the navbar (-> be sure to don't have cachedData, you can downgrade you connexion with your browser to handle the error more simply).

**Comment by rylanharper** [comment] 2023-12-05 02:01
This is still a major issue even with the latest release of Vue core `^3.3.10`. Is this on the pipeline to be addressed?

**Comment by tolgahanbeyazoglu** [comment] 2023-12-05 06:38
@rylanharper The problem continues in vue 3.3.10, I did the tests.

**Comment by gogoend** [comment] 2023-12-12 12:59
I'm trying to explore the commits between v2.6.1 and v2.6.2 and find that since [this commit](https://github.com/nuxt/nuxt/commit/d0dde6426fe6ae58ec1ea94e47c66f6e0e2a4d63), this bug started appearing.

**Comment by zzzhim** [comment] 2023-12-13 11:11
I have the same problem, hope it can be fixed soon

**Comment by danielroe** [comment] 2024-01-02 10:37
this is now resolved in vue v3.4. 🥳

**Closed by danielroe** 2024-01-02 10:37 UTC
Labels: 3.x, bug, upstream, 🔨 p3-minor-bug, ✨ good reproduction
