### ISSUE TITLE
Unable to process with npm i

### ISSUE THREAD

**Issue by hardik-wts** [nuxt/nuxt#24987] opened 2024-01-01 13:25 UTC
### Environment

```
------------------------------
- Operating System: Darwin (mac m2)
- Node Version:     v20.10.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, googleFonts, pinia, piniaPersistedstate, ui, css, app
- Runtime Modules:  @nuxt/ui@2.8.1, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.2, @element-plus/nuxt@1.0.6, @nuxtjs/google-fonts@3.0.2
- Build Modules:    -
------------------------------
```

### Reproduction

Can't find a relevant solution 

### Describe the bug

With the same config on window os all working fine  

Here is my package.json file
```
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/google-fonts": "^3.0.2",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.2",
    "nuxt": "^3.7.0"
  },
  "dependencies": {
    "@element-plus/nuxt": "^1.0.6",
    "@iconify/json": "^2.2.116",
    "@nuxt/ui": "^2.8.1",
    "@pinia/nuxt": "^0.4.11",
    "bootstrap": "^5.2.3",
    "pinia": "^2.1.6",
    "sass": "^1.66.1",
    "sass-loader": "^13.3.2",
    "vue-select": "^3.20.2",
    "vue3-otp-input": "^0.4.1"
  },
  "overrides": {
    "vue": "latest"
  }
}
```

On macOS m2 I just clone the repo and do `npm i` (also try `npm i -f`) even also try with diff node version e.g. 16, 18, 20 LTS

I am getting below error when I run `npm i`  or `npm run dev` command 

```
> dev
> nuxt dev

Nuxt 3.7.0 with Nitro 2.6.2                                                                                                                                                                    6:59:33 PM
                                                                                                                                                                                               6:59:33 PM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Using default Tailwind CSS file                                                                                                                                            nuxt:tailwindcss 6:59:35 PM

 ERROR  Error while requiring module @element-plus/nuxt: TypeError: _dayjs.default.extend is not a function                                                                                    6:59:35 PM


 ERROR  Cannot start nuxt:  _dayjs.default.extend is not a function                                                                                                                            6:59:35 PM

  at <anonymous> (packages/components/time-picker/src/time-picker.tsx:9:14)
  at evalModule (node_modules/jiti/dist/jiti.js:1:255614)
  at jiti (node_modules/jiti/dist/jiti.js:1:253542)
  at node_modules/element-plus/es/components/time-picker/index.mjs:1:2184
  at evalModule (node_modules/jiti/dist/jiti.js:1:255614)
  at jiti (node_modules/jiti/dist/jiti.js:1:253542)
  at node_modules/element-plus/es/components/calendar/src/date-table.mjs:2:1
  at evalModule (node_modules/jiti/dist/jiti.js:1:255614)
  at jiti (node_modules/jiti/dist/jiti.js:1:253542)
  at node_modules/element-plus/es/components/calendar/src/date-table2.mjs:3:18

``````

**Comment by hardik-wts** [comment] 2024-01-02 06:50
I edited my question please have a look

**Comment by manniL** [comment] 2024-01-02 08:25
@hardik-wts you still did not provide a reproduction as explained in the comment above.

My guess is though that you forgot to install `dayjs` as package that is used in your time picker component.

**Comment by madebyfabian** [comment] 2024-03-29 18:01
Can be closed as no reproduction/answer provided since 4 months. It's likely a missing module (dayjs), like @manniL said, not a Nuxt issue.

**Closed** 2024-03-29 20:49 UTC
Labels: 3.x, pending triage, needs reproduction, ⛔️ can be closed
