### ISSUE TITLE
Change in how the page middlewares works

### ISSUE THREAD

**Issue by typhoon11** [nuxt/nuxt#12455] opened 2023-01-02 05:01 UTC
### Describe the feature

So at this moment the middlewares that are in ~/middleware dir and mentioned in any page by definePageMeta works after the page loads, so this enables a non auth user to see the page content, so I was thinking that if this was changed it will be better, because adding skeleton css for every page or adding if statement for all page to check if user is authenticated and then load the div is a little strained job. 

Hope to see a change in this thing in future.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by madebyfabian** [comment] 2023-02-07 04:10
Hey there! Please add a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs) so we can look into that properly, thank you 🙏🏻💚.

Since there isn't any activity here for a longer time, I'd suggest closing this, but feel free to reopen. Thank you 🙏🏻💚

**Closed** 2023-02-07 04:29 UTC
Labels: 3.x, pending triage, needs reproduction
