### ISSUE TITLE
conflict between definePageMeta property x variable name

### ISSUE THREAD

**Issue by josuelrocha** [nuxt/nuxt#30405] opened 2024-12-28 15:31 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.15.0
- CLI Version:      3.17.2
- Nitro Version:    2.10.4
- Package Manager:  npm@10.9.2
- Builder:          -
- User Config:      default
- Runtime Modules:  nuxt-svgo@4.0.9, @nuxtjs/google-fonts@3.2.0, @vueuse/nuxt@12.2.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-z5rfehnw?file=pages%2Findex.vue

### Describe the bug

```
 ERROR  [nuxt] [request error] [unhandled] [500] [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt
 hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables.
```

In Nuxt 3.15, a strange bug started to appear in a relatively large project. I updated to the new version of Nuxt and came across an error 500. After a few hours trying to find the problem, I discovered that the bug occurs if there is a variable in the script and a property in definePageMeta with the same name, the bug occurs.

In the reproduction example, the specific variable is "auth". When you run the project, you will receive an error 500. If you change the name of the variable or the property in definePageMeta to "auth2", for example, the project will run without any error. So it seems to me that in Nuxt 3.15 there is some conflict with names, which did not happen in Nuxt 3.14.

### Logs

```shell-script

```

**Comment by cernymatej** [comment] 2024-12-28 18:04
hi there, thank you for the reproduction!
this has already been fixed in https://github.com/nuxt/nuxt/pull/30381, so you can test it in the nightly version

the problem was that when we introduced support for local functions in `definePageMeta`, we didn't check the type of identifiers in the macro (i.e. whether it references something, or not) and extracted all matching identifiers outside the macro with it

**Closed by cernymatej** 2024-12-28 18:04 UTC
Labels: bug, 🔨 p3-minor, ✨ good reproduction
