### ISSUE TITLE
Ignore this error ==> The client-side rendered virtual DOM tree is not matching server-rendered content.

### ISSUE THREAD

**Issue by brightchip** [nuxt/nuxt#8266] opened 2020-10-30 02:54 UTC
How to perform a full force rehydration ?
This happens all the time when there's a if clause for which I use the variable to lazy request only on client side .
It stops the entire client side app running(Hydrating) on Production when it encounters this error !

I need it do a Full Re-Hydration on the app if it is ever necessary Just Like in development mode which works perfectly fine!
[Note that on elements without the data-server-rendered attribute, hydration can also be forced by passing true to the hydrating argument of $mount](https://ssr.vuejs.org/guide/hydration.html)

**Comment by manniL** [comment] 2020-10-30 08:10
I think there is no way around [fixing you hydration error](https://blog.lichter.io/posts/vue-hydration-error/).

The linked part in the docs is another way of forcing hydration when, for whatever reason, `data-server-rendered` is not included in the markup. As Nuxt always includes it, it is not necessary to force hydration that way as it will happen anyway.
That means that no matter what you do, you still need to ensure that client and server "expect the same HTML". Everything "additional" on the client should happen in `beforeMount`, `mounted` or via `ClientOnly` tag.

**Comment by pi0** [comment] 2020-10-30 08:35
@manniL I think idea is to bail hydration process in case of dom mismatch and fallback to client-side rendering. Maybe worth trying to see if possible or not but i guess only for nuxt3...

**Comment by manniL** [comment] 2020-10-30 09:10
> @manniL I think idea is to bail hydration process in case of dom mismatch and fallback to client-side rendering. Maybe worth trying to see if possible or not but i guess only for nuxt3...

Yeah, I guessed so too. But right now that's not possible AFAIK.
Might be a nice option (for nuxt 3) but could also lead to hiding the root cause for the problem.

**Comment by RailgunWinjoy** [comment] 2020-10-30 16:03
I found in my case that the problem mostly solved by replacing the "serverPrefetch" into "fetch". Except some Dom involved with Client side only data like localstorage.  But Still I wanna a way to manually trigger the hydration after data's ready.   
Also this problem is really blur and hard to debug for which I had to remove code piece by piece

**Comment by RailgunWinjoy** [comment] 2020-11-06 02:10
Hi, I have found a solution and it works perfectly fine!

I created a `serverMiddleware`
And overide the res function to remove the ` data-server-rendered="true"` on response body 

`export default async function(req, res, next) {`
`            function rawEnd(res, cacheable, cacheKey, data) {`
          `      if (data) {`
              `     data = data`
              `          // .replace(/[\n\r]/g, '')`
               `         // .replace(/( data-v-.*?>)/g, '>')`
        `                // .replace(/ +(?= )/g, '')`
                  `      .replace(/data-server-rendered="true"/, '')`
            `    }`

                if (res.statusCode === 200) {
                    // console.log('setCacheData cacheKey', cacheable, cacheKey, data.length)
                    setCacheData(cacheable, cacheKey, data)

                    if (ALWAYS_CACHE == cacheable) {
                        // res.setHeader('Cache-Control', 'max-age=6540000')
                    } else if (MINUTES_CACHE == cacheable) {
                        res.setHeader('Cache-Control', 'max-age=' + (cacheable || 0) * 60)
                    } else {
                        res.setHeader('Cache-Control', 'no-cache ')
                    }

                }


                res.original_end(data)
            }

           res.end = function(data) {
                    rawEnd(res, cacheable, cacheKey, data)
                }
`

**Comment by danielroe** [comment] 2024-06-14 16:04
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉

**Closed by danielroe** 2024-06-14 16:04 UTC
Labels: enhancement, 2.x
