### ISSUE TITLE
$fetch in a server plugin seems to be recusive in Nuxt 3.2.2

### ISSUE THREAD

**Issue by k3z** [nuxt/nuxt#19143] opened 2023-02-18 15:41 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.27.0`
- Builder:          `vite`
- User Config:      `app`, `runtimeConfig`, `modules`, `css`, `postcss`
- Runtime Modules:  `nuxt-icon@0.2.11`
- Build Modules:    `-`

### Reproduction

```
npx nuxi init testnuxt3.2.2
cd testnuxt3.2.2
pnpm install
pnpm dev
```
Added this two files

plugins/auth.server.ts
```
export default defineNuxtPlugin(async () => {
    try {
      const resp = await $fetch('/api/auth/me', {
        headers: useRequestHeaders(['cookie']) as HeadersInit,
      })
      console.log(resp)
    } catch (error) {
      console.log(error)
    }
})
```

server/api/auth/me.get.ts
```
export default defineEventHandler(async (event) => {
  console.log('event.context', event.context)

  return createError({
    statusCode: 403,
    message: 'FORBIDDEN',
  })
})
```

### Describe the bug

To begin, Thanks for the great work with Nuxt.

Symptom
The index page never show in browser and load indefinetly
until this json response

```
{
  "statusCode": 404,
  "statusMessage": "Cannot find any route matching /login.",
  "stack": []
}
```

Code works perfectly until vers 3.2.2 and Nitro 2.2
If I downgrade to 3.0.0 and Nitro 1.0 same code work.

### Logs

```shell-script
On nuxt start I can see this output in console


Nuxi 3.2.2                                                                                                      16:31:50
Nuxt 3.2.2 with Nitro 2.2.2                                                                                     16:31:50
                                                                                                                16:31:50
  > Local:    http://localhost:3000/
  > Network:  http://192.168.2.190:3000/
  > Network:  http://[fd44:d9ce:68c4:4531:87a:76e2:ba27:b693]:3000/

ℹ Vite client warmed up in 426ms                                                                                16:31:51
✔ Nitro built in 180 ms
  > Local:    http://localhost:3000/
  > Network:  http://192.168.2.190:3000/
  > Network:  http://[fd44:d9ce:68c4:4531:87a:76e2:ba27:b693]:3000/                                             16:26:39

ℹ Vite client warmed up in 421ms                                                                                16:26:41
✔ Nitro built in 171 ms                                                                                   nitro 16:26:41
✔ Vite server hmr 13 files in 294.88ms                                                                          16:26:46
event.context { _nitro: { routeRules: {} }, params: {} }                                                        16:26:46
event.context { _nitro: { routeRules: {} }, params: {} }                                                        16:26:46
event.context { _nitro: { routeRules: {} }, params: {} }                                                        16:26:46
event.context { _nitro: { routeRules: {} }, params: {} }                                                        16:26:46
event.context { _nitro: { routeRules: {} }, params: {} }                                                        16:26:46
event.context { _nitro: { routeRules: {} }, params: {} }
```
```

**Comment by danielroe** [comment] 2023-02-18 18:12
If you don't have a pages folder, then your app.vue file will serve all routes, so it is easy to end up making a recursive fetch.

Does it make a difference if you move that into `~/pages/index.vue`

**Comment by k3z** [comment] 2023-02-18 18:30
@danielroe 

In the reproduction with a starter project, only App.vue exists.

In my main project, I have a `pages` folder, but the router is configured with `app/router.options.ts` that completly override the normal behaviour.

In both cases a $fetch in a server plugin to the local server is recursive.

**Comment by k3z** [comment] 2023-02-18 18:35
@ElYaiko 

> I had the same problem yesterday, 4+ hours trying to find what it was and the only solution was downgrading to 3.2.1 but then upgraded to 3.2.2 again and is working almost ok for now

This seems only to work in a dev env. 
I downgraded to 3.2.1 and restart, it works.

But, in a docker image with `pnpm run build` it doesn't work.

**Comment by ElYaiko** [comment] 2023-02-18 21:32
This seems to be a problem with Nitro 2.2.2 I also have a plugin with `await $fetch()` to get the auth in a plugin and when removing the fetch the page loads normal but sometimes it keeps loading infinitely, is there a way to downgrade the Nitro version?

**Comment by danielroe** [comment] 2023-02-18 21:36
You can pin the nitro version with overrides/resolutions depending on your package manager.

**Comment by ElYaiko** [comment] 2023-02-18 22:12
Yes, it is working well with Nitro 2.2.1

**Comment by k3z** [comment] 2023-02-19 08:00
With "nitropack": "2.1.2" I can run my project again localy and in production env.

```
  "devDependencies": {
    …
    "nuxt": "3.1.2",
    …
  },
  "pnpm": {
    "overrides": {
      "nitropack": "2.1.2"
    }
  }
```

A simple nuxt downgrade is not enouth, `overrides` do the trick.
Learned how to use overrides today. Great ! 
I waiting now for the next Nuxt/Niro release to test again an upgrade.

Thanks @ElYaiko @danielroe

**Comment by MKraust** [comment] 2023-02-22 10:27
Caught this bug developing a layer using `@nuxt/content`. 404 pages are not working with Nitro 2.2.2 because of fetch in the `documentDriven` plugin.
Overriding Nitro to 2.2.3 fixed this problem.

**Comment by danielroe** [comment] 2023-02-22 11:11
As pointed out, this should be resolved in nitropack v2.2.3. which you can get with `npx nuxi upgrade --force`.

Let me know if not and I'll reopen.

**Closed by danielroe** 2023-02-22 11:11 UTC
Labels: 3.x, pending triage, nitro

**Comment by k3z** [comment] 2023-02-22 14:57
@danielroe It works. Thank you.

**Comment by bpeab** [comment] 2023-03-13 16:16
I have the same issue, in a "slightly" different context; even after updating. 

I have a module, which exposes a composable that wrap `$fetch`  (to globally set the `baseURL` for example):

```
export const get = async (url: string) => {
  return $fetch(url, {
    baseURL: useRuntimeConfig()?.public?.myModule?.apiUrl,
  });
};
```

And I call it like so:

```
const { data } = await useAsyncData('myCall', () =>
  myModule.get('...')
);
```

Putting a simple `console.log` inside the composable shows that the composable is called thousands of times. If I replace it with a simple `new Promise`, I have no issue. 

The behavior seems to be exactly the same as described above: I have an error about an unmatched route and then I get the "Reloading server..." that doesn‘t stop. 

One thing to mention also is that, I call the composable inside a catch-all.

Let me know if you think it's something completely different and I'll create another issue. 

Thanks!

**Comment by danielroe** [comment] 2023-03-13 16:24
An issue with a reproduction would be great. I would also note that `useRuntimeConfig()` should not be called dynamically like that in a fetch handler unless the handler is always called synchronously in setup. See https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.

**Comment by bpeab** [comment] 2023-03-13 17:09
Mmmh.. seems it was the origin of the issue in my case. I did not had the "Nuxt instance is unavailable" though. Thanks!

I can‘t seem to find any example on the docs explaining how I could retrieve some globally set variable to use inside async composable. Is it simply not possible? Can I pass the module option to my composable instead?
