### ISSUE TITLE
Nuxt3 fresh project double render

### ISSUE THREAD

**Issue by Nexi77** [nuxt/nuxt#19213] opened 2023-02-22 10:14 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`, `experimental`, `vite`, `ignore`, `app`, `vue`, `components`, `typescript`, `css`, `hooks`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `nuxt-vitest@0.6.6`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-9ukebr-bvynb9?file=nuxt.config.ts,app.vue,package.json

### Describe the bug

App.vue and whole app renders twice on initial render, when u reload the whole page/server. That causes all the request through the whole app to launch at least twice or more. 
It happens in the fresh nuxt app created by `npx nuxi init` as shown in reproduction link, so I think it's a bug inside nuxt3 itself.

**Comment by Nexi77** [comment] 2023-02-22 10:16
@danielroe sorry for pinging, but I think it can be crucial

**Comment by danielroe** [comment] 2023-02-22 11:12
I can't reproduce this. Note that sometimes stackblitz logs are confusing in this way. When I clone and run the reproduction locally there is only one request made.

**Comment by Nexi77** [comment] 2023-02-22 12:24
What I've found is that if u start fresh starter project using `npx nuxi init` than inside app.vue file I'm getting double render, but when I create /pages directory and put at least 1 file with `.vue` extension than double render problem dissapears. Than when I put `<NuxtPage />` component inside app.vue I'm getting double render again.

Is it not possible to have app.vue that renders pages and launch all the scripts that are necessary for initial app load?

# Reproduction without pages
https://codesandbox.io/p/sandbox/objective-euler-98kgx8?file=%2Fapp.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A8%7D%5D

# Reproduction with pages
https://codesandbox.io/p/sandbox/nice-sea-k59bid?file=%2Fpages%2Findex.vue&selection=%5B%7B%22endColumn%22%3A42%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A42%2C%22startLineNumber%22%3A8%7D%5D

# Reproduction with NuxtPage
https://codesandbox.io/p/sandbox/condescending-hodgkin-obrtdz?file=%2Fpages%2Findex.vue&selection=%5B%7B%22endColumn%22%3A9%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A9%2C%22startLineNumber%22%3A5%7D%5D

**Comment by lssdo12** [comment] 2023-02-24 09:13
> Can you see if your browser is making two requests (as I think likely)? Maybe it's performing a hard reload of the page for some reason?

I have a similar problem，
I create a new project by `npx nuxi init <project-name>`, `cd <project-name>`and`npm run dev`
I replace the `<NuxtWelcome />` with `Hello` in app.vue, Browser displays `Hello`, but when I use F5 to refresh my browser, a momentary `<NuxtWelcome />`appears, and then `Hello` appears, Console got an error `Hydration completed but contains mismatches.`. I stop the project and run `npm run dev` again. Browser displays `Hello` normally.
Is this normal? Should I rerun this command every time after text content changed?

**Comment by danielroe** [comment] 2023-02-24 10:17
I think this should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release via https://github.com/nuxt/nuxt/pull/19179

**Closed** 2023-03-02 13:49 UTC
Labels: 3.x, pending triage, needs reproduction
