### ISSUE TITLE
nuxt generate throws error when loading local json file via useFetch

### ISSUE THREAD

**Issue by marcstorch** [nuxt/nuxt#21722] opened 2023-06-23 15:00 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      nitro, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mtjxhr?file=nuxt.config.ts

### Describe the bug

When I run nuxt generate, I cannot load a local json file via useFetch. In the client everything works and nuxt dev does not cause any problems. Also an external json file can be loaded without problems.

I searched all day and tried 1000 things but nothing worked.

Here you can see exactly what is happening:
https://stackblitz.com/edit/nuxt-starter-mtjxhr?file=nuxt.config.ts

### Logs

```shell-script
FetchError: request to http://127.0.0.1:3000/data/model.json failed, reason: connect ECONNREFUSED 127.0.0.1:3000 (http://127.0.0.1:3000/data/model.json)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async $fetchRaw2 (file:///Users/gopogo/Documents/work/hyundai-santa-fe/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:215:14)
          at async $fetch2 (file:///Users/gopogo/Documents/work/hyundai-santa-fe/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)
          at async setup (file:///Users/gopogo/Documents/work/hyundai-santa-fe/.nuxt/prerender/chunks/app/server.mjs:5200:34)
        statusCode: 500,
        fatal: false,
        unhandled: false,
        statusMessage: undefined
```

**Comment by danielroe** [comment] 2023-06-23 15:10
The issue is almost certainly that when prerendering you are fetching from `http://localhost:3000` - but this server is not running on that port when you are prerendering your pages.

Instead, you can enable the `nitro.serveStatic` option and omit the baseURL entirely in your fetch call.

**Comment by marcstorch** [comment] 2023-06-23 15:50
I was sure I had tried that. Obviously not. It works now. 1000 thanks!

**Comment by danielroe** [comment] 2023-06-23 21:32
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next nitro release.

Let me know if not and I'll reopen.

**Closed by danielroe** 2023-06-23 21:32 UTC
Labels: 3.x, workaround available, upstream
