### ISSUE TITLE
Nuxt SPA breaks when adding a preset for @vueuse/router

### ISSUE THREAD

**Issue by omar-labana** [nuxt/nuxt#27456] opened 2024-06-05 12:09 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  bun@1.0.26
- Builder:          -
- User Config:      devtools, ssr, modules, components, imports, app, colorMode, googleFonts, i18n, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0, @nuxtjs/google-fonts@3.2.0, @nuxtjs/i18n@8.3.1, radix-vue/nuxt, nuxt-icon@0.6.10, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/color-mode@3.4.1, nuxt-lodash@2.5.3, @vueuse/nuxt@10.10.0
- Build Modules: 

### Reproduction

https://stackblitz.com/edit/github-g5rvb6

### Describe the bug

Adding a preset to `nuxt.config.ts` from `@vueuse/router` somehow removes all the auto imports from `@vueuse/nuxt`

```ts
presets: [
      {
        from: '@vueuse/router',
        imports: ['useRouteHash', 'useRouteParams', 'useRouteQuery'],
      },
    ],
```

I get `500 useTextDirection is not defined` or the same error message for any of vueUse composables

**Comment by manniL** [comment] 2024-06-05 18:38
This could be an issue with `@vueuse/nuxt` 🤔

**Comment by danielroe** [comment] 2024-06-05 20:05
Would you raise an issue/reproduction on https://github.com/vueuse/vueuse? 🙏

**Comment by omar-labana** [comment] 2024-06-05 20:05
@danielroe on it

**Comment by danielroe** [comment] 2024-06-05 21:02
Thank you! I think we can close it in favour of https://github.com/vueuse/vueuse/issues/4021.

Happy to be looped in if it seems to be caused by Nuxt upstream.

**Closed by danielroe** 2024-06-05 21:02 UTC
Labels: 3.x, pending triage, upstream
