### ISSUE TITLE
`/public` directory in dev server is not correctly mapped to `baseURL`

### ISSUE THREAD

**Issue by kaikaibenkai** [nuxt/nuxt#22107] opened 2023-07-12 14:56 UTC
### Environment

```
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.3.1
- Builder:          vite
- User Config:      app
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

https://github.com/kaikaibenkai/nuxt-demo-22107

### Describe the bug

I set `baseURL` to `/app/`, but in the dev server, files in the `/public` directory can still be accessed from `http://localhost:3000/filename`.

This resulted in inconsistent behavior between the prod mode and the dev mode (like `favicon.ico`?)

**Comment by sebaguse** [comment] 2023-07-19 07:51
same issue, I think this is also affecting production, in both dev and prod my application is trying to open a file from '/' even if my baseURL is set to '/app'. However in dev the file gets opened (from wrong path) but in production it just returns 404.

**Comment by wavedeck** [comment] 2023-12-12 14:33
same problem for me, i set the `app.baseURL` to "/app" and use `app.head.link` to add a theme.css to the head using a relative path. Everything worked in dev but broke in production because of this.

initially, i believed that Nuxt prefixes the baseUrl automatically as described in #19818 (prefix favicon path with baseUrl) but took me some debugging in production to find out the opposite.

**Comment by danielroe** [comment] 2024-05-24 08:50
This was resolved in https://github.com/nuxt/nuxt/pull/26163

**Closed by danielroe** 2024-05-24 08:50 UTC
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

**Comment by danielroe** [comment] 2024-06-06 19:35
@marcotw Would you provide a reproduction and open a new issue?
