### ISSUE TITLE
Error resolving template alias on windows

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/nuxt#19453] opened 2023-03-04 17:36 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.28.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/tobiasdiez/nuxt-graphql-server using `pnpm dev`

### Describe the bug

In a module, 
1. create a template using
   ```
   const { dst: schemaPath } = addTemplate({
      filename: 'graphql-schema.mjs',
      getContents: () => "test",
      write: true,
    })
    ```
    This successfully writes the template in `.nuxt/graphql-schema.mjs`
2. create an alias for this template `nuxt.options.alias['#graphql/schema'] = schemaPath`
3. use the alias in a server file
4. run nuxt in dev mode

On windows, this fails with the following error
```
[worker reload] [worker init] D:/Programming/nuxt-graphql-server/playground/.nuxt/dev/index.mjsOnly URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

  at new NodeError (node:internal/errors:399:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:960:11)
  at defaultResolve (node:internal/modules/esm/resolve:1040:3)
  at nextResolve (node:internal/modules/esm/loader:164:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:419:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
  at link (node:internal/modules/esm/module_job:76:36)
```

The reason is that the generated `dev/index.mjs` file contains
```
import { schema } from 'D:/Programming/nuxt-graphql-server/playground/.nuxt/graphql-schema.mjs';
```
without the `file://` prefix that is necessary on windows. Digging a bit deeper, the issue comes from the `node-externals` plugin which resolves the alias as
```
{                                                                                                 
  assertions: {},
  external: 'absolute',
  id: 'D:/Programming/nuxt-graphql-server/playground/.nuxt/graphql-schema.mjs',
  meta: {},
  moduleSideEffects: false,
  resolvedBy: 'node-externals',
  syntheticNamedExports: false
}
```
since `.nuxt` is marked as `externals`. In fact, the issue goes away if one uncomments https://github.com/unjs/nitro/blob/c578df8bc85628933a3c0241d452a9b8389084ff/src/rollup/plugins/externals.ts#L82 , in which case the resolution is correct:
```
{                                                                                                  
  assertions: {},
  external: true,
  id: 'file://D:/Programming/nuxt-graphql-server/playground/.nuxt/graphql-schema.mjs',
  meta: {},
  moduleSideEffects: false,
  resolvedBy: 'rollup',
  syntheticNamedExports: false
}
```
Not sure what is the correct fix.

**Comment by tamutus** [comment] 2023-03-26 20:53
Not sure how helpful this will be, but I was troubleshooting the same error message in a completely different context. At some point I accidentally let VSCode intellisense auto-complete when I was typing out `createError` to use in an API file, which added an import statement `import { createError } from "~~/.nuxt/imports";` . Like in your case, the generated `.nuxt/dev/index.mjs` was preventing my application from running. What was generated by `nuxt dev` included a second import statement in the index.mjs file for createError, `import { createError as createError$1 } from "C:/..."`, without that necessary `file://` prefix. Deleting my superfluous, explicit import statement fixed the problem. This might be irrelevant to your case, but hopefully it gives useful context for this error message to the devs and anybody stumbling over, since neither my googling nor chatGPT pointed me at this solution.

**Comment by nzuyanov** [comment] 2023-05-02 11:11
I also faced this problem in my modules. Is there any news or workarounds?

**Comment by tobiasdiez** [comment] 2023-05-07 03:10
For a workaround, you can use `pathToFileURL` as eg in https://github.com/dword-design/nuxt-mail/pull/174.

**Comment by danielroe** [comment] 2023-09-18 10:33
@tobiasdiez Do you think this is an issue in Nuxt?

**Comment by pi0** [comment] 2023-10-03 17:22
Hi. Sorry for long delay on being back on this issue.

According to @tobiasdiez initial steps, i tried to assemble a reproduction:

https://stackblitz.com/edit/nuxt-starter-724hvd?file=modules%2Frepro.ts,server%2Fapi%2Ftest.ts

This seems to work fine on windows:

<img width="1115" alt="image" src="https://github.com/nuxt/nuxt/assets/5158436/6f516293-06c5-449c-b19c-e88c5ecf7b22">

Although i might have missed something, please feel free to fork sandbox with any additions that can lead to this issue and would be happy to investigate more 👍🏼  

Otherwise i think this issue might be marked as done /cc @danielroe

**Closed** 2024-06-16 22:03 UTC
Labels: 3.x, bug, nitro, upstream, windows

**Comment by tobiasdiez** [comment] 2024-07-09 22:09
@pi0 @danielroe I can confirm that this bug is indeed fixed in the most recent nuxt version! Thanks a lot for your work. 🚀
