### ISSUE TITLE
[Nuxt 3.9.0] dev server crashes hard when there is an optimize dep for vite that isn't installed

### ISSUE THREAD

**Issue by bernhardberger** [nuxt/nuxt#24927] opened 2023-12-27 20:28 UTC
### Environment

Nuxt project info:                                                                                                    10:10:31 AM  

------------------------------
- Operating System: Linux
- Node Version:     v20.10.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      modules, devtools, runtimeConfig, experimental, viewport, app, $production, site, sitemap, routeRules, router, image, svgo, content, components, tailwindcss, vite, nitro, gsap
- Runtime Modules:  @nuxt/content@2.10.0, @hypernym/nuxt-gsap@2.4.2, nuxt-svgo@3.7.0, nuxt-viewport@2.0.6, @nuxtjs/tailwindcss@6.10.1, @nuxt/image@1.1.0, @vueuse/nuxt@10.7.0, @nuxtseo/module@2.0.0-beta.51
- Build Modules:    -
------------------------------

### Reproduction

I'm sorry but I have no clue on where to start to reproduce this. I'll happily provide a reproduction if someone can guide me on how to narrow this down.

### Describe the bug

Since upgrading to 3.9 I the dev-server crashes and I get warnings of failed to resolve dependencies. ~~I have no clue if those are related (see logs below)~~. These seem to be related. In this case it's the `is-buffer` dependency that's declared in `@nuxtjs/mdc` package but isn't installed. IMHO the dev-server shouldn't crash hard with no clear error message. The "WARN" imho should at least be an "error".

### Logs

```shell-script
/home/beb/.nvm/versions/node/v20.10.0/bin/npm run dev

> dev
> nuxt dev

Nuxt 3.9.0 with Nitro 2.8.1                                                      10:06:50 AM
                                                                                 10:06:51 AM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Using Tailwind CSS from ~/assets/scss/tailwind.scss          nuxt:tailwindcss 10:06:54 AM
                                                                         nuxtseo 10:06:55 AM
Nuxt SEO v2.0.0-beta.51 by @harlan_zw                                    nuxtseo 10:06:55 AM
[nuxtseo 10:06:55 AM]   └─ 🧪 Help get Nuxt SEO stable by providing feedback https://github.com/harlan-zw/nuxt-seo-kit/discussions/108
                                                                         nuxtseo 10:06:55 AM  
  ➜ DevTools: press Shift + Alt + D in the browser (v1.0.6)                      10:06:56 AM


[10:06:58 AM]  WARN  Failed to resolve dependency: is-buffer, present in 'optimizeDeps.include'

ℹ Vite server warmed up in 12477ms                                              10:07:15 AM
ℹ Vite client warmed up in 17299ms                                              10:07:16 AM
✔ Nitro built in 7342 ms                                                  nitro 10:07:19 AM
free(): invalid size
free(): invalid size

 ERROR  [unhandledRejection] socket hang up                                      10:07:37 AM  

  at connResetException (node:internal/errors:787:14)
  at Socket.socketOnEnd (node:_http_client:519:23)
  at Socket.emit (node:events:526:35)
  at endReadableNT (node:internal/streams/readable:1589:12)
  at process.processTicksAndRejections (node:internal/process/task_queues:82:21)


 ERROR  [unhandledRejection] socket hang up                                      10:07:37 AM  

  at connResetException (node:internal/errors:787:14)
  at Socket.socketOnEnd (node:_http_client:519:23)
  at Socket.emit (node:events:526:35)
  at endReadableNT (node:internal/streams/readable:1589:12)
  at process.processTicksAndRejections (node:internal/process/task_queues:82:21)


 ERROR  [unhandledRejection] connect ECONNREFUSED 127.0.0.1:34221                10:07:38 AM  

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```

**Comment by bernhardberger** [comment] 2023-12-27 20:55
Looks like `@nuxtjs/mdc` is the reason for the dev-server crashing. I've opened a ticket upstream: https://github.com/nuxt-modules/mdc/issues/121

**however**: I still think the dev-server shouldn't crash hard when there's an invalid optimize dep in some upstream package.

**Comment by bernhardberger** [comment] 2023-12-27 21:18
Unfortunately I can't reproduce it on stackblitz:
https://stackblitz.com/github/nuxt/starter/tree/content?file=package.json

The warning is there but the server doesn't crash.

I also can't repro locally anymore after **manually** editing `node_modules/@nuxtjs/mdc/dist/module.mjs`, removing `is-buffer` from the optimizeDeps, running `npm run dev` successfully and then again adding `is-buffer` to the deps.

**Comment by Arthur-Chevron** [comment] 2023-12-28 13:07
I have the same error, i use Nuxt 3.9.0.
I have 3 layers and one main app, when i upgrade to 3.9.0 i have this error !

**Comment by madebyfabian** [comment] 2024-03-29 18:35
@bernhardberger Can we close this issue then? Since it seems not reproduceable anymore and may be fixed by the PR from pi0.

**Closed** 2024-05-24 14:34 UTC
Labels: 3.x, pending triage, needs reproduction, ⛔️ can be closed
