### ISSUE TITLE
Title is set before the `<meta charset="...">`

### ISSUE THREAD

**Issue by xzfnn** [nuxt/nuxt#18936] opened 2023-02-10 07:11 UTC
### Environment

Server environment

### Reproduction

Server environment

### Describe the bug

https://user-images.githubusercontent.com/58756175/218025237-6f052e78-7daf-4a58-aa23-558fc53b1194.mp4

### Additional context

Now when I enter the page for the first time, the title will be garbled, and it won't work if I cut the route randomly

**Comment by danielroe** [comment] 2023-02-10 08:19
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by xzfnn** [comment] 2023-02-10 08:29
I uploaded a short video of the problem. Could you please see if it is the problem of the head method rendering or other configuration requirements

**Comment by AloisSeckar** [comment] 2023-02-10 09:00
I only see white screen. Also without source codes it is probably impossible to tell, what's going on anyway.

**Comment by xzfnn** [comment] 2023-02-10 09:04
https://user-images.githubusercontent.com/58756175/218049009-d4995816-e29f-4362-a245-7ad36e2feae1.mp4

**Comment by xzfnn** [comment] 2023-02-10 09:05
OK, then I will attach the code

**Comment by xzfnn** [comment] 2023-02-10 09:22
https://github.com/xzfnn/jkeedu-m,


This is the project link. The novice uses nuxt for the first time and wants to make a static web page and put it on the server, but I don't know why. The title will be garbled when entering the page for the first time, and it won't be possible to switch the route randomly. My guess is that there is a problem with the rendering mechanism of the head method, or that I may lack any configuration. Please help me look at it. Thank you very much

**Comment by xzfnn** [comment] 2023-02-10 09:24
Use the command npm run generate

**Comment by harlan-zw** [comment] 2023-02-10 11:06
Try setting the meta charset

**Comment by AloisSeckar** [comment] 2023-02-10 14:35
> Try setting the meta charset, you have it commented out. Otherwise you'll need to make a minimal reproduction, ideally on StackBlitz

I checked the linked repo - from what I see they are adding `utf-8` through `head()` option in each page setup

**Comment by xzfnn** [comment] 2023-02-10 15:22
> 

Yes, I set the head on each page separately, because when I try to set the head method in nuxt.config.js, the title will always be garbled, while I set it separately, and it will only garbled when I first enter the page

**Comment by harlan-zw** [comment] 2023-02-11 03:36
The issue seems to be that the charset is being set AFTER the `<title>` tag. An upstream issue with [vue-meta](https://github.com/nuxt/vue-meta). This is something fixed in Nuxt 3.

Not sure exactly sure if there's a work around. The site looks relatively simple though, have you considered migrating to Nuxt 3?

**Comment by xzfnn** [comment] 2023-02-11 03:53
> 问题是字符集是在标记之后设置的。`<title>`
> 
> 确切的问题在这里：https://github.com/nuxt/nuxt/blob/2.x/packages/vue-renderer/src/renderers/ssr.js#L133。标题始终设置在元之前。

Ok, thank you for your patience. I tried to migrate to nuxt3. I wish you a happy life

**Closed** 2023-02-14 00:05 UTC
Labels: 2.x, 🔨 p3-minor-bug
