### ISSUE TITLE
useFetch returns null when used within layout and wrapped with ClientOnly

### ISSUE THREAD

**Issue by milelazar** [nuxt/nuxt#25131] opened 2024-01-10 10:04 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
------------------------------

### Reproduction

Not working (returns null): https://stackblitz.com/edit/github-uranmz?file=app.vue,layouts%2Fdefault.vue,components%2FTest.vue
Working (without layout): https://stackblitz.com/edit/github-uranmz-j92ydc?file=app.vue,components%2FTest.vue

### Describe the bug

There is a component that fetches data and it needs to be rendered on server or as client only. It depends on scenario.

Component is using useFetch composable to fetch data and data needs to be processed once fetched before returned to template. Everything works fine if data is fetched on server. But it returns null if component is wrapped with <ClientOnly> and used in layout.

If used without layout, it works fine.
The same problem exists when useFetch is used in onMounted hook. It returns null if layout is used.

**Comment by danielroe** [comment] 2024-01-10 15:45
The root cause here is likely https://github.com/vuejs/core/issues/6638.

**Comment by dargmuesli** [comment] 2024-07-25 11:35
Upstream is likely fixed in v`3.5.0-alpha.4` :raised_hands: @milelazar would you like to confirm?

**Closed** 2024-09-03 13:33 UTC
Labels: pending triage, upstream
