### ISSUE TITLE
useSeoMeta doesn't change the source code of the page

### ISSUE THREAD

**Issue by 22Crusader** [nuxt/nuxt#23608] opened 2023-10-10 19:11 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.6.7
- Builder:          vite
- User Config:      srcDir, ssr, builder, vite, app, css, typescript, components
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

These reproductions are the same. If you are using stackblitz, make sure you open the reproduction in a new tab to be able to check the source code

https://stackblitz.com/edit/github-srmrnj
https://github.com/22Crusader/useSeoMeta-issue

### Describe the bug

useSeoMeta and useHead composables are not changing the source code of the page. When the page loads, the meta tags are applied correctly, but the source code remains the same. This leads to the fact that opengraph for each page is the same, despite using useSeoMeta

**Comment by warflash** [comment] 2023-10-10 19:57
Could you explain what you mean by source code? For me only the test page has og:images attached which seems to be in line with what you're expecting, right?

**Comment by 22Crusader** [comment] 2023-10-11 09:42
> Could you explain what you mean by source code? For me only the test page has og:images attached which seems to be in line with what you're expecting, right?

Hey! Meta tags for index page are specified in nuxt config
By source code, I mean the page source (accessible by right click -> view page source in Chrome). As you can see, it's static and meta tags are taken from nuxt config, no matter what route are you on
As far as I know, search engine robots only index the initial load, where title, description etc are not yet changed if using useSeoMeta (those changes appear in the DOM tree after the page is loaded). So the metadata of pages with specified useSeoMeta is simply not indexed. The same goes for og card - it's the same for all pages

**Additional information:**
Moving metadata from nuxt config to app.vue or default layout with useSeoMeta leads to the same behavior
Removing metadata from nuxt config but leaving useSeoMeta for specific pages results in meta tags not being displayed in the source code
Navigating to the test page and then navigating back to index page completely removes the meta tags (specified in the useSeoMeta of the test page) from the DOM of the index page. You can check it by opening head tag and navigating between pages. Don't think this makes much difference to SEO tho

**Comment by danielroe** [comment] 2023-10-11 09:55
cc: @harlan-zw

**Comment by tiagosilvaalopes** [comment] 2023-10-12 16:31
We have a similar issue in my project where we are statically generating pages and have SEO scripts into the head using **useHead()**, however, after an NPM update, the script is no longer shown in the statically generated HTML (page source). We previously used Nuxt version 3.2.3 and then did a version update to 3.6.5. After this, we no longer see the SEO script in the page source. We see that the script is added into the HTML when running "npm run dev". But it's not added when we run "npm run generate".

This is a snippet of the composable we use to generate the SEO script tag:
![image](https://github.com/nuxt/nuxt/assets/55545737/8ffa6d7c-50d6-4539-9d72-b7d760f7a0bd)

**Comment by harlan-zw** [comment] 2023-10-12 17:47
> We have a similar issue in my project where we are statically generating pages and have SEO scripts into the head using **useHead()**, however, after an NPM update, the script is no longer shown in the statically generated HTML (page source). We previously used Nuxt version 3.2.3 and then did a version update to 3.6.5. After this, we no longer see the SEO script in the page source. We see that the script is added into the HTML when running "npm run dev". But it's not added when we run "npm run generate".
> 
> This is a snippet of the composable we use to generate the SEO script tag: ![image](https://user-images.githubusercontent.com/55545737/274666813-8ffa6d7c-50d6-4539-9d72-b7d760f7a0bd.png)

Not sure if this is directly related, would you be able to create a reproduction :pray:

**Comment by harlan-zw** [comment] 2023-10-12 17:52
As for the main issue, I'm not exactly sure what the issue is. Would you mind providing steps and what the expected output is.

One thing to keep in mind is that when you provide head data through nuxt.config `app.head` is that it's only server-side rendered so once the frontend modifies it, there isn't a way to revert it (this may be fixed in an upcoming Unhead release).

But this shouldn't be an issue for your og data as the only the initial server-side response will actually do anything. As a work around you can move the head data to a `useHead` on your app.vue

**Comment by liaowei59** [comment] 2023-10-13 08:29
I also encountered the same problem. I used useHead() after obtaining the interface data and assigned the obtained data to the title and description in my meta, but it did not actually change.

**Comment by harlan-zw** [comment] 2023-10-13 09:03
> I also encountered the same problem. I used useHead() after obtaining the interface data and assigned the obtained data to the title and description in my meta, but it did not actually change.

Can you provide a seperate reproduction?

**Comment by liaow-ww** [comment] 2023-10-13 09:11
> > I also encountered the same problem. I used useHead() after obtaining the interface data and assigned the obtained data to the title and description in my meta, but it did not actually change.
> 
> Can you provide a separate reproduction?

![5BEFB7B5-00CE-4bac-BC46-B971AB888147](https://github.com/nuxt/nuxt/assets/115768717/17fbb74d-2c24-4380-8d8f-775bf39be851)

**Comment by 22Crusader** [comment] 2023-10-13 09:13
> As for the main issue, I _think_ I understand it, but not exactly sure why it would cause og data issues. Basically the meta tags get deleted once you move around the pages a couple of times.
> 
> This is due to the head data from nuxt.config `app.head` being server-side rendered only so once the frontend modifies it, there isn't a way to revert it (this may be fixed in an upcoming Unhead release).
> 
> But this shouldn't be an issue for your og data as only the initial server-side response will actually do anything. As a workaround you can move the head data to a `useHead` on your app.vue.

Yeah, I thought that useSeoMeta is supposed to redeclare meta tags not only in VDOM, but also in the source code. After doing some research, I managed to find the solution with computed values for useServerSeoMeta in routeMiddleware to make all metadata server-rendered

**Comment by liaow-ww** [comment] 2023-10-13 09:15
> > I also encountered the same problem. I used useHead() after obtaining the interface data and assigned the obtained data to the title and description in my meta, but it did not actually change.
> 
> Can you provide a separate reproduction?

I can see in the google console that the meta information is correct, but it has not changed when viewing the page source code.

**Comment by harlan-zw** [comment] 2023-10-13 09:25
For the server-side response code (right click -> view source) to change, you need to be running `useHead` within a script setup (or plugin/middleware) synchronously (or awaiting the async) and running your site with SSR enabled.

If you believe you are doing this and it's not updating then please provide a Stackblitz and I'll either help you debug the issue on your end or fix the bug if it's an Unhead issue.

**Comment by liaow-ww** [comment] 2023-10-13 09:46
> For the server-side response code (right click -> view source) to change, you need to be running `useHead` within a script setup (or plugin/middleware) synchronously (or awaiting the async) and running your site with SSR enabled.
> 
> If you believe you are doing this and it's not updating then please provide a Stackblitz reproduction and I'll either help you debug the issue on your end or fix the bug if it's an Unhead issue.
> 
> Unfortunately, I can't do much with screenshots of code as it doesn't include enough context.

ok i'll try, thanks your reply.

**Closed** 2023-10-14 11:46 UTC
Labels: 3.x, bug, 🔨 p3-minor-bug

**Comment by hi-reeve** [comment] 2023-10-17 07:39
> > As for the main issue, I _think_ I understand it, but not exactly sure why it would cause og data issues. Basically the meta tags get deleted once you move around the pages a couple of times.
> > This is due to the head data from nuxt.config `app.head` being server-side rendered only so once the frontend modifies it, there isn't a way to revert it (this may be fixed in an upcoming Unhead release).
> > But this shouldn't be an issue for your og data as only the initial server-side response will actually do anything. As a workaround you can move the head data to a `useHead` on your app.vue.
> 
> Yeah, I thought that useSeoMeta is supposed to redeclare meta tags not only in VDOM, but also in the source code. After doing some research, I managed to find the solution with computed values for useServerSeoMeta in routeMiddleware to make all metadata server-rendered

can you please share the research you have done? or an example on how to implement it?

**Comment by liaow-ww** [comment] 2023-10-30 06:36
> ?

I have solved this problem. You need to configure the titleTemplate in nuxt.config.ts so that the title can be dynamically rendered. The rest of the meta tags need to be added using <Head></Head> in the template. Dynamic data can be obtained and displayed on the web page. You can see the rendering in the source code. Hope this helps you.

like this :
<template>
<Head>
      <Title>{{ data.title }}</Title>
      <Meta
          name="description"
          :content="data.desc" />
</Head>
</template>

**Comment by liaow-ww** [comment] 2023-10-30 06:41
I have solved this problem. You need to configure the titleTemplate in nuxt.config.ts so that the title can be dynamically rendered. The rest of the meta tags need to be added using <Head></Head> in the template. Dynamic data can be obtained and displayed on the web page. You can see the rendering in the source code. Hope this helps you.

like this : https://nuxt.com/docs/getting-started/seo-meta#components

**Comment by liaow-ww** [comment] 2023-10-30 06:42
> > > As for the main issue, I _think_ I understand it, but not exactly sure why it would cause og data issues. Basically the meta tags get deleted once you move around the pages a couple of times.
> > > This is due to the head data from nuxt.config `app.head` being server-side rendered only so once the frontend modifies it, there isn't a way to revert it (this may be fixed in an upcoming Unhead release).
> > > But this shouldn't be an issue for your og data as only the initial server-side response will actually do anything. As a workaround you can move the head data to a `useHead` on your app.vue.
> > 
> > 
> > Yeah, I thought that useSeoMeta is supposed to redeclare meta tags not only in VDOM, but also in the source code. After doing some research, I managed to find the solution with computed values for useServerSeoMeta in routeMiddleware to make all metadata server-rendered
> 
> can you please share the research you have done? or an example on how to implement it?

hi, You can view my latest reply.
