### ISSUE TITLE
`useCookie` does not work correctly in Chrome

### ISSUE THREAD

**Issue by teleskop150750** [nuxt/nuxt#28178] opened 2024-07-16 14:22 UTC
### Environment

ubuntu 24
Google Chrome 126

### Reproduction

https://github.com/teleskop150750/nuxt-useCookie

### Describe the bug

`useCookie` stopped working correctly in version 3.12 in `Chrome`. It works stably in Firefox
it worked fine in previous versions

There is also a problem on Windows

v3.12.3

https://github.com/user-attachments/assets/fb599a15-acef-4d0a-8635-851b349edee6

v3.11.2

https://github.com/user-attachments/assets/9abe64b0-0381-493a-92e5-3ec63bbc4c79

**Comment by manniL** [comment] 2024-07-16 14:32
Duplicate of https://github.com/nuxt/nuxt/issues/27660

**Closed by manniL** 2024-07-16 14:32 UTC
Labels: pending triage
