### ISSUE TITLE
fetch error with `node-cluster`

### ISSUE THREAD

**Issue by videmann** [nuxt/nuxt#22783] opened 2023-08-24 09:15 UTC
### Environment

node 16.4

### Reproduction

https://stackblitz.com/edit/github-6fcte8-arvx9n

### Describe the bug

when i run nuxi dev, everything works fine, but when i run nuxi build && nuxi preview. useFetch don't return response

### Additional context

i made my own composable useRequest with your docs. it's just a wrapper which returns useFetch composable.

/** Final Version */
export const useRequest = (
  request: Ref<string> | string | (() => string),
  opts?: useRequestOptions
) => {
  const config = useRuntimeConfig().public
  const loader = useLoader()

  return useFetch(request, {
    baseURL: opts?.baseURL ?? config.apiBaseUrl,
    headers: { authorization: `Bearer ${useCookie(config.cookie).value}` },
    transform: (_response: ApiResponse) => {
      return opts?.plain ? _response : _response.data
    },
    onRequest: ({ request, options }) => {
      // console.log(request.options.headers)
      if (opts?.silent) {
        return
      }

      loader.show()
    },
    onResponse: ({ error, response }) => {
      loader.hide()

      if (error) {
        useToast(error.message, 'error')
      }

      if (response?._data?.errors?.length) {
        response._data.errors.forEach((error: { message: string }) =>
          useToast(error.message, 'error')
        )
      }

      if (response?._data?.messages?.length) {
        response._data.messages.forEach((message: { message: string }) =>
          useToast(message.message, 'info')
        )
      }
    },
    onRequestError(context) {
      loader.hide()
    },
    onResponseError(context) {
      loader.hide()
    },
    ...opts,
  })
}

**Comment by videmann** [comment] 2023-08-24 09:29
Please, help. My production site is down!!!

**Comment by danielroe** [comment] 2023-08-24 09:33
This works fine in the reproduction provided. You can inspect `error` (returned from `useFetch`) to see what any errors are.

I would guess it's probably an issue with your API.

**Comment by videmann** [comment] 2023-08-24 09:34
> This works fine in the reproduction provided. You can inspect `error` (returned from `useFetch`) to see what any errors are.
> 
> I would guess it's probably an issue with your API.

response: FetchError: [GET] "https://api.loverepublic.ru/web/v1/catalog/sections?depthLevel=3": <no response> a is not a function
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async $fetchRaw (file:///C:/Users/videmanso/projects/lrp-front/.output/server/index.mjs:1:143792)
      at async $fetch (file:///C:/Users/videmanso/projects/lrp-front/.output/server/index.mjs:1:144612)
      at async Kt (file:///C:/Users/videmanso/projects/lrp-front/.output/server/chunks/app/server.mjs:1:78741)
      at async Promise.all (index 0)
      at async Proxy.fetch (file:///C:/Users/videmanso/projects/lrp-front/.output/server/chunks/app/server.mjs:1:80451)
      at async file:///C:/Users/videmanso/projects/lrp-front/.output/server/chunks/app/server.mjs:1:80804
      at async Object.callAsync (file:///C:/Users/videmanso/projects/lrp-front/.output/server/chunks/app/server.mjs:1:2493)
      at async Qi (file:///C:/Users/videmanso/projects/lrp-front/.output/server/chunks/app/server.mjs:1:4478)
      at async file:///C:/Users/videmanso/projects/lrp-front/.output/server/chunks/app/server.mjs:1:91217 {
    [cause]: TypeError: a is not a function
        at file:///C:/Users/videmanso/projects/lrp-front/.output/server/index.mjs:1:294030
        at localFetch (file:///C:/Users/videmanso/projects/lrp-front/.output/server/index.mjs:1:294419)
        at $fetchRaw (file:///C:/Users/videmanso/projects/lrp-front/.output/server/index.mjs:1:143683)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
  }

**Comment by danielroe** [comment] 2023-08-24 09:36
![CleanShot 2023-08-24 at 10 36 09](https://github.com/nuxt/nuxt/assets/28706372/8eabea44-4d6c-4638-b9c3-01ce04b201e0)

**Comment by videmann** [comment] 2023-08-24 09:58
Strange... No!, my api is ok, something is wrong with $fetch on server

**Comment by videmann** [comment] 2023-08-24 10:00
What means  FetchError: [GET] "https://api.loverepublic.ru/web/v1/catalog/sections?depthLevel=3": "no response" a is not a function?

**Comment by danielroe** [comment] 2023-08-24 10:13
Could you provide a reproduction then? 🙏

**Comment by videmann** [comment] 2023-08-24 10:13
> ![CleanShot 2023-08-24 at 10 36 09](https://user-images.githubusercontent.com/28706372/262930831-8eabea44-4d6c-4638-b9c3-01ce04b201e0.png)

can you check my reproduction again, please? https://stackblitz.com/edit/github-6fcte8-arvx9n
i copy my project

**Comment by videmann** [comment] 2023-08-24 10:38
omg...(( it's epic fail... Yesterday everything works...

**Comment by videmann** [comment] 2023-08-24 10:39
![изображение](https://github.com/nuxt/nuxt/assets/31483719/3e1ca7fb-550e-4d80-91e7-b97ffb838dd2)
![изображение](https://github.com/nuxt/nuxt/assets/31483719/a32f4c19-58d0-4187-8048-fdaf55e49939)

**Comment by videmann** [comment] 2023-08-24 10:40
and my api working fine: https://api.loverepublic.ru/web/v1/home

**Comment by danielroe** [comment] 2023-08-24 10:47
It's possible there's an issue with `ofetch` as there was a recent release. Try latest (v1.3.2) first and then try pinning to v1.2.1 just in case.

**Comment by videmann** [comment] 2023-08-24 10:58
I FOUND IT!!!

I JUST REMOVE nitro-preset option from nuxt.config.ts and from .env!!!

**Comment by videmann** [comment] 2023-08-24 11:00
> It's possible there's an issue with `ofetch` as there was a recent release. Try latest (v1.3.2) first and then try pinning to v1.2.1 just in case.

Please, check this error. It affects to $fetch. I don'n know know... but it's an fact!

**Comment by danielroe** [comment] 2023-08-24 11:07
Would you be able to restore your stackblitz to the minimal reproduction again, using `node-cluster`, if that is indeed the issue? 🙏

**Comment by videmann** [comment] 2023-08-24 11:22
> Would you be able to restore your stackblitz to the minimal reproduction again, using `node-cluster`, if that is indeed the issue? 🙏

https://stackblitz.com/edit/github-qg7zbm

Perhaps, there are some dependencies between modules, which cause this error

**Comment by danielroe** [comment] 2023-08-24 11:30
Hm. Indeed. I can't reproduce when cloning that locally. Let me know if you find anything.

**Comment by videmann** [comment] 2023-08-24 11:34
> Hm. Indeed. I can't reproduce when cloning that locally. Let me know if you find anything.

with pleasure

**Comment by LiNCH35** [comment] 2023-08-28 10:54
I had a similar problem. It helped to downgrade the nitro version to 2.5.2

**Comment by danielroe** [comment] 2023-10-20 11:01
Closing as I can't reproduce, but if you're encountering, it's likely something to raise in https://github.com/unjs/nitro/ rather than in Nuxt.

**Closed by danielroe** 2023-10-20 11:01 UTC
Labels: 3.x, pending triage, needs reproduction
