### ISSUE TITLE
Unexpected difference in error handling when running app for dev vs. prod

### ISSUE THREAD

**Issue by LLCampos** [nuxt/nuxt#10438] opened 2022-05-13 16:09 UTC
### Versions

- nuxt: v2.15.8
- node: v16.13.2 

### Reproduction

https://github.com/LLCampos/nuxt-500-issue

Use this repo for reproduction.

### Steps to reproduce

**Method 1 - Run for dev env:** 

```
npm run dev
```

vs.

**Method 2 - Run for prod:** 
```
npm run build
npm run start
```

### What is Expected?

In both methods of running the application, when I click "Trigger Error", I should be redirected to the error page.

### What is actually happening?

Only in method 1 I'm being redirected to the error page.

**Method 1**

https://user-images.githubusercontent.com/12008784/168323595-c349066a-bf6b-4849-bcf0-4b6945f820c0.mov

**Method 2**

https://user-images.githubusercontent.com/12008784/168323643-cc8c74b4-4cb8-4484-9d37-444414a53a41.mov

**Comment by danielroe** [comment] 2023-04-12 20:43
We've spent some time working on consistent error handling between dev/prod in Nuxt 3. I'm going to close this as it's not a bug report and we're not prioritising feature development in Nuxt 2.

**Closed by danielroe** 2023-04-12 20:43 UTC
Labels: pending triage, 2.x
