### ISSUE TITLE
3.9.1 Still redirecting.

### ISSUE THREAD

**Issue by AkcyZe** [nuxt/nuxt#25159] opened 2024-01-11 17:14 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.0.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      app, modules, plugins, components, ssr, nitro, vite, content, sitemap, runtimeConfig, gtag
- Runtime Modules:  nuxt-simple-sitemap@2.7.0, @nuxt/content@2.10.0, @vueuse/nuxt@9.13.0, nuxt-icons@3.2.1, nuxt-gtag@0.5.9, ./modules/default/index.ts
- Build Modules:    -
------------------------------

### Reproduction

Site https://reliz.com/

Redirection on (evil) site with double '//' and '/' at end -> https://reliz.com//mail.vecloud.net/

### Describe the bug

Redirecting on "evil" site, instead of 404 page https://reliz.com//mail.vecloud.net/

**Comment by manniL** [comment] 2024-01-11 17:36
related: #25156  

Could you provide a reproduction?

**Comment by aaharu** [comment] 2024-03-21 06:35
@AkcyZe 
I think, it is not the Nuxt problem.

```
> $ curl -I "https://reliz.com//mail.vecloud.net/"
HTTP/2 301 
server: CloudFront
date: Thu, 21 Mar 2024 06:28:38 GMT
content-length: 0
location: //reliz.com/mail.vecloud.net
x-cache: FunctionGeneratedResponse from cloudfront
via: 1.1 1c55b8998c14fe890c17f323fce0dd60.cloudfront.net (CloudFront)
x-amz-cf-pop: NRT12-P2
x-amz-cf-id: btOomHWIcebsZL51vRulyYzKxVqIimsWjmPJGchpNR9JWH9_UDz1Jg==
```

It seems to be generated by CloudFront Functions.

**Comment by manniL** [comment] 2024-03-21 06:41
Closing here as no reproduction was provided for a while.

**Closed by manniL** 2024-03-21 06:41 UTC
Labels: 3.x, pending triage, needs reproduction
