### ISSUE TITLE
pnpm support without `--shamefully-hoist`

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14146] opened 2022-06-10 16:26 UTC
Update: Since v3.0 release, pnpm without `shamefully-hoist` flag works out of the box but there are still known issues to be addressed (in nuxt or upstream):

- When pages enabled, `vue-router` dependency is implicit
- Multiple instances of vue are can be resolved and used
- Generated tyeps are not fully functional without hoisted `node_modules`

----

History: nuxt/nuxt.js#11823

We have progressively improved plug-and-play support over time and almost all underlying packages including nitro support and are tested against pnpm. 

Last step is making nuxt 3 working with pnpm out of the box before migrating modules and templates from first-class yarn to pnpm.

Using pnpm without `--shamefully-hoist` is possible today 🥳 but requires explicitly installing `vue` and `ufo` dependencies and we don't want this since Nuxt was always a zero-config package and we need to add deps of all nuxt modules as well this way.

One obvious solution is that same as Nitro, we internally (also for `unimport` ~> https://github.com/unjs/unimport/issues/69) resolve them to their full path but we also need to support non-resolved implicit imports in templates as modules might have similar implicit dependencies in their scope and they need to be resolved as well. I think this can be done using a custom resolver for vite (and webpack).

**Comment by kettanaito** [comment] 2023-02-09 13:49
I've opened a pull request that fixes an issue with the internal `Module.createRequire()` call in https://github.com/nuxt/nuxt/pull/18917. It may also help with this issue as creating the right require context will likely cause Node to resolve 4th party dependencies from the PNPM store instead of always looking them up from the root-level `node_modules`, where they won't exist when using PNPM.

**Comment by Dante-dan** [comment] 2023-03-14 06:14
From my test results, it appears that if you do not want to use `--shamefully-hoist` (especially in MonoRepo), you can specify certain packages that need to be hoisted.

example
```
// .npmrc
public-hoist-pattern[]=*vue*
public-hoist-pattern[]=*nuxt*
public-hoist-pattern[]=defu
public-hoist-pattern[]=ufo
public-hoist-pattern[]=h3
public-hoist-pattern[]=nitropack
```

**Comment by nicolaspayot** [comment] 2023-03-20 09:32
We are successfully using `pnpm` without `--shamefully-hoist` in our Monorepo by explicitly adding the following `dependencies` in each nuxt application:
```json
"@vue/reactivity": "3.2.47",
"@vue/runtime-core": "3.2.47",
"@vue/runtime-dom": "3.2.47",
"@vue/shared": "3.2.47",
"defu": "6.1.1",
"ufo": "1.0.0",
"unctx": "2.1.0",
"unstorage": "0.5.6",
"vue": "3.2.47",
"vue-router": "4.1.6"
```
and the following `devDependencies`: 
```json
"@nuxt/schema": "3.1.2",
"@types/node": "18.11.18",
"typescript": "4.9.5",
"vue-tsc": "1.1.5"
```
The drawback is handling the versions across the different applications but `pnpm update` command helps.

**Comment by kettanaito** [comment] 2023-05-02 12:29
I really wish there was a solution to this. Using `--shamefully-hoist` is equivocal to stripping PNPM of its superpowers. You may as well use NPM or Yarn, at that point. 

I couldn't get the `--shamefully-hoist=true` option to be respected in the monorepo because, to my best observation, that would hoist dependencies at _monorepo's root_. While the issue is that `packages/your-nuxt-app` doesn't even go outside the root while resolving the dependencies (may be wrong on this, please correct me). 

Explicitly installing the deps/devDeps as suggested by @nicolaspayot also didn't work for some reason, the Nuxt dev server still crashes with `503 (Server Unavailable)`.

**Comment by crunchwrap89** [comment] 2023-05-09 19:33
@pi0 @danielroe  it appears this issue is not assigned to anyone anyone. I just wanted to make sure its not a mistake.
Is someone currently investigating this issue?

**Comment by danielroe** [comment] 2023-05-09 19:40
Yes, I am. But of course if you would like to pitch in l, that is very welcome.

**Comment by david-bojnansky** [comment] 2023-05-18 21:11
Hello, I am not sure whether I had an issue related exactly to this one but I started to use **pnpm workspaces** and when I installed all packages in monorepo with `pnpm install` and run the nuxt app (`pnpm dev`) I got a bunch of errors:

```
Nuxi 3.5.0                                                                                                                         22:48:47  
Nuxt 3.5.0 with Nitro 2.4.1                                                                                                        22:48:47  
                                                                                                                                   22:48:48  
  > Local:    http://localhost:3000/
  > Network:  http://10.8.197.11:3000/
  > Network:  http://169.254.25.30:3000/
  > Network:  http://169.254.66.134:3000/
  > Network:  http://192.168.15.1:3000/
  > Network:  http://192.168.50.1:3000/
  > Network:  http://192.168.56.1:3000/
  > Network:  http://192.168.77.1:3000/

✔ Nuxt Devtools is enabled v0.4.6 (experimental)                                                                                   22:48:50

 WARN  Failed to resolve dependency: vue, present in 'optimizeDeps.include'                                                        22:48:51


 WARN  Failed to resolve dependency: @vue/reactivity, present in 'optimizeDeps.include'                                            22:48:51  


 WARN  Failed to resolve dependency: @vue/runtime-core, present in 'optimizeDeps.include'                                          22:48:51


 WARN  Failed to resolve dependency: @vue/runtime-dom, present in 'optimizeDeps.include'                                           22:48:51


 WARN  Failed to resolve dependency: @vue/shared, present in 'optimizeDeps.include'                                                22:48:51


[22:48:51]  ERROR  Failed to load url /@fs/S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/ufo@1.1.2/node_modules/ufo/dist/index.mjs?v=3526bf17 (resolved id: S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/ufo@1.1.2/node_modules/ufo/dist/index.mjs?v=3526bf17) in virtual:nuxt:S:/CODE/Bojn.IT/websites/consola/packages/client/.nuxt/paths.mjs. Does the file exist?


[22:48:52]  ERROR  Failed to load url /@fs/S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/defu@6.1.2/node_modules/defu/dist/defu.mjs?v=3526bf17 (resolved id: S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/defu@6.1.2/node_modules/defu/dist/defu.mjs?v=3526bf17) in S:/CODE/Bojn.IT/websites/consola/packages/client/.nuxt/app.config.mjs. Does the file exist?


 ERROR  Error: The following dependencies are imported but could not be resolved:                                                  22:48:52  

  vue (imported by S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/nuxt@3.5.0_@types+node@18.16.12/node_modules/nuxt/dist/app/nuxt.js)   

Are they installed?
    at file:///S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/vite@4.3.8_@types+node@18.16.12/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:44188:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/vite@4.3.8_@types+node@18.16.12/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:43597:38


[22:48:52]  ERROR  Failed to resolve import "unctx" from "virtual:nuxt:S:\CODE\Bojn.IT\websites\consola\packages\client\.nuxt\plugins\client.mjs". Does the file exist?


[22:48:52]  ERROR  Failed to resolve import "vue" from "..\..\node_modules\.pnpm\vite-plugin-vue-inspector@3.4.2_vite@4.3.8\node_modules\vite-plugin-vue-inspector\src\load.js". Does the file exist?


[22:48:52]  ERROR  Failed to resolve import "vue" from "..\..\node_modules\.pnpm\nuxt@3.5.0_@types+node@18.16.12\node_modules\nuxt\dist\app\plugins\revive-payload.client.js?v=3526bf17". Does the file exist?


[22:48:52]  ERROR  Failed to resolve import "vue" from "..\..\node_modules\.pnpm\nuxt@3.5.0_@types+node@18.16.12\node_modules\nuxt\dist\app\nuxt.js?v=3526bf17". Does the file exist?


[22:48:52]  ERROR  Failed to resolve import "vue" from "..\..\node_modules\.pnpm\nuxt@3.5.0_@types+node@18.16.12\node_modules\nuxt\dist\app\components\nuxt-root.vue". Does the file exist?


[22:48:52]  ERROR  Failed to resolve import "vue" from "..\..\node_modules\.pnpm\nuxt@3.5.0_@types+node@18.16.12\node_modules\nuxt\dist\app\plugins\router.js?v=3526bf17". Does the file exist?


[22:48:52]  ERROR  Failed to resolve import "vue" from "..\..\node_modules\.pnpm\@nuxt+devtools@0.4.6_nuxt@3.5.0_vite@4.3.8\node_modules\@nuxt\devtools\dist\runtime\plugins\devtools.client.mjs?v=3526bf17". Does the file exist?


[22:48:52]  ERROR  Failed to resolve import "vue" from "..\..\node_modules\.pnpm\nuxt@3.5.0_@types+node@18.16.12\node_modules\nuxt\dist\app\composables\payload.js?v=3526bf17". Does the file exist?


                                                                                                                                   22:48:52  

[22:48:52]  ERROR  Failed to load url /@fs/S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/ufo@1.1.2/node_modules/ufo/dist/index.mjs?v=3526bf17 (resolved id: S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/ufo@1.1.2/node_modules/ufo/dist/index.mjs?v=3526bf17) in virtual:nuxt:S:/CODE/Bojn.IT/websites/consola/packages/client/.nuxt/paths.mjs. Does the file exist? (x6)

                                                                                                                                   22:48:52  
[22:48:52]  ERROR  Failed to load url /@fs/S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/ofetch@1.0.1/node_modules/ofetch/dist/index.mjs?v=3526bf17 (resolved id: S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/ofetch@1.0.1/node_modules/ofetch/dist/index.mjs?v=3526bf17). Does the file exist?


[22:48:52]  ERROR  Failed to load url /@fs/S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/unctx@2.3.0/node_modules/unctx/dist/index.mjs?v=3526bf17 (resolved id: S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/unctx@2.3.0/node_modules/unctx/dist/index.mjs?v=3526bf17). Does 
the file exist?


[22:48:52]  ERROR  Failed to load url /@fs/S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs?v=3526bf17 (resolved id: S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs?v=3526bf17). Does the file exist?


[22:48:52]  ERROR  Failed to load url /@fs/S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/@unhead+vue@1.1.27_vue@3.3.4/node_modules/@unhead/vue/dist/index.mjs?v=3526bf17 (resolved id: S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/@unhead+vue@1.1.27_vue@3.3.4/node_modules/@unhead/vue/dist/index.mjs?v=3526bf17) in S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/nuxt@3.5.0_@types+node@18.16.12/node_modules/nuxt/dist/head/runtime/plugins/unhead.js. Does the file exist?


                                                                                                                                   22:48:52  

[22:48:52]  ERROR  Failed to load url /@fs/S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/h3@1.6.6/node_modules/h3/dist/index.mjs?v=3526bf17 (resolved id: S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/h3@1.6.6/node_modules/h3/dist/index.mjs?v=3526bf17) in S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/nuxt@3.5.0_@types+node@18.16.12/node_modules/nuxt/dist/app/composables/ssr.js. Does the file exist? (x5)

                                                                                                                                   22:48:52  
[22:48:52]  ERROR  Failed to load url /@fs/S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/ohash@1.1.2/node_modules/ohash/dist/index.mjs?v=3526bf17 (resolved id: S:/CODE/Bojn.IT/websites/consola/node_modules/.pnpm/ohash@1.1.2/node_modules/ohash/dist/index.mjs?v=3526bf17). Does 
the file exist?

✔ Nitro built in 779 ms      
```

I searched for the solution about a day and all solutions I found didn't work as expected... But I found one:

In workspace root I have `.npmrc` with content:

```
shared-workspace-lockfile=false
public-hoist-pattern[]=@vue/reactivity
public-hoist-pattern[]=@vue/runtime-core
public-hoist-pattern[]=@vue/runtime-dom
public-hoist-pattern[]=@vue/shared
public-hoist-pattern[]=vue
```

This ensures that the packages `vue` and `@vue/*` will be placed in the root of `node_modules/` inside the nuxt app package (and from there I could safely remove `.npmrc`).

Then I removed all `node_modules` folders and `pnpm-lock.yaml` files, run `pnpm install` from monorepo root and then I could successfully run the nuxt app by `pnpm dev`.

```
Nuxi 3.5.0                                                                                                                         23:03:13
Nuxt 3.5.0                                                                                                                         23:03:13
                                                                                                                                   23:03:14
  > Local:    http://localhost:3000/ 
  > Network:  http://10.8.197.11:3000/
  > Network:  http://169.254.25.30:3000/
  > Network:  http://169.254.66.134:3000/
  > Network:  http://192.168.15.1:3000/
  > Network:  http://192.168.50.1:3000/
  > Network:  http://192.168.56.1:3000/
  > Network:  http://192.168.77.1:3000/

✔ Nuxt Devtools is enabled v0.4.6 (experimental)                                                                                   23:03:15
ℹ Vite client warmed up in 1340ms                                                                                                  23:03:18
✔ Nitro built in 1307 ms   
```

Hope this help someone.

So when I see the responses from @Dante-dan and @YannicEl, they had truth but I didn't want to use `--shamefully-hoist`.

Seems like this is relatively clean solution...

**Comment by safejace** [comment] 2023-05-24 00:03
so like @david-bojnansky i tried to start a `pnpm-workspace` project. and running into the exact same issue.

although i was not able to resolve it like he did. i added the lines to the npmrc like in the solution, and while it seemed to fix it for those packages... it seems to just keep going deeper now. quite the game of whack-a-mole.

now i get
```
Could not resolve "unhead"
 Could not resolve "@unhead/shared"
 ```
 
 not sure how long i should keep it up?
 
 is there any insight into the root cause of the problem?
 
 im trying to figure out what to do, but i think maybe i just need to add `--shamefully-hoist` to some config? but im struggling to figure it out

**Comment by nicolaspayot** [comment] 2023-05-24 08:58
Hello, I bootstrapped an example on stackblitz with a mini pnpm monorepo: https://stackblitz.com/edit/nuxt-starter-xjec4j.

As you can see, `.npmrc` has `shamefully-hoist=false` which means we need to explicitly install required dependencies.

**Comment by david-bojnansky** [comment] 2023-05-24 17:03
> so like @david-bojnansky i tried to start a `pnpm-workspace` project. and running into the exact same issue.
> 
> although i was not able to resolve it like he did. i added the lines to the npmrc like in the solution, and while it seemed to fix it for those packages... it seems to just keep going deeper now. quite the game of whack-a-mole.
> 
> now i get
> 
> ```
> Could not resolve "unhead"
>  Could not resolve "@unhead/shared"
> ```
> 
> not sure how long i should keep it up?
> 
> is there any insight into the root cause of the problem?
> 
> im trying to figure out what to do, but i think maybe i just need to add `--shamefully-hoist` to some config? but im struggling to figure it out

Probably you should add those packages to `public-hoist-pattern[]=`

My current `.npmrc` (I had to add some other packages):

```
#shared-workspace-lockfile=false
public-hoist-pattern[]=@formkit/core
public-hoist-pattern[]=@formkit/vue
public-hoist-pattern[]=@vue/apollo-composable
public-hoist-pattern[]=@vue/reactivity
public-hoist-pattern[]=@vue/runtime-core
public-hoist-pattern[]=@vue/runtime-dom
public-hoist-pattern[]=@vue/shared
public-hoist-pattern[]=graphql-tag
public-hoist-pattern[]=vue
public-hoist-pattern[]=vue-router
```

and into `nuxt.config.ts` I added:

```
vite: {
    server: {
      fs: {
        allow: ['../server-api', '../../node_modules'],
      }
    }
  },
```

Important is node_modules which is located at the root of monorepo...

**Comment by Hebilicious** [comment] 2023-06-23 09:20
This is a tricky issue to fix because Nuxt relies on a flat module structure to work.
Ie by installing Nuxt, you should be able to `import { ref } from "vue"`, without having to explicitly install it. 

The issue is that by design, pnpm doesn't work that way, and needs vue in your deps to be able to use `import { ref } from "vue"`

There's a few approaches that I can think of on how we could achieve `--shamefully-hoist` (let me know if I missed any):

1) "break" pnpm and install  the needed dependencies in `node_modules` anyways

I don't see any advantage of doing this over using `node-linker` and `--shamefully-hoist`

2) use pnpm specific aliases in nuxt.config.ts for all the needed dependencies

This should work fine for simple scenarios, but this would break for scenarios where you have 2 different version of the same dependencies that needs to be resolved. 

3) bundle and re-export all needed dependencies through `nuxt`

Just writing this one out sounds like a bad idea, would leave to huge, messy bundle with strange semantics where you could import anything that comes from modules from `nuxt`. 

4) extend nuxi to detect pnpm usage, and add/remove all needed dependencies in package.json automatically 

I personally think this is the best compromise, yes it leads to "un-clean" `package.json`, but end users won't have to manually manage the dependencies. Nuxi should resolve what's needed for modules and run `pnpm i x y z`, as well as the upgrade command when needed.

**Comment by pi0** [comment] 2023-06-23 09:34
@Hebilicious You are right about type issues with flat structure. Just as an idea, have you tried using a `.d.ts` file / tsconfig to augment for missing (flat) module types with full path to them?

**Comment by Hebilicious** [comment] 2023-06-23 09:50
> @Hebilicious You are right about type issues with flat structure. Just as an idea, have you tried using a `.d.ts` file / tsconfig to augment for missing (flat) module types with full path to them? (btw for vue case, it is likely we start adding it as a direct dep in insiders, however there are always more indirect deps auto imported)

I haven't thought of using a `.d.ts` file! This seem to be similar to using `alias` in `nuxt.config.ts`.
Even if vue is in the direct dependencies, we'd still @vue/reactivity, runtime-core, dom and shared to be present in package.json right ?

**Comment by pi0** [comment] 2023-06-23 09:59
Yes. Comparing with an alias in nuxt.config, this would be a type-only fix. Since rollup/vite resolvers can already resolve sub-dependencies quite well without dedup even.

**Comment by gyhyfj** [comment] 2023-06-26 03:09
Hope this to be resolved, so that I can update my nuxt app in monorepo from 3.4.2 to latest.

**Comment by vis97c** [comment] 2023-07-24 02:46
> @jpsc there are two ways i have found to use pnpm workspaces with nuxt3
> 
> 1. Have a `.npmrc` file with `shared-workspace-lockfile=false` in your root folder and a `.npmrc` file with `shamefully-hoist=true` in your nuxt subfolder.  I use that approche here: https://github.com/YannicEl/try-finger/tree/dev
> 2. Have a `.npmrc` file with `shamefully-hoist=true` in your root folder. I use that approche here: https://github.com/YannicEl/hans

The second one did the job for me

**Comment by Hebilicious** [comment] 2023-08-02 13:52
There's a auto install peer setting in pnpm that is now true by default https://pnpm.io/next/npmrc#auto-install-peers
Could we solve this by ensuring that every package declares the right peer dependencies ?

**Comment by paro-paro** [comment] 2023-08-18 12:36
Is there any progress or ETA on this?

I believe pnpm is amazing (well... the whole vue/vite/vitest ecosystem is using it) and, as pointed out somewhere in the comments, the `shamefully-hoist=true` feels like not using pnpm in the first place. 

Yes, you can manually install some extra deps or mess out with the public-hoist configuration and make it work... but I feel like Nuxt should definitively be pnpm compatible. 

In any case, thanks for creating this amazing framework which I enjoy using every day! 😄

**Comment by akiot-b** [comment] 2023-08-21 04:27
The behavior with `pnpm --shamefully-hoist` is painful.
First of all, please make it work by specifying `shamefully-hoist=true' in .npmrc in the subdirectory for nuxt at least.

**Comment by akiot-b** [comment] 2023-08-23 02:50
Thank you. Yes, you can now set `shamefully-hoist=true` in the root directory instead of a subdirectory.
It seems that pnpm becomes useless because it sets `shamefully-hoist=true` for packages other than nuxt, but it's better than using other package management tools, so I'll hold out until this is resolved.

**Comment by danielroe** [comment] 2023-10-17 21:49
Nuxt should now be working without `--shamefully-hoist`. It currently requires explicitly installing `vue` and `vue-router` as these are needed to be optimised by Vite, and therefore they must be top level deps.

**Closed by danielroe** 2023-10-17 21:49 UTC
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

**Comment by crunchwrap89** [comment] 2023-10-18 05:16
That is awesome news :)

Den tis 17 okt. 2023 23:49Daniel Roe ***@***.***> skrev:

**Comment by dsvgl** [comment] 2023-10-18 07:27
> It currently requires explicitly installing vue and vue-router

Is this the new recommended way? This should be in the docs then...
Currently the [installation page](https://nuxt.com/docs/getting-started/installation) says under "Install the dependencies" for pnpm: `Make sure you have `shamefully-hoist=true` in `.npmrc` before running pnpm install`

**Comment by akiot-b** [comment] 2023-10-18 07:30
I'm wondering if "shamefully-hoist=false" is recommended, but I can confirm that I was able to run it with "false" for now. (@nuxt/content gave me a dependency warning, but that's another issue.)

**Comment by hlassiege** [comment] 2023-10-18 08:04
huge news. Thanks a lot

**Comment by paro-paro** [comment] 2023-10-18 10:10
Amazing!! Big thanks!

**Comment by cexbrayat** [comment] 2023-10-18 16:06
`@nuxts/i18n` still requires to add quite a few depencies explicitely if you try to remove `--shamefully-hoist`. 

I opened https://github.com/nuxt-modules/i18n/issues/2506 to track it for those of you who are interested.

**Comment by gyhyfj** [comment] 2023-10-20 10:38
Modules such as `@nuxtjs/tailwindcss` and `@element-plus/nuxt` will throw error with `pnpm`  without `--shamefully-hoist`:

**Comment by manniL** [comment] 2023-10-20 12:17
@gyhyfj https://github.com/nuxt/nuxt/issues/14146#issuecomment-1767243568

**Comment by P4sca1** [comment] 2023-12-17 11:20
@nuxt/content issue for pnpm compatibility:
https://github.com/nuxt/content/issues/2381

**Comment by Mateleo** [comment] 2024-09-10 15:51
I just checked : Lucia Auth is not working without shamefully-hoist=true

**Comment by danielroe** [comment] 2024-09-10 16:41
@Mateleo Is that a Nuxt issue? Would you open a new issue with a reproduction so we can track?

**Comment by Mateleo** [comment] 2024-09-10 18:23
@danielroe 
I think it was a mistake between the keyboard and the chair... I just tried again with a clean installation, and there was no problem...
Here is the project: https://github.com/Mateleo/nuxt-auth-lucia
