### ISSUE TITLE
Problem starting @nuxt/test-utils with URL

### ISSUE THREAD

**Issue by dev02iggy** [nuxt/nuxt#12368] opened 2023-01-09 13:50 UTC
### Environment

RootDir: /Users/dev02/dev/temporario/app-nuxt-3
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `css`, `windicss`, `build`, `modules`, `experimental`, `components`, `vite`, `runtimeConfig`, `intlify`, `vueuse`, `content`
- Runtime Modules:  `@intlify/nuxt3@0.2.4`, `@pinia/nuxt@0.4.6`, `@nuxt/content@2.2.2`, `@vueuse/nuxt@9.6.0`, `nuxt-windicss@2.5.5`, `nuxt-icon@0.1.8`
- Build Modules:    `-`
------------------------------

### Reproduction

// app-nuxt-3/test/hoje.test.js

import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { isWindows } from 'std-env'
import { setup, fetch, $fetch, startServer, createPage, url } from '@nuxt/test-utils'

await setup({
    rootDir: fileURLToPath(new URL('../../app-nuxt-3', import.meta.url)),
    server: true,
    browser: false,
    setupTimeout: (isWindows ? 240 : 120) * 1000
})

describe('pages', () => {
  it('render index', async () => {
    const html = await $fetch('/')
    expect(html).toContain('Fundação de Esportes DEV')
  })

![Captura de Tela 2023-01-09 às 10 41 34](https://user-images.githubusercontent.com/83841469/211321530-07c4551f-e133-41be-b11d-dc586cc768da.png)

### Describe the bug

Here are the links to the documentation and the example I took to make mine.
https://nuxt.com/docs/getting-started/testing
https://github.com/nuxt/framework/tree/main/test

The issue I'm having is the app is telling me the Url must be from the schema file. I'm in doubt if the Url is wrong when pointing to the application or if the scheme he wants to say is something else. I can't find any examples on the internet that help me.
Note: Remembering that I configured Vitest and use it normally, including together with Pinia. The real problem is when I started testing the Nuxt components themselves. I haven't even started yet.

Error picture:

<img width="643" alt="Captura de Tela 2023-01-09 às 10 42 12" src="https://user-images.githubusercontent.com/83841469/211322216-b68c08fa-1f02-4793-9a03-bd8e275439c1.png">

### Additional context

It's my first time writing a bug (I've always been able to solve it by searching), so forgive me if it's not good enough.

**Comment by danielroe** [comment] 2023-01-30 11:19
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

(I've tried with the code you provided but can't reproduce.)

**Comment by madebyfabian** [comment] 2023-02-07 04:11
Hey there! Please add a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs) so we can look into that properly, thank you 🙏🏻💚.

Since there isn't any activity here, I'd suggest closing this, but feel free to reopen. Thank you 🙏🏻💚

**Closed** 2023-02-07 07:10 UTC
Labels: 3.x, needs reproduction, test-utils, ⛔️ can be closed
