### ISSUE TITLE
Duplication of pre-rendered pages in Pascal and Lower Case on 'generate' at production [DigitalOcean App Platform].

### ISSUE THREAD

**Issue by wilDriven** [nuxt/nuxt#18372] opened 2023-01-20 03:45 UTC
### Environment

Nuxt project info:
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:     `nitro`, `alias`, `modules`, `sitemap`, `runtimeConfig`, `twicpics`, `plugins`, `app`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `nuxt-icon@0.1.8`, `@twicpics/components/nuxt3@0.12.0`, `~/modules/sitemap`
- Build Modules:    `-`
------------------------------

### Reproduction

Could be a potential issue with Digital Ocean as the 'generate' process seems to work fine on my local machine.

![image](https://user-images.githubusercontent.com/72958018/213613229-08c7a2ac-9efe-472f-8c5e-9c4843116caf.png)
![image](https://user-images.githubusercontent.com/72958018/213613240-83dce0fd-279d-43a6-a55a-5f22063637ff.png)

Here is the output from router.getRoutes() in dev mode, as you can see there is no pascal case here either.

![image](https://user-images.githubusercontent.com/72958018/213628409-4afc3647-c34a-4c1e-b755-4d97de42b003.png)

### Describe the bug

When I run 'generate' on my local system all routes are pre-rendered as expected. However, when I push to production the build process seems to pre-render duplicates of my non-dynamic pages in pascal case as well as lower case (should only be lower case). These duplicates also appear in my dynamically generated sitemap at prod on D.O but not in the output file on my local machine.

I should mention that I did initially have my .vue files for the pages named in pascal case (as per Vue conventions) but renamed them after seeing different conventions used by others in Nuxt.

Is there a file in .nuxt with router declarations where the pascal case might still be saved?

This is causing me some SEO issues and shouldn't be happening. Any ideas on how to debug the issue?

**Comment by danielroe** [comment] 2023-01-21 23:06
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by madebyfabian** [comment] 2023-02-07 04:15
Hey there! Please add a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs) so we can look into that properly.

Since there isn't any activity here for a longer time, I'd suggest closing this, but feel free to reopen. Thank you 🙏🏻💚

**Comment by driven-group** [comment] 2023-02-07 06:57
Sorry, I don't really know how to do that as the issue doesn't arise until I ship to Digital Ocean. Everything else looks entirely normal when I run 'generate' on my local system. It only adds the extra pages with Pascal Case when running 'generate' on the DO Server/App Platform.

If you can advise on how best to do it I will happily look at it. Or if you can suggest a place where I can find the config files for the router in nuxt to see if it has messed up the routes. (In the past I have renamed components and had to adjust the components.ts file when it hasn't updated properly. Is there an equivalent somewhere for the router? I cannot find it.

**Closed** 2023-02-07 06:56 UTC
Labels: 3.x, pending triage, needs reproduction

**Comment by madebyfabian** [comment] 2023-02-07 07:33
@driven-group Well, it sounds like DO has cached these routes somehow since you renamed them at some point. Otherwise I wouldn't have known why they would do something like that 😄.

A minimal reprod must not be a StackBlitz (mostly it's the best though), of course you can also create a minimal nuxt project with the CLI, add some example pages in it, and you sharing exactly the config/cli of DO and the preview urls. 

I suppose on a fresh newly deployed project this should not happen.

**Comment by driven-group** [comment] 2023-02-07 08:09
@madebyfabian I thought this myself however I have forced a rebuild and deploy without using cache and this didn't change the output. I also (after reading someone's similar caching problem on StackOverflow) tried setting the node and npm engines in the config file for the ones that DO specifically uses. This forced it to re-parse the package.json and build from scratch but it still pre-renders duplicate pascal case files.

I imagine that a fresh install shouldn't do it. But,  when I get time, I will try to set one up with the CLI and test on DO.

**Comment by madebyfabian** [comment] 2023-02-07 08:29
Do you use the Preset from Nitro?

**Comment by driven-group** [comment] 2023-02-07 08:36
@madebyfabian yes. I have included it in my nuxt.config under nitro: { preset: 'digital-ocean' } and also as an environment variable [NITRO_PRESET]  in the App Platform.

**Comment by madebyfabian** [comment] 2023-02-07 08:44
Let's wait for the result of your freshly deployed project so we discuss that. I'm happy to help, but I think it's fine to let this issue closed right?

**Comment by driven-group** [comment] 2023-02-07 08:47
Yeh sure. it definitely sounds like a DO issue and not a Nuxt one. Am I able to reply to you here after testing though? Even if it is closed?

**Comment by madebyfabian** [comment] 2023-02-07 09:35
@driven-group sure, it's already closed and out comments work regardlessly 😊
