### ISSUE TITLE
WebSocket proxy using devProxy not functioning in Nuxt 3.12.2

### ISSUE THREAD

**Issue by HorseNewBee** [nuxt/nuxt#28098] opened 2024-07-10 10:00 UTC
### Environment

Additional Information
Nuxt version: 3.12.2
Node.js version: v20.9.0
Operating System: Windows11

### Reproduction

 ```typescript
   export default defineNuxtConfig({
     nitro: {
       devProxy: {
         '/ws': {
           target: 'ws://localhost:8080',
           ws: true,
           changeOrigin: true
         }
       }
     }
   })

### Describe the bug

1. Set up `devProxy` in `nuxt.config.ts` as follows:
   ```typescript
   export default defineNuxtConfig({
     nitro: {
       devProxy: {
         '/ws': {
           target: 'ws://localhost:8080',
           ws: true,
           changeOrigin: true
         }
       }
     }
   })
2.Attempt to connect to WebSocket from the client using:
```javascript
const socket = new WebSocket('ws://localhost:3000/ws');
```
3.The connection fails with the error: "WebSocket connection to 'ws://localhost:3000/ws' failed".
Expected Behavior
The WebSocket connection should be successfully proxied to ws://localhost:8080 without any errors.

Actual Behavior
The WebSocket fails to connect through the proxy, and the browser console shows an error indicating the connection failure. However, directly connecting with ws.value = new WebSocket('ws://localhost:8080/ws'); functions without issues.

**Comment by izzygld** [comment] 2024-07-10 13:58
@HorseNewBee 

have you tried setting the devProxy like this:

`  nitro: {
    devProxy: {
      '/ws': {
        target: 'ws://localhost:4000',
        changeOrigin: true, // Typically true for proxies
        prependPath: false, // Change to false if the path is not needed to be prepended
        ws: true, // Ensures WebSocket proxying is enabled
      },
    },`
    
    the using it:
`const socket = new WebSocket('ws://localhost:4000/ws');
socket.onmessage = function (event) {
  console.log(event.data);
};`

**Comment by HorseNewBee** [comment] 2024-07-11 05:21
you mean Configuration in nuxt.config.ts:
```javascripts
nitro: {
    devProxy: {
      '/ws': { 
        target: 'ws://localhost:8080', // This is my WebSocket server address
        ws: true,
        changeOrigin: true,
        prependPath: false
      }
    }
  },
```
Usage:
```javascripts
ws.value = new WebSocket('ws://localhost:3000/ws'); // This is my Nuxt application port
```
this also not working

**Comment by HorseNewBee** [comment] 2024-07-11 08:28
> 你能提供[复制](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)品吗？🙏
> 
> 更多信息
> ### 为什么我需要提供复制品？
> 复制品使我们能够在相对较小的团队中快速分类和解决问题。它可以帮助我们发现问题的根源，也可以揭示您或我们可能做出的假设。
> 
> ### 会发生什么？
> 如果您提供了复制品，我们将移除标签并尝试重现该问题。如果可以，我们会将其标记为错误，并根据其严重程度以及我们认为它可能影响的人数对其进行优先级排序。
> 
> 如果标记的问题没有收到任何实质性活动（例如，带有复制链接的新评论），我们将关闭它们。那不是因为我们不在乎！在任何时候，请随时通过复制品发表评论，我们将重新打开它。`needs reproduction`
> 
> ### 如何创建复制品？
> 我们有几个模板可以从最小的复制开始：
> 
> 👉 👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz https://codesandbox.io/s/github/nuxt/starter/v3-codesandbox
> 
> 公共 GitHub 存储库也是完美的。👌
> 
> 请确保复制尽可能**少**。[请参阅我们的指南](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)中的更多详细信息。
> 
> 您可能还会发现这些其他文章有趣和/或有用：
> 
> * [复制品的重要性](https://antfu.me/posts/why-reproductions-are-required)
> * [如何生成最小、完整且可验证的示例](https://stackoverflow.com/help/minimal-reproducible-example)

https://github.com/HorseNewBee/nuxt_front_issue

**Comment by HorseNewBee** [comment] 2024-07-11 08:31
I've set up a repository to help reproduce the issue we're discussing. You can find it here:
[nuxt_front_issue](https://github.com/HorseNewBee/nuxt_front_issue)

Please take a look and let me know if you need any further information or if there's anything else I can assist with.

**Comment by kuhma** [comment] 2024-08-26 09:47
> @HorseNewBee
> 
> have you tried setting the devProxy like this:
> 
> ` nitro: { devProxy: { '/ws': { target: 'ws://localhost:4000', changeOrigin: true, // Typically true for proxies prependPath: false, // Change to false if the path is not needed to be prepended ws: true, // Ensures WebSocket proxying is enabled }, },`
> 
> ```
> the using it:
> ```
> 
> `const socket = new WebSocket('ws://localhost:4000/ws'); socket.onmessage = function (event) { console.log(event.data); };`

Sadly, this does not solve the issue in Nuxt 3.13.

My conf :

```
   nitro: {
    devProxy: {
      '/wss': {
        target: 'ws://wss:9501/',
        ws: true,
        changeOrigin: true,
        prependPath: false,
      },
    },
  },
```

```
webSocket = new WebSocket('ws://172.18.0.10:3000/wss');
```

The log :

> Page not found: /wss
> 
>   at Module.createError (node_modules/h3/dist/index.mjs:78:15)
>   _at node_modules/nuxt/dist/pages/runtime/plugins/router.js:123:100_
>   at fn (node_modules/nuxt/dist/app/nuxt.js:229:44)
>   at Object.callAsync (node_modules/unctx/dist/index.mjs:68:55)
>   at node_modules/nuxt/dist/app/nuxt.js:232:56
>   at Object.runWithContext (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2690:18)
>   at callWithNuxt (node_modules/nuxt/dist/app/nuxt.js:232:24)
>   at node_modules/nuxt/dist/app/nuxt.js:42:41
>   at EffectScope.run (node_modules/@vue/reactivity/dist/reactivity.cjs.js:47:16)
>   at Object.runWithContext (node_modules/nuxt/dist/app/nuxt.js:42:31)


I'm stuck to Nuxt 3.10 and cannot upgrade because of this issue.
The workaround from https://github.com/nuxt/cli/issues/107 does work until Nuxt 3.10, not following releases.

**Comment by matiaslauriti** [comment] 2024-08-27 09:24
I think the issue is that we are still using `nuxt/cli: 3.12.0` instead of the new version `3.13.0` (it is fixed there...

**Comment by danwritecode** [comment] 2024-09-24 02:51
Any update on this?

**Comment by danielroe** [comment] 2024-11-08 23:04
Closing as it's reported fixed in latest nuxi. If that's not the case, let me know with a minimal reproduction and I'll happily reopen.

**Closed by danielroe** 2024-11-08 23:04 UTC
Labels: pending triage, nitro, upstream, windows
