### ISSUE TITLE
[3.1] Many server middlewares issue 

### ISSUE THREAD

**Issue by Loyz07** [nuxt/nuxt#18518] opened 2023-01-25 16:07 UTC
### Discussed in https://github.com/nuxt/nuxt/discussions/18515

<div type='discussions-op-text'>

<sup>Originally posted by **Loyz07** January 25, 2023</sup>
Hello,

I've just updated nuxt to v3.1 and since this update I don't manage to run many server middlewares anymore.

I have 2 server middlewares `logger.ts` and `authentication.ts`. Only `logger.ts` is executed on requests.
If I add a 3rd middleware `test.ts` only this one is executed.
If I rename `test.ts` to `a.ts` only `logger.ts` is executed.

It seems that only the last middleware (A-Z sorted) is executed.

Someone could confirm so that I can submit an issue ?

Thanks.</div>

Here is a link to reproduce:
https://stackblitz.com/edit/nuxt-starter-511bme?file=server/middleware/a.ts

`a` is not console.logged.

**Comment by yassilah** [comment] 2023-01-25 17:28
Hi, I believe it was due to a regression from this PR https://github.com/unjs/nitro/pull/807 that should be fixed by https://github.com/unjs/nitro/pull/881 😅

**Comment by danielroe** [comment] 2023-01-26 06:23
This should be resolved in nitropack v2.1.3. which you can get with `yarn upgrade nuxt --force`.

Let me know if not and I'll reopen.

**Closed by danielroe** 2023-01-26 06:23 UTC
Labels: bug, nitro, ❗ p4-important, upstream-bug
