### ISSUE TITLE
can't save cookie

### ISSUE THREAD

**Issue by TianbinTobin** [nuxt/nuxt#20030] opened 2023-04-01 20:18 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.1.0`
- Builder:          `vite`
- User Config:      `app`, `css`, `typescript`, `modules`, `vite`, `vueuse`, `elementPlus`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`, `@element-plus/nuxt@1.0.4`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ygai5g?file=composables/user.ts

### Describe the bug

why can't save cookie?

**Comment by danielroe** [comment] 2023-04-02 14:09
I can't reproduce this locally - note that there may be issues saving cookies on stackblitz due to its setup.

**Comment by TianbinTobin** [comment] 2023-04-02 14:15
> I can't reproduce this when I run that sandbox locally - note that there may be issues saving cookies on stackblitz due to its setup.

I can't save cookies to the browser when i run that sandbox locally unless i delete ` token.value = '11111';`

**Comment by danielroe** [comment] 2023-04-02 14:17
My steps - download sandbox. Install dependencies with pnpm. Visit localhost:3000, click button and refresh page to confirm that the cookie is saved.

You could try refreshing your lockfile, perhaps. We merged a fix in `hookable` and you might be running the old version of it.

**Closed** 2023-04-25 22:25 UTC
Labels: 3.x, pending triage, needs reproduction
