### ISSUE TITLE
useState inside plugin is not reactive when ssr: false

### ISSUE THREAD

**Issue by sei-jdshimkoski** [nuxt/nuxt#27620] opened 2024-06-14 19:26 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.1`
- Nuxt Version:     `3.12.1`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@9.6.7`
- Builder:          `-`
- User Config:      `runtimeConfig`, `ssr`, `telemetry`, `typescript`, `app`, `css`, `modules`, `build`
- Runtime Modules:  `@nuxt/eslint@0.3.13`, `@nuxtjs/tailwindcss@6.12.0`, `@vueuse/nuxt@10.11.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-kttbxc?file=plugins%2Ftest.ts,app.vue,components%2FChangeTestButton.vue

### Describe the bug

When ssr: false, useState is not reactive across the application when used in a plugin.

If you set ssr: true, the reactivity issue goes away.

This was not an issue in 3.11.2.

### Logs

```shell-script
There are no logs.
```

**Comment by danielroe** [comment] 2024-06-14 21:02
This should be resolved in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel) by https://github.com/nuxt/nuxt/pull/27542, or in the next release.

Until the next patch, you can work around by creating `~/plugins/payload-reactivity.client.ts` with the following content:`

```ts
export default defineNuxtPlugin(nuxtApp => {
  const payload = nuxtApp.payload

  for (const key in ['_errors', 'data']) {
    if (!isReactive(payload[key])) {
      payload[key] = shallowReactive(payload[key])
    }
  }

  if (!isReactive(payload.state)) {
    payload.state = reactive(payload.state)
  }
})
```

**Closed by danielroe** 2024-06-14 21:02 UTC
Labels: 3.x, pending triage

**Comment by dimer47** [comment] 2024-06-15 13:55
I encountered an issue after installing an NPM package: the state variables managed by useState were no longer updating. After some investigation, I discovered that the installation of this package had upgraded the Nuxt.js version to 3.12.1 due to the ^ in front of the version. Reverting to my previous version resolved the issue, but it took me a while to identify the cause. Many thanks to @sei-jdshimkoski for pointing out this problem. 
@danielroe When issues like this are detected, it would be helpful to have a newsletter communication to inform users about such critical problems.

I thought I was going crazy 😵‍💫
