### ISSUE TITLE
lottie-web icon not show in nuxt3 build mode

### ISSUE THREAD

**Issue by sunnywanggit** [nuxt/nuxt#18574] opened 2023-01-27 11:57 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/sunnywanggit/coverage

### Describe the bug

lottie-web icon is normal in dev mode but not show in  build mode

### Additional context
dev mode:
![image](https://user-images.githubusercontent.com/53786183/215081257-31f8f95a-6987-4b97-b07a-b38a78512b6b.png)

build mode not show:
![image](https://user-images.githubusercontent.com/53786183/215081360-8d23e2ec-a548-4010-86e7-8dc84a2c4f99.png)

_No response_

**Comment by Baroshem** [comment] 2023-01-27 14:38
Hey,

That is an interesting issue. Could you create a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)?

**Comment by pascalwengerter** [comment] 2023-01-27 14:42
I have a working setup for using lottie-web, however with a different approach - I load the JSON file containing the animation from a static URL.
My guess after taking a look at the repository you linked is that the issue is somewhat related to having `.ts` files in the `assets/` folder - I can see URLs to `coverage/assets/useanimations/mail/mail.json` in the `.output/public/_nuxt/`-folder, but those should actually be part of your bundle (that is, _within_ the `.output/public` folder) as well?

**Comment by pascalwengerter** [comment] 2023-01-27 15:02
Update: Moving the ref to the div instead of binding it via `v-bind` works (`<div ref="useAnimationRef" v-bind="eventProps" />`), so I guess this issue can be closed as non nuxt-related

**Closed** 2023-02-01 17:29 UTC
Labels: 3.x, pending triage
