### ISSUE TITLE
Nuxt.config.ts and (i18n) language settings from Nuxt Layer overwriting the languages setting in current project [Nuxt Layers]

### ISSUE THREAD

**Issue by dora-jurcevic** [nuxt/nuxt#22196] opened 2023-07-18 12:42 UTC
### Environment

- i18n module installed in the Layer Project

The Layer project has 3 languages defined in the nuxt.config.ts as below:

```

i18n: {
    locales: [
      {
        code: 'en',
        iso: 'en_us',
        file: 'en-US.json',
        name: 'English',
        icon: 'circle-flags:uk'
      },
      {
        code: 'es',
        iso: 'es_es',
        file: 'es-ES.json',
        name: 'Español',
        icon: 'circle-flags:es'
      },
      {
        code: 'fr',
        iso: 'fr_fr',
        file: 'fr-FR.json',
        name: 'Français',
        icon: 'circle-flags:fr'
      }
    ],
    debug: false,
    lazy: true,
    langDir: 'locales',
    defaultLocale: 'fr'
  },

```

### Reproduction

Create a new project and extend from the Layer project thta has i18n installed with language settings in the nuxt.config.ts file

### Describe the bug

When creating a new project that extends from the Layer Poject, the new project inherits the language settings  from the Layer even though the new project uses other languages (or only one of the languages from the Layer).

### Additional context

This is for a e-Commerce Nuxt Layer  projectthat uses languages not only for texts but also for ElasticSearch indexes for fetching products .
Here is the link to the Layer project on github and the nuxt.config.ts file https://github.com/shopinvader/shopinvader-template-nuxtjs/blob/main/nuxt.config.ts

**Comment by danielroe** [comment] 2023-07-18 14:38
By design, layers _merge_ configuration, and arrays end up getting concatenated.

There are a couple solutions here:

1. you can use a [custom resolver](https://nuxt.com/docs/guide/directory-structure/app-config#app-config-merging-strategy-in-layers) to prevent this array merge behaviour.
2. you can use a custom module to replace the merged configuration with the configuration you want, or set the configuration based on the end user's project rather than just merging configuration.

**Closed by danielroe** 2023-07-18 14:38 UTC
Labels: 3.x, pending triage
