### ISSUE TITLE
(3.9.2) Unscoped styles are not working on the server side - only in development

### ISSUE THREAD

**Issue by darioferderber** [nuxt/nuxt#25258] opened 2024-01-17 13:33 UTC
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, css
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-19up3f?file=pages%2Findex.vue

### Describe the bug

This issue only occurs in the development mode using `nuxt@3.9.2`.

Unscoped styles are not working on the server side - there are no `style` or `link rel="stylesheet"` elements in the `head`.
`css` option from the `nuxt.config` doesn't work too. Styles are loaded only on the client side so everything flickers.

Scoped styles are working fine.
If we build the application everything works fine.

### Additional context

Maybe [this](https://github.com/nuxt/nuxt/commit/20e88bb171b34a749f5468238815b022163e262e#diff-db3a4ecfe5a4e5a379ed2f515a315f812ddc26b48ce80dd3f2cada3b75c06c12R369) could be a reason for the issue but I'm not 100% sure.

**Comment by manniL** [comment] 2024-01-17 13:55
Duplicate of https://github.com/nuxt/nuxt/issues/25240

**Closed by manniL** 2024-01-17 13:55 UTC
Labels: 3.x, pending triage

**Comment by darioferderber** [comment] 2024-01-17 14:01
> Duplicate of #25240

My bad, I wasn't looking at the `closed` issues. Although it's a bit strange that it's closed before the release of a patch 🙂
