### ISSUE TITLE
Named export 'consola' not found

### ISSUE THREAD

**Issue by hopkins385** [nuxt/nuxt#20209] opened 2023-04-11 16:52 UTC
### Environment

Nuxi 3.4.0

------------------------------
- Operating System: Darwin
- Node Version:     v19.8.1
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      runtimeConfig, modules, imports, app, vite, sitemap, tailwindcss, googleFonts, i18n, content
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.10, @nuxt/content@2.5.2, @nuxtjs/tailwindcss@6.6.5, @pinia/nuxt@0.4.8, nuxt-icon@0.3.3, nuxt-headlessui@1.1.1, nuxt-simple-sitemap@2.4.8, @nuxtjs/google-fonts@3.0.0, nuxt-swiper@1.1.0, @vueuse/nuxt@9.13.0
- Build Modules:    -

### Reproduction

1. yarn nuxi upgrade --force 
2. yarn dev
3. visit http://localhost:3000

### Describe the bug

> :warning: **Request Error 500**: Named export 'consola' not found.

```
[nuxt] [request error] [unhandled] [500] Named export 'consola' not found.
```

```
The requested module 'consola' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'consola';
const { consola } = pkg;   

 at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
```

**Comment by warflash** [comment] 2023-04-11 16:55
Experiencing the same issue after upgrading to 3.4

**Comment by danielroe** [comment] 2023-04-11 17:19
This issue is likely caused by other dependencies hoisting consola v2 to the top level.

For now, you can likely work around it by adding pnpm/npm overrides or yarn resolutions.

cc: @pi0

**Comment by stafyniaksacha** [comment] 2023-04-11 17:21
Same here, here is an output of `pnpm why consola`

```
devDependencies:
@nuxt/devtools 0.3.2
├─┬ @nuxt/devtools-kit 0.3.2
│ ├─┬ @nuxt/kit 3.4.0
│ │ └── consola 3.0.1
│ └─┬ nuxt 3.4.0 peer
│   ├─┬ @nuxt/kit 3.4.0
│   │ └── consola 3.0.1
│   ├─┬ @nuxt/telemetry 2.2.0
│   │ ├─┬ @nuxt/kit 3.4.0
│   │ │ └── consola 3.0.1
│   │ └── consola 3.0.1
│   ├─┬ @nuxt/vite-builder 3.4.0
│   │ └─┬ @nuxt/kit 3.4.0
│   │   └── consola 3.0.1
│   └─┬ nitropack 2.3.3
│     └── consola 3.0.1
├─┬ @nuxt/devtools-wizard 0.3.2
│ └── consola 2.15.3
├─┬ @nuxt/kit 3.4.0
│ └── consola 3.0.1
├── consola 2.15.3
└─┬ nuxt 3.4.0 peer
  ├─┬ @nuxt/kit 3.4.0
  │ └── consola 3.0.1
  ├─┬ @nuxt/telemetry 2.2.0
  │ ├─┬ @nuxt/kit 3.4.0
  │ │ └── consola 3.0.1
  │ └── consola 3.0.1
  ├─┬ @nuxt/vite-builder 3.4.0
  │ └─┬ @nuxt/kit 3.4.0
  │   └── consola 3.0.1
  └─┬ nitropack 2.3.3
    └── consola 3.0.1
@nuxt/image-edge 1.0.0-28008586.381b906
├─┬ @nuxt/kit 3.4.0
│ └── consola 3.0.1
├── consola 2.15.3
└─┬ ipx 1.0.0
  └── consola 2.15.3
@pinia/nuxt 0.4.8
└─┬ @nuxt/kit 3.4.0
  └── consola 3.0.1
@vite-pwa/nuxt 0.0.7
└─┬ @nuxt/kit 3.4.0 peer
  └── consola 3.0.1
consola 3.0.1
nuxt 3.4.0
├─┬ @nuxt/kit 3.4.0
│ └── consola 3.0.1
├─┬ @nuxt/telemetry 2.2.0
│ ├─┬ @nuxt/kit 3.4.0
│ │ └── consola 3.0.1
│ └── consola 3.0.1
├─┬ @nuxt/vite-builder 3.4.0
│ └─┬ @nuxt/kit 3.4.0
│   └── consola 3.0.1
└─┬ nitropack 2.3.3
  └── consola 3.0.1
pinceau 0.18.8
├── consola 2.15.3
├─┬ style-dictionary-esm 1.3.7
│ └── consola 2.15.3
└─┬ unbuild 1.2.0
  └── consola 2.15.3
```

Can be fixed by adding this into `package.json`

```json
  "pnpm": {
    "overrides": {
      "consola": "3.0.1"
    }
  }
```

**Comment by hopkins385** [comment] 2023-04-11 18:24
Workaround seems to be working.

`yarn add -D consola` installs in my case `"consola": "^3.0.1",`

Result: error no longer present

**Comment by lupus78** [comment] 2023-04-11 18:47
I also experience the issue, and yes the "workaround" works `npm install consola@3.0.1`

However, a fresh nuxt install works, so it must be one of the modules we have installed.

**Comment by luc122c** [comment] 2023-04-11 20:05
Hi, I'm having the same issue after upgrading to Nuxt 3.4.0. `yarn add -D consola` also resolves the issue for me. Below is the output of `yarn why consola` before and after adding the dependency. 

<details>
<summary>Before</summary>

```console
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "consola"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "consola@2.15.3"
info Has been hoisted to "consola"
info Reasons this module exists
   - Hoisted from "@nuxt#devtools#consola"
   - Hoisted from "@nuxt#image-edge#consola"
   - Hoisted from "@nuxt#devtools#@nuxt#devtools-wizard#consola"
   - Hoisted from "@nuxt#image-edge#ipx#consola"
info Disk size without dependencies: "220KB"
info Disk size with unique dependencies: "220KB"
info Disk size with transitive dependencies: "220KB"
info Number of shared dependencies: 0
=> Found "@nuxt/kit#consola@3.0.1"
info This module exists because "nuxt#@nuxt#kit" depends on it.
info Disk size without dependencies: "264KB"
info Disk size with unique dependencies: "264KB"
info Disk size with transitive dependencies: "264KB"
info Number of shared dependencies: 0
=> Found "@nuxt/telemetry#consola@3.0.1"
info This module exists because "nuxt#@nuxt#telemetry" depends on it.
info Disk size without dependencies: "264KB"
info Disk size with unique dependencies: "264KB"
info Disk size with transitive dependencies: "264KB"
info Number of shared dependencies: 0
=> Found "nitropack#consola@3.0.1"
info This module exists because "nuxt#nitropack" depends on it.
info Disk size without dependencies: "264KB"
info Disk size with unique dependencies: "264KB"
info Disk size with transitive dependencies: "264KB"
info Number of shared dependencies: 0
✨  Done in 0.21s.
```

</details>


<details>
<summary>After</summary>

```console
yarn why consola
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "consola"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "consola@3.0.1"
info Has been hoisted to "consola"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "nuxt#@nuxt#kit#consola"
   - Hoisted from "nuxt#@nuxt#telemetry#consola"
   - Hoisted from "nuxt#nitropack#consola"
info Disk size without dependencies: "264KB"
info Disk size with unique dependencies: "264KB"
info Disk size with transitive dependencies: "264KB"
info Number of shared dependencies: 0
=> Found "@nuxt/devtools#consola@2.15.3"
info This module exists because "@nuxt#devtools" depends on it.
info Disk size without dependencies: "220KB"
info Disk size with unique dependencies: "220KB"
info Disk size with transitive dependencies: "220KB"
info Number of shared dependencies: 0
=> Found "@nuxt/image-edge#consola@2.15.3"
info This module exists because "@nuxt#image-edge" depends on it.
info Disk size without dependencies: "220KB"
info Disk size with unique dependencies: "220KB"
info Disk size with transitive dependencies: "220KB"
info Number of shared dependencies: 0
=> Found "@nuxt/devtools-wizard#consola@2.15.3"
info This module exists because "@nuxt#devtools#@nuxt#devtools-wizard" depends on it.
info Disk size without dependencies: "220KB"
info Disk size with unique dependencies: "220KB"
info Disk size with transitive dependencies: "220KB"
info Number of shared dependencies: 0
=> Found "ipx#consola@2.15.3"
info This module exists because "@nuxt#image-edge#ipx" depends on it.
info Disk size without dependencies: "220KB"
info Disk size with unique dependencies: "220KB"
info Disk size with transitive dependencies: "220KB"
info Number of shared dependencies: 0
✨  Done in 0.21s.
```

</details>

**Comment by Kashalls** [comment] 2023-04-11 23:44
Noticing this when I add `nuxt-icon` to my current list of modules:
```js
  modules: [
    '@nuxt/content',
    '@nuxtjs/color-mode',
    '@nuxtjs/tailwindcss'
  ],
  ```

Removing the module using `yarn remove` allows everything to work correctly.

**Comment by Kashalls** [comment] 2023-04-12 04:09
> started

I'm on 3.4. I have a couple apps at 3.3 I can try updating.

**Comment by localusercamp** [comment] 2023-04-12 04:51
Same here, `overrides` does not helps

**Comment by minarc** [comment] 2023-04-12 05:17
I experienced the same problem. In my case, running `nuxi upgrade --force` resolved the issue.

I hope this works.

**Comment by jianbin-lim** [comment] 2023-04-12 06:05
I have the same issue

**Comment by agracia-foticos** [comment] 2023-04-13 06:20
Same issue 

- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.0`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `vite`, `i18n`, `nitro`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.1`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.13.0`, `nuxt-schema-org@2.1.2`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@sidebase/nuxt-auth@0.4.4`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`

**Comment by MikeAltinget** [comment] 2023-04-13 09:21
This also happens to me on 3.3.1 if i delete my node_modules and lockfile and reinstall. Fixed by the workaround

**Comment by jordan-boyer** [comment] 2023-04-13 11:11
For those using @nuxtjs/tailwindcss you need to wait for them to update they package because they are still in nuxt/kit 3.3.3 instead of nuxtkit 3.4

I'm using pnpm workspace so for me adding consola in my root package solve the issue

**Comment by therealokoro** [comment] 2023-04-14 10:12
On v3.4.1 and this fixed it for me


> 
> Can be fixed by adding this into `package.json` if using `pnpm`
> 
> ```json
>   "pnpm": {
>     "overrides": {
>       "consola": "3.0.1"
>     }
>   }
> ```

**Comment by steklopod** [comment] 2023-04-14 18:52
Fix with in `package.json`:
```js
  "peerDependencies": {
    "consola": "3.0.1"
  },
```

**Comment by jboada** [comment] 2023-04-15 16:22
> I experienced the same problem. In my case, running `nuxi upgrade --force` resolved the issue.
> 
> I hope this works.

It works this way. I did not use the --force option when I updated it the first time, then I ran the upgrade command using the --force option and it worked flawlessly.

**Comment by rizqirizqi** [comment] 2023-04-16 07:50
`nuxi upgrade --force` option is not for me since it will delete node_modules, lock file, and reinstall all my deps, it's too risky for a big project, I will be waiting for the update from the other deps to upgrade consola before upgrading nuxt

**Comment by fyyyyy** [comment] 2023-04-18 19:01
With npm and node >= 18 this happens in case you run
` npm update nuxt ` instead of ` npm update nuxt --legacy-peer-deps` 
to fix it, run npm i --legacy-peer-deps

**Comment by sdsoldi** [comment] 2023-04-21 08:36
Same here

**Comment by pi0** [comment] 2023-04-21 09:52
Hi. I apologize for any issues you are encountering with this upgrade. If you are using nuxt as a dependency in your project:

1. Use `npx nuxi upgrade --force` to upgrade the lock file. Check if the issue is solved.
2. Use [pnpm why](https://pnpm.io/cli/why), [npm-why](https://www.npmjs.com/package/npm-why) or [yarn why](https://classic.yarnpkg.com/lang/en/docs/cli/why/) and check list of dependencies that are still using `consola@2`. Please consider reporting them here so we can track and ask them to upgrade. If hoisted (top level) consola version in results is still v2, add a `resolutions` field to your project's `package.json` and renew lockfile or install:

```json
{
  "resolutions": {
    "consola": "^3.0.0"
  }
}
```


If you are a library or module author:

1. Check if you are directly having `consola` as a `dependency`, if you have it, upgrade to `v3` and change `import consola` to `import { consola }`
1. Followup steps above to find out about the possible sub-dependency issues
1. Use `resolutions`, to fix your **local development** branch and followup with sub-dependency issues here to be resolved. Advice your users to use above steps in the meanwhile.

**Comment by sdsoldi** [comment] 2023-04-21 10:32
> Hi. I apologize for any issues you are encountering with this upgrade.
> 
> If you are using nuxt as a dependency in your project:
> 
>     1. Use `npx nuxi upgrade --force` to upgrade the lock file. Check if the issue is solved.
> 
>     2. Use [pnpm why](https://pnpm.io/cli/why), [npm-why](https://www.npmjs.com/package/npm-why) or [yarn why](https://classic.yarnpkg.com/lang/en/docs/cli/why/) and check list of dependencies that are still using `consola@2`. Please consider reporting them here so we can track and ask them to upgrade. If hoisted (top level) consola version in results is still v2, add a `resolutions` field to your project's `package.json` and renew lockfile or install:
> 
> 
> ```json
> {
>   "resolutions": {
>     "consola": "^3.0.0"
>   }
> }
> ```
> 
> If you are a library or module author:
> 
>     1. Check if you are directly having `consola` as a `dependency`, if you have it, upgrade to `v3` and change `import consola` to `import { consola }`
> 
>     2. Followup steps above to find out about the possible sub-dependency issues
> 
>     3. Use `resolutions`, to fix your **local development** branch and followup with sub-dependency issues here to be resolved. Advice your users to use above steps in the meanwhile.


In my proyect: 

> nuxt-icon > nuxt-config-schema@0.4.5 > changelogen@0.4.1 > consola@2.15.3

**Comment by pi0** [comment] 2023-04-21 11:51
@sdsoldi Thanks for reporting. [nuxt-config-schema is fixed](https://github.com/nuxt-experiments/nuxt-config-schema/releases/tag/v0.4.6) you can try again by recreating lockfile.

**Comment by sdsoldi** [comment] 2023-04-21 12:02
@pi0 Fixed! Thanks!!!

**Comment by alko89** [comment] 2023-04-22 18:36
I literally get this in a new project:

```
$ npx nuxt init ui
$ cd ui
$ npm install
$ npm run dev
Nuxi 3.4.2                                                                                                                                                                     8:33:11 PM
Nuxt 3.4.2 with Nitro 2.3.3                                                                                                                                                    8:33:11 PM
                                                                                                                                                                               8:33:12 PM
  > Local:    http://localhost:3000/ 
  > Network:  http://172.18.0.1:3000/
  > Network:  http://172.19.0.1:3000/
  > Network:  http://172.20.0.1:3000/
  > Network:  http://172.21.0.1:3000/
  > Network:  http://192.168.10.159:3000/

ℹ Vite client warmed up in 761ms                                                                                                                                               8:33:13 PM
✔ Nitro built in 388 ms                                                                                                                                                  nitro 8:33:13 PM
[8:33:21 PM] [nuxt] [request error] [unhandled] [500] Named export 'consola' not found. The requested module 'consola' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'consola';
const { consola } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
[8:33:21 PM] [nuxt] [request error] [unhandled] [500] Named export 'consola' not found. The requested module 'consola' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'consola';
const { consola } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
npm run dev  4,93s user 0,28s system 28% cpu 18,018 total

$ node --version
v19.8.1
$ npm -version
8.19.2
```

**Comment by danielroe** [comment] 2023-04-22 18:41
@alko89 Would you check if you have a node_modules folder in a parent directory?

**Comment by alko89** [comment] 2023-04-22 18:54
@danielroe yep, its a monorepo project, parrent `package.json`

```
{
  "name": "task",
  "version": "1.0.0",
  "description": "",
  "authors": {
    "name": "",
    "email": ""
  },
  "license": "MIT",
  "workspaces": [
    "api",
    "ui"
  ]
}
```

**Comment by proalaa** [comment] 2023-04-23 14:14
Hi I faced the same issue

and this is the result of 

> $ npx npm-why consola

  Who required consola:

> @nuxt/devtools > consola@2.15.3
> @nuxt/image-edge > ipx > consola@2.15.3

**Comment by jjjuulliiaann** [comment] 2023-04-24 14:32
I have the same issue but adding a resolutions field is working fine.

`pnpm why consola` returns:

> dependencies:
@nuxtjs/sanity 1.6.0
└─┬ @nuxt/kit 3.1.0
  └── consola 2.15.3

**Comment by noook** [comment] 2023-04-25 09:44
> app > @nuxt/devtools > consola@2.15.3

**Comment by StefanVDWeide** [comment] 2023-04-26 12:46
Another two libaries using consola 2.X.X

```
npx npm-why consola

  Who required consola:

  studio-terabyte-website-nuxt-3 > @funken-studio/sitemap-nuxt-3 > consola@2.15.3
  studio-terabyte-website-nuxt-3 > @nuxt/image-edge > ipx > consola@2.15.3
```

Adding consola to resolutions has fixed the issue

**Comment by pumano** [comment] 2023-05-01 21:01
I'm using nuxt only few months and I got multiple problems not only for updating from 2 to 3 but every single release you something to broke! I'm frustrated. Please think about it, your product used by many people. Maybe invest in unit tests more?

**Comment by ChristoPy** [comment] 2023-05-02 19:40
Hi this issue just happened. These are the libraries who are using consola 2.X.X:

```
npx npm-why consola

  Who required consola:

  @nestjs/core > @nuxtjs/opencollective > consola@2.15.3
```

Adding consola to resolutions didn't fix the issue, either in the nuxt app `package.json` or the root `package.json`

**Comment by Orbitoly** [comment] 2023-05-03 09:33
Solved for me when upgrading to nuxt's latest version and removing nuxtImage module.

**Comment by hopkins385** [comment] 2023-05-10 15:08
Upstream

**Closed** 2023-05-10 15:08 UTC
Labels: 3.x, workaround available, upstream

**Comment by AliNaraghiA** [comment] 2023-05-12 16:49
what can i do with this: Error cannot start nuxt :cannot read properties of undefined (reading 'hook')

-nuxtbootstarpvue
-installmodule
-async initNuxt/load/_main/Object.invoke

**Comment by danielroe** [comment] 2023-05-12 16:58
@AliNaraghiA You are using a module that isn't compatible with Nuxt 3.

**Comment by KevinNTH** [comment] 2023-05-14 18:45
I fail to understand how to fix this, but `npx nuxi init my-app` will result with this consola error...

**Comment by hermanndettmann** [comment] 2023-05-14 21:05
> Hi. I apologize for any issues you are encountering with this upgrade.
> 
> If you are using nuxt as a dependency in your project:
> 
> 1. Use `npx nuxi upgrade --force` to upgrade the lock file. Check if the issue is solved.
> 2. Use [pnpm why](https://pnpm.io/cli/why), [npm-why](https://www.npmjs.com/package/npm-why) or [yarn why](https://classic.yarnpkg.com/lang/en/docs/cli/why/) and check list of dependencies that are still using `consola@2`. Please consider reporting them here so we can track and ask them to upgrade. If hoisted (top level) consola version in results is still v2, add a `resolutions` field to your project's `package.json` and renew lockfile or install:
> 
> ```json
> {
>   "resolutions": {
>     "consola": "^3.0.0"
>   }
> }
> ```
> 
> If you are a library or module author:
> 
> 1. Check if you are directly having `consola` as a `dependency`, if you have it, upgrade to `v3` and change `import consola` to `import { consola }`
> 2. Followup steps above to find out about the possible sub-dependency issues
> 3. Use `resolutions`, to fix your **local development** branch and followup with sub-dependency issues here to be resolved. Advice your users to use above steps in the meanwhile.

I have a monorepo project that consists of nuxt for the frontend and strapi for the backend. I tried to fix it with the "resolutions" key in nuxts package.json but it didn't work.

Those are the deps that still using console v2:
> @strapi/strapi > @strapi/admin > webpackbar > consola@2.15.3
> strapi-plugin-io > @strapi/strapi > @strapi/admin > webpackbar > consola@2.15.3

**Comment by danielroe** [comment] 2023-05-15 08:32
@hermanndettmann You may need to use `overrides` or `pnpm.overrides` depending on your package manager.

**Comment by hermanndettmann** [comment] 2023-05-15 23:00
Thanks @danielroe for your reply! I tried `overrides` because I'm using just plain ol' `npm` but unfortunately it didn't help. I added the following to my package.json:
```
"overrides": {
     "consola": "^3.0.0"
},
```

**Comment by hermanndettmann** [comment] 2023-05-28 21:47
> Thanks @danielroe for your reply! I tried `overrides` because I'm using just plain ol' `npm` but unfortunately it didn't help. I added the following to my package.json:
> 
> ```
> "overrides": {
>      "consola": "^3.0.0"
> },
> ```

Just for the record: I got it working finally. I just put the `overrides` into the wrong place. My monorepo is structured like this:

```
nuxt/
- package.json
strapi/
- package.json
package.json
```
I first put the overrides into `nuxt/package.json` but that didn't work. What made it work was putting it into the roots `package.json`.

I hope that helps some other desperate node tinkerer like me. :-)
