### ISSUE TITLE
useAsyncData with { immediate: false } returns pending = "true" until fired at least once.

### ISSUE THREAD

**Issue by Zebnastien** [nuxt/nuxt#23562] opened 2023-10-07 10:21 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools, modules, build, typescript, supabase
- Runtime Modules:  @nuxtjs/supabase@1.1.3
- Build Modules:    -

### Reproduction

Using the following code...

```vue
<template>
  {{ pending }}

  <input
    @click="refresh()"
    type="button"
    value="Refresh"
  />
</template>

<script setup lang="ts">
const { data, error, pending, status, refresh } = useFetch(
  "https://jsonplaceholder.typicode.com/todos/1",
  { immediate: false }
);
</script>
```

...you will notice that "pending" will remain **true** until the request is triggered at least once.

### Describe the bug

Maybe it is by design, but I have the feeling pending should stay **false** while not fetching, even in not immediate mode.
A workaround is to use "status === pending" in template loaders, but I feel it less straightforward than "pending".

### Additional context

I hope my English is understandable, qnd thank you for your amazing work.

**Comment by manniL** [comment] 2023-10-07 11:05
Duplicate of https://github.com/nuxt/nuxt/issues/15714 I think. That's one of the reasons why the status was created originally https://github.com/nuxt/nuxt/issues/18810.

**Closed by manniL** 2023-10-07 11:05 UTC
Labels: 3.x, pending triage
