### ISSUE TITLE
Inlined style are not minified

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#22909] opened 2023-08-30 15:04 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      app, runtimeConfig, modules, css, nitro, content, unocss, site, sitemap, routeRules, devtools
- Runtime Modules:  @nuxt/content@2.7.2, @vueuse/nuxt@10.3.0, @unocss/nuxt@0.55.3, nuxt-simple-robots@3.1.1, nuxt-simple-sitemap@3.2.5, nuxt-schema-org@2.2.0, @nuxthq/studio@0.13.4, @nuxtjs/plausible@0.2.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/github/unjs/website?file=README.md

### Describe the bug

Hello,

I don't know how to create a smaller reproduction of this issue.

You can read more in this issue https://github.com/unjs/website/issues/89

**Comment by danielroe** [comment] 2023-09-11 11:38
Checked and I can't reproduce with a new Nuxt project. Would you see if you can pare down the example to the minimum level to cause this issue? 🙏

**Comment by manniL** [comment] 2023-12-26 13:22
No reproduction so far, closing here ☺️

@Barbapapazes (or anyone else who might experience a similar issue) If you can provide a running repro, please comment here 👍🏻

**Closed by manniL** 2023-12-26 13:22 UTC
Labels: 3.x, pending triage, needs reproduction
