### ISSUE TITLE
NuxtLink, target and config.app.baseUrl

### ISSUE THREAD

**Issue by jeanmatthieud** [nuxt/nuxt#23931] opened 2023-10-25 09:58 UTC
### Environment

- Operating System: Linux
- Node Version:     v20.2.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.6.6
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Describe the bug

NuxtLink is not using the Nuxt config app.baseUrl when `target="_blank"` is set.

### Reproduction

- Create an app with a [baseUrl](https://nuxt.com/docs/api/nuxt-config#baseurl), eg `/en`
- Add a NuxtLink without target, eg `<NuxtLink to="/my-page">snip</NuxtLink>`
- Add a NuxtLink with target, eg `<NuxtLink to="/my-page" target="_blank">snip</NuxtLink>`

Result:
- The first link will be transformed as `<a href="/en/my-page" ...>snip</a>`
- The second link will be transformed as `<a href="/my-page" target="_blank" ...>snip</a>`

**Comment by manniL** [comment] 2023-10-25 10:01
Duplicate of #23737, resolved via https://github.com/nuxt/nuxt/pull/23751, already available on the latest nightly release ☺️

**Closed by manniL** 2023-10-25 10:01 UTC
Labels: 3.x, pending triage

**Comment by jeanmatthieud** [comment] 2023-10-25 10:02
Sorry, I didn't saw it during my search
